blackmagic-debug/blackmagic

src/target/lmi.c

As identified in https://github.com/blackmagic-debug/blackmagic/issues/1412 , we were missing the DID0 value for Tiva-C TM4C129 parts. This PR fixes this so we can properly detect those pparts again.
Partially fixes #1412

Fix: Tiva-C TM4C129 identification

---

src/target/lpc11xx.c
src/target/lpc15xx.c
src/target/lpc17xx.c
src/target/lpc43xx.c
src/target/lpc546xx.c
src/target/lpc_common.c
src/target/lpc_common.h

After the changes in #1323 which makes the Flash structure member `writebufsize` a computed value, it was found that on supported LPC targets BMD would attempt to divide by 0.
This PR addresses that by lifting the code that initalises the writesize member into lpc_add_flash() so initialisation occurs in the proper order and we avoid dividing by 0.

Fix: LPC Flash registration

---

src/target/adiv5.c

This PR adds an ADIv5 component entry to the arm_component_lut for Nordic Semi's nRF series Nordic Trace Buffer (NTB)
Fixes https://github.com/blackmagic-debug/blackmagic/issues/1394

Feature: NTB component entry

---

src/target/sam3x.c

Many thanks to the Discord user "Colonel Panic" for reporting this issue. On ATSAM3Xxx parts, toggling the nRST line during setup to enter/exit Flash mode causes a complete reset of the device (including the debug components). This disconnects us from the target and trashes the ability to read or write debug registers.
This PR solves this by using `CORTEXM_TOPT_INHIBIT_NRST` to inhibit this physical reset, which allows Flash programming to proceed normally.

Fix: SAM3Xxx Flash programming

---

src/target/jep106.h
src/target/jtag_devs.c
src/target/jtag_devs.h
src/target/jtag_scan.c
src/target/jtag_scan.h

As part of investigating further RISC-V support (ESP32-C3), and to address a long-standing issue with the handling of Xilinx parts, and other parts, this PR rewrites how we do JTAG scan so we first read out ID codes, then the IR chain w/ quirks to handle misbehaving parts, and finally the BYPASS DR chain to validate chain length.
We have tested this against all JTAG targets on our desk and have not seen any breakage, and it does fix the scan issues with the ESP32-C3 once a quirk is provided for that part.
This is suggested for v1.10 ahead of the RISC-V support so it gets time to be tested and stablised.

Fix: JTAG IR quirk handling

---

src/hex_utils.c
src/include/gdb_main.h
src/include/general.h
src/include/hex_utils.h
src/main.c
src/platforms/common/jtagtap.c
src/platforms/hosted/bmp_remote.c
src/platforms/hosted/bmp_remote.h
src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap.c
src/platforms/hosted/dap.h
src/platforms/hosted/dap_command.c
src/platforms/hosted/dap_command.h
src/platforms/hosted/remote_jtagtap.c
src/platforms/hosted/remote_swdptap.c
src/platforms/hosted/serial_unix.c
src/platforms/hosted/serial_win.c
src/remote.c
src/remote.h
src/target/adiv5.c
src/target/adiv5.h
src/target/adiv5_jtagdp.c
src/target/adiv5_swdp.c
src/target/cortexm.c

This PR addresses several regressions in ARM JTAG handling detailed below and necessarily rewrites the ADIv5 high level remote protocol.
The regressions fixed are as follows:
* Fixed a regression introduced with 6dcc5d41 which broke non-multiple-of-8 TDI-TDO sequences
* Fixed an issue whereby CMSIS-DAP adaptors such as ORBTrace should never have worked with JTAG ADIv5 devices due to initialising the IR length information too late
* Fixed a timing issue in the TDI sequence function much like the TDI-TDO sequence one
* Fixed the remote protocol going "everything's ok" even when dp->fault is set non-zero and everything is not ok
* Fixed the remote protocol pretending exceptions don't exist and the ADIv5 JTAG and SWD layers can't throw them (they can) resulting in permanent comms loss when …

Fix: ARM JTAG regressions

---

src/target/stm32l0.c

Following on from https://github.com/blackmagic-debug/blackmagic/pull/1099, this PR implements mass erase and protected chip detection for STM32L0 and STM32L1 series devices.
There are 3 possible protection states to consider:
* Level 2 protection is unrecoverable and likely results in no-scan when attempting JTAG or SWD scan.
* When L1 protected, most memory operations will fail and our only real recourse is to switch back into L0 protection - this is by nature mass erase (and performs a target reset on completion).
* L0 protection is anything goes - but, importantly, attempting to switch into this mode does nothing to the erase state of the device. So, for this protection mode we must implement sending an actual mass erase command. This does not result in communications reset.
This …

Fix: stm32l0/l1 is missing a mass erase implementation

---

src/target/adiv5.c
src/target/adiv5.h
src/target/cortexm.c
src/target/cortexm.h
src/target/efm32.c
src/target/kinetis.c

As prompted by #968, we took a dive into the halt/resume code which was subtly broken in a couple of ways. This PR addresses these issues and documents how this tricky part of the Cortex-M support works better.
The exact issues addressed are:
* Recovery APs wrongly specified non-0 register size information which leads to a crash on main
* Our handling of the C_HALT and C_DEBUGEN bits was dubious at best
* C_MASKINTS (interrupt masking) was being mishandled during detach
* Post-DP-scan resumption was doing bad things to targets not found in the current adiv5_dp_init() call
* DHCSR halt was being done wrongly for minimal DP targets
* State was spilling from DHCSR halt into CIDR readout, making that fail under some circumstances when it shouldn't
* Error messages around CIDR readout failing …

Fix: Cortex-M halt/resume correctness

---

src/platforms/hosted/remote_swdptap.c

This PR acts as a follow-up to #1389 which saw the remote protocol implementation largely rewritten. That PR focused on JTAG but there were some outstanding consistency issues with the SWD implementation. This PR addresses those.
The result should be a consistent naming scheme for the BMDA remote protocol functions - both SWD and JTAG - and consistent variable naming within those functions + consistent use of logging levels.

Fix: BMDA's BMP remote protocol SWD cleanup

---

src/gdb_hostio.c
src/include/gdb_main.h
src/main.c

In the wake of #1284, Koen correctly identified that a private (UB) declaration of gdb_main_loop() had the semihosting Host IO code broken with nobody having noticed. This PR addresses this by removing that declaration, putting one in the gdb_main.h header so mismatches with gdb_main.c result in compilation failure, and updating how the Host IO code calls the main loop.
Fixes #1385

Fix: Semihosting

---

src/crc32.c

Round up read length to a multiple of four so it'll be performed as 32b reads.
When I were working on a LPC4078-based project, `compare-sections` were failing on a section which length was not a multiple of four. Rounding up the read length fixed it.
I have not investigated why non multiple of four reads were not returning correct data; whether we've got a bug somewhere else, or whether this is a limitation of this specific MEM-AP implementation, but there's an argument to be made for performing the read as 32b reads in any case, also from a performance perspective.

crc32: Round up read length to a multiple of four

---

src/target/lpc55xx.c

This pull request adds some support for flashing LPC55xx devices. Because I only have an LPC5504 device, this is the only device I have tested. It _should_ work for LPC5502 and LPC5506 and the corresponding S-variants as well. Based on user manuals and other online sources, I have tried to write the code such that it will also work for LPC551x, LPC552x and LPC556x, but I can provide no guarantees as to what this code will do to them.
Based on my research, it is possible that there may be two different silicon revisions in the wild with (very) different IAP interfaces. My device has "ROM API version 1", so that is what I have tested. The code in this PR has support for "ROM API version 0" but it is untested.
The IAP interface for this device family is very poorly documented with a lot of …

Add some basic LPC55xx flashing support, tested only on LPC5504

---

src/platforms/native/platform.c
src/platforms/native/platform.h

There were a couple of pinout mistakes in the native platform and a lack of clarity about how certain pins related to their respective functions. This PR seeks to clarify these relationships and fixes the issues in the pinout.
Fixes: #1427

Fix: Native platform pinout mistakes

---

src/command.c
src/gdb_main.c
src/platforms/hosted/bmp_hosted.h
src/platforms/hosted/gdb_if.c

Prior to this the following command gave many errors.
```
make PROBE_HOST=hosted HOSTED_BMP_ONLY=0
```
This fixes are by 'dragonmux' on Discord.  tested here on Windows10/Cygwin64.

Fix: cygwin compilation of BMDA

---

src/target/lpc55xx.c

This pull request fixes a memory leak of `flash` variable in function `lpc55xx_add_flash` if `lpc55xx_flash_init` fails.
No issues fixed.

target/lpc55xx: Fix memory leak in lpc55xx_add_flash

---

src/target/jtag_scan.c

This pull request fixes an out of bound array access in `jtag_scan` function if `device` variable reaches 32.
This PR does not fix any existing issues.

target: Fix out of bound array access in jtag_scan

---

src/platforms/common/jtagtap.c
src/platforms/hosted/libftdi_jtagtap.c

Due to an issue with marginal timings on some devices, SWD->JTAG sequence operations were not reliable after #1389 and #1430. This PR addresses this by adding the = back into the `<= 50` condition used to generate enough idle cycles before the sequence and documenting it as intended behaviour.

Fix: SWD to JTAG sequence

---

src/command.c
src/include/target.h
src/platforms/hosted/cli.c
src/platforms/hosted/platform.c
src/platforms/hosted/stlinkv2.c
src/platforms/hosted/stlinkv2.h
src/target/jtag_scan.c

Thanks to #1446 spurring us on, we have now addressed the way the manually specified IR lengths logic is handled as between the VLA usage, lack of length checking and other handling issues, the soundness of the IR lengths code was questionable.
This PR addresses this with a partial rewrite and finishes the refactoring work began in #1389 in jtag_scan() + cleans up the ST-Link v2 specific version of this routine. The result should be more consistent and robust with better user feedback.
This PR does slightly alter how the IR lengths are specified - dropping the need for a trailing 0 in the array, and making any 0's specified on the command line errors - but as this fixes a bug in how they could be specified and the user was not visibly aware of this behaviour/need, we think it's a safe …

Fix: JTAG scan irlens handling

---

src/platforms/blackpillv2/platform.c

This pull request fixes the compiler error ```undefined reference to `platform_target_voltage_sense'``` when PLATFORM_HAS_POWER_SWITCH is defined for the blackpillv2.
It fixes the error by adding the function platform_target_voltage_sense as it was previously undefined.
As the blackpillv2 does not sense the voltage on the power pin, the function is implemented by returning a 0.

blackpillv2/platform: add function platform_target_voltage_sense

---

src/target/rp.c

Performing ROM calls on the RP2040 is not completely reliable as if the device starts off in a bad state, the calls will simply fail with no real recourse. Instead of trying to hit our head on that, and noting that the ROM call code was consuming a fair whack of Flash on BMP, we've opted to rewrite the SPI Flash erase and programming routines using the same mechanism we're using to directly talk with the SPI controller as used for SFDP readout.
This PR is the culmination of that work. Tested working on both a ROM v0 and ROM v2 RP2040.
This PR does not address the secondary bug of `kill` in GDB after `load` on the RP2040 causing the target to spin off to 0xfffffffe and trap rather than execute the newly loaded program. We will address that in a follow-up PR
Fixes #1364

Fix: RP2040 Flash reliability

---

src/target/lpc55xx.c

This PR adds the chip IDs for the LPC551x and LPC55S1x processors from their reference manual. We don't have the hardware to test this, but figured they seem close enough to the LPC550x parts that the worst that can happen here is that they need special handling they don't yet have, but the IDs are otherwise correct.

Feature: LPC551x chip IDs

---

src/platforms/common/aux_serial.c
src/platforms/common/aux_serial.h
src/platforms/common/usb_serial.c

This PR implements support for the USB CDC ACM control request "GET_LINE_CODING" which is used by Windows and Linux most notably to ensure they're in step with the firmware for things like baud rate, control signalling state, etc.
With this PR, the reliability of GDB to BMP connectivity should be improved as are various ancillary things to do with the AUX serial to USB serial bridge.

Feature: CDC GET_LINE_CODING support

---

src/target/cortexm.c
src/target/cortexm.h
src/target/lpc11xx.c
src/target/lpc15xx.c
src/target/lpc17xx.c
src/target/lpc40xx.c
src/target/lpc43xx.c
src/target/lpc546xx.c
src/target/lpc_common.c
src/target/lpc_common.h

This PR addresses the breakage that occurred between v1.8.2 and v1.9 in the IAP routines used by the LPC8xx parts, among others. While investigating this it turned out that the `lpc_iap_call` was invoking undefined behaviour and was quite poorly documented.
We've addressed this with a near complete rewrite of the routines affected and adding handling for the LPC8xx parts support to handle their needs around `target_reset()` and entering/exiting Flash mode
Fixes #1230

Fix: LPC IAP correctness

---

src/target/adiv5_swdp.c
src/target/rp.c

As part of #1364 it was identified that when running `load` followed immediately by `kill` in GDB on a RP2040, the result would be the target instantly crashing. This PR fixes that by fixing the behaviour of the Flash mode exit routine so the core's put back into a good state on exit ready to go.
This PR also improves the handling of unused DPs in a multi-drop system to reduce the number of protocol recoveries and failures to deal with and speed up SWD scan.

Fix: `load` -> `kill` crash

---

src/platforms/hosted/Makefile.inc
src/platforms/hosted/bmp_hosted.h
src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/ftdi_bmp.h
src/platforms/hosted/jlink.c
src/platforms/hosted/jlink_adiv5_swdp.c
src/platforms/hosted/jlink_jtagtap.c
src/platforms/hosted/platform.c
src/platforms/hosted/stlinkv2.c
src/platforms/hosted/stlinkv2.h
src/platforms/hosted/stlinkv2_jtag.c
src/platforms/hosted/stlinkv2_protocol.h
src/platforms/hosted/stlinkv2_swd.c
src/target/adiv5.h

This PR fixes the ST-Lijnk backend for BMDA writing 2 bytes to a single byte of storage when doing a target_mem_read8() and entirely overhauls this backend, bringing it mostly up to speed with the other backends.
A side effect of this PR is that both the ST-Link and J-Link backends should now run considerably faster due to their improved use of libusb Bulk transfers.
Tested against the ST-Link v2.1 that is part of the STM32F411 Nucleo board.
This PR also pre-emptively fixes several other issues including the frequency selection/calculation logic and splits the backend up into JTAG-specific, SWD-specific and general components to match the other backends more closely
Fixes: #1455

Fix: BMDA ST-Link v2 crash

---

src/platforms/hosted/serial_unix.c
src/target/adiv5.c

This pull requested fixes two compiler errors encountered when compiling for `PROBE_HOST=hosted` on Apple (macOS). These were reported in #1466.
#1466

Fix: build error for hosted platform on Apple

---

.github/workflows/build-pr.yml

There is a warning going on in the action runs, see https://github.com/blackmagic-debug/blackmagic/actions/runs/4802868427 for example:
```
Annotations
1 warning
size-diff
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
which can be fixed easily by updating to checkout@v3.

github: Switched to checkout@v3 in size-diff job of the build PR CI

---

src/command.c
src/platforms/stlink/platform.c
src/platforms/stlink/platform.h
src/platforms/stlink/stlink_common.c

This patch series fixes two issues I had using the BMP firmware on an ST-Link v2 clone with a target that requires using SRST:
- The nRST pulse length is too short and didn't trigger a target reset at all in my case.
This is addressed by adding an optional parameter to `cmd_reset` specifying the pulse length in milliseconds, defaulting to the previous behaviour of no delay (0ms).
- Unlike the original ST-Link v2 hardware which has nRST connected to PB0 or PB1, the "clones" use PB6.
Despite having completely different PCB layouts and ICs, all three different types of "clones" I examined don't have nRST hooked up to PB0 or PB1 but rather to PB6. Some have PB6 and PB7 connected together.
The clones are now assigned their own hardware revision (0x101 to leave plenty of room for more …

Reset pulse length, fix ST-Link v2 clone nRST pin

---

.pre-commit-config.yaml
src/platforms/hosted/bmp_serial.c
src/target/cortexm.c

This pull request fixes issue #1469, where a pre-commit error was encountered on macOS using Apple Silicon, as `libzstd` was not found.
`pre-commit` uses a mirror of `clang-format`, which is located at https://github.com/pre-commit/mirrors-clang-format and defined in the `.pre-commit-config.yaml` file.
Upgrading from clang-format v15.0.4 to v16.0.2 fixes the issue.
#1469

pre-commit/mirrors-clang-format: update from v15.0.4 to v16.0.2

---

src/platforms/hosted/bmp_hosted.h
src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/cmsis_dap.c

Unlike ST-Link and JLink's init functions, CMSIS-DAP's `dap_init_bulk()` uses `libusb_open_device_with_vid_pid()` which just grabs the first matching device without filtering by serial, which makes it impossible to select other devices than the first.
Rather than transplanting the opening/filtering code from one of the other interfaces, this PR leverages the fact that we've already found and decided on which USB device we want to use in `find_debuggers()`, so all we have to do is to keep a reference to the selected `libusb_device` so that the interface drivers can pass that to `libusb_open()` without having to do a new scan.
The natural next step would be to simplify the ST-Link and JLink interface drivers to also make use of this, but I'm not able to test those right now, so I've left …

Fix selecting between multiple identical CMSIS-DAP devices

---

src/Makefile

Together with releases we also provide sourcecode archives. The archives contain the `version.h` file but no `.git` as it is not an active git repository. When the code is cleaned in a source archive the version.h should not be deleted. Also we should not require `git` to be installed so we check if it is in the path before running `git desscribe`.
This patch checks if git exists in the PATH and is executable, and makes cleaning of `version.h` optional.

make: Don't delete version.h in archives.

---

src/Makefile

When the `blackmagic` repository is used as a submodule of another repository the .git is a file redirecting to where the directory is instead of being the directory itself. We need to test for "a file" existing not for a directory.
I have tested this by creating a mockup repository using this repository as a submodule. Now building within the submodule works again as intended.
Not sure if we need to backport this patch to the v1.9 branch and include in the next point release. It depends on what the liklyhood` is of anyone using the stable branch or any of the tags instead of `main` as submodule.
Fixes #1483

Fix git detection when using blackmagic as a submodule.

---

src/target/imxrt.c

This fixes the build on macos, after it was discovered that `PRIu8` didn't work due to integer promotion rules.

imxrt: use %u for formatting status code

---

src/command.c
src/include/target.h
src/platforms/hosted/cli.c
src/platforms/hosted/platform.c
src/target/jtag_scan.c

This pull request removes the old IR lengths system, where a user would manually specify the expected IR lengths as part of doing a JTAG scan monitor command. This has been done in preference for the IR quirks system which allows specifying not just expected IR lengths but also expected values, making it a considerably more flexible system.
This results in a ~220 byte saving in Flash, which might be enough for #1474 to then fit.
Fixes: blackmagic-debug/black-magic-org#1

Feature: Remove the JTAG scan IR lengths mechanism

---

src/command.c

As discussed in #1460 modify command help output to use the same syntax as used by BMD `--help` output and other applications (e.g. Python `argparse`). This makes it easier to understand which parameters are optional.

Unify help syntax

---

src/Makefile
src/include/general.h
src/include/maths_utils.h
src/maths_utils.c
src/platforms/hosted/stlinkv2.c
src/target/cortexm.c

DWT can match power-of-two sized memory regions up to an implementation-defined limit. Properly calculate the mask length for region sizes of more then 4 bytes rather than writing reserved bits.
Factored out `stlink_ulog2()` from [`src/platforms/hosted/stlinkv2.c`](https://github.com/blackmagic-debug/blackmagic/blob/5a925ee79c36a2a3f13d32570fd48b890b4a4f4e/src/platforms/hosted/stlinkv2.c) as `ulog2()` into a new source file `src/compat.c` so we can use it in `src/target/cortexm.c`. I didn't find a good location for this function (the closest match I could find was `hex_utils.c`) so I created a new file.

Fix DWT mask calculation

---

src/platforms/hosted/ftdi_bmp.c

Fixes the compilation error.
```
$ make -j 30 clean && make -j 30 PROBE_HOST=hosted HOSTED_BMP_ONLY=0 ENABLE_DEBUG=1
...
platforms/hosted/ftdi_bmp.c: In function ‘libftdi_jtagtap_tdi_tdo_seq’:
platforms/hosted/ftdi_bmp.c:694:32: error: implicit declaration of function ‘alloca’; did you mean ‘malloc’? [-Werror=implicit-function-declaration]
694 |                 uint8_t *tmp = alloca(rsize);
|                                ^~~~~~
|                                malloc
platforms/hosted/ftdi_bmp.c:694:32: error: initialization of ‘uint8_t *’ {aka ‘unsigned char *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
cc1: all warnings being treated as errors
make[1]: *** [Makefile:125: ftdi_bmp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** …
```

Build - Fix building BMDA due to alloca being undefined.

---

src/platforms/common/blackpill-f4/README.md

This pull request fixes a typo in the readme of the common blackpill-f4 code.
The typo is a remaining `blackpillv2` entry in the command to upload the firmware. This is updated in this pull request.

Fix: platforms/blackpill-f4: fix typo in readme

---

src/target/stm32f1.c

1. This is a new feature with add support with gd32f2xx chip decection.
2. I have a board with GD32F205RKT6 chip,and I try debug the board with blackmagic, but I found I couldn't recongise the chip correctly, so I try to add support with this feature.
3. I found gd32f1x series chip has supported with blackmagic, and gd32f2xx is compatiled with gd32f1xx in a sense.

gd32f2xx: add support detection of GD32F2XX microcontrollers

---

src/platforms/hosted/remote/protocol_v0_adiv5.c
src/platforms/hosted/remote/protocol_v1_adiv5.c
src/platforms/hosted/remote/protocol_v3_adiv5.c
src/remote.c

This PR addresses a regression caused by #1459 where BMDA can calculate a memory write transfer length inappropriate to the alignment required for that write. In the process, this also improves the error reporting of the BMDA remote protocol implementation to make debugging in the future easier.
Fixes #1492

Fix: Remote protocol write length alignment error

---

.github/workflows/build-pr.yml

We were using a different GitHub action for the PR CI builds, also we were using an older compiler which is causing some issues with more recent PRs.
This PR synchronizes the actions between each other and updates the GCC ARM cross compiler to the newest release for the PR builds.
This change was tested outside of the main repository to still build within the action as expected.

actions: Updated PR workflow to use up to date arm compiler.

---

src/target/cortexm.c

* The only place in firmware involving long division is in `cortexm_hostio_request` with a `uint64_t csec64` intermediate, as analyzed by Puncover.
* This PR reorders expression terms to stay in uint32_t type.
Indirectly affects issues with FTBFS for flash-constrained platforms (native/stlink/swlink).
Impact: users of on-probe Semihosting. Testing required (esp. BMP vs BMDA-processed semihosting).
When building with gcc-{10,11,12}, code size decreases by ~780 bytes by dropping `__aeabi_uldivmod`.

cortexm: Avoid long division for non-hosted

---

src/command.c
src/gdb_packet.c
src/target/stm32f1.c

* The PR tries to optimise flash size by slightly reducing the set of functions required from libc.
* Precisely, I've identified the three places where `strtol` is called in firmware with help of Puncover. `strtoul` seems to be sufficient to store into uint32_t results in all three cases, and the `base` argument is 16 or 0 (for hexadecimal) anyway.
man 3 strtoul: 
>Negative values are considered valid input and are silently converted to the equivalent unsigned long value.
Even though newlib provides `_strtol_r` & `_strtoul_r` as different implementations (not calling each other, unlike atoi()/atol() wrappers), the resulting program ends up referencing both functions via (si)scanf implementation anyway (newlib & newlib-nano). There is only an effectively 20-40-byte .text reduction from …

Fix: Replace strtol with strtoul

---

src/command.c

* The strtok in newlib pulls in assert, fiprintf and other FILE*/reentrant stuff which is a code size problem.
* This PR rewrites the sole caller (`command_process()`) to manage the state (`char* saveptr`) and use the reentrant `strtok_r`.
Caveats: `-DNDEBUG` for disabling asserts doesn't influence this, as this is a special `__reent_assert`;
any introduction of assert() or direct fiprintf() usage will pull the dropped functions (`_vfiprintf_r` and friends) back into firmware binary.
Build-tests for native,stlink,blackpill-f4 show 1.5 kilobyte flash size reduction.
Now even `make PROBE_HOST=stlink ST_BOOTLOADER=1` produces 7524 + 114424 binaries (131072-8192=114688 limit) which fits both a 16k ST DFU and a 112k BMP firmware into 128k adapter flash.
This is (helped by and) a follow-up to …

Fix: Use reentrant strtok_r

---

src/platforms/common/blackpill-f4/blackpill-f4.c

This pull request fixes a bug where the command `monitor tpwr disable` would enable tpwr, and `monitor tpwr enable` would disable tpwr.
With this fix, running `monitor tpwr disable` sets the voltage of the tpwr pin to 0.00 V, and running `monitor tpwr enable` sets the voltage of the tpwr pin to 3.30 V.
> **Note**
> A remaining issue is that tpwr is enabled upon startup, whereas `monitor tpwr` reports `Target Power: disabled`. This was already the case before this pull request, and remains an issue. @dragonmux Do you perhaps know what could cause this, and what could be a fix?

platforms/blackpill-f4: fix inverted tpwr command

---

src/target/imxrt.c

* Makeflag `ENABLE_DEBUG=1` includes many debugging printf statements into the probe firmware.
* `src/target/imxrt.c` had some funky `DEBUG_TARGET` code/variables partially guarded by `ENABLE_DEBUG`.
* Fix the build by additionally guarding with `PC_HOSTED==1`, as these statements are intended only for BMDA.
This change was introduced/discussed on Discord on June 15th, and I don't see it in PRs against `main`. Will drop/close this PR if the change is going to be included in a larger PR to avoid the trouble of rebasing.
No issues reporting ENABLE_DEBUG=1 builds were spotted, but I certainly did face this problem.

Fix: ENABLE_DEBUG=1 build throws -Wunused-variable in imxrt.c

---

src/target/stm32h7.c

Fixes a wrong check on the result from second bank erase. This was resulting in prematurely exiting the mass erase call.

target/stm32h7: fix checking result from bank erase while mass erasing

---

src/target/cortexm.c

1) When probing under reset, reset is held for too long.
Some parts, in particular the STM32F0, do not respond to queries
for their MCUID while the hard reset line nRST is being asserted.
When attempting to connect under reset, BMP incorrectly continues
to assert reset while querying MCUID. Therefore, some chips only
identify as "ARM Cortex-M", not the proper chip ID. This prevents
binaries from being loaded.
2) When attaching under reset, reset is released too soon.
When attaching under reset, it's critical that user code not be
allowed to run before the debugger commands the chip to halt.
If bad user code is loaded on the device (e.g. that disables the
clock), any window in between releasing reset and commanding a
halt can prevent the BMP from attaching. The BMP incorrectly
releases …

Fix: Connect-under-reset handling reliability

---

src/target/lpc546xx.c

* I noticed a long switch-case in the lpc546xx_probe with relatively low entropy: to me, it seemed inefficient, as the branches only differed in part name string. All 11 chips have either 256k or 512k flash. Moreover, SRAM123 size difference was not handled.
* I took inspiration from efm32 detection code and hoisted all part-specific data into a .rodata LUT/array. I also stored known flash & ram sizes there and used these in target_add_ram/flash calls.
* ~In case the LUT is deemed unnecessary, I tried dropping most of name strings for a 192 byte flash reduction.~
* upd: I reduced the name strings from 11 to 2 distinct. Exact Part ID goes into DEBUG_INFO logs.
The LUT approach should be more efficient and readable, ~but in fact results only in -4 bytes flash footprint.~ First squashed …

Feature: Refactored LPC546xx device identification using a LUT

---

src/platforms/common/stm32/dfu_f4.c

I think I found bug in Black Magic DFU bootloader for stm32f4 platform, where I'm testing BMP firmware.
I've encountered with DFU not erasing flash memory, where after manually erased chip, dfu bootloader successfully loaded BMP firmware. The commit where erase flow was changed  SHA:
3647a627bf1f2d42560a007085e7c06d1a82cb28
After the changes I've made I was able to download BMP firmware with DFU bootloader successfully.
* [* ] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [*] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [* ] It builds for hardware native (`make PROBE_HOST=native`)
* [* ] It builds as BMDA (`make PROBE_HOST=hosted`) …

Invalid sector_num fixed for dfu erase stm32f4

---

src/target/samx5x.c
src/target/stm32l4.c

* No new feature implemented.
* This pull request is aimed at flash size/footprint reduction.
* Repeated parts of message strings in stm32l4 & samx5x could be output via `%s` of tc_printf/gdb_voutf/vasprintf, and this allows GCC to fold string literal constants, saving 200 bytes in `.rodata`.
Disclaimer: I don't have targets handled by stm32l4 code available (and certainly not samx5x), so I can't runtime-test whether the probe now crashes at this stack depth etc.
Additionally, I didn't find a `tc_puts()` or something similar to print simple `\n\0`-terminated string literals. GCC is known to optimise such calls of `printf("...\n")` to `puts("...")` (see `gimple_fold_builtin_printf()`). Some of the changes could be alternatively split into two print statements, the second printing the …

Fix: target: Deduplicate message strings

---

src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap.h
src/platforms/hosted/dap_jtag.c

In the process of working on #1428 we encountered several bugs in the JTAG implementation of ORBTrace which renders older gateware unable to correctly handle a multi-TAP JTAG scanchain. This PR introduces an implementation quirks system and checks to guard against this and improve the experience of using adaptors that need updating or otherwise need workaround applied to work correctly.

Fix: ORBTrace version protection

---

src/target/imxrt.c

When building debug mode for hardware, the `boot_mode` flag is consulted. However, the `boot_mode` flag is only present when debug mode is enabled on PC_HOSTED.
Remove the requirement for this to be built on PC_HOSTED in order to fix compiling when built on native hardware with debug mode enabled.
* [√] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [√] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [√] It builds for hardware native (`make PROBE_HOST=native`)
* [√] It builds as BMDA (`make PROBE_HOST=hosted`)
* [√] I've tested it to the best of my ability
* [√] My commit messages provide a useful short description of what the commits …

imxrt: ungate boot_mode even on non-hosted

---

src/target/imxrt.c

Patch a674dff2495a78cd4b87a091ad5c7ef10bd94daf accidentally had `||` rather than `&&`, resulting in build errors when enabling debug mode on certain hardware targets. Correct this logic in order to fix builds with certain other platforms.

imxrt: correct logic of debug guard

---

src/include/timing.h

* The pull request solves the problem of relatively slow RTT streaming speed of BMF.
* The pull request solves the problem by making it possible to poll faster than every 10ms. This requires raising the SysTick interrupt frequency from historically 100Hz to 1000Hz.
No known to me issues solved by this PR.
I conducted tests of RTT streaming from @koendv 's Arduino sketch running on NUCLEO-G071RB (and some tests were repeated on a WeAct Studio BluePIll-Plus with genuine stm32f103cbt6). Here are the results in chars/s as reported by DUT measuring a hardware timer prescaled to 1ms ticks:
* `blackpill-f411ce` before: 34000..51000, after: 87000..102400;
* `swlink` before: 32000..34000, after: 78000;
* `f072rb` before: untested, after: 42000. This is on a 32F072B-DISCO just to …

Fix: Increase SysTick frequency to 1kHz

---

src/include/platform_support.h
src/include/stdio_newlib.h
src/platforms/96b_carbon/platform.h
src/platforms/common/blackpill-f4/blackpill-f4.h
src/platforms/f072/platform.h
src/platforms/f3/platform.h
src/platforms/f4discovery/platform.h
src/platforms/hydrabus/platform.h
src/platforms/launchpad-icdi/platform.h
src/platforms/native/platform.h
src/platforms/stlink/platform.h
src/platforms/swlink/platform.h

* The previous PR #1530 reduced visibility of "newlib integer-only stdio" redefinitions to only those translation units which `#include platform.h` This lead to flash size increase for 7 platforms (all not using newlib-nano) by 37 KiB because of linker pulling float/double capable stdio implementations (and softfp routines for double etc).
* This PR ties these redefinitions back to `platform_support.h` visible via `general.h` to every platform except `hosted`.
To reproduce/verify, `make all_platforms` and compare binary sizes of files under `src/artifacts/v1.9.0-...` for relevant revisions.
Also Puncover to check for functions pulled from libc. 
*I don't know yet how to easily automatically perform checks for ENABLE_DEBUG=1 builds without encountering build failures or invoking make …

Fix: Factor out integer-only stdio into a common header

---

src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/blackpill-f4.h

This PR implements support for the internal (on-board) SPI Flash found on the Blackpill series boards, mirroring the work done for "native" (BMP).
* A new feature was implemented in #1499 for accessing probe-attached SPI flash chips via BMP remote protocol (and desktop cross-platform bmpflash client).
* However, it only implements SPI platform code for `native` hardware, providing no-op stubs for all the other platforms.
* I propose implementing platform_spi_init/deinit/chip_select/xfer for `blackpill-f4` hardware, which I own and test on.
This change results in ~~+320~~ +448 bytes flash footprint for `blackpill-f4x1cx`. Testing included `sfdp` and `read` from onboard w25q64 to desktop dualboot host (Linux Mint 21.1, Windows 11) using latest manually compiled …

Feature: Implement SPI support for blackpill-f4

---

src/target/target_flash.c
src/target/target_internal.h

This PR splits off from https://github.com/blackmagic-debug/blackmagic/pull/1241 the introduction of Flash region state tracking to allow special behaviour to be introduced based on going into an erase vs write operation. This needs merging ahead of that PR to make things all make sense.
It tries to make the change in a way that creates the least impact possible and prevents targets that don't need the new features, for paying for them.

Feature: Flash state tracking

---

src/platforms/hosted/cmsis_dap.c

This PR addresses an issue that cropped up since the ORBTrace v1.3 gateware was released as that gateware includes a `v` prefix on the version string for the adaptor. This meant that we'd see the thing as version "0.0.0" because of a quirk in how that broke the CMSIS-DAP implementation's version string parsing routine.
With this PR applied, the latest ORBTrace gateware is correctly identified as being v1.3.1 by BMDA and the multi-TAP quirk correctly applied, where before it was always applied.

Fix: CMSIS-DAP versioning identification

---

src/include/general.h
src/platforms/hosted/bmp_serial.c
src/platforms/hosted/debug.c
src/platforms/hosted/debug.h
src/platforms/hosted/gdb_if.c
src/platforms/hosted/platform.c
src/platforms/hosted/serial_win.c

This PR addresses a regression introduced in https://github.com/blackmagic-debug/blackmagic/pull/1452 which saw the output on Windows get munged by a standards conformity issue in `wprintf()` on that OS. With the [help of Microsoft](https://developercommunity.visualstudio.com/t/wprintf-has-non-conforming-string-format/10386390), we have come to a compromise involving switching the output code page to try and guarantee correct operation.
This change also introduces `printf()` format string warnings for Windows, consistent with Linux and macOS compilation.

Fix: Windows debug output

---

src/target/stm32f1.c

* A new feature is implemented: detection of AT32F435 cores by DBGMCU_IDCODE with assignment of respective total internal Flash sizes and SRAM in default NZW split.
* The pull request solves an existing problem of none/generic detection of these cores as "Cortex-M4".
* The pull request solves that by introducing a list of ID codes from reference manual for mentioned parts.
Arterytek / Artery / ARTERY AT32F435 is a more powerful (than F403A/F407/F415) core variant with possible Flash sizes of 256, 1024, 448 or 4032 KiB and bank split at 512 or 2048 KiB watermark. 
AT32F437 is a F435 with an Ethernet "EMAC" core.
Note that at the moment flash (re)programming is unsupported/unreliable, although the page (or "sector") sizes should be correct -- I couldn't get BMF or BMDA to erase the target …

Feature: Identify AT32F435/437

---

src/target/lpc43xx.c

* No new features implemented.
* The pull request is aimed at flash size/footprint reduction.
* I propose to change lpc43x0_detect and lpc43xx_detect logic to use local stack variables and fewer calls, which leads to measurable firmware .text shrink.
Disclaimer: I don't have NXP LPC43xx targets and hence cannot test the change on them. But this approach is already present in other targets code and improves readability by removing duplication/syntactic noise. +12b stack usage (if spilled) should not be a problem.

Fix: Refactor LPC43xx target sram detection code

---

src/target/adiv5.c

This PR does a much needed cleanup in `adiv5_dp_init`, related to the `TRY_CATCH` blocks
`TRY_CATCH` brings clobbering errors, forcing us to volatile certain variables and thus blocking certain optimizations
This contains the problematic code and unblocks optimizations, bringing a small code size saving
Tested with BMDA (J-Link  V8) and native on a RP2040 target

Fix: ADIv5 DP init

---

src/platforms/f4discovery/README.md

Nothing fancy here. This just updates the README.md of the f4discovery and adds the missing UART pins, which are actually there just not documented. 
Tested on my f4 discovery board. Works just fine.

platforms/f4discovery: Update README.md

---

src/platforms/hosted/bmp_libusb.c

The original ST-Link v2 has a firmware bug that remains unfixed which means that instead of the serial number being properly hex encoded UTF-16 returned to the host, the serial number is returned raw as a series of uint16_t's that must then be converted to hex for display and which must bypass and side-step libusb's libusb_get_string_descriptor_ascii() function due to it converting any character with numerical value >= 0x80 to '?'.
This PR addresses this long standing problem, allowing the serial number matching mechanics to work properly with ST-Link v2 serial numbers. This builds on the new probe scanning engine which already stopped us from displaying garbage on the user's console.

Fix: ST-Link v2 serial number readout

---

.clang-tidy

This PR adds case checking for various elements of the source code.
These checks were added to assist contributors in checking their submissions against the project contribution requirements.

clang-tidy: Additions for case checking in source code

---

src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/platform.c

This PR addresses a small regression introduced in https://github.com/blackmagic-debug/blackmagic/pull/1502 which causes CMSIS-DAP probes to be assumed to be v1 even when they might be v2 or support both.
We fix this by re-checking the descriptors of the probe if it's a CMSIS-DAP probe, once it's been selected by the probe discovery code. We then check for the v2 descriptors and extract the correct endpoints to allow the backend to do the right thing.
The way this is done also ensures that we should always pick up the proper interfaces no matter what order they appear in.
Fixes https://github.com/blackmagic-debug/blackmagic/issues/959

Fix: BMDA CMSIS-DAP v2 selection

---

src/platforms/common/swdptap.c
src/remote.c

This PR addresses a regression introduced in PR #1531 which forgot that the SWD bitbanging code needs to deal with target_clk_divider = UINT32_MAX fully. The effect of this mistake was that SWD would "hang" and soft-crash the probe.
We've also taken the opportunity to clean up the SWD remote protocol implementation the same as we did the JTAG implementation, saving a couple of bytes of Flash from that routine.

Fix: remote protocol SWD hangs

---

src/platforms/hosted/bmp_libusb.c

In #1551, @dragonmux used char16_t to safely deal with the readout of ST-Link v2 serial numbers. However, what she didn't know was that Apple Clang *still* does not ship that particular bit of the C11 standard: https://stackoverflow.com/questions/24608832/uchar-h-file-not-found-on-os-x-10-9
This can be easily remedied as described in the following glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=17979
Fixes #1557

hosted/bmp_libusb: Work around missing char16_t typedef in Darwin

---

src/crc32.c
src/include/buffer_utils.h
src/include/crc32.h

While toying with LTO and doing a BMDA build, GCC warned of a type error in the CRC32 header. On checking it out, the type for the length parameter was indeed mismatched between header and both implementations.
This PR addresses this and does cleanup on the CRC32 implementations to bring them up to standard and make them easier to read and understand. Tested against a LPC4370 on both BMP and using BMDA, this offers no functional change but does fix some undefined behaviour.

Fix: CRC32 type error

---

src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/windows/ftdi.c
src/platforms/hosted/windows/ftdi.h

The copyright notices on a couple of BMDA related files were not up-to-date

hosted: Correct copyright notices

---

src/gdb_main.c

Back in v1.8.2 we introduced fake threads support to allow modern GDBs to work with the project. As part of that we had to report to GDB that there's always and forever one thread to match the 1 core no OS reality of debugging bare-metal. Unfortunately a consequence of that was that IDEs that don't properly gate checking for threads against being presently attached to a target would then ask, after detaching, if there were any threads, get told yes, and then go sulk due to their impaired logic.
This PR addresses this by gating our telling GDB there are threads, behind being attached to a target. This means we report an empty thread list when detached, preventing the logic issue in those IDEs. It technically also means we're being more correct in our handling of the request which is why …

Fix: threads-induced IDE hangups

---

src/target/lpc43xx.c

This PR address a bug in the LPC43x0 support found via ASAN in which when Flash detection fails, the Flash structure is never allocated.
This leads to `lpc43x0_detach()` trying to dereference a NULL pointer in `priv->flash`and so crash. Checking for the possible NULL pointer and guarding the whole Flash structure freeing operation avoids this.

Fix: LPC43x0 Flash detection failure mishandling

---

src/gdb_packet.c

In the current implementation of the GDB remote protocol in BMD, the code for processing incoming packets and dispatching based on them being actual GDB remote protocol packets or BMD remote protocol packets is kind of a mess - spaghetti code even.
This PR addresses this with a reorganisation that helps simplify the code flow and reduce cognitive complexity. This forms the basis of part of the work of PR #1361 and bringing this oft overlooked part of the code base up to standard.

Fix: Remote protocol packet handling organisation

---

.gitignore
src/target/efm32.c
src/target/lpc43xx.c
src/target/lpc546xx.c
src/target/sfdp.c
src/target/stm32g0.c
src/target/stm32h7.c
src/target/target_flash.c

This PR came about by trying `-fanalyzer` on BMDA and seeing what fell out. In this PR we fix several missing pieces of error handling around allocations, and some logic errors the analyser found resulting in buggy behaviour on a couple of targets and some UB.
While we have not been able to test all of the results, this should be a low-risk set of changes, and definitely solves an issue seen with LPC43x0 targets.
We did not address /all/ lints this compiler option produces yet as a couple of the lints being produced are rather complicated to address. This means there will be a follow-up PR at some future point to look into the remaining lints.

Fix: GCC -fanalyzer lints

---

src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap_command.c

While helping Sid debug some really curious target behaviour from the Ambiq Apollo SoC's, he ran into an issue where ORBTrace would report the device gave a no-response response to a DAP_TRANSFER and BMDA would fail to pick up on that, pretending the DP register read worked just fine and gave a response of 0.
This PR corrects this behaviour by improving the perform_dap_transfer() error handling, allowing the detection of sequences such as
```
-> dap_transfer (1 requests)
command: 05 00 01 06
response: 05 01 01 00 00 00 f4
dap_read_reg: 04 -> f4000000
dp_read 0004 f4000000
Read CTRL/STAT: 0xf4000000
-> dap_transfer (1 requests)
command: 05 00 01 06
response: 05 01 07
dp_read 0004 00000000
Read CTRL/STAT: 0x00000000
```
With this change, the request will by noted as having triggered …

Fix: CMSIS-DAP transfer failure handling

---

src/target/adiv5.c
src/target/adiv5.h
src/target/adiv5_swd.c

I initially meant  to properly abstract away the multidrop handling and swd scan in general, but left it rather early, this PR doesnt have much going for it, just a place to document and later continue work from
as is the jlink scan (and I believe stlink too, but i have not tested or looked at it) does not handle multi-drop, I was meaning to get rp2040 working on jlink as means to develop and test this work but it is unable to comunicate with its DP, the reason is I would guess the Lack of "selection alert sequence for SW-DP-V2" that is present on the regular adiv5_scan
The jlink probe and api should be able to do it, but it needs to be implemented, ideally as a `seq_out` method, and the cmds in jlink in general could do with some work
since the jlink usb spec is not that easy to find I …

start seperating swd multi drop

---

src/command.c
src/include/target.h
src/platforms/hosted/cli.c
src/platforms/hosted/platform.c
src/platforms/hosted/stlinkv2.c
src/platforms/hosted/stlinkv2.h
src/platforms/hosted/stlinkv2_jtag.c
src/platforms/hosted/stlinkv2_swd.c
src/target/adiv5_swd.c
src/target/jtag_scan.c

Fix: scan return type + swdp naming phase out

---

src/Makefile
src/gdb_main.c
src/gdb_packet.c
src/include/gdb_packet.h

This is the start of no acknowledge mode (**QStartNoAckMode**) support.
The BMP uses a USB connection with the CDC class (Bulk transfers) for GDB data transfer, this means the connection *should* be reliable, with integrated integrity checks and data delivery guarantees (provided there are no bugs in the class handling side of things in the firmware), this means that acknowledgment and checksum verification is redundant and should be safe to ignore, hopefully providing a performance benefit, GDB provides support for this with **QStartNoAckMode**.
See [GDB: Packet-Acknowledgment](https://sourceware.org/gdb/onlinedocs/gdb/Packet-Acknowledgment.html#Packet-Acknowledgment) for context.
The intent is to test if this brings improvements in performance, particularly in the flashing routines.
As …

Feature: qStartNoAckmode

---

src/target/stm32l4.c

The device->sram1 and device->sram2 are in kilobyte. A multiplication by 1024 is required when used as an argument to target_add_ram()
Discord 2023-07-26:
@jcamdr: The patch multiply some RAM size by 1024U, because I can't understand how it can possibly work without that.
@dragonmux: ah, that is indeed a bug re the missing `* 1024U`'s

stm32l4.c: Fix RAM size argument to some target_add_ram()

---

src/include/gdb_packet.h

A recent change to gdb_set_noackmode() caused it to get a `bool` as an argument. However, in order to use this in a standard C compiler, you must include <stdbool.h>.
Add this include file.
This fixes the build for Farpatch.

gdb_packet: include stdbool.h

---

src/target/stm32l4.c

Addition of the documentation reference for the STM32U5.
Addition of the DP_TARGETIDR id for the STM32U5.
Addition of the stm32l4_device_info for the STM32U5.
Addition of the RAM map for the STM32U5.

Stm32u5 support

---

src/command.c
src/platforms/common/stm32/timing_stm32.c
src/platforms/native/platform.c

During a conversation on Discord with @compuphase it came up that the native hardware with current firmware allows you to some quite nasty things with the target power pin once feeding power from BMP has been enabled.
Saying "don't backfeed tpwr" is fine and all, but given the STM32F103 and related devices have an internal 1.2V bandgap reference, we set about figuring out how hard it might be to use the systick timer to sample that bandgap every few miliseconds and if we detect too much of a voltage rise or fall, switch tpwr feeding off.
This PR is the culmination of that work and should provide robust handling of tpwr backfeeding causing VCC to be driven up above 3.6V or down below 3.0V.

Feature: improved target power backfeed safety

---

src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/probe_info.c

While testing an unrelated change set, we realised that the BMDA identification banner that's displayed was showing a duff output for the probe selected. This PR addresses this by properly sorting out how that output is generated and cleaning up some loose ends in the BMD firmware product and version string handling to help identify when things are going wrong.
The result changes
```
❯ src/blackmagic -s 8BB20695 -tv 1
Black Magic Debug App v1.9.0-1056-g95e768be
for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, J-Link and FTDI (MPSSE)
Using 1d50:6018 8BB20695 Black Magic Probe (Black Magic Debug)
```
to displaying
```
❯ src/blackmagic -s 8BB20695 -tv 1
Black Magic Debug App v1.9.0-1062-gf35b2403
for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, J-Link and FTDI (MPSSE)
Using 1d50:6018 …
```

Feature: probe scan cleanup

---

src/platforms/hosted/jlink.c
src/platforms/hosted/platform.c

While testing an unrelated patch set with our LPC-Link 2 running the J-Link firmware, we discovered a firmware-crashing regression from Perigoso's PR #1570 which revolves around how the adaptor frequency is set.
This PR addresses this and a couple of clang-tidy and naming lints spotted along the way.

Fix: BMDA J-Link set frequency regression

---

src/target/adiv5.c
src/target/adiv5.h

During the process of building target support for the Ambiq Apollo 3, Sid wound up hitting and issue where the debug reset code in the ADIv5 implementation would cause the target to quit talking SWD or JTAG till power cycled, preventing scan from working.
After working with zyp, mubes and Sid and reading the ADIv5 spec closely, we have come to the conclusion that we can get the effect of the reset sequence logic by instead powering down the debug engine on the target, then powering it back up. This is guaranteed by the spec for targets that actually implement power control on the APs and debug bus to cause the APs and debug bus to come back up via a reset, getting the same net effect as the prior logic.
This has been tested on a couple of different targets including the STM32F411, LPC4370 …

Fix: ADIv5 debug bringup reliability

---

src/gdb_main.c

In a recent commit this comment got auto formatted, making it make slightly less sense, reword it

Fix: reword vMustReplyEmpty comment

---

src/platforms/hosted/dap_command.c

This PR addresses a bug found while tracing another bug in the GD32F1/STM32F1 handling. We encountered this issue while using ORBTrace.
With the `dp->abort()` call present, it screws up state on CMSIS-DAP and results in a no-scan situation due to the target generating FAULT and getting angry at us.

Fix: CMSIS-DAP WAIT handling

---

src/target/jtag_devs.c
src/target/jtag_devs.h
src/target/jtag_scan.c
src/target/jtag_scan.h

This PR seeks to improve the Flash usage of the firmware by cutting down on the amount of data in one of the largest tables built in - the JTAG devices descriptor table.
It does this in two ways: It makes the description strings (which are only used in ENABLE_DEBUG=1 builds) optional; It makes all entries in the table that are there for description purposes only, optional.
This saves 800 bytes of Flash.

Feature: reduced JTAG devices table Fflash usage

---

src/gdb_packet.c
src/platforms/hosted/Makefile.inc
src/target/stm32f1.c
src/target/target_flash.c

This PR does some cleanup and addresses a regression found while trying to debug dragonBoot on BMP.
When attempting to `load` firmware in GDB on a target and the firmware winds up containing 0x04 somewhere, the revised GDB packet handling from #1361, the packet state machine incorrectly interprets this as a GDB end of transmission packet, and aborts, causing the BMD GDB main loop to run target_detach() and enter idle mode.
The packet handling should only be considering 0x04 characters received while in the idle state for being EOT packets.

Fix: STM32F1 load regression

---

src/include/morse.h
src/morse.c

Discord 2023-08-02
jcamdr: I can't understand how a morse(NULL, false) can work without dereferencing a NULL pointer inside morse_update() after a morse() with a string.
dragonmux: good catch, that's because it does dereference NULL under that circumstance
jcamdr: Is there any possible atomic issue with morse_msg and morse_index between morse() and morse_update() on some plateform?
dragonmux: technically, yes. morse() should update those 3 variables in exactly the opposite order to how they are currently
that is, morse_repeat, then msg_index then morse_msg. that'll guarantee the update, while not atomic, will apply correctly and do sensible things
jcamdr: Fully agree. All 3 variables probably need to be volatile AFAIK.

Fix morse new null msg

---

src/platforms/hosted/cli.c
src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap_command.c
src/platforms/hosted/dap_jtag.c
src/platforms/hosted/dap_swd.c
src/platforms/hosted/ftdi_bmp.c
src/platforms/hosted/ftdi_swd.c
src/platforms/hosted/gdb_if.c
src/platforms/hosted/serial_win.c
src/remote.c
src/target/adiv5.c
src/target/imxrt.c
src/target/jtag_scan.c
src/target/lpc11xx.c
src/target/lpc15xx.c
src/target/lpc546xx.c
src/target/lpc55xx.c
src/target/lpc_common.c
src/target/nrf51.c
src/target/sam3x.c
src/target/samd.c
src/target/samx5x.c
src/target/stm32f4.c
src/target/stm32g0.c
src/target/stm32l4.c

Fix (some) warnings for `-Wpedantic`

Fix: warning pedantic empty init

---

src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/ftdi_jtag.c
src/platforms/hosted/platform.c
src/platforms/hosted/remote/protocol_v0_jtag.c
src/target/adiv5.h
src/target/renesas.c

Fix (some) warnings for `-Wpedantic`

Fix: warning pedantic void return

---

src/gdb_main.c
src/morse.c

Fix warnings for `-Wchar-subscripts`

Fix: char-subscripts warnings

---

src/target/riscv_debug.c

If the board does not have a hw reset pin (or  misconfigured or does not work), and without RV_TOPT_INHIBIT_NRST,
the riscv_reset relies entirely on the hw reset and ignores errors.
As a result the board can be not reset and behave weirdly.
The MR tries to detect the HW reset failed (riscv_dm_poll_state timeout) and if so, tries to do a system reset through DM.
With that MR i can use the "r" gdb command to restart the system properly without explicitly disabling the HW reset
(i dont have it on my board)

riscv: Check if hw reset worked, if not do a DM reset

---

src/target/riscv32.c
src/target/riscv_debug.c
src/target/riscv_debug.h

Hi this tempative MR adds the following featurettes  and could receive some feedback :
- Allow single register access (rw) . This is done only for RV32 , i dont have RV64 to do & test, should be straightforward.
- Exposes common CSRs trough the xml description. 
- Allow CSRs rw as regular registers. There is an offset so that the it does not clash with GPR registers
Please note that i extracted this MR manually from a larger codebase (including Perigoso wchlink work, the CH32V3xx chip support and flashstubs) to have a small one. It looks alright but it is  hard for me to test on its own.
Finally, it may be a good idea to think about having a generic way to add CSR per MCU (the designer custom ones) ?
There is placeholder for ch32xx_probe under #if 0, if this is bothersome please tell me …

riscv: add single register access, add csr access with an offset, expose some CSRs

---

src/command.c
src/gdb_main.c
src/include/command.h
src/platforms/hosted/bmp_hosted.h
src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/bmp_serial.c
src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/ftdi_bmp.c
src/platforms/hosted/ftdi_jtag.c
src/platforms/hosted/jlink.c
src/platforms/hosted/platform.c
src/platforms/hosted/platform.h
src/platforms/hosted/probe_info.c
src/platforms/hosted/probe_info.h
src/platforms/hosted/remote/protocol_v0_jtag.c
src/platforms/hosted/stlinkv2.c
src/platforms/hosted/stlinkv2.h
src/platforms/hosted/windows/ftdi.c
src/target/adiv5.c
src/target/jtag_scan.c

Fix warnings for `-Wshadow=local`

Fix: warning shadow

---

src/gdb_hostio.c
src/gdb_packet.c
src/platforms/hosted/cli.c
src/platforms/hosted/dap_jtag.c
src/platforms/hosted/jlink_jtag.c
src/platforms/hosted/stlinkv2.c
src/target/HACKING.md
src/target/adiv5.c

Fix some warnings for `-Wformat=2 -Wformat-overflow=2 -Wformat-signedness -Wformat-truncation`

Fix: warning format

---

src/include/target.h
src/target/adiv5.c
src/target/cortexa.c
src/target/cortexm.c
src/target/target.c
src/target/target_internal.h

This one was missed from the initial batch
Fix (some) warnings for `-Wpedantic`

Fix: warning pedantic range expr

---

src/platforms/hosted/stlinkv2_swd.c
src/target/adiv5.c
src/target/adiv5.h
src/target/adiv5_jtag.c
src/target/adiv5_swd.c

In this PR we address the STM32MP15x having a JTAG ID of 0x6ba00477 indicating a DPv0 TAP, and an ADIv5 non-compliance issue the part has which results in it hanging in the new power down code in adiv5_dp_init().
The latter is caused by the control and status register hanging at the value 0xa0000000 forever contrary to how the acknowledgement bits are supposed to work according to the ADIv5 spec.
@Perigoso given your experience with ADIv5, please check our logic regarding the ID code part of this fix.

Fix: ADIv5 DPv0 ID Codes

---

src/include/general.h

This extern declaration is not being used anywhere, nor does it map to an existing symbol in the codebase, hence "dangling"
While looking for the reason it was there I was expecting to find it to be a leftover from a previous refactor, but it seems it was introduced in 1ca9f234f7527396da91bfc1f98cb05c305c6472 by mistake, as it was not used in the commit itself, nor on any of the following commits I looked through

Fix: remove dangling extern

---

src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap_command.c
src/platforms/hosted/dap_command.h

Without this fix, dap_mem_write() accounts for write buffer header size incorrectly when calculating `blocks_per_transfer`. Long transfers (via HID) fail with error "Attempted to make over-long request of 66 bytes, max length is 65".
Sample stack trace from where this error is triggered:
<details><summary>Click for a a sample stack trace where this error is triggered.</summary>
```
0  dbg_dap_cmd_hid (request_data=request_data@entry=0x7fffffffc103 "\006", request_length=request_length@entry=65, 
response_data=response_data@entry=0x7fffffffc077 "", response_length=65) at platforms/hosted/cmsis_dap.c:383
#1  0x000055555557930d in dap_run_cmd_raw (response_length=3, response_data=0x7fffffffc100 "\377\377\377\006", request_length=65, 
request_data=0x7fffffffc103 "\006") at …
```

Fix: cmsis_dap: error when writing long buffers to DAP (>59 bytes)

---

src/target/imxrt.c
src/target/stm32g0.c

Two of the targets are using single braces to initialize arrays of structs, and this fails on my compiler:
```
CC      target/imxrt.c
GEN      include/version.h
CC      target/stm32g0.c
target/imxrt.c:325:42: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
imxrt_flexspi_lut_insn_s sequence[8] = {0};
^
{}
1 error generated.
make: *** [imxrt.o] Error 1
make: *** Waiting for unfinished jobs....
target/stm32g0.c:694:50: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
option_register_s options_req[OPT_REG_COUNT] = {0};
^
{}
1 error generated.
make: *** [stm32g0.o] Error 1
make: *** wait: No child processes.  Stop.
```

target: Add missing braces to array of struct initializers.

---

src/platforms/native/platform.c

In this PR we address an issue with target power bring-up that has come about on BMP v2.3b hardware. During bring-up with targets that have a heavy capacitive load, the power supply on BMP winds up dropping below the brown-out threshold and on recovering, shoots way up to 4.5V before coming back down into regulation.
This results in dangerous conditions for the processor that could lead to damage, and for the target to which we're attached. To fix this, this PR implements power-on soft start using PWM to gradually bring the target's power rail up and charge the capacitors without causing problems on our own power supply. This is accomplished with a high frequency (1.125MHz) pulse train and 32 steps from "off" to fully "on".
Fixes #1567

Feature: Soft start for target power on BMP

---

src/target/stm32f1.c

This PR provides support for a new target: MindMotion MM32SPIN05 and updates documentation how to add new MindMotion MM32 processors.
```
(gdb) tar ext /dev/ttyBmpGdb
Remote debugging using /dev/ttyBmpGdb
(gdb) mon swd
No. Att Driver
1      MM32SPIN05 M0
```
To add support for a new MM32 Cortex-M0 processor, first check the product id at address 0x40013400.
E.g. for MM32SPIN05:
```
(gdb) mon swd
Target voltage: 
No. Att Driver
*** 1   Unknown ARM Cortex-M Designer 0x43b Part ID 0x471 M0
(gdb) at 1
Attaching to Remote target
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
warning: while parsing target memory map (at line 1): Required element <memory> is missing …
```

mm32: support for mm32spin05

---

src/include/align.h
src/include/general.h
src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap.c
src/platforms/hosted/stlinkv2.c
src/target/adiv5.c
src/target/adiv5.h
src/target/efm32.c
src/target/lmi.c
src/target/lpc_common.c
src/target/stm32_common.h
src/target/stm32f1.c
src/target/stm32f4.c
src/target/stm32h7.c

This is a cleanup of alignment type and helper macros. the align type was moved out of the adiv5 specific files to a general header, along with it's related macros, some of which were being defined in multiple places, an additional macro was added for the common pattern of getting the minimum alignment for two given addresses.

misc: consolidate alignment macros into single header out of adiv5

---

src/platforms/native/platform.c

Due to a small accident with Git, the initial commit for this patch is already on `main` as b83657e1, so in this PR we fix a small mistake with the platform initialisation that saw the timer used by soft-start failing to be powered up on hardware older than the BMP v2.3 hardware. 
This enables tpwr soft-start for hw1 and up.

Fix: Target power soft-start for older native hardware

---

src/platforms/hosted/jlink.c

Add support for older J-Link V5 adapters to BMDA. 
OEM considers these "legacy" https://wiki.segger.com/J-Link_BASE_V5_or_lower , in fact everything pre-V11.
IMO these are still okay for raw sequences and "accelerated bit-banging" of conventional good old JTAG, fixed-direction bus transceivers included.
* This does not look like a new feature.
* Current Blackmagic Hosted App crashes V5 hardware (2008 firmware) adapters (but works with JLink V8 hw 2014 fw)
* This pull request adds a few checks regarding "multiple interfaces" capability bits to keep BMDA+JLink V5 always in JTAG mode.
I tested this on V5.4 and V5.3 yellow "Kickstart" adapters from 2006 and now they at least work. Also tested on V8 (same AT91SAM7S64, more bus transceivers for bidirectional SWD), no regressions, both SWD & …

Fix: honor capability bits of legacy J-Link V5 probes

---

src/platforms/common/stm32/timing_stm32.c
src/platforms/common/usb.c
src/platforms/common/usb.h

* Addresses #1566 (WIP).
* Monitors USB configuration state in `usb_config_morse_msg_update()` within the systick handler.
* Outputs a message using the morse subsystem (error LED) if USB is not configured.
* No patches to libopencm3 required.
Tested in the following scenarios:
1. USB host data lines disabled and then enabled
- Plug in to host USB hub with data lines disabled
```bash
$ echo 1 | sudo tee /sys/bus/usb/devices/3-1.4/port/disable
```
-  Result- error LED outputs morse message
- Enable data lines
```bash
$ echo 0 | sudo tee /sys/bus/usb/devices/3-1.4/port/disable
```
- Result- error LED turns off
2. Unbind and rebind host driver
- Plug in to USB hub with data lines enabled
- Result- error LED is off
- Unbind host driver
```bash
$ echo '3-1.4' | sudo tee …
```

Feature: Add LED feedback for USB enumeration

---

src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/ftdi_bmp.c

This PR fixes a memory leak in `bmp_libusb` and a bug in `ftdi_bmp`. 
The former was a missing `probe_info_list_free` inside a failure case for FTDI lookups. The  latter being a case where the `ftdi_lookup_cable_by_product` would erroneously return `false` if the cable was specified on the command line with `-c` resulting in an incorrect lookup failure.

Fix: memleak/handling FTDI adapters

---

src/platforms/common/stm32/rtt_if.c

This PR silently drops rtt output if the aux serial is unresponsive for 10ms.
Fixes #1488 RTT output hangs the BMP when not read by host.
Tested on blackpill-f411.
A more general solution would be to append the output of usb serial, traceswo decode, rtt, and redirect_stdout to a single circular buffer, and use the usb tx interrupt to trigger usb writes.
fixes #1488

rtt: fix hang when aux serial not read

---

src/target/cortexa.c

In this PR we set out to complete the replacement of the `apb_read()` and `apb_write()` functions in the Cortex-A code using the newer `cortex_dbg_read32()` and `cortex_dbg_write32()` functions as the former functions make gross assumptions about the state and configuration of the AP that no longer hold.
This had resulted in scan-then-crash issues on targets and would have caused issues on any part that has both a Cortex-M and Cortex-A core on the same Access Port as the Cortex-M code would have caused the same state inconsistency problem.
This also reduces the Flash footprint for the Cortex-A support by ~200 bytes.

Fix: Cortex-A support

---

src/platforms/hosted/ftdi_bmp.c
src/platforms/hosted/ftdi_bmp.h
src/platforms/hosted/ftdi_jtag.c
src/platforms/hosted/ftdi_swd.c

This PR sets out to clean up the FTDI port state structure, document it, document where to find the MPSSE protocol and command documentation, and clean up the use of that structure.
This was spurred on when helping @lethalbit figure out how to describe the Kria SOM KV260's FTDI device pinout and getting caught up on what all the bits meant and did, resulting in us having to read the source and FTDI documentation to figure it out.
Tested against Tigard

Feature: FTDI structure clarity & documentation

---

src/target/cortexm.c
src/target/imxrt.c
src/target/sfdp.c
src/target/spi.c

This uses a word of the ROM to distinguish different chips. Once distinguished, we can use the correct FLEXSPI base address.  Specifically, the 1011 has the FLEXSPI at a different address. Tested on the 1011, 1015, 1020, 1040, 1050 and 1060 EVK boards.
This change also checks the length of the SFDP basic parameters table to ensure it is long enough to include page size. The 1011 and 1015 EVKs use the AT25SF128A which has an old SFDP table that is only 9 DWORDS long. Page size is in DWORD 11.
The 1176 is detected but the flash SFDP doesn't work still. So, it doesn't fully work.

Detect iMX RT variant to support more than 1060

---

src/target/cortexa.c

BMD at current `main` busy-loops (hangs, effective DoS) if user attempts to scan a STM32MP15x device with any of supported adapters, requiring BMDA restart or probe reboot. This behaviour was enabled recently by Cortex-A related PRs. Previously BMD did not attempt to attach, halt, or otherwise touch CA7 during scan/probe.
* This is more a fix than a feature, but introduces registers not touched previously.
* The pull request solves an existing problem of BMD hang upon trying to even scan STM32MP15x SoC.
* To solve this, the pull request implements checking and clearing OSLock in ARMv7-A Debug registers.
It took three consecutive days of log analysis from different adapters and gdbserver software with help and suggestions from Dragonmux to come up with some working fix.
Our working …

Fix: Avoid a hang in scanning Cortex-A of STM32MP15x

---

src/remote.c
src/target/adiv5.h
src/target/adiv5_jtag.c

This PR seeks to address a crash-inducing bug reported by ALTracer on Discord. Under certain conditions during failed communications with a target over the remote protocol, `dp->error()` is called and the remote protocol layer in the firmware was improperly initialising the faked DP structure it uses, resulting in an attempted call through a NULL function pointer.
This patch addresses this problem for both JTAG and SWD over remote protocol + documents that structure a bit to help prevent future problems.
Tested by ALTracer against the STM32MP157 with which this bug was found and triggered.
This bug has existed in the firmware since about 3 years ago and does affect v1.7, v1.8 and v1.9 - we may wish to backport it at least to v1.9 because of this.

Fix: Remote protocol target communications initialisation

---

src/target/cortexa.c

In #1628 handling for the Cortex-A/R register for "OSLock" was introduced into `cortexa_probe()`, but this handling doesn't quite go far enough as it's possible for software running on the core to re-set this bit between the core being resumed and its next halt.
This PR address that by moving that logic into cortexa_halt_poll() so it gets applied every halt so we reduce the chances of getting stuck unable to set ITRen and so unable to launch instructions on the core that enable us to do debugging.

Fix: Cortex-A halt handling of OSLock becoming set between resumption and the next halt

---

src/platforms/native/platform.c

ALTracer was kind enough to point out on Discord that the timer setup code for BMP introduced in #1615 also wound up introducing ~400 bytes of extra Flash usage for a single function - `timer_set_oc_mode()` - so this PR, in combination with some changes to libopencm3, addresses this.
This results in a 332 byte saving.

Fix: timer setup Flash usage

---

src/platforms/stlink/README.md

This PR adds the pinout documentation figured out in #1632 to the README.md for the ST-Link platform.
While we aren't very satisfied by this representation of the pinout, it starts to address the documentation issue of the stlink and swlink platforms a touch.

Fix: Added pinout documentation to the stlink platform

---

src/target/stm32f1.c

mm32: typo in comment

---

src/target/cortexm.c
src/target/cortexm.h
src/target/lpc40xx.c

Scanning an unknown ARM Cortex M4F (TM4C1294KCDT) microcontroller crashes BMDA while running lpc40xx_probe, as that did not check to make sure that the (potential) core being probed was only a M4 (not a M4F). From discussing this with dragonmux, this adds in a check for that at the beginning of the probe routine.

Fix LPC40xx crash with hosted

---

src/target/adiv5.c

This provides an escape out of the AP initialization process for Tiva processors (like the TM4C1294KCDT) that incorrectly report the same AP multiple times. Developed in discussion with dragonmux when adding support for the aforementioned processor
Note that as this specifically checks for the string `Tiva` in the driver field, this does not prevent an unknown-to-BMP (Tiva or other) processor from spitting out 255 extra APs (or however many the native hardware will do before running out of memory).

Workaround for TM4C AP duplication

---

UsingRTT.md
UsingSWO.md
src/command.c
src/platforms/hosted/cli.c
src/target/adiv5.h
src/target/adiv5_swd.c
src/target/jtag_scan.c

The purpose of this PR is mainly to update the SWD naming (from SW-DP to SWD ) in the SWD scan commands, since the command itself has already been renamed, it also reflects the rename of the swd scan command in the documentation, and fixes a typo and some comment farming

Fix: swd command message swd naming

---

src/platforms/hosted/platform.c

This PR addresses an issue found with @desertsagebrush's help where the AP for a request would always be decoded for DEBUG_PROTO display as being AP 1.
This PR also addresses the same function's (`decode_access()`) handling of the AP/!DP bit in the address value passed to it.

Fix: BMDA AP access decoding

---

src/platforms/common/stm32/timing_stm32.c

The function `adc_start_conversion_direct()` is only defined for STM32F1, and not for STM32F4.
This caused a compilation issue for STM32F4 based boards.
This pull request fixes this issue, as described in #1644, by adding a check if the platform is based on an STM32F1.
Fixes #1644

Fix: platforms/common/stm32: fix for adc_start_conversion_direct not being defined for STM32F4

---

src/platforms/common/blackpill-f4/blackpill-f4.h

This pull request fixes the issue that LED_IDLE_RUN is not working on the blackpill-f4 platforms when it is assigned to PC13, the onboard LED. The issue is caused by the need to set PC13 to low to turn the LED on, rather than to set PC13 to high to turn the LED on.
The root cause of this is the schematic of how the LED is connected to PC13:
3.3v -> R 1k -> Blue LED -> PC13 ([reference](https://stm32-base.org/assets/pdf/boards/original-schematic-STM32F411CEU6_WeAct_Black_Pill_V2.0.pdf)).
This pull request fixes the issue described, by inverting the state used by for SET_IDLE_STATE. This results in setting PC13 to low when the state is true, and PC13 to high when the state is false. This is exactly the behavior needed to turn the LED on when the state is true.
This issue is a partial fix to …

Fix: platforms/blackpill-f4: invert state of SET_IDLE_STATE

---

src/gdb_main.c
src/include/target.h

This PR fixes a clang-tidy lint in `gdb_main_loop()` and adds some documentation to the target_halt_reason enumeration. It does not materially change the firmware (the assignment removed is provably unused) and this PR serves as a predicate to #1657 which presently contains a merge commit for the branch.

Feature: gdb_main.c cleanup

---

src/Makefile
src/target/at32f43x.c
src/target/cortexm.c
src/target/stm32f1.c
src/target/target_probe.h

* This can be considered a new feature, but in essence is old code cloned/ported/refactored to suit Artery targets.
* The previous PR #1540 attached `stm32f1_flash` routines to AT32F435 targets and this doesn't work.
* This PR implements mandatory erase/write routines specifically for AT32F43x so that it's actually possible to reprogram target flash.
ARTERY AT32F435 (and F437) series chips have a flash controller which is similar in operation to `stm32f1` but have its register base at 0x40023C00 like `stm32f4`. It has even sectors (all the same size, 2048 or 4096 byte pages) unlike most `stm32f4` (or `gd32f4`) targets, and requires selecting sectors to erase by their address, not sector number. I considered using code in one of these target drivers but the difference are too significant. …

Feature: AT32F435/F437 flash programming

---

src/target/lmi.c

Add support for the TI TM4C1294KCDT processor. This is largely the same as the TM4C1294NCDT, although with less flash (512 KiB versus 1 MiB). With the fixes from earlier, this works on native and hosted/BMDA platforms.
Additionally, I added some extra documentation around some of the preprocessor defines to give a bit more context about what is being masked in the ID registers; I'm glad to drop this if it seems like too much.

Feature: add support for TM4C1294KCDT

---

src/target/jtag_devs.c
src/target/jtag_devs.h
src/target/jtag_scan.h

This fixes potentials issues that one may run into when they have a scan-chain with an Xilinx FPGA on it, as not all Xilinx FPGAs have the 6-bit IR. The documentation such as UG570[^1] states that the IR is 6-bits as a general rule of thumb, however one must consult  the device specific BSDL[^2] files in order to divine the correct IR length for any given device.
Upon consultation of the BSDL models provided by Xilinx, it is made apparent that the following IR lengths are present: 6, 12, 14, 18, 21, 22, 28, and 38. While the vast majority of the devices are in-fact 6-bit wide IR devices, the chance of encountering a device with one of the other IR lengths is reasonably high.
Rather than individually listing each device ID and it's IR length, effort has been made to reduce the device ID …

Fix: proper IR  quirk handling for Xilinx FPGAs

---

src/platforms/hosted/dap_swd.c
src/platforms/hosted/jlink_swd.c
src/platforms/hosted/platform.c
src/remote.c
src/target/adiv5.h
src/target/adiv5_swd.c

Noticed while working on the multi-drop handling, that a couple error handling routines could be replaced by the default error handling routine (J-Link and DAP), but this needs to be tested and validated to be true.

Feature: SWD error handling deduplication

---

src/platforms/common/blackpill-f4/Makefile.inc
src/platforms/common/blackpill-f4/README.md
src/platforms/common/blackpill-f4/blackpill-f4.h

This pull request implements a new `SHIELD` macro for the blackpill-f4 platforms.
The SHIELD macro is used to compile the blackpill-f4 code for the use case when a printed circuit expansion board (also known as shield) is used with one of the blackpill-f4 boards.
If the SHIELD macro is passed to make, other macros are defined. If SHIELD is defined, the platform is able to power the vRef pin using the PWR_BR pin. Therefore the PLATFORM_HAS_POWER_SWITCH is defined. If SHIELD is defined and ALTERNATIVE_PINOUT is not defined, the ALTERNATIVE_PINOUT 1 is selected.

Feature: platforms/blackpill-f4: add SHIELD macro

---

.envrc
.gitignore

Quality of life improvement for [nix-direnv](https://github.com/nix-community/nix-direnv) users:
When such a users cd's into the blackmagic repo dir, direnv let's them know that a development environment is available. The user can opt-in to using it, which immediately imports the devshell that is described in the `shell.nix` already present in the repo. In contrast to just running `nix-shell` from the repo root, the direnv integration defaults to using the currently installed nixpkgs checkout, instead of picking the pinpointed version from the repo. Given the generic nature of the `shell.nix`, this is likely not less robust than the pinpointed version from `shell.nix`, and it saves a lot of time upon first execution, as no completely unrelated nixpkgs checkout has to be fetched.

misc: add nix-direnv integration

---

src/platforms/hosted/platform.c

This PR fixes a small bug that crept in when merging #1549 due to the API change in `decode_access()`.
This broke the build due to a missing parameter.

Fix: BMDA SWD no_check routines

---

src/target/samd.c

In the Device Identification Register (DID) of samd mcu's, the "series" field is 6 bit, and the "family" field is 5 bit.
This PR sets the correct masks for these fields. 
See also #571, #1162 and #1659.

samd: fix device id register masks

---

src/target/target.c

* Some remote monitor messages of BMD are formatted improperly.
* This pull request fixes this UX problem by cosmetically editing some message strings.
This is how it was rendered:
```
(gdb) mon erase_range
usage: monitor erase_range <address> <count>        <address> is an address in the first page to erase        <count> is the number bytes after that to erase, rounded to the next higher whole page(gdb)
```
This is how it should look:
```
(gdb) mon erase_range
usage: monitor erase_range <address> <count>
<address> is an address in the first page to erase
<count> is the number bytes after that to erase, rounded to the next higher whole page
(gdb)
```
And the `Mass erase not implemented for target_s(gdb)` error I got while using STM32MP157 Cortex-A7. For Cortex-M4 it somehow assigned …

Fix `monitor erase*` usage messages (UX)

---

src/platforms/hosted/jlink.c

* Trying to use BMDA with JLink adapters may raise a LIBUSB_ERROR_OVERFLOW under specific conditions.
* This pull request solves this problem by properly anticipating full-length responses in USB read calls.
RM08001 states that the IO TRANSACTION (JTAG3) command should return TDO (or SWDIO) data according to requested nBytes length, like JTAG2, and one more byte for OK status from adapter (or nonzero error). Requesting that in two libusb calls may not work on [my] setup and render BMDA inoperable with this adapter type.
Reading some libusb docs I figured that we should optimistically request a read for length of entire possible packet, then check whether we got handed that 1 byte less (apparently some firmwares give it in a separate bulk packet), and only then do a second read for it. The …

Fix: libusb overflow with JLink

---

src/target/jtag_devs.c
src/target/stm32f1.c

This PR fixes a bug pointed out to us by ALTracer on Discord where passing ENABLE_DEBUG=1 for the firwmare without also passing ENABLE_RISCV=1 would result in a broken build due to missing preprocessor logic in jtag_devs.c

Fix: RISC-V vs ENABLE_DEBUG=1

---

src/platforms/hosted/serial_win.c

This PR fixes a bug in platform_buffer_write() for Windows which would make wrongly it skip chunks of the buffer to write, corrupting the message to send.
This should probably be backported to v1.10 and v1.9.
This bug was introduced in v1.9.0-rc0.

Fix: BMDA remote protocol writes

---

src/target/riscv32.c
src/target/riscv64.c
src/target/riscv_debug.c
src/target/riscv_debug.h
src/target/riscv_jtag_dtm.c

In this PR we implement support for the RISC-V debug 'System Bus' (sysbus) component, as not all targets have to nor do implement the memory I/O abstract command. This complicates things but is required to support, eg, the ESP32-C3.
To accomplish this, we have to deal with sysbus having made all I/O widths optional to support while also needing to be able to do any arbitrarily sized and aligned read/write. The one benefit is that, depending on implementation, sysbus may be used without halting the Hart, unlike the abstract command interface which requires it halted (read: due to it injecting an instruction stream into the core to run the read/write, though this is strictly an implementation detail).
Unfortunately, this puts the burden of performing the I/O correctly on us, but we've …

Feature: RISC-V System Bus support

---

src/command.c

This PR 
- replaces the "%p" format with "%x", keeping existing functionality, but saving a few bytes flash.
- documents how to use "mon heapinfo" 
- see #1676

command: Convert format-string in heapinfo

---

src/include/general.h
src/target/riscv32.c

This PR addresses an oversight of #1683 resulting in a build error when `ENABLE_DEBUG` is not true.

Fix: Missing RISC-V debug guard

---

src/gdb_hostio.c
src/target/cortexm.c

* The problem is BMP's implementation of semihosting via GDB File-I/O (not BMDA) has been broken since #1284. Some attempt was made in #1432 to make it at least not crash the adapter.
* The PR solves the problem by introducing a second loop to service GDB packets before/other than F-reply.
I based the WIP tree on PR1432 single commit v1.9.0-435-g906f8878 backported to just past PR1284 merge, v1.9.0-55-g5cf0dd27. I had to enable DEBUG_GDB, DEBUG_GDB_WIRE and drop a bunch of drivers to fit into `swlink`, because my adapter of choice (blackpill-f411ce) did not exist until approximately v1.9.0-700 in usable form. The logs from BMP internals were **critical** for understanding how RSP packets go missing.
Current patch adds a `while(true)` loop at stack depth of 9 functions to allow for parsing …

Fix: Semihosting in BMP

---

src/gdb_hostio.c
src/gdb_main.c
src/include/gdb_packet.h

* This is not a functional feature; rather, an attempt to reduce unexpected behaviour, especially in BMF.
* The problem is many printf-like calls in BMD core code are not checked by compiler for their correctness.
* This pull request solves this problem by marking the printf-like functions with format attributes. Where applicable, this PR also tries to fix appearing warnings.
I deal here only with `gdb_voutf()` and `gdb_putpacket_f()`, as their direct usage (with dubious specificators, specifically) is less numerous. Let someone else deal with all the `tc_printf()`.
I am build-testing the changes for `native` on Linux amd64, and for `swlink` which is armv7-m. Runtime testing pending -- there is no code coverage tooling, so I have to reason about which aspects need testing, like GDB remote …

Fix: -Wformat in gdbserver (gdb_main, command, gdb_hostio)

---

src/platforms/common/usb_serial.c

Hi,
I was looking into usb-cdc-acm implementations to understand the required descriptors/endpoints when I found something that's probably a bug:
It looks like usb cdc acm notifications are sent from the data endpoint in `usb_serial_set_config()`
instead of the notifications endpoint. The function `usb_serial_set_state()` is called twice more in this file, but with notification endpoints as argument.
https://github.com/blackmagic-debug/blackmagic/blob/main/src/platforms/common/usb_serial.c#L106
https://github.com/blackmagic-debug/blackmagic/blob/main/src/platforms/common/usb_serial.c#L144
`make PROBE_HOST=native` fails for me for both pre & post fix, due to firmware size overruns, but I've tested an stlink / blue pill build which works.
I was expecting the wrongly sent data to come out of …

send initial usb cdc notification from the correct endpoint

---

src/gdb_main.c
src/include/general.h
src/include/target.h
src/platforms/hosted/gdb_if.c
src/rtt.c
src/target/adiv5.c
src/target/ch32f1.c
src/target/kinetis.c
src/target/msp432p4.c
src/target/renesas.c
src/target/target.c
src/target/target_flash.c
src/target/target_internal.h

This includes several fixes that help to build under MSVC. In particular, this helps me to build blackmagic as a module under Rust, which effectively uses Cargo to drive MSVC.
There are two broad classes of fixes:
1. Pointer math on `void *` was replaced with pointer math on `uint8_t *` where necessary. This is because MSVC refuses to compile this type of code, ahd it's UB anyway. It was assumed that `void *` math is the same as `uint8_t *` math.
2. VLAs are totally unsupported. While there is a desire to remove them entirely from BMP, they were replaced with `alloca()` instead.
There are additional fixes for missing features on MSVC, however this includes most of the fixes in my local branch.

Msvc fixes

---

src/target/riscv_debug.c

When #1380 was merged and the source branch deleted, it closed a follow-up PR which adds handling for a quirk of how WCH RISC-V devices work in regards their trigger slot information registers. This PR re-introduces that fix along with a short explainer on why it's needed and what it's doing.

Fix: RISC-V missing quirks

---

src/target/adiv5.c

This PR addresses a memory leak of the AP structure for Tiva-C targets due to a missing unref in the part-specific bailout path in `adiv5_dp_init` used to avoid re-scanning the same AP multiple times due to a hardware bug.

Fix: Tiva-C AP leak

---

src/target/cortexar.c
src/target/imxrt.c
src/target/msp432e4.c

Debug print statements were added that cause build breakage on ESP32 Xtensa targets.

Fix xtensa formatting

---

src/command.c
src/gdb_main.c
src/include/general.h
src/platforms/hosted/Makefile.inc
src/target/cortexm.c

* The problem is BMDA fails to build from source (FTBFS) on FreeBSD because of no `<alloca.h>` and missing hidapi-hidraw.
* PR solves this by purging all (3) of alloca.h references in light of #1661 and guarding the remaining inclusion by OS-specific macro. And adding a proper/available hidapi library name.
Tested on NomadBSD 13.2-RELEASE and a bunch of cheap adapters I have. `HOSTED_BMP_ONLY=0`. CMSIS-DAP (Picoprobe, free-dap) are detected, opened in v2/bulk mode and result in successful scan of an empty chain (nothing wired up). BMP-compatibles work only after indicating a `--device /dev/ttyU0` and under root privileges (there is no `/dev/serial/by-id`); including scanning SWD and attaching to a Cortex-M target. JLink and STLink/v2 result in a crash in `libusb.so.3.0.0` …

Fix building `hosted` under FreeBSD

---

src/gdb_packet.c
src/platforms/common/stm32/gdb_if.c

* This is not a new feature.
* The problem existing on stm32f4/dwc2 platforms is full busy-polling between gdb interactions, whereas the stm32f1 platforms sleep (WFI). Also under DEBUG_GDB any BMP will spam "Enabling NoAckMode" to ttyBmpTarg.
* This PR solves the problems by updating the gdb interface to also WFI when no data is received (in stm32f4/f7 specific part); and by gating the logging statement to only log on actual state changes.
First problem discovered by running orbtop over swlink against blackpill-f4; second problem discovered earlier in the process of fixing semihosting.
Also update the `cpsid i; isb` to more idiomatic style and to use libopencm3 API (there's no __ISB(), like there is CMSIS).
There seem to be no issues highlighting this, and I rarely report issues myself.

Fix: allow gdbserver to idle more

---

src/target/cortexar.c

This PR fixes/improves the diagnostics in the Cortex-A/R memory IO routines so we get comparable debugging information to the Cortex-M memory IO routines to aid with debugging target support.
This wound up being a problem we needed solved when writing the Renesas RZ/A1LU support which is an upcoming PR.

Fix: Missing Cortex-A/R memory IO diagnostics

---

src/platforms/hosted/remote/protocol_v0_jtag.c
src/target/adiv5.c

This PR comes after a UBSAN issue was found by ALTracer on Discord which involves a missing widening cast needed to legalise the packet data in shifting in the BMP remote protocol v0 JTAG implementation.
This is because C defines left shifting by more than a type's width to be undefined behaviour so we have to pre-widen the data to resolve this.

Fix: Remote protocol UBSAN error

---

driver/99-stlink-plugdev.rules

There is a typo in the udev rules

Typo fix in udev rule

---

src/platforms/common/blackpill-f4/blackpill-f4.h

* This is not a feature, but may affect external/out-of-tree features (like direction GPIO for bus turnaround).
* The existing problem is a long function call to gpio_mode_setup() in the process of high-performance bitbanging of SWD on `blackpill-f4` family of platforms.
* This PR solves the problem by porting inline code / macros existing in other platforms.
Testing on fix/tap-timing branch with a blackpill-f411ce in max frequency (~8MHz) against a STM32MP157_CM4 shows an increase of performance of loading a 64 KiB binary into RETRAM from 156 to 180 KiB/s. Impact may be less noticeable when using Flash-based targets, or using this BMF with BMDA as proxy.
I'll mention that stlinkv3 also toggles a GPIO wired to direction pin of a bidirectional level translator in the respective macros. …

Fix: Speed up bus turnaround for blackpill-f4 like other platforms

---

src/include/general.h
src/include/maths_utils.h
src/maths_utils.c
src/platforms/common/swdptap.c
src/platforms/hosted/dap_swd.c
src/platforms/hosted/ftdi_swd.c
src/platforms/hosted/jlink_swd.c
src/platforms/hosted/stlinkv2.c
src/target/cortexm.c

This PR is aimed at two problems:
* Problem 1: swdptap of firmware references both popcount and parity builtins to do the same task (of calculating SWD parity), and `__popcountsi2(): 40 bytes` is more expensive. Solution 1: create a shim/dispatcher in maths_utils, name it `swd_odd_parity` and call *that* from swdptap (the gpio-bitbanging one). This leads to cleaner code at that callsite, and less flash space occupied
* Problem 2: *_swd.c `hosted` adapter driver backends also want to calculate parity, and also do that via both popcount and parity builtins. MSVC does not provide these builtins, only the `__popcount` for x86-64 optional instruction. Solution 2: incorporate this _MSC-specific builtin as well into the shim, and tweak all said `hosted` parity calculations to call the shim.
This …

Fix: extract method for SWD parity calculation

---

src/platforms/native/platform.c

DFU detach wasn't lowering the USB pullup. This meant that BMP was rebooting into DFU bootloader mode, but the host wasn't re-enumerating it, because it hadn't detected a detach.
In `platform_request_boot`, The `gpio_set_mode` config was for analog instead of floating input. PA8 isn't defined as an analog pin on this chip, so it's arguably undefined behavior.
Also confirmed that using `scb_reset_system` instead of `scb_reset_core` to do the DFU reboot would correctly detach and enter the bootloader, if the boot button was held down.

native/platform: fix DFU detach

---

src/platforms/common/swdptap.c
src/target/adiv5_swd.c

There were multiple problems with SWD turnaround. In the write-to-read direction, a short clock pulse could be produced (#1706). When terminating a read transaction, the clock wasn't driven low. If a subsequent clock float was requested, as for a detach, the clock would float low, then be driven high when re-enabled, causing an extra rising clock edge.
Additionally, idle cycles weren't being inserted as required after a read transaction.
There's a small chance of a regression with targets that pull the SWD clock high.
Fixes #1706.
These are debug logs from BMDA.
Log excerpt from unpatched, attaching after detaching. Note the non-response error after re-enabling the clock.
```
!SI20#
K2000497C
remote_v0_swd_seq_in_parity 32 clock_cycles: 2000497c OK
Read RDBUFF: 0x2000497c
!GE0#
K0 …
```

fix SWD turnaround issues

---

src/crc32.c
src/gdb_main.c
src/include/crc32.h

* On the scale between "fix" and "feature" this is closer to "fix".
* The existing problem is suboptimal performance of `(gdb) compare-sections` because of extra ADIv5 MEM-AP setup overhead.
* This PR solves that by increasing the stack buffer inside `generic_crc32()` from 128 to 1024 bytes.
There is an intentionally separate commit which adds DEBUG_INFO logs displaying "KiB/s" metric to BMDA, and copies that (ms and KiB/s) to the implementation for STM32 CRC IP enabled platforms. I avoid this calculation for small sections/regions (abundant in some firmware projects) for integer precision and overhead reasons.
On my quest to increasing runtime performance such that BMP-compatibles are more usable (Quality of Life for developers) against targets with Big Flash and with RTT, following (and …

Fix: qCRC performance uplift

---

src/crc32.c

* Not a new feature.
* The existing problem is MacOS/darwin failing to build from source due to `aliases are not supported on darwin` after #1711
* This PR solves the problem by replacing the mechanism used to keep distinct function names.
During writing PR1711 I applied the `DEBUG_ERROR("%s: ...", __func__, ...)` idiom, removing the `generic_crc32` name message-string from `stm32_crc32()` renamed implementation in the process. To keep the proper function names and avoid complicating the single callsite in `gdb_main.c`, I introduced a GCC-specific extension `__attribute__((alias("")))` to substitute jumps at link time. This does not fly on MacOS (Mach-O limitation vs. ELF), and I'm unable to test for that desktop platform. Note that this is fine on `arm-none-eabi-` adapters and Linux …

Fix: Replace attribute alias in CRC32

---

src/target/stm32h7.c

* This sounds like a feature (target flavour support).
* The existing problem is STM32H7 driver declaring the memory map of H74x for all chips detected, even if there are ID codes for H72x and H7Bx.
* This PR solves the problem by adding different parts of the memory maps, dispatched on part ID.
Flash cost is around +170 bytes. I am not sure whether contiguous regions composed of different SRAM banks should be added as such (increasing detail, but also BMP flash footprint and memory impact for memory-map.xml) or as single long regions. I tried keeping the common regions (ITCM and DTCM) unified, but a portion of DTCM can be aliased on some flavours (see RM).
I could only test on Nucleo-H743ZI2 and WeAct Studios MiniH723 boards. H72 has smaller regions and total amount of SRAM than H74. I …

Feature: Increase SRAM layout detail for STM32H7 chip variants

---

src/platforms/common/stm32/serialno.c

* This can be considered a new feature (because I don't see how it was usable previously)
* There is an existing problem of BMPBootloader with `DFU_SERIAL_LENGTH=13` becoming larger than 16 KiB due to `siprintf` pulled from newlib (not nano).
* The PR solves this problem by replacing the single expensive `sprintf()` call with a few calls of simpler functions and introducing a variant of `utoa()`.
12-symbol serialno consists of three halfwords calculated by pulling 16-bit values from Device Electronic Signature memory. I don't believe `hexify()` can be useful here.
I would not like to choose to mitigate this by downgrading the F4 BMPBootloader to newlib-nano because it would provide a small and inefficient memcpy, which is important for flash writes/upgrade reprogramming speed. And it's …

Feature: Space-efficient 12-symbol serialno generation

---

src/platforms/common/blackpill-f4/Makefile.inc
src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/blackpill-f4.h

* This is a new feature common to other platforms but missing from this one.
* There is an existing problem of no log traces available on `blackpill-f4` family of platforms.
* The PR solves the problem by adding required pieces and fixing linker flags.
How to reproduce the issue: build with `PROBE_HOST=blackpill-f411ce ENABLE_DEBUG=1`, optionally also with `BMP_BOOTLOADER=1`, upgrade/flash to the board, open gdb, ask for `monitor debug_bmp enable` (aka "mon debug en") -- `Target does not support this command.` Even though the binary is 40 KiB bigger.
I've been carrying the patches to use logging on my platform of choice since probably June 2023, which is when I started using the project, and I'm tired of unstashing them on top of every feature branch I'm testing just to see some important …

Feature: Working logs on `blackpill-f4` via DebugMon

---

src/platforms/common/stm32/timing_stm32.c

Added an error counter to address an occasional glitch, where a threshold violation is detected during normal operation.
Now we need to count 3 threshold violations to trigger the protection mechanism.

Fix: Momentary bandgap reference read glitch

---

src/platforms/hosted/serial_unix.c
src/platforms/hosted/serial_win.c

After having a couple of conversations with ALTracer about the speed and performance of BMDA interacting with the firmware, we realised that the current 1-byte-at-a-time solution for reads, while correct, is extremely far from performant but there's a simple solution to the problem that doesn't sacrifice correctness - slipping a large buffer in between the reads and the reading.
This PR addresses this by adding a 4KiB buffer in between the probe reads and BMDA's platform_buffer_read() on both Linux/macOS and Windows. This significantly reduces the number of syscalls being made and streamlines the data transport through BMDA from the probe. A reasonable speedup on current firmware was observed with no drawbacks.

Feature: Faster BMP -> BMDA communications

---

src/command.c
src/target/cortexar.c
src/target/stm32l4.c

This PR addresses some of the new warnings being produced under Meson which uncovered some additional printf-style format string mistakes that were being made.

Fix: target printf style format cleanup

---

src/gdb_main.c
src/hex_utils.c
src/include/hex_utils.h
src/include/target.h
src/platforms/hosted/bmp_remote.h
src/platforms/hosted/remote/protocol_v0_jtag.c
src/platforms/hosted/remote/protocol_v0_swd.c
src/remote.c
src/remote.h
src/target/cortexm.c
src/target/cortexm.h
src/target/semihosting.c
src/target/semihosting.h
src/target/semihosting_internal.h
src/target/target.c
src/target/target_internal.h

This PR addresses the correctness of the semihosting implementation in BMDA and represents the last in the series.
We do this in two major steps - fixing the mechanism by which I/O with the probe is done for SYS_FLEN, SYS_TIME, and SYS_READC which solves issues with how GDB sees these transfers; and then fixing how and when BMDA inserts its own libc syscalls in to speed things up.
This also provides support for BMDA to do stdio redirection just like the firmware, so the user gets the expected behaviour by default (semihosting output and interaction in GDB), while then being able to punt that onto the controlling TTY for BMDA.
As best as we can tell, with this PR we now have a conforming semihosting implementation that works the same in both firmware and as BMDA and which meets the …

Fix: semihosting BMDA correctness

---

src/platforms/hosted/bmp_hosted.h
src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/cmsis_dap.c

This PR fixes the way the CMSIS-DAP code handles adaptor packet sizing and the differences between HID and Bulk endpoint (v1 and v2) based firmware.
Tested working against ORBTrace and picoprobe (which is based directly on the ARM reference implementation).
This finally solves the mystery too of how the packet size and buffer interact with one another and the HIDAPI code, documenting this properly.

Fix: CMSIS-DAP packet size handling

---

src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/usbdfu.c
src/platforms/common/stm32/dfu_f4.c

* This looks like a feature to end users but is just a collection of tweaks and ported code.
* The existing problem is an inefficient DFU configuration for `blackpill-f4` family of platforms (and probably other STM32F4 boards).
* This PR solves the problem by tightening DFU F4 delays, introducing an LED show/blinky in BMPBootloader (usbdfu), and provisioning it all to fit under 16 KiB for optimal reachable performance.
The first couple commits belong to the serialno PR this PR is based on (or blocks on). I fail to see what mechanism checks that the usbdfu binary fits under the allocated space (8 1-KiB sectors for F1, first 16 KiB sector for F4, etc.), but I noticed that flipping the DFU_SERIAL_LENGTH from 9 to 13 pulled sprintf and bloated the dfu binary past first sector. See that PR for …

Feature: Fancy DFU on `blackpill-f4`

---

src/target/target_probe.c

@dragonmux got a report on Discord that the weak aliasing of probe functions caused a linking error on macOS. I was able to reproduce the issue by building BMP once with `-Dprobe=''`, then reconfiguring with `-Dprobe='native'` and rebuilding.
Upon looking into the functions with Binary Ninja, I realised that the true issue was that AppleClang does not support aliases *at all*. Therefore, when saying "attribute weak" on the probe declaration, since the alias never takes effect, the linker would then expect a framework or library to supply the symbol [1].
The fix is to define a weak linkable pivot that will call the alias. If a strong definition appears later, the linker will emit just that definition. Otherwise, it'll emit an overridable pointer to the weak definition in the symbol table. …

target: properly fix weak aliasing of probe NOPs on macOS

---

meson.build

Add wether firmware and BMDA are being built to the summary output
This just adds a couple entries to meson configuration summary output, telling the user if it's configured to build firmware, and if it's configured to build BMDA, given that the following situations are possible:
- building firmware and BMDA
- building  firmware but not BMDA
- building BMDA but not firmware
Some feedback as to which one we are in felt needed.
* [c] My commit messages provide a useful short description of what the commits do

meson: add build target feedback to summary

---

src/platforms/common/stm32/gpio.h
src/platforms/common/swdptap.c

Fix a few instances of undefined behavior (that I'm not yet aware of any concrete consequences of) in left shift expressions. Roughly, it's undefined behavior to shift a `1` into the sign bit of a signed type.
Operands in bit shift expressions undergo integer promotions, but not the usual arithmetic conversions. Notably, the second operand can't promote the first operand to unsigned. Shifting `1` rather than `1U` can lead to shifting a `1` into the sign bit, causing undefined behavior.
Relatedly, the integer promotions on a 32-bit platform will usually promote `uint16_t` to a signed `int`, leading to undefined behavior in left shift expressions.
* No new feature
* No known existing misbehavior or incorrect code generation, though it's theoretically possible
* This fix increases standard …

common: fix UB in some bit shifts

---

.github/workflows/build-pr.yml
src/include/target.h
src/main.c
src/platforms/common/usb_serial.c
src/platforms/hosted/Makefile.inc
src/platforms/hosted/stlinkv2.c
src/platforms/hosted/utils.c
src/platforms/launchpad-icdi/platform.h
src/platforms/native/platform.c
src/platforms/stlink/platform.c
src/platforms/stlinkv3/platform.c
src/platforms/swlink/platform.c
src/platforms/swlink/platform.h
src/platforms/swlink/platform_common.c
src/platforms/swlink/platform_common.h
src/platforms/swlink/usbdfu.c
src/target/semihosting.c
src/target/semihosting_internal.h

In this PR we aim to tie up some loose ends from the Meson build system's introduction, including the spate of new warnings, and some low-hanging UB that attempting LTO builds finds.
With these changes building normally should now be warnings-free. This also cleans up from the semihosting PRs by moving some straggler enums to the correct files as much as possible and fixing naming around them.
This fixes some more of the classes of warning targeted by the list in #1590

Feature: declarations cleanup

---

src/platforms/hosted/serial_win.c

Following blackmagic-debug/bmpflash#12 which as part of the speed-ups fixes the timeouts configuration for the remote protocol on Windows, as BMDA has the same exact issue, this PR ports those same fixes over.
Tested on the same laptop and VM to validate we've not obviously broken anything.

Fix: BMDA Windows serial timeouts

---

src/platforms/stlink/Makefile.inc
src/platforms/stlink/platform.c
src/platforms/stlink/platform.h
src/platforms/stlink/stlink_common.c

The [stlink-isol-v2](https://estore.st.com/en/st-link-v2-isol-cpn.html) variant differs from other stlink-v2 variants with how the SWDIO pin is multiplexed. This commit adds support for it. I have tested the commit on my STlink ISOL and it seems to work fine.
N/A

Feature: Support stlink v2 isol variant

---

.pre-commit-config.yaml

v0.3.1 fixed a default encoding issue when running the pre-commit hooks on windows
Bump the pre-commit hooks to the new minor version, tagged after https://github.com/perigoso/pre-commit-hooks/pull/3
This should have no impact on the CICD or linux users

Fix: use v0.3.1 perigoso/pre-commit-hooks

---

src/gdb_main.c
src/include/general.h
src/target/renesas_ra.c
src/target/stm32f1.c
src/target/stm32f4.c

This PR addresses the Clang warnings about switch-case fall-through caused by it not understanding the magic comment `/* fall through */`. To do this we've introduced a new macro and definition logic to use the compiler attribute for the job.
Tested on GCC 12, ARM GCC 12 and Clang 18. CI build items should be added in the future but as CI needs an overhaul post-Meson-PR we'll do that in a separate PR.

Fix: Clang fall-through warnings

---

src/platforms/stlink/platform.h

This is a follow up to [PR1720](https://github.com/blackmagic-debug/blackmagic/pull/1720) where I used the Output Data Register of the GPIO peripheral, causing read modify write. Now we use BSRR and BRR which only require a single write. I benchmarked the speed(when flashing 128kb firmware file) of the probe after this patch and it seems to be very similar, however the code size is reduced by a few bytes and as we know - every byte counts
N/A

stlink: replace odr register for the isol variant

---

.github/workflows/build-pr.yml
src/include/general.h
src/platforms/hosted/meson.build
src/target/riscv_debug.c
src/target/semihosting.c
src/target/target_probe.c

This PR implements CI support for MSVC, Apple Xcode, and Homebrewed GCC for macOS.
For the latter two, dependencies are fetched from Homebrew as:
- `libftdi` depends on boost and others to be built from scratch
- GCC cannot build hidapi due to extensive usage of Objective-C constructs
This PR also includes the relevant fixes to make MSVC builds happy, in particular around standards compliance (#1742).
I'm open to any feedback. Let me know what you think!

Add MSVC and macOS coverage

---

src/command.c
src/platforms/hosted/cli.c
src/platforms/hosted/cli.h
src/platforms/hosted/platform.c

On BMDA, the scan routines set the interface frequencies according to command line options, always, meaning any changes by the user through monitor commands are overriden. This fixes that, this is a rather simplistic fix, that *just* resolves the issue, there is space for improvement on this code generally, but that would be more involved and can be done later.
This adds storage to the max frequency, meaning the frequency set by the user will be remembered over the initial command line value.
Before:
setting SWD frequency with mon freq 400000
immediately followed by a scan mon swd
```
Speed set to 0.400MHz for SWD
Speed set to 1.600MHz for SWD
-> jlink_swd_init(0)
Switching out of dormant state into SWD
jlink_swd_seq_out 32 clock_cycles: ffffffff
...
```
After:
setting SWD frequency with …

hosted: fix ephemeral max frequency

---

src/target/stm32mp15.c

* The problem existing approx. since 9a5e3e7b is `monitor revision` failing to report silicon revision of STM32MP15x device.
* This PR solves the immediate minor problem by adjusting the bitshifts in `stm32mp15_cmd_rev()` of DBGMCU_IDCODE to match the DEV_ID value.
Tested on a live device over both DP transports. IDC is 0x20016500.
Appending an issue here, in case I manage to fix both.
There is a related issue of MP15x having an erroneous 0x450 ID in JTAG mode matching H74x 0x450 (0x4500) ID in JTAG mode. This manifests as "STM32MP15 M7" detected by BMD instead of "STM32H7 M7" when scanning e.g. a Nucleo-H743ZI2 over 4-wire JTAG (its onboard ST-LINK/V3E is SWD-only). Fixing that involves editing similar IDCODE values in stm32h7.c to match stm32h5.c target driver style, and implementing …

Fix revision-reporting command for STM32MP15x

---

src/target/stm32h7.c

* The existing problem is incomplete revision printout in stm32h7 target driver.
* This PR starts fixing that by aligning part IDs with stm32h5 driver style.
There may be more changes needed, like using `ap->partno` or all-out reading of `DBGMCU_IDC` over whatever AP (and address alias) is appropriate.
I verified across 4 RMs that the documented revision hex values match to given letters on given chip families, so it's valid to attempt to match across entire array.

Fix `stm32h7_cmd_rev`

---

src/platforms/hosted/cmsis_dap.c
src/target/adiv5.c
src/target/adiv5.h
src/target/cortex.c
src/target/cortexar.c
src/target/cortexm.c

This PR addresses some of the speed concern with Cortex-A/R targets by speeding up (at least for the firmware) accesses that involve instruction launches using the AP banked register interface to improve throughput by reducing ADIv5 protocol overhead for the DBG_ITR, DBG_DTR{T,R}X and DBG_DCSR core debug interface registers.
Tested against the Renesas RZ/A1LU, this delivers at least a 5x speed up in the firmware and 3.75x speed up in BMDA.

Feature: Cortex-A/R speedups

---

src/target/riscv_debug.c

riscv: make the debugger stop on ebreak
This is a temptative bugfix for the (*)ebreak statement not working with the blackmagic probe
Without the modification, the ebreak is completely ignored.
This is problematic for flashstub and for chips that do not have triggers at all  (e.g. ch32v20x and ch32v00x)
The patch just enables the ebreak stop in the debug register. Not sure it is the righ way to do it but it works for me.
* [x ] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [ x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ out of flash but not related to my patch ] It builds for hardware native (see [Building the …

riscv: make the debugger stop on ebreak

---

src/platforms/common/stm32/dfu_f1.c

* Not a new feature.
* The existing problem is slow (suboptimal) DFU upgrade times of F103CB-based BMP-compatibles.
* This PR solves this problem by decreasing timeouts returned from BMPBootloader.
This commit from July 2023 resulted from a deeper look into `dfu-util` operation (and partially `bmputil`) and BMPBootloader DFU internals (usbdfu, dfucore, dfu_f1). Armed with some DFU operation specs and MCU datasheets for STM32F103CB and GD32F103xx, I added a bit of instrumentation (blinky on dfu_event) to `swlink` and tried to reduce the timings.
The logic is similar to `dfu_f4.c` in that there should be two different timeouts for page erase (1 KiB on F1) and buffer program (1024 because of `wTransferSize` over EP0) calculated from *typical* or *minimum* characteristic times (but not …

Fix: Declare smaller timeouts in F1 DFU to speed up probe upgrades

---

src/target/s32k3xx.c

printf-style formatting should use standard format strings in order to keep code portable across architectures.
This fixes the build on Xtensa targets.

s32k3xx: fix debug logging format

---

src/target/riscv32.c
src/target/riscv_debug.c
src/target/riscv_debug.h

* This adds basic support for hw single precision fpu (rv32)
* Without the patch gdb will reject the binary as the register list is incomplete
* This is not exactly the same as the patch posted in the bug report, it actually connects the registers
* With that patch on a CH32V307 , i can load the binary and print the registers with a value that looks correct (limited testing), seems ok for fs0, f1, fs2 , fs3
* Tested only on rv32
* May lack some CSR relatated to FPU declared as CSR , not clear.
* [up to linking then out of rom ] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
fixes #1765

riscv : add basic single precision hw float support

---

src/target/adiv5.c
src/target/adiv5.h
src/target/samd.c
src/target/samx5x.c

In response to a user report in Discord of troubles with part identification on an ATSAMD21E18A, we took a look into how the SAMD support code identifies parts that might be ATSAMD's and saw it manually reading out the DSU component and peripheral identifiers rather than using the information already in the target structure.
This PR replaces this logic by the normal target structure values which match up and are already checked. It does the same for the SAMx5x support as this does identical things to check for those devices.
Tested working on an ATSAMD11D14AM. We have no reason to suspect this will create any kind of regressions.

Fix: SAMD/SAMx5x part idententification

---

meson_options.txt
src/include/jtagtap.h
src/platforms/hosted/bmda_gpiod.c
src/platforms/hosted/bmda_gpiod.h
src/platforms/hosted/bmda_gpiod_platform.h
src/platforms/hosted/cli.c
src/platforms/hosted/cli.h
src/platforms/hosted/meson.build
src/platforms/hosted/platform.c
src/platforms/hosted/platform.h

This change adds a new backend/probe type to the "hosted"/BMDA platform which uses libgpiod to connect up the `jtagtap.c` and `swdptap.c` bitbanging routines to gpios.  This is of course linux specific.
* A meson build option is added to enable this backend, this only has an effect on linux and defaults to attempting to find the dependency but disabling the feature if libgpiod is not found.
* A new probe type for gpiod is added in the BMDA code.
* An include file is added which provides mappings from the `gpio_set`, `gpio_clear`, `gpio_get`, `gpio_set_val` routines to the libgpiod backed routines for compiling the jtagtap and swdptap code.
* A new cli option is added when the feature is enabled which allows the user to set a mapping of debug signals to GPIOs if this is specified then it …

libgpiod based BMDA gpio bitbang backend

---

.github/workflows/build-and-upload.yml
.github/workflows/build-pr.yml
deps/hidapi.wrap
deps/libusb.wrap

In this PR we update the BMDA dependencies libusb and HIDAPI. The fork of libusb we use for Meson support has been moved into the organisation and updated to v1.0.27. HIDAPI has been forked to fully Meson-ify it so we can avoid mesonbuild/meson#12761 which Xobs hit on his M3. This also locks HIDAPI to v0.14.0.
Note that in both cases, these are fallbacks for if the libraries and their build files are not found on a user's system, and so we will prefer the user's versions if possible w/ the build system allowing much older versions of both to be used.
Fixes #1774

Fix: Update dependencies

---

src/platforms/hosted/gdb_if.c

BMDA is supposed to listen for connections on both IPv6 and IPv4 if possible, this is accomplished by dual stack support when using an IPv6 listening socket.  However there are two problems that prevent this from working as intended.
* When `getaddrinfo` returns results the first result is not always the IPv6 address to bind to if one is returned.  To fix this the results are walked over to select the first IPv6 result if one exists.  The first result is used if no IPv6 address can be found.
* An IPv6 listening socket accepting IPv4 connections relies on the `IPV6_V6ONLY ` socket option being set to 0 (off, dual stack) on the socket before it is bound.  On windows this option defaults to 1 (on, v6 only) and must be explicitly disabled to allow dual stack listening sockets.  On linux this …

Fix dual stack listening

---

.github/workflows/build-pr.yml
deps/libftdi.wrap
src/platforms/common/blackpill-f4/meson.build
src/platforms/f4discovery/meson.build
src/platforms/hosted/meson.build
src/platforms/native/meson.build
src/platforms/stlink/meson.build
src/platforms/stlinkv3/meson.build
src/platforms/swlink/meson.build

This PR adds a Meson Wrap for libftdi1 to act as fallback if the user's system doesn't have the library. This completes the Wraps necessary for BMDA to always be enabled and always done as a full build.

Feature: BMDA libftdi1 Meson Wrap

---

src/platforms/native/platform.c
src/platforms/native/platform.h

This PR attempts to improve the re-enumeration situation on M3 silicon powered machines as the controller built into the M3 does not properly recognise our setting up the conditions for re-enumeration for re-entry into the bootloader as reported on Discord by @xobs.
We attempt to improve things by ensuring we drive the reset condition described by the USB 2.0 specification version 20230224 §7.1.7.1 Table 7-2 pg145:

Fix: BMP on M3 reenumeration

---

src/target/flashstub/rp.ld
src/target/renesas_rz.c

This PR addresses a couple of missed changes from two earlier PRs. The first is from the RP2040 Flash stub PR where the linker script used was forgotten. The second is from the RZ/A1LU PR where the mass erase handler was forgotten.

Fix: Missed changes

---

src/target/cortexm.c

Support for NXP ke04 series part is a little broken. More specifically, I tested the following for a S9KEAZN8* part:
Built with:
```shell
meson setup --wipe build --cross-file cross-file/native.ini -Ddebug_output=true -Dtargets=corte
xm,nxp
meson compile -C build
```
Flashed with:
```shell
sudo dfu-util -d 1d50:6018,:6017 -s 0x08002000:leave -D build/blackmagic_native_firmware.bin
```
Debugged with gdb-multiarch:
```shell
(gdb) mon tpwr enable
Enabling target power
(gdb) mon debug_bmp enable
Debug mode is enabled
(gdb) mon swdp_scan
Target voltage: 3.3V
Please report unknown device with Designer 0xe Part ID 0x0
No. Att Driver
*** 1   Unknown ARM Cortex-M Designer 0xe Part ID 0x0 M0+
2      Kinetis Recovery (MDM-AP)
```
Virtual Serial Port Output:
```shell
Switching out …
```

target/nxp: Re-enable ke04 support.

---

src/command.c
src/gdb_main.c
src/hex_utils.c
src/include/gdb_main.h
src/include/hex_utils.h
src/target/samd.c
src/target/semihosting.c
src/target/semihosting.h

The gdb packet parsing and some other firmware relevant code makes use of sscanf.  This is both somewhat prone to mistakes in usage which can result in undefined behaviour and constitutes a significant size of code in flash.
This set of changes removes usage of sscanf from the firmware relevant code, these are still a few uses in purely BMDA code but as that does not have the same space constraints I have not removed it at this time.
Most of the use cases for sscanf in the existing code has been for integer parsing, to fulfill this need with much less code required I have added a helper function read_unum32 which will read an unsigned 32 bit integer of arbitrary base from the given string.  This function provides a pointer to the rest of the string upon success.  It also includes an …

Remove usage of sscanf in firmware code to reduce code size

---

.clang-tidy

The .clang-tidy config file had previously been changed but left with indentation that resulted in an invalid map/sequence.
Fix the indentation so that the CheckOptions sequence is valid YAML again.
A previous change to the .clang-tidy config file in the repository messed up the whitespace resulting in invalid YAML.
Correct the whitespace back to valid YAML for a sequence containing maps.

Restore .clang-tidy config to valid YAML

---

src/target/jtag_devs.c

For the Artix 7 XC7A200T `./blackmagic.exe -jtv 63` would previously bail out with an unknown IR value. This PR adds the IR found on this chip.

Fix: Xilinx Artix-7 IR quirk for 6-bit IR found on XC7A200T

---

src/target/kinetis.c

This PR adds support for a MK20DX256 chip in `kinetis.c`. It specifies flash region, both RAM segments and FlexNVM. It doesn't, however, add support for FlexRAM that this chip features. That support seems to lack from all other kinetis targets too, I guess due to the complication that this region can be configured both as RAM and EEPROM.
One of the comments made on the branch was to use defines instead of addresses directly, which doesn't seem to be common practice in `kinetis.c`. So for now I added the values directly as function arguments. If that's still desired, I can make a change :)
The following was tested on Tiva ICDI platform, with GDB 8.3.1:
* load firmware to a MK20 target
* run target
* set & remove breakpoint
* set & remove watchpoint
* pause target, and while paused
* get …

Added support for kinetis MK20DX256 chip

---

src/gdb_main.c

When removing use of sscanf from gdb_main the calculation of the length of the remaining data portion of the 'X', 'M', and 'vFlashWrite' packet types was done wrongly. The difference between the start of data pointer and start of buffer pointer was reversed resulting in adding this to the total length rather than subtracting it.  For the 'X' and 'M' packets this causes them to accept lengths longer than the supplied data but correct packets would still function as expected. For the 'vFlashWrite' packet the length passed to the flash write function was about 8 larger than it should have been which could cause problems.
The calculation of the data length portion of the packets has been corrected so all three now work as expected.
Tested vFlashWrite with '-v 2' on BMDA to confirm the correct …

Fix remaining length calculation for 'X' 'M' and 'vFlashWrite'

---

src/platforms/hosted/stlinkv2.c
src/platforms/hosted/stlinkv2_protocol.h

* This is not a feature.
* The existing problems are 1) BMDA over STLINK/V2 (incl. onboard) adapter with original firmware failing to scan/attach to STM32MP15x; 2) RTT not working over these adapters (with errors "Too large!").
* The PR solves that by carefully using what's already there (apsel) and raising the block read limit to at least 4096.
On DK1, its onboard V2-1 is the only way to access and debug the SoC, but BMDA's support for that adapter used to assume AP 0 is the only one usable, which flies for simpler MCUs but not for this MPU -- it has AXI-AP at 0 with no debug components. A bug in the backend then resets `stlink.apsel` to 0 and next accesses targeted at Cortex-A (halt and) detection via APB-D AP 1 land at AP 0 and lock it up, rendering further debug impossible until next …

Fix STLINK/V2 operation with multi-AP chips and block reads

---

src/platforms/common/usb_serial.c
src/target/adiv5.h
src/target/stm32l4.c

This PR fixes some compiler warnings and CI complaints that had crept in. This includes a clang-tidy lint, a duplicated decl warning, and the clang-format oops that crept in via PR #1807.
These fixes are preparation for the STM32H7 support fix branch.

Fix: Tooling cleanup

---

src/platforms/common/stm32/timing_stm32.c
src/timing.c

This PR addresses an issue in the platform timeouts subsystem where the firmware will execute and handle timeouts very wrongly for a few seconds after ~49.7 days of uptime.
The gist of the bug is that as the time_ms counter approaches UINT32_MAX and platform_timeout_set() starts generating expiration times close to 0, the comparison for whether the timeout has expired will incorrectly determine that it has at the start of the timeout validity interval. This is incredibly wrong and will cause all manner of broken behaviour in anything that depends on timeouts to function properly.
We fix this by detecting this edge condition where the uptime counter has the MSb set and the expiration time does not and force the comparison to false. This is wrong if a timeout is requested that is …

Fix: Timeout mishandling issue

---

src/target/imxrt.c

* Existing problem is a compiler error for *firmware builds* with `DEBUG_TARGET()` log statements enabled (unusual configuration, unreachable through meson/Makefiles alone).
* The PR solves this problem by updating one macro guard.
This is a contextual follow-up to #1517, also see PR1533-PR1534, and really it's #1684 which enables *this* PR.
```c
In file included from ../src/target/imxrt.c:34:
../src/target/imxrt.c: In function 'imxrt_probe':
../src/target/imxrt.c:224:50: error: 'boot_mode' undeclared (first use in this function)
224 |         DEBUG_TARGET("i.MXRT boot mode is %x\n", boot_mode);
|                                                  ^~~~~~~~~
```

Fix: Simplify debug log guard in imxrt.c

---

src/target/stm32f4.c

This PR adds support for the STM32F410 which, while the ID existed in the implementation, was not plumbed in at all.
We have also taken the opportunity to address and sort out the write parallelism handling mess in the support implementation, greatly simplifying the whole lot and saving a good amount of Flash. It turned out our earlier suspicions (noted in comments in the code) about the psize handling were in fact correct.
Full debug and Flash support tested on the Nucleo-F410RB where all seems to be working properly even after a week straight of using the support to debug code on the board.

Feature: STM32F410 support

---

src/include/buffer_utils.h
src/target/stm32h5.c
src/target/stm32h7.c

In this PR we address the STM32H7 support being broken in a few different ways, and formalise the support for the H72x and H73x parts.
While trying to use the support for a project that's been going on, we ran into issues first with trying to Flash parts, resulting in this sequence:
```
stm32h7_flash_cr: patching FLASH_CR from 0x00000034 to 0x00000034
Erasing, ctrl = 00000034 status = 00000005
stm32h7_flash_cr: patching FLASH_CR from 0x00000030 to 0x00000030
stm32h7_flash_busy_wait: error status 00250000
Write failed at 8002790
stm32h7_flash_cr: patching FLASH_CR from 0x00000030 to 0x00000030
stm32h7_flash_busy_wait: error status 00250000
```
This is caused by the Flash writes not respecting the datasheet's 32 byte blocks point and trying to blast data at the Flash like other ST parts. …

Fix: STM32H7 support

---

src/Makefile
src/target/meson.build
src/target/stm32_common.c
src/target/stm32_common.h
src/target/stm32f1.c
src/target/stm32f4.c
src/target/stm32h5.c
src/target/stm32h7.c
src/target/stm32l4.c
src/target/stm32mp15.c

* This is a new feature expanding the existing stm32{h7,mp15} (potentially h5) UID-printing targe commands.
* The existing problems are plain hex in multiple O-packet and unused pattern/decode info.
* This PR solves these by buffering hex into a stack `char[]` (sprintf) and adding a small parser/decoder based on info from RMs.
TODO includes migrating sprintf usage to utoa (upper or lower) and testing the decoder on other families like STM32F4/F2/F7 which also include a Digital Electronic Signature containing Lot and Wafer info.

Feature: STM32 DESig UID decoder

---

src/target/efm32.c
src/target/sam3x.c
src/target/stm32l0.c

* The existing minor problem is inconsistency in usage of sprintf/snprintf in firmware (target drivers).
* This PR solves it by replacing (almost as-is) the three remaining `sprintf` calls as highlighted by `puncover` and `grep` / `the-silver-searcher` with `snprintf` which is used much more often.
Bonus points for bounds checking, as all touched cases deal with copying a runtime-constructed pattern into a target private storage struct, which has a fixed capacity, and it's cheap to take its size [and stuff into second argument] -- not invented by me, I was just looking at other callers of snprintf. There could be stricter bounds enforced, but I won't be researching that.
As measured on gcc-12 and `native` this drops a 64-byte `siprintf` shim function from current `main`, …

Fix: Replace `sprintf()` calls remaining in firmware with `snprintf()`

---

.github/workflows/build-pr.yml

@dragonmux just shared with me a macOS build log, and I noticed that it started to fail because Homebrew has started deploying GCC 14.1.
This PR ensures that Homebrew can cleanly deploy earlier versions by unlinking the version provided by GitHub Actions, before installing the requested GCC version.

ci: Fix deployment of GCC < 14 under macOS

---

src/target/adiv5.c
src/target/jep106.h

Tried to use blackmagic to program/debug one of the infamous "bluepill" boards with a counterfeit STM32F103C8 MCU. BMDA reports `Please report unknown device with Designer 0x8055 Part ID 0x29b` and is not able to flash the board.
I had a deeper look, added a `DEBUG_INFO`to print the PIDR before processing and figured that the PIDR is apparently 0x000000050005529b, which would indicate a manufacturer code of 0x555 and part id 0x29b, which would actually already be recognized if the `PIDR_JEP106_USED` bit would be set. Which is sadly missing. Therefore in `adiv5_component_probe()` the if-clause where the designer code would be re-written to STM is not entered, instead the code is handled as "legacy ascii code" and extended to 0x8055.
To allow recognition of this chip as an STM32F103C8, this …

Please report unknown device with Designer 0x8055 Part ID 0x29b - Add support for another STM32F01 clone

---

.github/workflows/build-pr.yml

@amyspark very kindly fixed the macOS Homebrew CI yesterday in #1822, only GHA just rebuilt the CI image ~10h ago. This undid the image change that caused the need for the fix in the first place - this PR reverts the previous PR w/ permission and thanks from Amy as the GHA CI image has been sorted back out.

Fix: macOS Homebrew CI

---

driver/99-blackmagic-plugdev.rules
driver/99-blackmagic-uucp.rules

Back in udev 247, a change was made that introduced new actions that have to be handled by rules files, breaking the rules in the repo.
This PR addresses this as this impacts Debian Stable, Arch and a slew of other distros that are all now using systemd/udev >= 247, and as there are some other silly mistakes in the rules to do with how attributes are looked up for the permissions setting component.
Tested on our Debian box and Arch boxes.

Fix: udev rules

---

src/platforms/hosted/stlinkv2.c
src/target/adiv5.c
src/target/adiv5_swd.c

This PR fixes a couple of bugs that were accidentally introduced a while back in the ADIv5 implementation, and provides a workaround for the ST-Link firmware not supporting multi-drop at all, unlike what the release notes advertise.
The first of the regressions that this fixes is in the ADIv5 memory I/O code where the handling for TAR wrap-around got botched by typo in aa9bb48d (as much as the keys are right next to each other, e is not 3!).
The second regression was accidentally introduced in 44422c9f when SWD multi-drop was refactored and rewritten - most likely due to an oversight.
The ST-Link component of this PR partially fixes/alleviates #1813 but does not resolve the issue laid out in that issue.

Fix: ADIv5 handling issues

---

src/target/stm32f4.c

This PR takes the patch from #1816 and formalises it to add support. We don't have the hardware to test it on, but the patch seems very reasonable and minimal, so as the user indicates it's functional from how the issue ticket is written we have no issues with that.
With thanks to @klenSA for the patch!
Fixes #1816

Feature: GD32F405 support

---

src/gdb_packet.c

* This is a fix, not a feature.
* The existing problem is free-after-malloc-failure [from vasprintf] in `gdb_putpacket_f()`, which crashes probe firmware on that denied heap allocation.
* This PR solves that by guarding the free properly in the existing adjacent conditional.
There are only two calls to the "allocating" function `vasprintf` in BMD, both in scope. I felt like adding `*buf = NULL` initialization for pointers on stack to be more defensive (during debug it was some 0x400 garbage). In the extremely pessimistic case of heap not working altogether, some of the first GDB RSP host packets trigger an `exec_q_supported()` reply with first `vasprintf()` which calls sbrk(0) internally, then sbrk(+72) and sbrk(+104); the second sbrk fails, failing malloc, returning -1, which indicates …

Fix checks of `vasprintf` in gdb_packet.c

---

cross-file/stlink.ini
meson_options.txt
src/platforms/stlink/Makefile.inc
src/platforms/stlink/README.md
src/platforms/stlink/meson.build
src/platforms/stlink/platform.c
src/platforms/stlink/platform.h

Adding UART to stlink probe introduced in #1087 has created a conflict between UART TX and NRST pins on stlink clones
(both are PB6). More discussion here: https://github.com/blackmagic-debug/blackmagic/pull/1087#issuecomment-2053975402
This PR fixes this by moving NRST pin to PB0 on stlink clones (same one as on original stlink). 
Note that PB0 is not present on the header itself, so NRST functionality is lost (However this seems to be the intention of the original PR).
Also this PR renames build option from SWIM_AS_UART to SWIM_NRST_AS_UART for better clarity that it occupies both SWIM and NRST header pins. 
This is also changed for meson configs.

Fix UART TX and NRST pin conflict  on stlink clones with SWIM_AS_UART

---

src/platforms/hosted/remote/protocol_v3_adiv5.c
src/remote.c
src/target/adiv5_interface.h
src/target/adiv5_jtag.c
src/target/adiv5_swd.c

This PR addresses some issues with fault handling in the remote protocol that were identified as part of a set of issues @Xobs reported earlier in the year.
The first of two major issues that were occuring are that if a fault happens in the ADIv5 acceleration interface on the probe, setting remote_dp.fault non-zero, that would become a permanent error and lock the stack out of correctly handling further communication. This is addressed by making sure the fault status gets reset during request setup processing on the probe.
The second is that some errors, such as no-response, were not being properly propergated back up to BMDA. This has been addressed by a fix to `adiv5_dp_recoverable_access()` which solves a long standing issue with how it would (fail to) deal with a still-faulting …

Fix: remote protocol fault handling

---

src/platforms/common/blackpill-f4/Makefile.inc
src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/meson.build

* Not a feature, this was available via Makefiles for some time.
* The existing problems are meson always building ST MaskROM-jumping firmware, and mismatching serial number lengths.
* This PR solves these problems by updating settings in meson.build for this family of platforms.
Attention blackpill-F4x1Cx users, a recent PR has effectively moved the .noinit boot magic variable flag location (above the 4 KiB of stack), and you may need to rebuild and reflash BMPBootloader (via BOOT0 method, i.e. ST MaskROM USB DFU or USART) so that it matches latest Blackmagic Debug Firmware.
Not self-opening an issue for this.

Fix meson BMPBootloader on blackpill-f4

---

src/target/semihosting.c

* This fixes an issue.
* The origin of the issue was the change contributed in #1686 which added the loop in semihosting_get_gdb_response.
* The check for an F-packet reply was too late as gdb_main_loop may have already clobbered the packet by the time this is checked.
Collaborative inspection of debug logs from #1845 and provided by others pointed to inconsistent behaviour dealing with remote file i/o completion, which was narrowed down to the F-packet reply check being done after the packet had been processed and the packet buffer possibly clobbered.
This is corrected by checking if the received packet is an F-packet first then processing it and using the result of the check to exit the loop after the processing.
Fixes #1845.

Fix: Ensure F-packet replies from gdb are reliably detected

---

cross-file/96b_carbon.ini
cross-file/blackpill-f401cc.ini
cross-file/blackpill-f401ce.ini
cross-file/blackpill-f411ce.ini
cross-file/bluepill.ini
cross-file/f072.ini
cross-file/f3.ini
cross-file/f4discovery.ini
cross-file/hydrabus.ini
cross-file/launchpad-icdi.ini
cross-file/native.ini
cross-file/stlink.ini
cross-file/stlinkv3.ini
cross-file/swlink.ini

This will enable building libftdi's C++ component with the correct compiler, avoiding the defaulting to C++03 on macOS,
once https://github.com/blackmagic-debug/libftdi/pull/2 and https://github.com/blackmagic-debug/libusb/pull/3 are merged.
cc @dragonmux

meson: add C++ compiler entry to the default cross files

---

src/platforms/stlinkv3/README.md
src/platforms/stlinkv3/platform.c

* There is a small new feature.
* Existing problems are `(gdb) compare-sections` potentially not working on STLINK/V3, and SWO capture baudrate too low.
* This PR solves these by enabling RCC_CRC and switching UART5 clocksource from APB1 Pclk to Sysclk.
Also I add a couple paragraphs of documentation to platform README.md with info from ST manuals and libopencm3.
Testing on stlinkv3 required prior to merge.
None reported.

Fix stlinkv3 platform bits

---

src/include/exception.h
src/target/target.c

In this PR we address the lack of exception handling in `target_list_free()` which results in some very funky behaviour including crashes from double-free() and some other badness.
In the advent that the function is called and thinks it needs to detach from a target, but that target has gone away, `target->detach()` will throw. If left unhandled in this function, the `target_list` state becomes invalid/stale and in an unpredictable state, leading to all the bad things that happen. So, we envelop this section of the function in a `TRY()`-`CATCH()` so we can discard the exception and continue clean-up, giving a consistent and valid final state on the function returning.
Tested working on the STM32H503.
Test protocol is to scan and attach, then either disconnect the debug umbilical, or cut …

Fix: `target_list_free()` exception handling

---

src/platforms/common/stm32/gdb_if.c

* Not a new feature.
* The existing problem is 2x reduced performance in `bmpflash read -b int file.bin`, `blackmagic -r file.bin` BMDA memory dumping, and less obvious in other actions, on `blackpill-f4` (and possibly `stlinkv3` F723, `f4discovery` F407).
* This PR solves it by correcting the check in USB interrupt callback code which controls WFI entry.
Follow-up to #1689. Because I added the check on `if(count_new == 0) __WFI();` but by the time of check `count_new` was either zeroed by previous lines of code, or already zero at callback entry, this added an extra sleep, reducing how often USB packets could be fetched from Host OUT endpoint. What I should've done instead is save the `count_new` value at entry and use that to dispatch the WFI. Now this works as I expect it to. Despite …

Fix gdb idling too much on DWC

---

src/include/platform_support.h
src/platforms/native/platform.c
src/platforms/native/platform.h
src/target/adiv5.c

In this PR we refactor the `hwversion` handling a bit using ALTracer's suggestions as a basis, saving close to 300 bytes of Flash and modestly improving the speed of the bitbanging routines due to them having to deal with a little less code on the hot path for every pin change.
Tested with the RP2040 due to it being one of the more expensive targets to enumerate and rewrite the Flash on, so giving one of the better benchmarks for this change.

Feature: Improved native platform `hwversion` handling

---

src/Makefile
src/platforms/hosted/Makefile.inc

* The existing problem is CI failures for Makefile builds of `native` firmware, including size-diff workflows.
* The PR solves (postpones) it by disabling building of CH579 driver by default in Makefiles, just like meson does.
This is a follow-up to #1788. Inspired by 8be1fcf5. CC @ArcaneNibble and maybe jediminer543.
I may similarly gate my at32f43x driver which will grow after adding OB support, so please merge before 1852 not after.
I'm not sure how would CI check disabled drivers in firmware builds later, but the clues are in >=256 KiB platforms, and meson_options.txt + cross-files ini.

Fix: Guard the CH579 driver in Makefile builds for parity with meson (opt-in)

---

src/target/at32f43x.c

* This is technically a new feature in a driver I contributed.
* The existing problem is at32f43x.c not supporting option bytes, which are required for e.g. RDP1 and EOPB0 modification.
* This PR solves it by porting driver code from stm32f1.c and adapting where necessary.
ArteryTek MCU AT32F435, F437 chips contain 512 byte User System Data regions (in SKUs with 2048 byte flash page size), or 4096 byte (for 4096-byte page size), that is 256 and 2048 halfwords [byte-invbyte]. The first 8 are very similar to STM32F1 in function, like 0x5AA5 for RDP1, but during testing via BMDA I encountered some functional differences. Also it's too long to overwrite all of them (and print), so some shortcuts were taken. Compared to #1803 my intent is to get this merged, because I don't have to tread …

Feature: AT32F435/437 Option Bytes support

---

cross-file/96b_carbon.ini
cross-file/blackpill-f401cc.ini
cross-file/blackpill-f401ce.ini
cross-file/blackpill-f411ce.ini
cross-file/f3.ini
cross-file/f4discovery.ini
cross-file/hydrabus.ini
cross-file/launchpad-icdi.ini
cross-file/stlinkv3.ini

* No new feature.
* The existing problem is big adapters missing three relatively new, gated, target drivers, so users don't get them by default, and CI doesn't check whether that code compiles in firmware builds.
* This PR solves it by updating target lists in cross-files.
Follow-up to #1858, 1857 etc. Keep in mind F103CB platforms still need custom -Dtarget= options to change the built set.

Fix: Update meson targets in cross-files for bigger platforms

---

src/target/stm32_common.c

* It's a fix to a new-ish feature.
* The existing problem is STM32 UID decoder sending whatever bytes to GDB remote monitor output, potentially resulting in control characters messing up display in terminal emulators.
* This PR solves that by conditionally skipping the "decoded" print, leaving just the hex print.
In testing I noticed that some of ST parts have a different UID encoding. For example, stm32f1.c driver supports STM32F072, and those have what I expect, and decode appropriately; but older designs, including STM32F103, and their followers, like GD32F103, AT32F403A, can have arbitrary non-printable bytes, then BMD interprets them as a null-terminated string and sends as an O-packet. I have had my gnome-terminal corrupted multiple times due to that, and I was running gdb in a …

Fix: STM32 UID decoder: avoid displaying non-printable bytes

---

src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/usbdfu.c

* This is an old feature ported between platforms.
* The existing problem is `blackpill-f411ce` and likely other variants hanging in either BMF or BMD bootloader upon exiting ST MaskROM USB DFU -- mitigated by pressing reset button (after the initial flashing of BMD bootloader, or after `dfu-util -s :leave` for project bootloader-less builds.
* This PR finally solves it by copying the register pokes for restoring STM32F4 memory remap.
Armed with inception debugging, knowledge of adjacent platforms, and dfu-util on Linux amd64 I dived into this once more and noticed something weird. After ST MaskROM USB DFU (located at 0x1fff_0000) performs a leave into application (located at 0x0800_0000), it keeps itself remapped to 0. If BMD bootloader is present, it then updates SCB->VTOR to …

Fix `blackpill-f4` requiring a reset after exiting ST MaskROM

---

src/target/efm32.c
src/target/nrf51.c
src/target/renesas_ra.c

* Not a new feature, but rather a minor fix for size optimization.
* The existing problem is four distinct variants of the same idea of a message in UID commands or equivalents in target drivers for EFM32, nRF51, Renesas RA.
* This PR replaces the help messages to match the STM32 one, shrinking all builds by ~60 bytes thanks to linker relaxation.
I can't exactly test it live, due to no devices, but `strings -n12 blackmagic.bin | grep "unique"` no longer matches four entries, and the binary is smaller.

Fix: Unify help messages for Unique ID with STM32

---

src/platforms/common/swdptap.c

Make SWD timing more consistent: output changes (including floating) take place after the falling edge, and reads take place before the rising edge.
This includes moving a gpio_get to occur after the clock-low delay, which would help reduce incorrect reads from lower-bandwidth target connections.
Eliminate redundant GPIO operations, typically ones that set the clock low, by making the bit string input/output primitives always end by outputting a falling clock edge.
This makes the bit banging code more consistent and easier to analyze. It also removes some redundant clearing of the clock, typically because most existing big banging functions ended on a falling clock edge, and also began with an explicit clearing of the clock. This is no longer necessary, if we adopt a convention that the …

common/swdptap: make SWD timing more consistent

---

src/platforms/hosted/platform.c

* The existing problem is BMDA on Windows defaulting to 4 KiB block buffering on stdout. Users don't see output progress (which is line-buffered on Linux) until enough text appears, or BMDA exits.
* This PR switches stdout to unbuffered mode for WIN32 and Cygwin.
Initially I tried _IOLBF, but it returns some error from libc internals.
I don't feel like dealing with placing strategic fflush(stdout) calls in BMDA to massage it into printing info interactively.
Tested on Msys2 ucrt64 to remove delays between activity and printed output. Also tested in Qt Creator Debug to corrupt (mix) Program output significantly.
Not self-opening one.

Fix: Use unbuffered stdout on Windows

---

.github/workflows/build-pr.yml
cross-file/ctxlink.ini
meson_options.txt
src/Makefile
src/platforms/ctxlink/Makefile.inc
src/platforms/ctxlink/README.md
src/platforms/ctxlink/ctxlink.ld
src/platforms/ctxlink/meson.build
src/platforms/ctxlink/platform.c
src/platforms/ctxlink/platform.h

This is an initial PR to bring ctxLink with basic USB functionality into the upstream repository.
TRACESWO is not tested/implemented in this firmware. It will be added  in the future when the ongoing F4 TRACESWO work is merged into main.

CtxLink_usb

---

src/platforms/ctxlink/README.md
src/platforms/ctxlink/platform.c

This PR refactors the request for the STM32F401 to enter the system bootloader, based upon input from @ALTracer. The platform readme is also updated to request dfu-util leaves boot loader mode and enters the ctxlink firmware upon flash completion.

ctxlink: Fix bootloader related readme and optimize code

---

src/platforms/common/aux_serial.c
src/platforms/common/aux_serial.h
src/platforms/common/usb_serial.c

* The existing problem is Virtual COM port terribly broken on `stlinkv3` platform Blackmagic Debug firmware, whereas it works fine on original proprietary firmware.
* This PR solves it by bumping aux_serial.c buffer sizes to 2x512 for USB HS STM32F723, index type widths, and correcting USB Out endpoint size.
Tested on ST-LINK/V3E by performing a cbrake/linux-serial-test in external loopback mode at 12 Mbaud (Hclk DIV18 gives a round number, and I need OVER8 to go 432M/24=18M) with 1'200'000 chars/s reported in both directions and Wireshark usbmon displaying Bulk packets up to 511 bytes long.
May need independent testing both on FSDev STM32F1 and OTGFS STM32F4 (so an swlink and a blackpill-f4), but the code is macro-gated. I expect slightly better codegen and faster …

Fix CDC-ACM on STLINK/V3

---

src/platforms/common/usb_serial.c

* The existing problem is the opt-in ENABLE_DEBUG logs misbehaving on stlinkv3 platform due to 8-bit ringbuffer indices overflowing from 512-byte HS Bulk packets.
* This PR solves it by increasing index width to 16-bit. Follow-up to #1865.
Tested on STLINK/V3E. I often use optional advanced diagnostic logging in-probe (sacrificing some targets on size-restricted platforms), but on this one under ST bootloader something hung/misbehaved (RDP2 forbids DebugMon?), so I applied my usual hack of skipping the `initialize_monitor_handles()` call in usb_serial.c and not linking with `-lrdimon`. This time I was greeted with working, but malformed, logs, which seemed somewhat faster than all the FS probes.
Sure enough, I haven't noticed the other two `uint8_t` gated by macros in a …

Fix diagnostic logs on CDC-ACM of STLINK/V3

---

src/platforms/hosted/dap_swd.c

This PR addresses a UBSAN runtime notice in the SWD support for CMSIS-DAP adaptors. This is caused by an improper widening via integer promotion (which discards unsigned-ness during widening) of sequence data in `dap_swd_seq_in_parity()`. When this widening takes place and a shift right that would change the sign bit occurs, such as shifting 128 up 24 bits on a platform where `int` is 32-bit, this invokes undefined behaviour.
Before this PR, users would see a message such as `../src/platforms/hosted/dap_swd.c:170:39: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'` from BMDA when built with UBSAN and this buggy behaviour triggers. After, no UBSAN errors are reported and SWD comms proceed normally.

Fix: CMSIS-DAP SWD data shift UB

---

src/command.c
src/include/platform_support.h
src/platforms/96b_carbon/platform.c
src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/f072/platform.c
src/platforms/f3/platform.c
src/platforms/f4discovery/platform.c
src/platforms/hosted/cli.c
src/platforms/hosted/ftdi_bmp.c
src/platforms/hosted/platform.c
src/platforms/hydrabus/platform.c
src/platforms/launchpad-icdi/platform.c
src/platforms/native/platform.c
src/platforms/swlink/platform.c

* The existing problem is Read of NULL in remote.c on platforms which implement a stub for `platform_target_voltage()` as returning a NULL char*.
* This PR offers three possible solutions to this problem, two of them behind `#if 0` because of bigger flash impact.
Before deploying a development build of BMF to stlinkv3e in RDP2 (so no inception debug) I tested my MPU setup idea on my trusty blackpill-f411ce. As I was tapping into the newfound power that is a working MPU on Cortex-M, I also felt like adding (to region 6 "uncaching" top 16 KiB out of 128 KiB of F411CE SRAM) a region 7 to catch any accesses to address 0, that is, NULL dereferences as a known UB in C. Even though libopencm3 doesn't help much, I have already had written the helper functions and tested them …

Fix: avoid a NULL ptr dereference in HL-remote from !GV#

---

src/platforms/ctxlink/platform.h

This PR addresses the failure of the ctxLink USB UART to either send or receive data from the dewvice under test.
The DMA configuration used by ctxLink was based upon the F4Disco platform (STM32F407) and several things needed to be corrected before the ctxLink (STM32F411) USB UART worked.

Correct USB UART DMA configuration

---

src/platforms/common/syscalls.c

* This is not really a feature.
* The existing problem is that `arm-none-eabi-` toolchains based on newlib-4.3.0 and newer, pull about 4 KiB of ARM EABI unwinder stuff and fail to link BMF for native.
* This PR solves it by making the explicit choice to not use the libgcc unwinder, via overriding one of (weak?) Personality functions.
Blackmagic Debug Firmware is a unique C project in that it's not C++ and does not use ARM EABI unwinder for C++ exceptions, but it still uses setjmp/longjmp for hand-rolled custom exceptions.
In newlib-4.3.0 a change to setjmp.S was merged which marks the assembly setjmp implementation for ARMv7-M (THUMB2) as `.fnstart/.fnend` but not `.cantunwind`. This was described as necessary for ARMv8-M PAC/BTI features; however all affected in-tree BMF platforms are …

Fix: Opt out of libgcc unwinder pulled by >=newlib-4.3.0

---

.github/workflows/build-and-upload.yml
.github/workflows/build-pr.yml
src/platforms/hosted/meson.build

This PR overhauls both the PR CI workflow and the build-and-upload workflow.
The PR workflow changes are relatively minimal - bumps to OS releases used, compilers targeted and dropping ones that have either already been removed from GHA's runners set, or will be soon.
The build-and-upload workflow rewrite is very comprehensive and encompases completely rewriting the flows to use Meson only (Makefile builds are already tested by the PR CI), and to work smarter rather than harder with the firmware builds. Additionally, this introduces macOS builds of BMDA, makes the Linux Windows builds stand-alone, and cleans up which Windows builds get done as the volume and combinations were a bit ridiculous.
Overall, the resulting flows should be faster, less duplicated, and produce more meaningful …

Feature: CI overhaul

---

src/command.c

I'm currently porting this project to my custom platform and at one point I needed to add a custom command for my platform.
My port uses this project as a submodule, so I thought it would be great to be able to add platform-specific commands without patching command.c file.

Feature: Add platform-specific commands support

---

src/platforms/common/blackpill-f4/Makefile.inc
src/platforms/common/blackpill-f4/blackpill-f4.h
src/platforms/common/blackpill-f4/meson.build

* The feature is technically not new.
* The existing problem is traceswo.c driver (TIM) not working / incompatible with blackpill-f4 platforms.
* This PR solves it by switching altogether to the patched traceswoasync.c driver (UART).
It's based on the branch patching traceswoasync.c, so when that's merged I'll replay/rebase it away and diff becomes smaller.
If other F4 platforms require a similar switch procedure, please provide the macros like here, required to leverage the driver.
Buffer size could be smaller, I haven't found a good rule of thumb for it.

Feature: Switch `blackpill-f4` to traceswoasync.c driver

---

src/command.c

Fix: Fixed platform_cmd_list extern declaration in command.c that causes hardfault.

Fix: Fixed platform_cmd_list extern declaration in command.c

---

src/target/cortexm.c
src/target/stm32h7.c
src/target/stm32mp15.c

* There are minor features here, I think.
* The existing problem is `STM32MP15 M4` wrongly identified by BMD as `STM32H7 M4` since 0f226232 of #1819.
* This PR solves it by adding gated code to read the DBGMCU_IDC value as mandated by ST for silicon identification.
First thing I tried is simply reordering the probe calls, and sure enough, that made the two chips light up as `STM32MP15 M4` again but also `STM32MP15 M7` which is unheard of. Then I added the H74x, H7Bx short literals to H7 driver to see slightly more detail in reported target list -- those don't have the H723-like string in their Engineering bytes.
Then the logging of three variants of IDs. By staring at them long enough I figured we only need to read DBGMCU in the dubious case of seeing 0x450.
Tested on STM32MP157C and …

Fix mis-identification of STM32MP15x_CM4 as STM32H74x_CM4

---

src/target/cortexm.c
src/target/riscv_debug.c
src/target/riscv_debug.h
src/target/stm32f1.c
src/target/stm32f4.c
src/target/stm32g0.c
src/target/stm32h5.c
src/target/stm32h7.c
src/target/stm32l0.c
src/target/stm32l4.c
src/target/stm32mp15.c

In this PR we sort out support for and deal with WDTs support across the whole STM32 range supported. Included in this are fixes for issues such as bad Flash maps on some families, which were necessary to properly deal with differences in part addresses such as on the STM32L1 family where the address the DBGMCU is at changes based on which part it is in the family.
The approach used here needs work for handling what happens if a user attaches into a part, changes the code in Flash on the part, runs that new code which then modifies certain DBGMCU registers such as to set up tracing, and then detaches. Even with this limitation/bug in place, this greatly improves the state of debug across these families, by properly handling the WDTs during processor halt, and by properly setting up …

Feature: STM32 watchdog timer control

---

meson_options.txt
src/Makefile
src/platforms/hosted/Makefile.inc
src/platforms/hosted/bmp_remote.c
src/platforms/hosted/bmp_remote.h
src/platforms/hosted/platform.c
src/platforms/hosted/remote/meson.build
src/platforms/hosted/remote/protocol_v3_adiv5.c
src/platforms/hosted/remote/protocol_v4.c
src/platforms/hosted/remote/protocol_v4.h
src/platforms/hosted/remote/protocol_v4_defs.h
src/platforms/hosted/remote/protocol_v4_riscv.c
src/platforms/hosted/remote/protocol_v4_riscv.h
src/remote.c
src/remote.h
src/target/meson.build
src/target/riscv_debug.h
src/target/riscv_jtag_dtm.c

In this PR we implement acceleration of the RISC-V Debug protocol when using BMDA with the BMD remote protocol with a probe. This dramatically improves the speed of RISC-V communications, bringing the 3s discovery time for the GD32VF103 down to just under 0.5s.
This acceleration makes use of the protocol v4 framework for optional accelerations, allowing it to be introduced in an entirely backwards and forwards compatible way. It is gated behind a new Meson compilation option (`enable_riscv_accel`) so the Flash usage it causes is fully opt-in.
Additionally, this PR introduces RISC-V specific acceleration expansion, allowing other protocols for the DTM to be implemented later without bumping the protocol version, due to the supported RISC-V DTM protocols being enumerated in the same manner …

Feature: RISC-V Debug remote protocol acceleration

---

src/target/stm32h7.c
src/target/stm32mp15.c

These functions incorrectly use formatting, resulting in build errors on ESP32. Use the correct formatting arguments to DEBUG_TARGET() to fix the build on those platforms.

stm32: fix formatting for DEBUG_TARGET on esp32

---

src/target/stm32h7.c

Use PRIx32 rather than PRId32 in the formatting string.
Unfortunately the wrong string was included in f1aec5f786ab2decfe577f880adeb29fc667cd57.

target: stm32h7: print hex instead of decimal

---

.clang-tidy
.vscode/extensions.json
src/platforms/stlinkv3/usb_f723.c

In this PR we update libopencm3 to pull in patches for a variety of things, including and most notably Stoyan Shopov's libopencm3/libopencm3#1259 which fixes libopencm3/libopencm3#1241.
We have taken the opportunity to do a little non-code repository maintenance too. This cleans up the clang-tidy configuration situation to help keep it working.

Feature: Update libopencm3

---

src/command.c

In this PR https://github.com/blackmagic-debug/blackmagic/pull/1881 I forgot to add "Platform commands:" message in cmd_help to highlight plaftorm-specific commands, so this PR adds this.

Feature: added "Platform commands:" message in cmd_help

---

src/target/stm32l4.c

In this PR we fix an issue with the new DBGMCU handling for the STM32L4-like parts. In the original PR for this, #1882, we accidentally mishandled the device family checks when going to configure the DBGMCU, using the parameter version of `device` rather than the `priv` structure version. This results in a NULL dereference and a crash on attach.
Fixes #1787, closing the final item in the issue.

Fix: STM32L4 DBGMCU handling

---

src/target/ch579.c
src/target/efm32.c
src/target/lpc546xx.c
src/target/nrf51.c
src/target/renesas_ra.c
src/target/sam3x.c
src/target/samd.c
src/target/samx5x.c
src/target/semihosting.c
src/target/stm32f1.c
src/target/stm32g0.c
src/target/stm32h7.c
src/target/stm32l0.c
src/target/stm32l4.c
src/target/target_internal.h

https://github.com/blackmagic-debug/blackmagic/pull/1676

Fix: -Wformat for tc_printf

---

src/target/s32k3xx.c

* The existing problem is that the S32K3xx driver, introduced in #1652, references `assert()` which pulls `fiprintf()` and `_vfiprintf_r` again, resulting in extra 1.5 KiB of newlib stdio.
* This PR solves it by ~~replacing the assert with a logged runtime error.~~ IIUC target flash layer should call it with a `len=writesize`. Depending on review and API guarantees I can drop even that. Update: dropped.
I expect a significant size-diff from CI. This should restore the effect of my previous #1513.
Cannot test on hardware. CC @via.

Fix: s32k3xx: Remove the single assert 

---

.github/workflows/build-pr.yml

* This can sound as a minor new feature.
* The existing problem is suboptimal utilisation of Free runners, which are 4-core, and hence longer build times (4 minutes) for Makefile workflows.
* This PR solves it by reintroducing -j option and nproc applet (coreutils). Not touching Windows/mingw or MacOS.
Tested on GH CI Free in fork by manually triggering a workflow from branch, the speedup is there (2m20s).
There was a known problem with log clobbering, where multiple `make` jobserver workers attempt to pass compiler errors up simultaneously. Make 4.3 now supports `--output-sync` option, and I used `-Otarget` here to make it buffer and sync output up to one build target (object). https://www.gnu.org/software/make/manual/html_node/Parallel-Output.html Did not test this yet, I'd need to see …

Fix: Enable parallel make workers on GH Actions CI

---

src/platforms/96b_carbon/Makefile.inc
src/platforms/96b_carbon/meson.build
src/platforms/96b_carbon/platform.h
src/platforms/common/blackpill-f4/Makefile.inc
src/platforms/common/blackpill-f4/blackpill-f4.h
src/platforms/common/blackpill-f4/meson.build
src/platforms/common/stm32/traceswo.c
src/platforms/ctxlink/platform.h
src/platforms/f072/platform.h
src/platforms/f3/platform.h
src/platforms/f4discovery/platform.h
src/platforms/hydrabus/platform.h
src/platforms/native/platform.h
src/platforms/stlink/Makefile.inc
src/platforms/stlink/meson.build
src/platforms/stlink/platform.h
src/platforms/swlink/Makefile.inc
src/platforms/swlink/meson.build
src/platforms/swlink/platform.h

* This is an existing/missing feature.
* There is an unconfirmed problem of Manchester capture not working on `native`, and a "feature request" to bring it back to swlink (on which it originally existed), stlink (this is new) and blackpill-f4 (neither mode worked due to various reasons).
* This PR solves that by restoring and copying some macros and introducing compile-time selection of traceswo protocol.
Changes from November 2023, so meson buildsystem parts are missing. I wonder how seamlessly it rebases this far forward.
Default capture modes are Manchester for `native` (and I'm not changing that), but Async/UART+DMA for `stlink` and `swlink`, which I tested to be somewhat working. Building with `TRACESWO_PROTOCOL=1` reverts the two latter platforms to TIM-based Manchester. The PR …

Restore TraceSWO capture in Manchester mode

---

src/target/target_flash.c

* The existing problem is BMDA crashing upon vFlashWrite packet received with no target.
* This PR solves it by adding a nullptr check.
Discovered during compatibility testing with Segger emStudio V7. When BMD has detached from last target (or never attached to a target), the `target` pointer is set to NULL. This function does not check for this and will try to dereference the `flash_mode` field.
https://github.com/blackmagic-debug/blackmagic/blob/992f8714ffff647ae87d2a63aa5be21d0fa4864b/src/target/target_flash.c#L301-L304
Invokable via the `else` branch in `exec_v_flash_write()` here
https://github.com/blackmagic-debug/blackmagic/blob/992f8714ffff647ae87d2a63aa5be21d0fa4864b/src/gdb_main.c#L794-L799
Normally GDB will fail on vFlashErase, but SES is special. I also …

target_flash: Prevent NULL dereference when detached from targets

---

src/command.c
src/platforms/common/aux_serial.c
src/platforms/common/stm32/traceswoasync.c
src/platforms/common/stm32/traceswoasync_f723.c
src/platforms/common/tm4c/traceswo.c
src/platforms/common/traceswo.h

* This is a small new feature.
* The existing problem is BMP platforms parroting back whatever baudrate you set it to. The discrepancy gets significant at high baudrates, close to Pclk DIV16, effectively ruining communications to other boards +-5% (especially TraceSWO Async which is tuned by an integer(!) divisor off TraceClk).
* This PR makes TI ICDI and STM32 platforms recompute real baudrate by reading back the programmed USART BRR divisors. It's a function missing from libopencm3 API, but to upstream this there OVER8 support would be required.
As I was compile-testing this, I also noticed some stray hardcoded 0x85 endpoints in ICDI and replaced them with new compile-time macros.
Runtime tested on `blackpill-f411ce`, `swlink`-bluepillplus, stlinkv3-minie (f723). I needed this for …

Feature: Calculate and report real USART baudrate

---

src/target/renesas_rz.c

* Previously, RAM was statically set to size 0x200000U but the RZ/A1L and RZ/A1LU have an additional 1MB of RAM. This code adds a function to determine RAM size ~~for a given part_id~~ based on auto-detection (there may be other examples of this in the RZ series).
* Code currently iterates through RZ-series RAM at probe time at 512kB intervals and sets the RAM size to the maximum error-free read position. If that fails, it sets RAM to the maximum known for the RZ series (at present, 10MB).

Fix: renesas_rz: autodetect RAM size based on RAM reads

---

meson_options.txt
src/platforms/common/blackpill-f4/blackpill-f4.h
src/platforms/common/blackpill-f4/meson.build
src/platforms/common/blackpill-f4/usbdfu.c

The LED used to indicate the bootloader is active
is selected according to whether the bootloader
was built for Blackpill-F4 on carrier or standalone.
The option set using Meson:
meson setup --reconfigure -Don_carrier_board=true
This option only applies to the BMD bootloader for Blackpill-F4, that opiton should also be set:
meson setup --reconfigure -Dbmd_bootloader=true
This PR updates the build system to provide a conditional compilation  option to build the Blackpill-F4 bootloader so that the bootloader LED is driven correctly when the Blackpill is on a carrier or standalone.
None

Feature-bootloader led mapping blackpill on carrier or standalone

---

src/platforms/ctxlink/platform.c

This PR addresses a change made in other platforms to remove the usage of "NULL" value returns. When these changes were made, ctxLink was not updated. 
None

ctxlink/platform: Fix plarform_target_voltage_return

---

meson_options.txt
src/platforms/common/blackpill-f4/meson.build
src/platforms/native/Makefile.inc
src/platforms/native/meson.build
src/platforms/native/platform.h
src/platforms/stlink/meson.build
src/platforms/stlinkv3/Makefile.inc
src/platforms/stlinkv3/meson.build
src/platforms/stlinkv3/platform.h
src/platforms/swlink/meson.build

This PR introduces a new meson build option, "trace_protocol."
This option is used to select the protocol used by a platform for trace SWO.
Platforms will need testing to verify the changes made.

Meson_build_option_for_trace_protocol_selection

---

src/platforms/common/blackpill-f4/blackpill-f4.h

This PR fixes a minor commenting error in the platform header file for blackpill-f4. 
None

blackpill-f4: Fix error in comment describing the timer used for traceswo

---

src/platforms/common/blackpill-f4/README.md

* This is a UX feature, no code is changed.
* The existing problem is unobvious workflow of blank board flash upgrade for blackpill-f4.
* This PR helps solve it by expanding documentation in platform README with Meson-specific and BMD-bootloader-specific paragraphs.
This partially reverts bb6a7ce to keep Makefile docs portion, because both buildsystem technically still work, and there is no counterpart to lenvm's SHIELD=1 makeflag in meson flags.
I feel like BMDbootloader-specific portion of docs is board-agnostic, but there is no good existing Markdown file to move this into and cross-link.
Awaiting stylistic review of most text, as English is not my native language (I know the vocabulary enough, but not the syntax details).
Fixes #1899.

Feature: expand docs for `blackpill-f4`

---

src/platforms/common/aux_serial.c
src/platforms/common/stm32/traceswoasync.c
src/platforms/common/stm32/traceswoasync_f723.c
src/platforms/common/traceswo.h
src/platforms/stlinkv3/README.md

* This is a new non-breaking feature.
* The existing problem is low max baudrates on in-tree platforms with STM32 USART IP which supports OVER8.
* This PR solves it by adding a register poke to unlock higher baudrates in DIV16..DIV8 range, switching to hardware oversampling x8.
F103 platforms should not be affected, the new code is gated by a macro.
F4 platforms should reach double the baudrates on all ports. This is a logical follow-up to #1864 and whatever went in libopencm3.
F723, likewise, should be able to reach double the baudrates (especially when coupled with #1854), becoming the fastest UART of in-tree platforms.
Whether enabling CR3 ONEBIT mode for better clock deviation tolerance (2%->3%) is also required -- is a good discussion point.
I tried drying the implementation since …

Feature: Enable USART OVER8 as needed

---

src/platforms/hosted/Makefile.inc
src/platforms/hosted/bmda_gpiod.c

* This feature is not new.
* The existing problem is it's impossible to build BMDA with libgpiod backend when Meson doesn't work, i.e. via Makefile buildsystem.
* This PR enables said support by adding required sources, macros, and pkg-config flags.
Tested in March of 2024 to work on STM32MP157 in OpenSTLinux userspace.
I also thought to expand the reason message for when gpiod_get_line() fails to claim a pin. `strerror()` is already used elsewhere in this codebase (in hosted).

Fix: Support libgpiod in Makefiles

---

src/platforms/ctxlink/Makefile.inc
src/platforms/ctxlink/meson.build
src/platforms/ctxlink/platform.h

Note: The UART protocol is tested, however, the Manchester
protocol is not tested, in fact, the defines still
need adjusting to match the ctxlink hardware.
This PR implements UART TraceSWO protocol for ctxLink. Having SWO trace over USB is a new feature of ctxLink and is possible because of the new implementation of USB endpoint usage now present in BMF.
Lack of trace SWO over USB in ctxLink

Add TraceSWO UART protocol to platform

---

src/target/adi.c
src/target/adi.h
src/target/adiv5.c
src/target/adiv5.h
src/target/cortex.c
src/target/cortex.h
src/target/cortex_internal.h
src/target/cortexar.c
src/target/cortexm.c
src/target/cortexm.h
src/target/riscv_debug.c
src/target/stm32f1.c

In this PR we deal with some issues with core register I/O for ARM targets, and with TrustZone support between GDB and BMD for Cortex-M23 and Cortex-M33 targets. This is split into four main parts as described below.
The first part of this PR deals with some lints and code quality issues. The second deals with a residual ADIv6 support bug whereby because the register I/O code for both Cortex-M and Cortex-A/R support was directly writing the DP's SELECT register and presuming ADIv5, that was unintentionally deselecting the AP under ADIv6 and causing the reads and writes to go to an arbitrary point on the DP's debug resource bus.
The third part of this PR deals with some code organisation consistency problems, moving all the target.xml builder code for Cortex-M to the bottom of the file to …

Feature: Cortex-M TrustZone support

---

src/platforms/ctxlink/Makefile.inc
src/platforms/ctxlink/meson.build

ctxLink uses the ST built-in bootloader and does not need the BMD DFU bootloader.
This PR removes the builkd settings for the DFU bootloader from both the makefile and meson build file.
None.

Remove DFU from ctxlink platform

---

src/target/at32f43x.c

* This is a follow-up to #1869 (merged recently) which is supposed to deal with WFI/sleep and WDT/reset on AT32F437.
* This PR corrects a couple typos in that.
This, edited, version of that is tested on AT-START-F437 using its AT-Link EZ CMSIS-DAP firmware, affected by #1925 as well.
Now BMDA actually writes into correct DBGMCU offsets and hence works better than AT32IDE's version of OpenOCD (in which Tcl scripts still write 0x307 into CTRL, neglecting APB1_PAUSE), allowing me to halt, step, and reflash a chip with nWDT_ATO_EN option bit unset in SSB.
Not appending extra log instrumentation which I used to confirm that the reads and writes are happening in the order I expect them to.
Sorry for introducing typos in the process of responding to review of PR1869, that codestyle was more …

Fix: AT32F435/437: Correct typos in WFI/WDT handling

---

src/platforms/hosted/dap.h
src/platforms/hosted/dap_command.c

In this PR we correct an issue pointed out by both @litui on the MCULink adaptors, and by @asumagic on debugprobe firmware running on a RPi Pico. When using the logic from ARM for handling these transactions, they come out wrong (1 bit shifted due to all the in sequences capturing data one cycle too early).
We adjust for this with a new quirk flag when we detect this bugged behaviour during DP IDR readout, and post-processing the results with a corrective loop.
Tested working with both adaptors, allowing the debugprobe firmware to work flawlessly with BMD and the MCULink firmware to get a lot further with the MCXC041 before hitting a different issue (FAULT response handling during memory accesses setup). This latter issue will be dealt with in a separate PR.

Fix: Broken CMSIS-DAP SWD sequence

---

src/include/rtt_if.h
src/platforms/common/stm32/rtt_if.c
src/platforms/hosted/rtt_if.c
src/platforms/launchpad-icdi/rtt_if.c
src/rtt.c

Add support for targets that use channels other than 0. Currently these channels are all ignored, which can prevent confusion, however furure work may be done to connect other channels to e.g. different USB endpoints.
RTT supports the concept of multiple channels. Usually, up channel 0 is stdout and down channel 0 is stdin, however it supports more than just those two.
Add an argument to the RTT interface to indicate which channel is being addressed, and ignore it if the channel is not channel 0.
This enables platforms to take special actions for channels other than channel 0.

rtt: support channels other than 0

---

src/target/cortexm.c
src/target/cortexm.h

Allow outside accessors to update the demcr. This is useful for updating the exceptions to catch for handling things like devices that go into powersave.
Certain targets need to fail safe rather than failing into a debugger. An example of this is a heater, where it is preferable to have the target reboot when it has a hardfault.
Another example is an STM32F4 device that powers itself off. When catching reset vectors, it'll break into GDB every time the system is powered on, which may not be desirable.
Add functions to be able to peek into these values, as well as update them from outside of `cortexm.c`.

cortexm: allow updating demcr from outside

---

src/platforms/common/swo.h

SWO can run on devices that do not have USB connections. Gate the USB-specific functions behind `!defined(NO_LIBOPENCM3)`.

swo: gate usb-specific defines behind `!defined(NO_LIBOPENCM3)`

---

src/platforms/hosted/cli.c
src/platforms/hosted/cli.h
src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/cmsis_dap.h
src/platforms/hosted/platform.c

* This sounds like a small new compatibilty feature.
* The existing problem is BMDA unusable on Windows with adapters implementing CMSIS-DAP v2 (Bulk) and v1 (HID) transports when no drivers are installed on them (WinUSB, libwdi, Zadig etc.)
* This PR solves it by attempting to open the adapter again (on a failed v2 call) via v1 API.
Tested on Windows Msys2 ucrt64 to allow working with RP2040 running free-dap again. Could test against other impls. I understand FS HID is worse performance than FS Bulk, but some users may have no admin rights to keep installing/associating drivers. So much for Plug&Play.

Allow reopening CMSIS-DAP v2 adapters in v1 mode

---

src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/blackpill-f4.h

* This is a new feature (no new code, just opt-in config/macro extension).
* Some users of BMP-compatibles expect BMF's jtagtap pins on self SWJ-DP pins of `blackpill-f4` probe (since `swlink`).
* The PR solves this by adding some pins to `PINOUT_SWITCH()` macros and a third `SWDIO_MODE_REG_MULT`.
Build this via `make PROBE_HOST=blackpill-f411ce ALTERNATIVE_PINOUT=2` (...optionally `ENABLE_RTT=1 ENABLE_DEBUG=1 BMP_BOOTLOADER=1)`, or, under meson, 
`meson setup build --cross-file cross-file/blackpill-f411ce.ini -Dalternative_pinout=2` (...optionally `-Drtt_support=true -Ddebug_output=true -Dbmd_bootloader=true` and flash using `dfu-util` (`bmputil` is untested and may be incompatible). 
Then your WeActStudio MiniSTM32F4x1 board 1) unmaps its entire SWJ-DP away from SYS_AF AF0 so you can no …

Feature: Add to `blackpill-f4` an `swlink`-like alternative pinout 2

---

src/platforms/stlinkv3/platform.c
src/platforms/stlinkv3/platform.h

* This feature is a principle from `native` #1192 applied to other platforms.
* The existing problem is unbuffered BMP-compatibles hogging SWDIO/SWCLK lines in push-pull output modes, rendering other debuggers unusable when connected in parallel for extended diagnostics (this includes onboard debuggers).
* This PR solves that by switching GPIOs from push-pull output into input mode on the same function call that `native` uses.
Tested on stlink/v3e of Nucleo-144 to give up the lines and allow using another external debugger. If SWDIO_MODE_DRIVE/SWDIO_MODE_FLOAT of swdptap.c and TMS_SET_MODE of jtagtap.c macros worked correctly, then I'd only need to touch the TCK gpio, but it was not enough. It may have to do with the sequence of swd writes (BMP is expected to write the next command and …

Feature: tri-state SWDIO, SWCLK on unbuffered platforms

---

src/command.c
src/include/general.h
src/include/platform_support.h
src/platforms/common/usb_descriptors.h
src/remote.c

The feature to modify PLATFORM_IDENT in runtime has been added. To enable this, `PLATFORM_IDENT_DYNAMIC` should be defined, and the `platform_ident` function must be implemented to return `PLATFORM_IDENT`.

Feature: allow dynamic PLATFORM_IDENT

---

src/platforms/common/stm32/swo.c
src/platforms/common/stm32/swo_itm_decode.c
src/platforms/common/swo.h
src/platforms/common/tm4c/swo_uart.c
src/platforms/common/usb_serial.c

In the aftermath of the SWO fixup PR, we noticed some items around how the AUX serial interface is used that could do with some work. This PR is the culmination of that, delivering a small Flash size usage improvement and simplifying some of the code driving the SWO ITM decoder.
There are still improvements to be made for the AUX serial interface as if the host is not pulling data quickly enough right now, we will begin dropping packets of data even if buffers aren't full and waiting would solve it.

Feature: AUX serial cleanup

---

src/include/general.h
src/include/target.h
src/platforms/hosted/bmp_hosted.h
src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/bmp_serial.c
src/platforms/hosted/platform.c
src/platforms/hosted/serial_win.c
src/platforms/hosted/utils.c
src/platforms/hosted/utils.h

In this PR we address the recent CI breakage for BMP-only BMDA builds on Windows. This was caused by the compiler becoming stricter and so detecting and erring on some buffer overflow issues in the Windows-specific probe discovery code for BMP-only BMDA.
This PR addresses it by rewriting that code using the probe_info_s structure to store probes, and with considerably more error handling and proper buffer management to discover available devices on the user's system.
This could still do with some de-duplication between serial_win.c and bmp_serial.c, however it works (tested with both a native BMP and a Black Pill made into a BMP) and unifies the output with BMP-only BMDA on Linux by using the same `find_debuggers()` with different logic plugged in for probe discovery and building a …

Fix: BMDA BMP-only probe discovery for Windows

---

src/command.c
src/platforms/hosted/platform.c
src/platforms/hosted/platform.h

In this PR we address where the output of `monitor version` in GDB was being put under BMDA and what exactly was being reported.
This brings BMDA closer to being consistent with the other platforms, reducing user surprise, and making the output of `mon ver` more helpful when users are facing issues by providing which BMDA version and probe they're using precicely.
We have taken the opportunity to update the copyright string in the process.

Fix: BMDA version command output

---

src/target/stm32l4.c

In this PR we address some issues in stm32l4.c with part identification - while the logic that was present was probably alright for SWD, it absolutely does not work for JTAG due to an encoding difference between SWD-DPv2's TARGETID register and the AP ROM table PIDR's part number value. Additionally, it turns out the logic was sketchy when it comes to the second core on dual core parts.
To address these two issues, we fully overhaul the identification system for these parts and update all of the part IDs used. Tested confirmed working with a couple of different STM32WL parts and a STM32G4. Detailed cross-checking with the TRMs performed for everything.

Fix: STM32L4/L5/U5/G4/WL/WB family identification

---

cross-file/f072.ini
cross-file/native.ini
cross-file/stlink.ini

Due to space constraints we have to disable some of the targets enabled on certain host hardware. Users can mix and match what targets they need supported if they rebuild their firmware.
We will need to have a more comprehensive automatic build system for different sets of target support and allow for easier firmware swapping to make the use of BlackMagic with an ever growing set of supported targets. But for the moment the only choice we have is to disable some stuff so that the firmware targets are building again.
This PR disables the following:
* f072 host: efm, hc32 targets
* stlink host: hc32, rp targets
* native host: efm, hc32

meson: Disabled some of the default targets to make the code fit again.

---

src/target/cortex_internal.h
src/target/cortexm.c
src/target/cortexm.h
src/target/lpc40xx.c
src/target/riscv_debug.c
src/target/target.c
src/target/target_internal.h

In this PR we address the incredibly broken target halting for memory access heuristic, replacing it fully with a TOPT which can be set on targets that are confirmed to work without bad reads, CPU halts or perturbed timings (such as stolen bus cycles that upset hard real-time applications).
For now this is only enabled on RISC-V targets that use the System Bus mechanism for memory access as that's guaranteed to be okay by the RISC-V Debug specification, however it can be easily enabled for targets where it's confirmed okay by simply adding `target->target_options |= TOPT_NON_HALTING_MEM_IO;` in the probe routine for that target.
This method has been chosen on account of how difficult it is to find out if a target can do this correctly, and the numerous counter-examples shown for, eg, …

Fix: Memory access halting heuristic

---

.github/workflows/build-and-upload.yml
.github/workflows/build-pr.yml

In this PR we address the upcoming macOS 12 GHA deprecation and switch-off scheduled for the 3rd of December this year. This moves CI entirely to macOS 13 and 14 (latest), with 15 currently in beta.

Fix: macOS CI deprecation

---

.gitignore
src/platforms/hosted/serial_unix.c
src/platforms/hosted/serial_win.c

TCP connections can behave similarly to sockets on all supported platforms. This patch allows for specifying "address:port" on Linux, Windows, and Mac for connecting to a remote device.
Currently this has been tested with Farpatch, however future versions could allow inception debugging wherein low-level commands are forwarded from BMDA to the target, which could even be a second instance of BMDA.

Support connecting to BMP devices via TCP

---

src/target/adiv5_internal.h
src/target/adiv5_swd.c

* The current Dormant to SWD code manages correctly the case where SWD is default/the only interface
* If the chip has both SWD & Jtag and default is Jtag, it lacks the Jtag->dormant sequence and does not work
* The proposed patch adds that sequence
For what i could see, it still works with RP2040 and older Arm chips i have (STM32F1/GD32F3)
Tested on a chip with both Jtag & SWD/Default jtag + Debug Protocol v3, it works with the change, doesnt without
NB: Not completely sure the 8 trailer '1' bits are really needed, it works fine with, was there in the demo code
* [X ] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [X ] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIB …

ARM:Add Jtag to Dormant sequence in case the target has both jtag and swd

---

src/platforms/hosted/gdb_if.c
src/platforms/hosted/remote/protocol_v0_jtag.c

* There are no new features, just porting.
* The existing problem is the BMDA part of the project being *almost* buildable via cross-compilation for Windows, except there are a couple minor errors, even on Windows-hosted MSYS2 MINGW32.
* This PR corrects a Makefile and gdb_if.c, trying to not affect much else.
Tested to succeed up to linking on Gentoo crossdev i686-w64-mingw32-gcc-13 (x86_64- as well) and Ubuntu 22.04 LTS i686-w64-mingw32-gcc-10 (x86_64, too), also MSYS2 MINGW32 (previously only UCRT64 worked, and probably MINGW64). I don't know how this affects MacOS or FreeBSD or anything other I'm not able to test on -- relying on CI.
I am not claiming to *provide* further support for 32-bit desktop operating systems, the world is moving on to 64-bit; but the changes required seem …

Fix cross-compiling BMDA for 32-bit Windows

---

src/platforms/hosted/serial_unix.c

This is required to set `__USE_XOPEN2K` which is required to have access to `getaddrinfo`.

hosted: #include "general.h" before system headers

---

src/platforms/hosted/cli.c

* Not a feature
* Since #1871 when libgpiod-dev is installed on build host, a warning is emitted.
* This PR solves it by terminating both cases with a `break`.
CMSIS-DAP and GPIOD backends are runtime mutually exclusive, so it was not critical, but also nobody picked it up, so I'll clean it up myself.

Fix `hosted/cli.c`, minor implicit fallthrough

---

src/target/at32f43x.c

* This could be described as a new feature (new target support in existing driver)
* The existing problem is AT32F405 not identified by BMD but likely supported via AT32F435 API.
* This PR solves it by adding required match code in `at32f43_probe`.
I do not have any chips accessible for that target and cannot test live, only read refmans. FPEC is at 0x40023C00, which is promising. USD and DBGMCU support not considered yet.
The generic F_SIZE method was used to not carry yet another table of Part IDs.

Feature: Add support for Arterytek MCU AT32F405, F402

---

src/remote.c

When sending data to the remote client, data is hex-encoded. However, an additional byte needs to be allocated in the buffer so as to allow space for the NULL byte.

remote: provide correct 3-byte buffer to `hexify()`

---

src/include/rtt.h
src/rtt.c

This fixes an issue wherein RTT will report the following every 200 ms until it finds an RTT block:
```
rtt: match at 0x0
```
As part of this patch, remove a trailing `\r` that appears in several debug strings.
Finally, make `poll_ms` available globally as `rtt_poll_ms`. This will enable other projects to know when to poll RTT next.

miscellaneus RTT fixes

---

deps/winc1500.wrap
src/command.c
src/platforms/common/stm32/meson.build
src/platforms/ctxlink/WiFi_Server.c
src/platforms/ctxlink/WiFi_Server.h
src/platforms/ctxlink/ctxLink_mode_led.c
src/platforms/ctxlink/ctxLink_mode_led.h
src/platforms/ctxlink/ctxLink_traceswo.c
src/platforms/ctxlink/ctxlink_gdb_if.c
src/platforms/ctxlink/meson.build
src/platforms/ctxlink/platform.c
src/platforms/ctxlink/platform.h
src/platforms/ctxlink/winc1500_driver_stub_api.c

This PR brings an early version of Wi-Fi support for ctxLink. Initially, it attempts to update the souce code to fit more closely with the style of BMF source code as definied by Clang-Tidy.
The built firmware, while offering initiall Wi-Fi connectivity and operation, is not full featured. The intent of this PR is to allow outstanding features in smaller PRs, thus reducing the burden on the author and the reviewer.
None

Initial merge of Wi-Fi support code for ctxLink.

---

src/platforms/common/stm32/meson.build
src/platforms/common/syscalls.c
src/platforms/common/usb_serial.c

Save about 1.2KiB (depending on GCC version) by redirecting `_write` directly in `libnosys`, instead of pulling in `librdimon`.
* Improves firmware footprint on native BMP when debug output is enabled
* There doesn't appear to be a current need to use `librdimon` semihosting capabilities
* `libnosys` I/O functions such as `_write` can be retargeted directly without using semihosting
* Initializing `librdimon` semihosting brings in a lot of unused code
I haven't tested on other probe platforms, so I might have unintentionally broken something.
N/A

common: remove rdimon when debug is enabled

---

src/target/adi.c

Add missing APB2 and APB3 case in `adi_configure_ap`.
This was tested against a [Solitude AML-S905D3-CC](https://libre.computer/products/aml-s905d3-cc/).

Feature: Add support for APB2/APB3 configuration

---

src/target/cortexar.c

As per A-profile TRM, MIDR_EL1 access when not powered or in double lock is implementation defined.
Instead of reading the value after the halt request, let's do it right after the core is powered up and not in double lock.

Fix: Read CPUID when the core is powered

---

src/command.c

In this PR we address a crash that was reported by triggered_tux on Discord and via the issue tracker.
In this crash, if the user has not yet done a JTAG scan on their probe or run any JTAG remote protocol commands since boot prior to issuing `mon tdi_low_reset`, then the probe (or BMDA if done in BMDA) will crash due to trying to call a NULL pointer in the `jtag_proc` structure. To rectify this, we guard this call and make the command fail if the JTAG structure has not been initialised yet.
Fixes #1979

Fix: `tdi_low_reset` crash

---

src/platforms/ctxlink/README.md

This PR updates the ctxLink README to reflect the current Blackmagic Debug build system.
Also, some changes were made to clarify the instructions and some steps were reordered.
None

fix/ctxlink/readme: Update ctxlink readme to reflect the recent build system changes

---

src/target/cortexar.c

This reverts commit 9b68194a8dadeb790c03a181c85a84eecb8e73e7.
As reported on Discord, this seems to cause issues on some boards.
The ARMv7-A spec specify that: "If external debug over powerdown is supported, these registers can be implemented in either or both power domains."
This means that the CPUID handling on ARMv7-A is the opposite of what ARMv8-A requires.
/cc @dragonmux

Revert "cortexar: Read CPUID when the core is powered"

---

src/target/stm32f1.c

When printing a uin32_t, macros from `inttypes.h` should be used.
This fixes the build on Xtensa targets.

stm32f1: use PRIx32 macro for debug log

---

src/target/at32f43x.c
src/target/meson.build

* The `bank_split` field of `struct at32f43_flash` can be eliminated from `_probe`/`_add_flash` if I can use a different method of accessing second bank in `_mass_erase`, checking that `target->flash->next` list has a non-NULL entry. No other functions need it because BMD API guarantees no operations span multiple banks. *This change was rebased past AT32F405 merge.*
* Also, hook the STM32-generic UID printing command to this driver and introduce a meson dependency between these TUs. Move the macros for "engineering bytes"/UID into its own group.
Verified on AT-START-F437 to not break flashloading, a firmware spanning two banks was used.
This should bring a minor reduction to target_flash priv size, and it's a preparation to refactoring this driver to carry USD_BASE and FPEC_BASE in that …

Fix: AT32F43x cleanup

---

src/target/mspm0.c

* Both assert conditions are true due to all respective calls in target_flash.c being `flash->write(..., flash->writesize)` (that's 8 bytes) or `flash->erase(..., flash->blocksize)` (that's 1024 byte blocks)
* This also should restore CI to passing status (for swlink/bluepill which overflow first)
* Not touching any other refactoring opportunities in here for now (like mixed usage of DEBUG_INFO/TARGET and string deduplication for `calloc failed for`... or new mass_erase).
See #1900 for additional explanations.

Fix: mspm0: Remove a couple asserts

---

src/platforms/hosted/bmp_libusb.c
src/target/efm32.c
src/target/stm32l0.c
src/target/stm32l4.c

In this PR we address an issue uncovered while poking at a BMP running pre-v1.7 firmware where the version string is not embedded in the product string. With probes in this configuration, BMDA will correctly find them but then display "Probe" as the version string and "Black Magic" as the product string due to getting handling of the versionless string wrong.
We address this by porting the Windows BMP-only probe discovery product string parsing to the libusb probe discovery logic, which also allows us to properly address probes that use alternative platforms such as Blue Pills and Black Pills and which may not have a version string if their firmware is too old, thus solving the problem.

Fix: Old firmware BMP identification via libusb

---

src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/cmsis_dap.h
src/platforms/hosted/dap.c
src/platforms/hosted/dap.h
src/platforms/hosted/dap_command.c
src/platforms/hosted/dap_jtag.c
src/platforms/hosted/dap_swd.c

This PR addresses a series of bugs found by j4cbo and Xobs on Discord concerning CMSIS-DAP adaptors. They concern: how the backend handles FAULT responses; how the backend handles WAIT responses due to AP hangs during block transfers (and subsequently, short responses); how the backend handles full responses over Bulk (ZLP handling); how the backend chunks reads; how the backend chunks writes.
This fixes the behaviour of the backend so that when a FAULT response is encountered, the backend cleanly returns up the stack as in a normal transport request - the main code base knows how to handle this, so don't `exit()` out when it can usually be recovered, and otherwise reported.
This fixes the behaviour of the backend not aborting a transfer on encountering a WAIT response, which is roughly …

Fix: CMSIS-DAP block I/O

---

cross-file/stlink.ini
meson_options.txt
src/platforms/stlink/meson.build

Just an addition to https://github.com/blackmagic-debug/blackmagic/pull/1720 since the Makefile buld system was removed, this adds support for the host while building with meson

stlink: add config for the ISOL variant

---

src/target/mspm0.c

This PR does some post-initial-PR cleanup for clang-tidy lints and small pattern issues that do not change functionality of the implementation but do improve code size and consistency a little. Nothing too huge - the implementation could still do with having the mass erase function refactored into a bank erase function and registered as `flash->mass_erase` rather than `target->mass_erase`, but without a part to test that against we're unwilling to go changing that for the moment.

Fix: MSPM0 cleanup

---

src/platforms/ctxlink/WiFi_Server.c
src/platforms/ctxlink/platform.c
src/platforms/ctxlink/platform.h

The reading of the ADC to acquire the target and battery
voltages was being done in a blocking manner and at
a place in the code that blocked the timely servicing
of the Wi-Fi channel.
In this updated code the ADC is read in the Timer service of the Wi-Fi Server.
There are two channels and each channel conversion is started on one timer service and read on the next timer service. Giving four phases of operation.
Also, the ADC reading code is only run every 100ms.
None.

ctxlink/wifi: fix the speed issues with the Wi-Fi interface

---

src/target/cortexm.c
src/target/cortexm.h

The DWT block is different on Arm V8m compared to older revisions.  As a result the watchpoint(s) function are not working. 
The patch adds a second path dealing with the ArmV8m  .
Tested on cortex m33, check setup watch some_variable  (such as xTickCount on freeRtos)
- without the patch, does not stop
- with the patch, does stop as expected
It was partially tested, i dont have other chip with that DWT block. Only test write watchpoints.
As far as i can tell, watchpoints are still working with older chips (cortex M4)

Cortex-M: Temptative fix for watchpoints so they work on ARMv8-M cores (eg Cortex-M33)

---

src/target/cortexar.c

This should have been clearing data and mmu fault flags.
Fixes: 56f744eb7950 ("cortexar: Implemented caching for the fault information, doubling memory IO performance")
This should have been clearing data and mmu fault flags.

cortexar: fix typo in cortexar_check_error

---

src/target/cortexar.c

This seems to be an oversight, let's mirror whaT cortexar_mem_read does.
This seems to be an oversight, let's mirror whaT cortexar_mem_read does.

cortexar: halt core in cortexar_mem_write

---

src/gdb_main.c
src/target/adi.c
src/target/adiv5_internal.h
src/target/adiv5_swd.c
src/target/adiv6.c
src/target/cortexm.c
src/target/cortexm.h
src/target/target.c

In this PR we address some structural clean-up that is needed in the wake of all the ADIv6 work and some issues in Cortex-M debug of ARMv8-M targets.
This has wound up touching the ADI, Cortex-M, target and GDB layers so apologies that this PR is a little all over the place. With this however, we now have proper diagnostics on what GDB is asking us to do vs what we're doing in regards to `step`/`next`/`stepi`/`continue`/`run`/etc and ARMv8-M debug works properly. Tested on a Cortex-M33 and Cortex-M4 (to ensure we didn't break ARMv7-M debug in the process).
This solves what we could reproduce of the final issue raised in #1970. Any further issues in relation to ARMv8-M debug are likely to do with S vs NS modes and what debug is allowed per the DHCSR.
The GDB changes fix GDB trying to guess …

Fix: ADI structural cleanup and ARMv8-M debug improvements

---

.github/workflows/build-pr.yml
cross-file/bluepill.ini
cross-file/swlink.ini
src/target/nrf51.c
src/target/nrf54l.c
src/target/nrf91.c
src/target/stm32f1.c
src/target/stm32f4.c
src/target/stm32g0.c
src/target/stm32h5.c
src/target/stm32h7.c
src/target/stm32l0.c
src/target/stm32l4.c

In #1882 we introduced control of the WDT halt state to prevent debug sessions getting clobbered by them while the part is intentionally halted. In that PR we stored the state of the DBGMCU on attach, and restored it on detach - which on its face seems like a reasonable heuristic, however.. we worried at the time and have since had that fear confirmed that this doesn't work well because both the user code and the debugger can change the state of the DBGMCU register in question itself to do things like enabling tracing, and users want to be able to detach from the target to leave tracing running.
In the scenario outlined above, however, BMD will disable tracing by restoring the pre-image of the DBGMCU control register, and undo any other freeze configuration by restoring the freeze …

Fix: STM32 DBGMCU attach/detach behaviour

---

src/include/gdb_packet.h

gdb_packet.h now calls `strlen()`, but does not have the include for it. This causes build failures on systems where warnings are treated as errors.
Add `#include <string.h>` to `gdb_packet.h` to fix this warning.

gdb_packet: add missing <string.h> include

---

src/platforms/ctxlink/WiFi_Server.c

when the firmware has debug enabled some DEBUG_WARN messages in ctxLink had invalid/undefined names. These are fixed by this PR.
None

ctxlink/wifi_server: Fix variable names when debug is enabled.

---

src/target/stm32f1.c

* The existing problem is incorrect SRAM size declared in stm32f1.c for STM32F0 families, 20 KiB, which matches neither of them (but might have been copied from STM32F103). This interacts badly with RTT auto search.
* This PR adjusts ram_size values to whatever documented in reference manuals, just like flash size.
Tested on 32F072B-Disco to no longer trigger lots of `SWD access resulted in fault, retrying` every time mainloop calls `poll_rtt()` and that crosses 0x20004000 boundary of a 16 KiB SRAM F072RB device to "search" for control blocks up to 0x20005000.
I think also the DUT BMF (which I ported there as a f072-if derivative) got stuck when this bug was triggering, judging by the morse blinky stopping.
My problem is specifically advertising 20 KiB on a 16 KiB device; …

Fix: Shrink SRAM sizes of STM32F0

---

README.md
meson.build

In this PR we address the state of the main project README, giving it an overhaul for the upcoming v2.0 release where a great many things about how the project is built and managed changes.
During this process we have also addressed descriptional issues with how the README introduces the project and its purpose, and updated the pills displayed to include more useful information.
Fixes #1933 and #1937

Fix: main README.md overhaul

---

src/target/at32f43x.c

* The F_SIZE readout and usage as implemented in #1949 is incomplete and results in failure to reprogram internal flash of AT32F405RC.
* This PR solves that by factoring in the kibibytes multiplier, for both AT32F402/405 and AT32F423 added in that commit.
For a (C) 256 KiB flash part, the F_SIZE "register" contains not 262144 but 256, which (as used in PR1949 26d27b90) generates a target flash map of 256 byte length and 2048 (or 1024) byte erase-sectors, which is broken.
Assumed tested on some BMD-derivative platform.

Fix AT32F405 flash size/map

---

src/platforms/ctxlink/WiFi_Server.c

This PR enables a transfer speed increse for file loading and other operations over wi-fi. It does this through management of the power saving modes of the WINC1500.
The WINC1500 API was also updated to better control the power saving API.
None

ctxlink/wifi_server: Change winc1500 power mode to manual.

---

src/platforms/ctxlink/platform.h

The ctxLink platform did not have the required enable/disable code for debug output. This PR adds that functionality.
None

ctxlink/platform: Add debug output control to platform.

---

src/platforms/hosted/cmsis_dap.c

In Uwe's #1614, the point was raised that some older NXP MCU-Link firmware misbehaves in how it reports CMSIS-DAP versioning and such. This PR seeks to address that properly by special-casing the handling of version strings hitting the buggy behaviour.
This PR supersedes that one as after more than a year it has seen no response to the review given. This should leave just one quasi-bug remaining from that PR which is to do with interfacing with older CMSIS-DAP v1.x firmware as we use a feature that is not supported.

Fix: MCU-Link CMSIS-DAP version handling issues

---

.github/workflows/build-and-upload.yml

In this PR we address that the build-and-upload flow doesn't properly embed the version string associated with the build being done. This is caused by a lack of tags being pulled with the cloning process the flow uses.
This should result in all future nightly (build-and-upload) builds having the full versioning information embedded in.

Fix: Nightly build version strings

---

src/gdb_main.c

* This is a minor but important bugfix.
* The existing problem is gdbserver returning unexpected read errors E02 `Cannot access memory at address` to otherwise normal accesses.
* The PR solves it by fixing a mistranslated bounds-check introduced in ca. v1.10.0-1567-g de645593 of #2014.
Tested on gd32f103cb bluepillplus running bluepill.ini/stlink BMF; and BMDA; against stm32g474ce. At first I expected wrong RCC/Flash config or invalid SRAM mapping, but interactive debugging of BMDA and extended logging proved otherwise.
Note: `(gdb) maintenance packet m08070000,201` triggers a 513 byte read which is rejected by BMD. Only <=512 is good because of 1024 byte RSP packet buffer.

Fix: unexpected E02 from gdb m-packets

---

src/target/riscv_debug.c

* This is a small typo fix.
* The existing problem is `tscratch` description for gdb target.xml of MSCRATCH CSR.
* The PR solves it by renaming to `mscratch`.
Not tested on anything, because I don't have a gd32vf1/sipeed longan nano, and ESP32-C3 needs burning OTP eFuses for external JTAG (USJ is not supported by BMDA). Unsure what uses this.

Fix: Rename RISC-V machine scratch CSR

---

src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/blackpill-f4/blackpill-f4.h

* For this board, this is a new feature (from other boards).
* The existing problems are TRST unused and SWCLK always driven.
* The PR solves them by initializing TRST_PIN in output open-drain pull-up mode, and implementing `platform_target_clk_output_enable()` which switches SWCLK/SWDIO to inputs or outputs.
This should allow keeping multiple BMPs wired up to a single target for cross-testing etc. and should prevent drive fight with low pin count chips like STM32G030J6 (I don't have one) or which remap their PA13/14 to output mode otherwise. No known shields/carriers/mainboards exist for it which have directional buffers and TCK_OEn aka TCK_DIR_PIN -- it would need similar treatment.
TRST pin high is required to even scan Raspberry Pi 3B (BCM2837), otherwise its TAP is disabled (default …

Feature: blackpill-f4 better control of pin mode

---

src/platforms/common/usb_descriptors.h
src/platforms/hosted/remote/protocol_v4_adiv5.c
src/platforms/hosted/remote/protocol_v4_defs.h
src/remote.c
src/remote.h
src/target/adiv5_swd.c

In this PR we address issues found while trying to debug STM32WL55 discovery. This process found bugs in both the error recovery implementation for SWD, and in the remote protocol.
On the SWD side, the error detection code failed to properly notice when a read of the DP's CTRL/STAT register failed and then properly handle that with protocol recovery. This slightly complicates the routine, but makes the error discovery and recovery process significantly more robust.
On the remote protocol side, the protocol failed to transfer the TARGETSEL value to use for a given DP for SWD multi-drop, resulting in protocol recovery failing to execute correctly to re-select the target and resume communications. This is corrected by addition of a new command for transferring this information to the shadow …

Fix: STM32WL55 discovery

---

meson.build
src/gdb_main.c
src/include/target.h
src/rtt.c
src/target/cortexar.c
src/target/cortexm.c
src/target/riscv_debug.c
src/target/target.c
src/target/target_internal.h

This change breakwatch::addr to be 64-bit as this will be required for ARMv8 AArch64 support.
This also change the layout of breakwatch to avoid extraneous padding in 64-bit and reduce the size of the reserved array to 64 bits.

target: Support 64-bit address for break/watch point

---

src/target/stm32h5.c
src/target/target_flash.c

In this PR we address an issue found by Esden where reprogramming a STM32H5 part would go wrong due to erase not completing properly.
As it turned out, this was caused by a mistake in the beginning address calculation. While fixing this we have opted to clean up the implementation using the guarantees of the target Flash API to simplify the code.

Fix: STM32H5 reprogramming

---

src/target/adiv5.h
src/target/adiv5_jtag.c

* The existing problem is GD32E508ZE device no longer accepted by BMD since introduction of #1981 ADIv6 JTAG-DP support, v1.10.0-1445-g e0100843 (bisected), because this chip is only ADIv5.
* The PR "solves" it by recognizing 0xba04 partno and setting DP version to 0 like older JTAG-DP, which used to work.
A temporary patch "like LPC43xx errata" may not be ideal, because this is not mentioned in GD32E5 errata, but likely ends up an actual Cortex-M33 DAP ("TEALDAP") that is SWJ-DP MINDP. But I leave DPv0/v1 and ADIv6 DPv3 distinction details to maintainers. It works with JLink and with OpenOCD, and it used to work with BMD, it's not new.
Note: the other in-tree CM33 chips, STM32H5, identify as 0xba00 which corresponds to CoreSight SoC-400 JTAG-DP, and ST is known to have …

Fix: Treat GD32E508 in JTAG transport as ADIv5

---

meson_options.txt

Enabling noackmode advertisement tells GDB we support and prefer noackmode, who will then enable it by default. Right now the mode is supported but not advertised, it needs to be explicitly enabled by the user.
This should make the protocol more efficient even if by negligible amount without any drawbacks, as we have a reliable data connection making the checksums and acknowledgements redundant.

Feature: enable noackmode by default

---

src/target/adiv5.h
src/target/adiv5_jtag.c

This PR addresses a mistake made in the way that we handle DP versioning for JTAG-DPs in ADIv5 and v6.
ADIv5 implements *protocol* version 0, while ADIv6 implements version 1. This is a totaly different thing to the detectable version from the JTAG IDCODE `PARTNO` field which is related to the DP version instead.
We correct the low-level handling in adiv5_jtag.c with this, so that DPv0-2 work properly as protocol v0, while DPv3+ are protocol v1. This allows the PARTNO -> version translation to then be corrected and handled more appropriately.
Tested on a LPC4370.

Fix: adiv5/6 JTAG version handling

---

src/platforms/common/blackpill-f4/blackpill-f4.c

This pull request slightly updates the code for the blackpill-f4 platforms:
- it adds an `#ifdef` around the line of the code where the `LED_BOOTLOADER` pin is set up using `gpio_mode_setup()` for the second time in the same file, in case `BMP_BOOTLOADER` is not defined. This change is made as it is redundant to setup the `LED_BOOTLOADER` pin twice.

Feature: platforms/blackpill-f4: only setup LED_BOOTLOADER once

---

src/target/imxrt.c

* The i.MX RT1176 includes both an M7 and M4 core but only the M7 was being detected by BMP / BMDA. This fix enables detection of the M4 core (a separate AP entry) under the same target part_id as the M7.
* The generic RAM mapping provided in imxrt.c for all i.MXRT devices was inaccurate for the RT117x and did not distinguish between the memory available to the M7 core vs. the M4 core. This fix maps the RAM based on the target->part_id and core and includes a fairly comprehensive mapping for the RT117x.
* Flash detection logic did not require changing (both cores map the FlexSPI controller at the same location).
* The i.MX RT117x supports register-configurable SDRAM and SRAM but the addresses for this are not fixed and the same controller can be used for flash memory as well. These ranges …

Fix: imxrt: Cortex-M4 core detection for RT1176

---

meson_options.txt
src/platforms/common/blackpill-f4/meson.build

This PR adds back the option to compile using the `SHIELD` macro for blackpill-f4* boards.
This functionality was available when the code was compiled using make, but got lost in the translation to meson. This PR adds back this functionality.

Add option to compile blackpill-f4* with SHIELD option, using meson

---

src/gdb_main.c
src/gdb_packet.c
src/include/gdb_packet.h

When a connection is terminated abruptly the noackmode state may be left in a "zombie" state, enabled, because we are unable to detect the connection was terminated.
We previously used the qSupported packet to signal a new connection and reset the state, but this breaks compatibility with LLDB which does not send qSupported as the first packet.
This attempts a new approach, by checking if a acknowledgement was sent in response to qSupported reply, we can detect when noackmode is enabled when it shouldn't. This also needs some special cases to acknowledge the first packets in a connection when noackmode is in a zombie state.
This introduces a small issue on LLDB connections, it tries to get an acknowledgement on qSupported which never comes, this is intended but, at least in hosted, the …

Fix: noackmode zombie state handling

---

src/platforms/common/blackpill-f4/blackpill-f4.c

This PR corrects a naming issue with the Blackpill-F4 platform.
The bootloader LED pin was not being setup.
None

blackpill/platform: Correct the condiitonal compilation symbol to initialize the bootloader LED pin.

---

src/platforms/common/blackpill-f4/README.md

This PR updates the Blackpill-F4 readme to describe the need for the "on_carrier_board" bujild option.
None

Blackpill/readme: Update to describe need for "on_carrier_board" option

---

src/target/efm32.c

#402 introduced a bug with silabs devices (efm32/efr32) related to the parsing of the DI (Device Info) page. An example is [efr32xg13](https://www.silabs.com/documents/public/reference-manuals/efr32xg13-rm.pdf), which I believe would currently be broken. I do not have any of the relevant devices and cannot test this, but I noticed it while playing with adding support for the newer "series 2" parts (eg. EFRMG24).
The driver currently knows about two versions (it calls them "version 1" and "version 2") of the DI page with completely different layouts. It decides which version to use by:
1. Reading the EUI64 from the location specified by DI layout version 1
2. checking if the 24 bit OUI therein is equal to `EFM32_V1_DI_EUI_SILABS`, in which case layout version 1 is used
3. If not, checking …

[efm32_probe] Fix detection of DI v2

---

src/platforms/common/blackpill-f4/blackpill-f4.c

* This is a bug fix for an half-implemented feature.
* The existing problem is floating nRST pin of `blackpill-f4`, which is, at least, inconsistent with other in-tree platforms.
* The PR solves it by enabling internal weak pull-up resistor on it.
The original implementation was contributed like this in #1280 v1.8.0-702-g 02986d67 and such code snippet is correct for F1 GPIO, where resistors are part of input stage, but superflous for F4 GPIO, which retains PU/PD config across all digital modes (Input, Output, AF). I don't even see a reason to change modes or output-settings away from Output + Open-Drain + Pull-up + Lowest OSPEED. `gpio_clear` activates the low FET, `gpio_set` deactivates it, so `GPIO_ACTIVE_LOW` in Linux device-tree gpio bindings speak, or inverse polarity (`!assert`). …

blackpill-f4: Enable internal weak pull-up on nRST, simplify set_val

---

src/include/platform_support.h
src/platforms/common/blackpill-f4/blackpill-f4.c
src/platforms/common/stm32/timing_stm32.c
src/platforms/stlinkv3/platform.c
src/platforms/stlinkv3/platform.h

* This is a new feature.
* The existing problem is poor signal integrity (ringing/reflections, ground bounce) of `stlinkv3` and `blackpill-f4` platforms resulting in failure of initial scan on setups with poor ground connections. 
* This PR solves it by runtime-matching STM32 GPIO OSPEED to the toggle rates indicated in datasheets.
Prior changes: 
`stlinkv3`: #1945, v1.10.0-1289-g 27cbec7e
`blackpill-f4`: #1717, v1.10.0-500-g b9969de3; and #2044, v2.0.0-rc1-3-g a3bb02e9
Because STLINK/V3E onboard Nucleo-H743ZI2 outright didn't work at highest reachable frequency (above 12 MHz) at 2 MHz slew rate, I gave 25 MHz a try and it worked. That platform is able to checksum target data at about 400 KiB/s.
MiniSTM32F4x1Cx is slower, but still can hit 8.72 MHz (96/11) without significant firmware …

Feature: change platform GPIO slew rate when high SWCLK frequency is requested

---

src/platforms/common/blackpill-f4/blackpill-f4.c

In #1717, the output slew rate for the JTAG/SWD pins on bluepill-f4 was changed to 25MHz. This leads to failing target scans even with low bus speeds when the target isn't connected by e.g. two ground wires. In #2065, this was mitigated by switching output slew rate depending on requested speed. However, the cutoff was set at 2MHz, while the default bus speed is 3MHz. This keeps the bad out-of-the-box experience for users that don't know or are not able to set their own bus frequency.
The 2MHz slew rate is fine for a signal frequency of 3MHz, see datasheet DS10314.
cc @ALTracer

blackpill-f4: change slew speed frequency cutoff to 3 MHz

---

src/command.c
src/platforms/ctxlink/WiFi_Server.c
src/platforms/ctxlink/WiFi_Server.h
src/platforms/ctxlink/ctxLink_mode_led.c
src/platforms/ctxlink/ctxLink_mode_led.h
src/platforms/ctxlink/ctxlink_gdb_if.c
src/platforms/ctxlink/platform.c
src/platforms/ctxlink/platform.h

This PR adds Wi-Fi management for ctxLink using GDB and a new monitor command.
With the original releases of ctxLink some users had issues using the HTTP and WPS provisioning features of ctxLink.
Also, after provisioning some users found it hard to discover the IP address of ctxLink, this is required to connect to the probe.
The new monitor command is "wifi".
To inspect the current Wi-Fi status the following command is used:
mon wifi
This will display either "Not Connected," or the SSID, Signal Strength (RSSI), and IP address of the connected Access Point.
To connect to a Wi-Fi Access Point the following command is used, substituting the SSID and PassPhrase settings of the AP:
mon wifi SSID,Passphrase
Spaces are accepted for these two parameters, however, there should be no space before …

Fix: WiFi configuration issues via USB (HTTP/WPS provisioning sometimes unreliable)

---

README.md

Add basic instructions on how to build the BMP bootloader to README.md.
The existing documentation tells you how to build probe firmware but assumes you've already got a working bootloader - took me a while to work out how to build this, so I figure it is worth documenting.

misc: Add bootloader build instructions to README.md

---

src/platforms/common/stm32/dfucore.c

* This is a minor feature with no new code.
* The existing problem is BMD bootloader ignoring `dfu-util --detach` requests. It still does reboot on `dfu-util -s :leave`.
* This PR solves it by adding an explicit request handler.
DFU runtime is unaffected, it already handles DFU_DETACH.
BMD bootloader still auto-reboots in Manifest phase when it has written a new firmware, this is not about that.
Tested on `blackpill-f411ce` with `dfu-util -v` and `bmputil`.

Fix BMD Bootloader to handle DFU_DETACH requests explicitly

---

src/target/cortexm.c

This is a partial workaround for  #2094  
The core problem is depending on the option enabled ( FPU, Trustzone,..) the size needed for target_read/write_regs varies. Part of the code was wrongly computing the needed size and causing stack overflow/corruption and FPU+Trustzone was present.
The partial workaround is to use a define correctly settings the needed size and using it in cortemx.c
This is only partial because :
1- It is local only. There are similar wrong constructs in lpc55 code at least.
2- It does not really solve the core issue of ensuring the proper size has been allocated by design.
On option for the later would be to define a structure cortexm_registers / riscv_registers.. 
with the proper size. 
I tested it on my test case which adds more trustzone registers …

cortemx: use a global define to make sure we allocate enough room for registers

---

src/target/stm32f4.c

* The existing problem is RTT Auto Search triggering lots of SWD Fault past end of physical SRAM on STM32F722.
* This PR solves it by shrinking declared memory map and dispatching datasheet values per-family.
As I've tried to inspect/debug a project on a board involving STM32F722, the RTT Auto Search feature (which is supposed to be plug&play without configuration) started scrubbing available RAM but fell off the 192 KiB cliff trying to scan all 384 KiB of AHB SRAM which should be present on STM32F777. Confirmed with `blackpill-f411ce` and BMDA. I know about `mon rtt mem` ranges but this sounds more like a workaround rather than fix, BMD should provide knowledge of DUT flash and RAM maps and sizes.
Note this was not rigorously tested with a real project yet. I don't …

Fix: Declare correct RAM sizes for STM32F7

---

src/target/stm32f4.c

* The existing problem is too generous AHB SRAM maps for most STM32F4 families which are smaller than STM32F469. This triggers SWD faults for access beyond end of physical RAM (including RTT auto-search). CCM is fine.
* This PR solves it by matching AHB SRAM size to part ID per refmans.
Follow-up to #2075.
I can only test on F411CE and maybe F427, F469. Entire series is described by (14 datasheets and) 8 refmans, of which only 2 are linked now.
Note that STM32F207/217 is defaulted to 128 KiB here, F205/215 likewise, which is correct, but some F205 parts also come in 96 and 64 KiB smaller flavours -- I have no idea how to do this cheaply other than coupling this to (B)/(C) flash size read out from F_ID engineering bytes. Their RM0033+PM0059 and DS6329+DS6697 can be added …

Fix: Declare correct RAM sizes for STM32F4

---

src/target/stm32f4.c

* Not a new feature.
* The existing problem is BMP/GDB `Load failed` for STM32F7 binaries linked to 0x0200_0000 ITCM flash bigger than 64 KiB.
* This PR solves it by extending/copying AXIM flash map to ITCM flash alias map.
Tested on STM32F722RE with BMDA/`blackpill-f411ce` to allow loading 512 KiB binaries (erase, write, verify, in-firmware check). Testers with F76x/F77x (like STM32F777) are otherwise welcome.
I've changed the order of first bank `stm32f4_add_flash()` calls here, maybe it's unwanted. But the following code block will also want to append to ITCM dual-bank sectors. If mixed order in-BMP is a problem, please state so. Another worry is this will interact with future `blank_check` feature, forcing it to walk entire NVM twice. I'd like to treat this separately by tracking e.g. …

Fix STM32F7 ITCM Flash alias map

---

src/platforms/native/platform.h

In the code for the native probe, the TMS_DIR and TCK_DIR weren't properly documented. This makes custom implementations of the BMP board harder.
I fixed the description of the TMS_DIR pin.
I also added description for the TCK_DIR pin, including the reason why we would like to switch the direction of the TCK signal.
None

native/platform: Fix and add documentation for TMS_DIR and TCK_DIR on native

---

src/platforms/hosted/bmp_libusb.c
src/platforms/hosted/cmsis_dap.c
src/platforms/hosted/dap.c
src/platforms/hosted/dap.h
src/platforms/hosted/dap_command.c
src/platforms/hosted/dap_command.h
src/platforms/hosted/dap_jtag.c
src/platforms/hosted/dap_swd.c
src/platforms/hosted/windows/ftdi.c
src/target/jtag_scan.c

In this PR we address several issues encountered with certain CMSIS-DAP adaptors, notably ones from Atmel such as the JTAGICE3 which use HID (CMSIS-DAP v1.0.0, the unpublished spec) and massive packets (512 bytes) over HS.
We aim with this to fix the transfer behaviour for these adaptors (the packets are one byte too short before this, causing problems with the communication cycle), and provide various fallbacks and such for commands not implemented in the older versions of the spec.
The over-all result should be a more stable CMSIS-DAP experience and saner behaviour out of HID based adaptors.

Fix: CMSIS-DAP HID I/O

---

meson.build
src/command.c

This PR addresses the version number reported from a tarball of the source being wrong (v1.10.0) and similarly addresses the displayed copyright string when the firmware is asked for its version.
This solves a couple of cosmetic problems with the latest release candidate - note that the Meson-reported version number will need updating again when the full release is performed.
A better way of maintaining this version number will be a goal for v2.1 as having to update it every release is going to be a drag.

Fix: Version and copyright display

---

src/platforms/hosted/bmp_libusb.c

This PR fixes the detection of CMSIS-DAP V2 adaptors which have the optional SWO trace USB bulk endpoint. This configuration is allowed by the [CMSIS-DAP documentation](https://arm-software.github.io/CMSIS-DAP/latest/dap_firmware.html#dap_bulk_usb). The documentation also prescribes the order of USB endpoints, meaning we are safe to ignore the optional endpoint.
Closes #2107 (tentative)

hosted/CMSIS-DAP: Do not discard devices with optional SWO endpoint

---

src/target/riscv_debug.c

This PR addresses a bug reported to us on Discord. The bug manifests as the string `rvhu<extensions>` being returned to GDB from the firmware (but not BMDA) for identifying the exact RISC-V ISA of a core.
This is caused by newlib-nano not understanding width modifiers (which `PRIx8` is defined with on ARM, giving `%hu` instead of `%u` for the core bit width format specifier).

Fix: RISC-V ISA identification

---

.github/workflows/build-and-upload.yml

In this PR we address the issues identified with builds of the `native` firwmare on the build-and-upload flow which result in the builds stomping on each other when building the firmware archive artefact.
This is due to the build system putting out the same `blackmagic_native_firmware` base name for all profiles, while to not wind up trampling each other, the variants need the variant name included as in `blackmagic_native-uncommon_firmware` or so.
This should be being smartly managed now with room for expansion if other platforms wind up requiring variants in the future.

Fix: CI for native on the build-and-upload flow

---

.github/workflows/build-and-upload.yml
.github/workflows/build-pr.yml
.github/workflows/lint.yml

In this PR we handle some items discovered by running CodeQL code scanning on the project. Specifically, CI jobs are supposed to be specified with a permissions restriction block that list out what all exactly the job needs from its access token to complete its work, so the token can be locked down and not overly broad.
We achieve that by providing job-global permissions blocks across all 3 configurations run to set what they need to be able to do

Fix: Missing CI permissions restrictions

---

meson.build

As part of getting `bmputil` ready for its v1.0 release, the tool was renamed to `bmputil-cli` and the CLI overhaulled.
This PR addresses these changes by introducing some logic for finding this version of the tool in preference for the pre-v1.0 `bmputil`, and providing logic under the new CLI structure for doing probe reprogramming via `ninja flash`.

Fix: `bmputil` CLI changes

---

src/remote.c

In this PR we clean up after #2129 where a couple of mistake were made that can result in incorrect values getting generated from the new remote protocol packets.
The mistakes consist of two things: 3 typos in the config macros checked (`CONFIG_EFM` => `CONFIG_EFM32`, `CONFIG_RENESAS_R{A,Z}` => `CONFIG_R{A,Z}`; and some bad logic for checking if the values are defined as on/set.
To explain the latter slightly, in the C standard an undefined macro is allowed to be interpreted by the preprocessor in `#if` checks as if it were defined to 0; however this may generate a diagnostic and is allowed to be overridden. In the case that a config macro is set and to a value that's not expected, or the compiler is treating undefined macros as errors, the old logic would go wrong. The pattern required …

Fix: Config macro errors

---

src/target/cortexm.c

Add ARM v8m SecureFault exception to `vector_catch` command.
The control bit in `DEMCR` is named `VC_SFERR`, so it's shortened to `sf` following the same pattern as the existing exceptions.

cortexm: Add v8m secure fault to vector_catch

---

src/target/samd.c

Add support for PIC32CM MC Family.
This change adds support for the PIC32CM MC family, a cost-optimized version of the SAM C2x series. The family includes four members:
- PIC32CM1216MC000(32|48) - 128K flash, 16k ram, 32 or 48 pins
- PIC32CM6408MC000(32|48) - 64K flash, 8k ram, 32 or 48 pins

Feature: samd: Add support for PIC32CM MC Family

---

src/platforms/stlinkv3/meson.build

Testing the previous firmware on STLink-v3Mini revealed that the program load address was incorrectly configured for ST's bootloader (`-Dbmd_bootloader=false`). The correct offset is the same as for when using the BMD bootloader; hence, the option has been removed altogether now.

stlinkv3: get rid of bmd_bootloader option and fix load address for OEM bootloader

---

src/target/sam3x.c

In this PR we address a report from user dhylands on Discord where his SAMV71 based board would refuse to take firmware past the first 8KiB of Flash with an erase failure.
This PR consists of two parts - modernisation of the code, and then addressing the user's issue. In modernisation we have fixed nomenclature and file organisation, bringing things inline with, eg, stm32h5.c. To address the user's issue, we have implemented proper mass erase support, and found an erase page count that should be common to all the Flash on SAMx7x parts, having the code switch between sizes depending on what the part's detected as being (SAM4x vs SAMx7x).
This has been tested working by the user, erasing and programming 2MiB of Flash successfully.

Fix: SAMx7x support

---

src/include/target.h
src/target/adi.c
src/target/adiv5_internal.h
src/target/arm_coresight_cti.c
src/target/arm_coresight_cti.h
src/target/cortex.c
src/target/cortex.h
src/target/cortexa_armv8.c
src/target/meson.build
src/target/target.c
src/target/target_probe.c
src/target/target_probe.h

As ARMv8-A changed entirely debug interactions, a new target was needed.
This implements a new basic target for ARMv8-A that only support AArch64 for now.
I tested all those changes with a [Solitude AML-S905D3-CC](https://libre.computer/products/aml-s905d3-cc/) on core 0 in u-boot (JTAG access can be enabled with `smc 0x82000040 2`)
Things left as todo that will not be tackled by this PR:
- Float registers
- AArch32 support (Lot of cortexar.c could be reused for this)
- Any relevant ARMv8-A extensions to expose (Pointer Authentication)
- Possibly weird CoreSight tables where the CTI component isn't after the DC
- SMP
Depends on #2017.

Feature: Add a new target for ARMv8-A

---

src/target/cortexa_armv8.c

Fix the formatting args for cortexa_armv8. This fixes the build on ESP32.

cortexa_armv8: fix formatting args

---

src/target/stm32f1.c

In this PR we clean up the logging for the STM32F1 support which now duplicates that in the Target Flash API layer. This causes logs to be confusing and messy, so let's remove the extra logging.

Feature: STM32F1 logging cleanup

---

src/target/adiv5_swd.c
src/target/at32f43x.c
src/target/lpc546xx.c
src/target/lpc55xx.c
src/target/msp432p4.c
src/target/mspm0.c
src/target/nrf51.c
src/target/nrf54l.c
src/target/nrf91.c
src/target/nxpke04.c
src/target/puya.c
src/target/rp2040.c
src/target/s32k3xx.c
src/target/sam3x.c
src/target/sam4l.c
src/target/stm32f1.c
src/target/stm32f4.c
src/target/stm32g0.c
src/target/stm32h5.c
src/target/stm32h7.c
src/target/stm32l0.c
src/target/stm32l4.c
src/target/target.c
src/target/target_flash.c

In this PR we clean up nomenclature across the code base and significant clean up and unify structure and layout of particularly target support. This concludes the long-running refactoring campaign to modernise and unify the code base that was started back in v1.8.
This brings with it a fix for #2148 removing a diagnostic that some users we relying on for writes, and target Flash API modernisation for several targets' Flash code, thus reducing Flash usage for that support.
Due to the sheer number of commits in this PR, we are opting to call it complete where it is and resume cleanup in the platforms and BMD core in a new PR to help manage review and load.

Feature: Nomenclature cleanup
