src/lmi.c, src/nrf51.c, src/stm32f1.c, src/stm32f4.c
o Stubs were declared as globals which means they will be initialized
data.  No need for this.  Now, stubs are static const and are only
present in the program image.
=> Fix to move stubs into rodata.

src/gdb_main.c
`target_attach` [can return false](https://github.com/blacksphere/blackmagic/blob/master/src/cortexm.c#L412)! Handle this gracefully :)
=> Check target_attach succeeded in vRun command, and return error if not

src/sam3x.c
The memory map is identical to the SAM3N.
Tested on http://www.dresden-elektronik.de/funktechnik/produkte/boards-und-kits/development-boards/derfnode/
With greetings,
-Martin
=> SAM3S support

src/sam3x.c
The SAM4S has a working "Erase Page" command. We can use that instead of "Erase/Write Page", which is the only option for SAM3X/SAM3N.
Furthermore, I must abashedly admit that the "Erase/Write Page" command *does not* work on the SAM4S *except in the first 16 kilobytes of flash*. I didn't catch this case previously because the chip comes erased and I only tested writing high memory once.
Cheers, David
=> Add support for SAM4 erase command

src/sam3x.c
This pull request (1) changes SAM4S flash erases to use 8 page chunks instead of 16 page chunks, and (2) corrects a bug in the generation of the FARG field for SAM4S flash erases.
(1) This issue is due to an error in the SAM4S datasheet. Table 20-4 states that 16 page erases may be used on all sectors, but buried in section 8.1.3.1 is a note that only 8 page erases are guaranteed to work in sectors 0 and 1.
(2) FARG[15:2] is not supposed to be shifted left by two bits. This bug was masked by the fact that an invalid 16 page erase on sector 0 also erased sectors 1-3.
I've been testing this change for more than a month now, so I am confident that there are no more SAM4S flash erase issues lurking within.
Cheers,
Dave
=> SAM4S: Erase flash in 8K instead of 16K chunks.

src/Makefile, src/adiv5_jtagdp.c, src/adiv5_swdp.c, src/command.c, src/cortexm.c, src/exception.c, src/gdb_main.c, src/include/adiv5.h, src/include/exception.h, src/main.c, src/platforms/f4discovery/platform.h, src/platforms/launchpad-icdi/platform.c, src/platforms/launchpad-icdi/platform.h, src/platforms/libftdi/platform.c, src/platforms/libftdi/platform.h, src/platforms/native/platform.c, src/platforms/native/platform.h, src/platforms/stlink/platform.c, src/platforms/stlink/platform.h, src/platforms/stm32/timing.c, src/platforms/swlink/Makefile.inc, src/platforms/swlink/platform.c, src/platforms/swlink/platform.h
Implement a programmatic way of raising and handling exceptions to replace the platform specific macros based on setjmp/longjmp.
This also allows timeouts to be handled more gracefully, and better user feedback when the target is in WFI.
=> Cleaner exception handling.

src/nrf51.c
Hi,
The NRF51 chip I'm using has the idcode 0x0072. I've tested the Blackmagic debugger with the chip on my board and everything is working fine.
Thanks
=> Add 0x0072 as a valid & supported idcode for NRF51

src/stm32f4.c
The F405 rev A uses a wrong CPUID, this patch use the core identifier to make
the distinction.
Tested with:
- F205
- F405 rev Z
- F429
Unfortunately, I do not have any F405 rev A.
=> Add support for STM32F2xx family

src/platforms/common/cdcacm.c, src/platforms/launchpad-icdi/platform.c, src/platforms/launchpad-icdi/platform.h
Hi,
These changes fix USB enumeration and communication over the CDC serial port on the TI Launchpad platform. With them applied, connecting to the probe and scan using both JTAG and SWD works. I'm using a LM4F120 Launchpad but the TM4C123 shouldn't be any different in this regard.
Attaching to the target fails, however. I've traced it down to the snprintf call in map_ram() in target.c. In fact, any call to snprintf with a format argument seems to crash the MCU. Google suggests it might be a stack size issue, but I'm not sure how to rectify that.
=> TI TM4C/LM4F cdc-acm fixes

scripts/get_openocd_nrf51_ids.py, src/nrf51.c
There were a lot of nRF51 device ids missing. I wrote a script to pull nRF51 IDs from the openocd repository, which seems to be more up-to-date.  The script's output goes in nrf51.c.
=> Update nRF51 IDs, add nRF51422 and xxAB/xxAC devices.

src/nrf51.c
Lightly tested, appears to work for erasing, loading code, and basic debugging.
=> Add nRF52 support.

src/platforms/native/platform.h, src/platforms/native/usbdfu.c, src/platforms/stlink/dfu_upgrade.c, src/platforms/stlink/usbdfu.c, src/platforms/stm32/dfu_f1.c, src/platforms/stm32/usbdfu.h, src/platforms/swlink/usbdfu.c
This change has also a practical reason. When flashing and testing the
hardware this change makes it easier to make sure all the LEDs work. Now
when the DFU bootloader is idle it is scanning the LEDs making it easy
to see if one of them has an issue.
In addition to that, the bootloader now indicates when there is data
being flashed using the DFU interface. In cases when one has more than
one device connected and accidently starts flashing a wrong device this
is very useful feature to have.
=> [native] Make the native bootloader bit more flashy.

flashstub/Makefile, src/crc32.c, src/efm32.c, src/gdb_main.c
These fixes several issues that we found during tests with our hardware:
* crc32: speed up the generic crc32 routine which caused us some trouble by buffering larger chunks of memory. I don't know if the STM32's routine needs similar modification.
* flashstub: mostly cosmetic adjustments in Makefile
* efm32: we had some trouble when doing loads and breaks with srst switching enabled
* gdb_main.c: fixes a buffer overflow, observed when issuing `dump` commands
In my sense, the last one is the most critical.
Please let me know if you'd prefer these to be submitted in their own pull request.
=> Some various fixes

src/adiv5_swdp.c, src/command.c, src/cortexm.c, src/include/jtagtap.h, src/include/platform_support.h, src/include/target.h, src/jtag_scan.c, src/platforms/f4discovery/platform.c, src/platforms/hydrabus/platform.c, src/platforms/launchpad-icdi/platform.c, src/platforms/libftdi/jtagtap.c, src/platforms/libftdi/platform.c, src/platforms/native/platform.c, src/platforms/native/platform.h, src/platforms/stlink/platform.c, src/platforms/stlink/platform.h, src/platforms/stm32/jtagtap.c, src/platforms/swlink/platform.c, src/platforms/tm4c/jtagtap.c, src/samd.c, src/target.c
- Remove connect_assert_srst global.
- Attach functions always release reset.
- Platforms provide a method to poll the reset pin.
- Reset on scan is all internal to command.c
- Reset is released on a failed scan.  Fixes #111
=> Cleanup of SRST handling.

src/adiv5.c
Working on LPC812.
Fixes #131. Supersedes #130.
=> adiv5: Probe ARMv6M devices with Cortex-M driver.

src/platforms/native/platform.c
BMPM V2 uses a biasing resistor for the true switch mosfet circuit.
Because of that the weak pull-up/down of the stm32 is not asserting the
correct gate voltage for the mosfets to fully switch through. Because of
that we need to use open drain configulation of the GPIO instead.
=> BMPM V2 target power control GPIO needs to be an open drain drive.

src/Makefile, src/adiv5_swdp.c, src/command.c, src/platforms/native/platform.h, src/platforms/stm32/jtagtap.c, src/platforms/stm32/usbuart.c
The upcoming CID/PID tables rely on this code.
The way it is implemented it could probably be made more generic and usable on other platforms too. I do not want to have it enabled everywhere because I am not sure that it will not surpass their flash memory budget, this is why it is native platform only.
=> Added black magic verbose/debug mode switch.

src/adiv5.c, src/jtag_scan.c
This patch adds tables that allow us to decode the Product ID and
Component ID registers. Based on those tables we can decide what probe
function to use. Also this makes it possible for us to understand what
ADIv5 components the target is offering to us, even if we do not
need/use them.
The tables include a comment describing how the register bits need to be
interpreted.
=> Use Product ID and Componend ID tables instead of defines.

src/Makefile, src/cortexm.c, src/include/target.h, src/lpc15xx.c
This pull request adds support for LPC15xx chips using the same lpc_common infrastructure as lpc11xx.c and lpc43xx.c. I have been testing it with an LPC1549 on a custom board for a few weeks.
There are a few lines of code duplicated from lpc11xx.c, but I think it makes sense to put the 15xx chips in a separate file. The memory map is very different (RAM location and IAP entry location have moved).
Cheers,
David
=> lpc15xx support

src/target/nrf51.c
This is just another update for the Config ID value that has changed for the nRF52 Revision 1 QFAA B00.  It has been built and upgraded on a BMP v2.  I am still looking into using the INFO.PART factory information register as a better long term solution, and will make a followup commit if that is better way to go.
=> Adding new ConfigID value for nRF52832 QFAA B00

src/target/nrf51.c
I found that I could not program a new batch of nRF51822 devices, and tracked down the problem to them containing a new revision of device QFAAH1, which I confirmed with Nordic as having ConfigID code 0x008F
See https://devzone.nordicsemi.com/question/97769/can-someone-conform-the-config-id-code-for-the-nrf51822qfaah1/
=> Add support for nRF51822QFAAH1

src/platforms/common/timing.h, src/platforms/stm32/usbdfu.h, src/target/adiv5.c
Correct/add #include guards.
Correct the const declaration to achieve the intended behavior. (as a side note clang manages to spot this and complain about double const, we might want to add clang at least for the ftdi target in the CI run)
=> Compile fixes

src/platforms/libftdi/gdb_if.c
This significantly improves performance by not waiting for TCP timeout on transmission.
=> libftdi: Disable Nagle algorithm and buffer sends internally.

src/target/stm32l4.c
=> STM32L4: Use buffered flash model.

src/target/stm32f1.c
Adds ID codes for the STM32F303 targets.
Values are taken from [RM0316](http://www.st.com/resource/en/reference_manual/DM00043574.pdf), section 33.6.1.
=> add STM32F303 targets

src/Makefile, src/gdb_main.c, src/platforms/common/swdptap.c, src/target/cortexm.c, src/target/cortexm.h, src/target/sam4l.c, src/target/target_internal.h
These are the changes to add the SAM4L target to the BMP code base. There are two intertwingled things here, one is the SAM4L driver and the other is an addition to the internal Target interface which adds an extended-reset OPTION and function. Documentation is:
##Extended Reset
This allows a target to do some additional house keeping after reset has been asserted but before returning control the target. In this driver the function re-enables the SMAP peripheral if it had become disabled, and resets the SMAP.HCR (hold core reset) bit if it has become set.
=> Target Driver for Atmetl AT91SAM4L target

src/target/adiv5.c
=> adiv5_dp_init: make ctrlstat volatile to supress warning.

src/platforms/native/platform.c, src/platforms/native/platform.h
Added TMS/SWDIO direction pin & adjusted SRST sense.
1) This version uses a direction control level shifters. We need to control
the direction of the TMS/SWDIO pin.
2.1) Because we want to support a large voltage range for SRST we use an
external dual MOSFET for asserting and sensing the SRST line. We have
added the hardware version 3 to be handled the same way as version 0.
Meaning using separate pins for assertion and sensing of the SRST line.
2.2) The new SRST sense circuit is inverting, thus we have dedicated
code for hardware version 3 that inverts the SRST status pin on read.
This code is compatible and tested on the V2.1b prototype hardware.
=> Add BMPM V2.1 support

src/platforms/stlink/platform.h
I was stuck trying to debug the issue why my probe would not find any attached targets. This is because I was doing the pin mapping as per the comments, and not the actual code. There is a mismatch!
This PR updates the comment to reflect the values set in code. :)
=> Actual pin mappings and the comment differ!

src/target/target.c
This shows targets enumerated in their natural order, rather than in reverse.
=> target: Add new targets to end of list.

src/target/adiv5.c, src/target/kinetis.c
- Add support for KL03Z and K22F devices.
- Force security byte to unsecured value by default.
- Allow security byte to be programmed with `mon unsafe enable` command
- Provide a fake recovery target to access mass erase over MDM-AP to recover secured devices.
=> Kinetis stuff

src/target/cortexm.c
This fixes an bug, where if the target was lost while polling the stub, the already free'd target
would be interrogated to check for the breakpoint instruction.  This would result in a crash in the firmware.
This is at least a partial fix for #185 and #191.  There may be other issues causing us to loose the target.
=> cortexm: Check halt reason on stub exit.

src/platforms/stm32/stlink.ld
Although the devices are only documented to have 64K flash,
they have been obeserved to have a full 128K, although the undocumented
half may be untested and have problems.
=> Increase st-link flash allowance to 128K.

src/target/lmi.c
Fix for #185.  On this target, asserting SRST resets debug state causing flash programming to fail.
=> lmi: Inhibit SRST on Tiva and add some fault checks.

src/platforms/f4discovery/platform.c, src/platforms/f4discovery/usbdfu.c
USB_VBUS is not an alternate function, it is an additionnal function which is
always enabled.
If configured as an alternate function, it will draw current from VBUS.
=> Fix usage of USB_VBUS

src/platforms/native/platform.c, src/target/kinetis.c
- Write unsecured value to flash in 'done' handler if it hasn't been programmed.
- Drive TMS high during reset to avoid enabling EzPort (and disabling the micro)
=> K22F security hack

src/platforms/stlink/Flashsize_F103, src/platforms/stm32/dfucore.c
With flashing above 0x0800ffff on a F103C8 introduced with merge request 204, some way to verify success is needed. DFU upload provides this mean.
=> Dfu upload

src/target/target.c
The order of the expressions in the 'for' loop increment part is reversed, and the code may break depending on the order in which breakpoints are inserted and removed. Apparently, GDB inserts and removes breakpoints in the 'right' order, so the problem is not triggered, but in the case of a debugger that I am writing, things break badly and the BMP gets into a hard fault
=> fixed a bug in the breakpoint removal code

src/target/stm32f4.c
Fix typo introduced in recent commits (another option would be to be less specific in commands section name).
=> stm32f4: fix typo in target name

src/target/nrf51.c
New device Id - for NRF51822 QFAA G1 1529AM.
=> New Device Id update - QFAA G1

src/target/stm32f1.c
Indicate in the driver string that STM32F0[3|7]0 has same ID as other STM32F0Xx
=> STM32F0: Several STM32F0[3|7]0 have same ID as other STM32F0X0.

src/target/nrf51.c
I have added the `NRF51_FICR_CONFIGID` value for nRF51822 QFAA H2.
Here's the picture of the chip and the output when I read the NRF51_FICR_CONFIGID memory location of the chip.
=> Added NRF51_FICR_CONFIGID for nRF51822 QFAA H2

src/target/nrf51.c
Got one of the Preview Development Kits for the nRF52840 and got it running with black magic.
Just needs a few lines.
Thanks for your awesome tool!
Tested:
* flashing to main flash (UICR not tested)
* debugging
=> Add nRF52840 support (PCA10056, nrf52840 PDK)

src/target/lmi.c
This adds memory map information for TM4C1230C3PM.
=> lm3s/tm4c: add TM4C1230C3PM

src/target/cortexa.c
The old code for 'fast' memory accesses using the AHB directly has problems with data consitency.  Until this can be resolved, I'm removing the affected code.
This should also fix #275
=> cortexa: Remove problematic code for AHB access.

src/platforms/stlink/Bootloader_Upgrade, src/platforms/stlink/Flashsize_F103, src/platforms/stlink/Makefile.inc, src/platforms/stlink/dfu_upgrade.c, src/platforms/stlink/platform.c, src/platforms/stlink/platform.h, src/platforms/stlink/stlink_common.c, src/platforms/stlink/usbdfu.c
Factor out hardware revision detection, USB detach and power settings, as
all three program (bootloader, bmp and dfu-upgrade) need it.
Stlink V2.1 is now known as rev 2
=> stlink: Use common initialization and detect V2.1 boards.

src/target/cortexm.c, src/target/cortexm.h
- On probe, read CTR for cache presence and minimum line length
- Make D-Cache clean a function
- Clean before memory reads
- Clean and invalidate before memory writes
- Flush all I-Cache before resume
This supersedes #258
=> Cache support for Cortex-M7

src/platforms/stm32/usbuart.c
=> platforms/stm32: Ignore noise errors on USBUART

scripts/gdb.py
I tried flashing an STM32L0 with hexprog.py:
`sudo python hexprog.py -s main.hex`
But it fails during programming...
Running with the -r flag didn't help and I know for certain that there is no flash read protection on my DUT.
I looked around a bit and noticed that, for whatever reason, the first memory section it tries to flash has totalblocks=0 when evaluating flash_commit()--causing a divide-by-zero error. The fix is self-explanatory.
=> hexprog.hex fails due to divide-by-zero

src/target/kinetis.c
Added support for the K64 Sub-Family of microcontrollers. I used the document K64P144M120SF5RM
and a K64FN1M0 (1MByte Flash Memory) to test. The additions I made are:
- Added documentation  for where I got the K64 information from (and the reference for K22 which was not listed)
- Added the `FTFE_CMD_PROGRAM_PHRASE` `#define`. Otherwise the K64 `FTFE` and the L series `FTFA` module are very close.
- Added the ability to set alignment. The L series has a 4 byte flash memory alignment and the K64 has an 8 byte flash memory alignment for writing phrases.
- Added a match for `0x620` (K64, see errata for why this is not `0x640`). With maximum memory specs. 
- Compensated for different blocksizes in erase (information was being taken, but was hardcoded to 0x400)
- Compensated for different …
=> Added support for k64

src/target/cortexm.c
Hi, I took the changes @mubes did and expanded a bit, to make it a formal PR.
This will split the `special` register into its sane parts `BASEPRI`, `PRIMASK`, `FAULTMASK`, `CONTROL`.
BR Emil
=> Update to split 'special' register into its sane parts

src/target/nrf51.c
This adds the (mysterious) nRF51802.
@NordicSemiconductor is rather cagey about this chip so I can't find any docs to point to, but it seems to be mostly the same as the nRF51822. I retrieved the device ID, RAM size & flash size from the FICR. It's tested and working without any issues so far.
For future reference the chip markings are:
N51802
QFAAA1
1720IW
=> nrf51: Add nRF51802 device id.

src/gdb_main.c, src/include/target.h, src/platforms/stlink/Readme, src/platforms/stlink/platform.c, src/platforms/stlink/platform.h, src/target/stm32f1.c, src/target/stm32f4.c, src/target/stm32l4.c, src/target/target.c, src/target/target_internal.h
In some devices, peripheral registers are inaccessible when the device is in reset.  As a result the memory map can only be constructed at the attach stage, when the core can be halted and released from reset.
See #329 for more discussion.
This PR splits the probe and attach functions for affected STM32 devices.  The memory map is constructed during attach.
To save memory, the XML memory map is constructed on the stack.
Minor accommodating changes to the stlink platform are included.
=> Split probe and attach

src/target/stm32f4.c
In commit c4d3712 the `target_add_ram` call for STM32F4 devices was changed from a size of 0x40000 to 0x10000, which means gdb by default will refuse to read variables that live in RAM beyond the first 64kB. This also impacts semihosting when the memory to read lives beyond the first 64kB. Setting `mem inaccessible-by-default off` in gdb resolves the issue, but is a workaround rather than a solution.
This PR updates the calls to use the maximum RAM sizes for the F4 and F7 devices.
I'm not clear if `target_add_ram` should give the _minimum_ or _maximum_ RAM sizes; specifically does this change how much is attempted to be written at once when writing flash? If so I guess these calls should somehow work out precisely how much RAM is available rather than the family min/max. This updated …
=> Update maximum RAM sizes for F4 and F7 devices

src/target/stm32f4.c
This way swdp_scan and jtag_scan commands will show the chip that was
detected instead of the generic STM32F4 string. The generic name is
most confusing when attaching to an STM32F7 target.
=> Setting the stm32f247 driver string on scan.

src/Makefile, src/target/cortexm.c, src/target/msp432.c, src/target/target_internal.h
Introduces flashing and debugging support for Texas Instruments MSP432
series of MCUs
Note: This is a new pull request to correct the git problems I had with the original one #306. 
Only one commit, as requested by Uwe.
Sorry for the mishap.
Flash buffering has been fixed at 1024 bytes.
Both flashing and debugging seem to work correctly.
Two extra commands have been added:
- monitor erase: erase the entire Main Flash, leaving alone Info Flash with bootloader and device calibration.
- monitor sector_erase <address>: erases just the sector (4096 bytes) that contains <address>, also in Info Flash.
Test Hardware:
- Target: MSP432 Launchpad Red
- Platform: STM32f103 "BluePill" (stlink platform)
Test Software:
- gdb on Windows, Linux and the Windows Linux Subsystem (native Ubuntu/bash in …
=> Support for MSP432 TI MCUs

src/command.c, src/target/adiv5.c, src/target/cortexm.c, src/target/cortexm.h
This RP has now single issue commits with debug output removed. It  also allows the user to configure when to release SRST when asserted and how long to wait for the device halted is requested. This fixes issues with STML0 and F7 devices when WFI is used.
=> Probe halted

src/platforms/libftdi/jtagtap.c
Seen when scanning e.g. Zync with mon jtag 6 4.
=> libftdi/jtagtap.c: Fix error introduced with commit de33473

src/target/stm32f4.c
I removed the debug bits which are being set in the F4/F7 target, so that it converges to the other targets and makes low-power development work as expected.
When the bits are set by the debugger one has to fight the debugger when doing low-power work, plus the user have to know the internal workings of the BMP to understand why the power measurements are all wrong.
I have been testing this for one day now on an F4 and F7 board, and it is working as expected now.
=> Removed debug bits for F4/F7 target, same as all other MCUs now

src/target/stm32f1.c
Fix to make option erase work for STM32F070x6 STM32F070xB STM32F030xC.  STM32F070x6 has been tested and it works.  Others should work per the reference manual.
=> Fixes option erase for STM32F070x6 STM32F070xB STM32F030xC

src/target/nrf51.c
ID is 0x0139.
This rev comes with a notice: http://infocenter.nordicsemi.com/pdf/in_105_v1.0.pdf
=> Another chip ID for Nordic nRF52832.

src/target/adiv5.c, src/target/kinetis.c, src/target/nrf51.c
Mostly copied from the equivalent in kinetis.c and
https://devzone.nordicsemi.com/f/nordic-q-a/12484/approtect-and-dap/47301
Kinetis equivalent was added at 7de304d
=> Add extra port for mass erasing / unprotecting nRF52 with APPROTECT set.

src/target/cortexm.c
since it performs an IAP call which can hang when performed on other devices than a LPC17xx. Fixes #388 
I've checked the other LPCxx probes, but they don't use IAP for probing.
=> Move the LPC17xx probe function down

src/target/adiv5_swdp.c, src/target/cortexm.c
These extra cycles are needed by some CPU, e.g. STM32L0x1 to cross the SWCLK
/HCLK domains. Revert insufficient #373 also tackling that problem.
Thanks to Thorsten von Eicken for pointing out.
=> adiv5_swdp: Add extra idle cycles with write transactions.

src/target/lpc11xx.c
The DeviceID register has a different address from the LPC11XX devices: `0x400483F8` instead of `0x400483F4`. Memory and flash is compatible.
Tested on a `lpc11u34/421`
=> Add target support for LPC11U3X devices.

src/target/cortexm.c, src/target/stm32f1.c
While playing with [these](https://robotdyn.com/stm32f103-stm32-arm-mini-system-dev-board-stm-firmware.html) boards as both bmp host and target, I found that every other gdb `load` command failed with an erase error.
After some debugging, I determined that it only happened after a target reset, and that loads that didn't involve a reset went through fine. After some more debugging and googling, I happened upon [this thread](https://community.st.com/s/question/0D50X00009kKtahSAC/flash-page-erase-operation-never-completes), which lead me to suspect an HSI-related timing issue.
Sure enough, adding a loop to poll for `RCC_CR_HSIRDY` before attempting to erase the flash solved the problem and allowed *every* load to succeed.
@UweBonnes suggested a generic delay in `cortexm_reset` instead, …
=> Add slight delay to cortexm_reset

src/target/efm32.c
Silabs are using some additional OUIs we don't know about. Reported in issue #389
These should use a DI version 1 layout, so assume version 1 layout for OUIs we don't
know. However do print a notice about this on DEBUG() as suggested by @UweBonnes
The IDCODE value is sufficient to make a positive identification of an EFM32 device.
See AN0062 Section 2.2. Therefore accepting any OUI is reasonable behaviour.
Additionally the part familiy is checked, and the target rejected if not in the
`efm32_devices` table. This commit makes that rejection explicit, although it does
not change the logical behaviour here.
Note that the important registers (part number, part family, flash size) are at the
same addresses in both layouts anyhow. Currently only `efm32_cmd_serial` and
`efm32_cmd_efm_info` …
=> [efm32] Assume Device Identification (DI) version 1 if we don't know the OUI

src/Makefile, src/target/cortexm.c, src/target/kinetis.c, src/target/nxpke04.c, src/target/target_internal.h
I have added the needed probing and flashing routines for the [Kinetis KE04](https://www.nxp.com/products/processors-and-microcontrollers/arm-based-processors-and-mcus/kinetis-cortex-m-mcus/e-series5v-robustm0-plus-m4/kinetis-ke04-48-mhz-mainstream-microcontrollers-mcus-based-on-arm-cortex-m0-plus-core:KE04) series.
Two target monitor commands for mass and sector erase have been also added.
Given the many small differences in the ID and flash module registers, adding the support to the existing kinetis.c would have been messier.
Moreover, kinetis.c has been modified in the MDM-AP target part, as there's no way to discriminate a KE04 from others through the MDM-AP IDR, even if the control and status register and the mass erase sequence are slightly different.
The new "ke04_mode" command …
=> Kinetis KE04: Flash and debug support

src/target/stm32f4.c, src/target/stm32h7.c
Flash sector calculation was wrong with small flash sizes.
=> Handle STM32F730 and STM32H750.

src/target/stm32f1.c
Use 32-bit variable for 32-bit read. Also fixes DEBUG compile error due to mismatch of format and argument.
=> Use 32-bit variable for 32-bit read

src/Makefile, src/platforms/native/Makefile.inc
THese changes allow for the building of the Black Magic Probe for all the current platforms, except the launchpad-icdi, on a Windows development machine. This is done without the need for Cygwin, using only PowerShell.
Note that the  "all_platforms" target is not tested and will not work. If the launchpad-icdi host is fixed then "all_platforms" may be added.
=> Native Windows builds

src/target/stm32h7.c
When `target_add_flash` or `target_add_ram` are called in an attach
function they may be added multiple times. This very much confuses
GDB. This issue has already been reported and fixed for `stm32l4` (See
Issue #455 ).
`stm32f4` and `stm32l4` are the only other cortexm drivers that
implement this pattern. These are both fine.
=> [stm32h7,bugfix] Fix bug: target_add_flash called in attach

src/gdb_main.c
=> gdb_main: Always release CPU when detaching.

src/target/adiv5.c, src/target/adiv5.h, src/target/stm32h7.c
* Reference latest version of the ARM specification
* ROM tables - more debug information, including printing SYSMEM bit
* MEM-AP - reject when Debug Base Address entry is not
present/invalid. These would only have errored in
adiv5_component_probe.
* Resolve note in STM32H7 driver with explaination
=> [adiv5] Improvements in ADIv5

src/target/adiv5.c, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c, src/target/cortexa.c, src/target/cortexm.c, src/target/efm32.c, src/target/kinetis.c, src/target/lmi.c, src/target/lpc_common.c, src/target/msp432.c, src/target/nrf51.c, src/target/nxpke04.c, src/target/sam3x.c, src/target/sam4l.c, src/target/samd.c, src/target/stm32f1.c, src/target/stm32f4.c, src/target/stm32h7.c, src/target/stm32l0.c, src/target/stm32l4.c, src/target/target.c
This is will make debugging earier if this does happen, rather than
dereferencing the null pointer (or passing it to memcpy, or worse).
=> Generate DEBUG warnings and return if `malloc`/`calloc` fail.

src/include/target.h
I am trying to integrate a new platform into the BMP repo and my new platform uses a library from Microchip, the winc1500 driver that is a part of the MLA library. When the file "unistd.h" is included in "target.h" there is a function name clash for "close". Since this is a third party source library I did not want to edit it to resolve the clash, this would make maintenance difficult when library updates are released. Fortunately, the header file is not required for the build to succeed.
This change appears to have to effect on building any of the BMP platforms.
=> Removed redundant include file

src/target/target.c
this fixes a bug that was introduced in blackmagic PR #475 which lead to firmware crashes when connecting to a BMP more than once without a power-cycle.
=> fix overwriting of still-needed value

src/target/sam3x.c
The datasheet specifies the EEFC_BASE(0) is at `0x400E0A00` and EEFC_BASE(1) is at `0x400E0C00` which means they're spaced 0x200 bytes apart rather than 0x400.
This fixes #489.
=> Fixed SAM3X8C large file flashing.

src/Makefile, src/platforms/native/Makefile.inc
After update of GNU make the tests for Windows OS are no longer needed. Note that GNU make 4.2.1 is used to build BMP under Windows OS.
=> Windows Build Fixes GNU make 4.2.1 (#502)

src/platforms/swlink/platform.c
=> swlink: Remove redundant conditional usbart_init().

scripts/dfu.py, scripts/stm32_mem.py
I modified the flash script and its dependency to have braces for print statements, allowing execution with python3.
Because every set of braces only includes 1 value (by keeping the string concatenation with % in place), even if python2 interpretes it as a tuple, it still prints it as previously. Therefore, this should be compatible with python2 and python3 at the same time.
Tested by flashing various stlink / stm32 boards with blackmagic probe firmware using python3.7.
=> Allow STM32 flash script to be used with python3

src/gdb_main.c, src/include/target.h, src/target/cortexa.c, src/target/cortexm.c, src/target/target.c, src/target/target_internal.h
- Add new target methods to access single registers
- Add GDB packets support for `p` and `P` packets
- Implement new methods in Cortex-M and Cortex-A drivers
=> Single register access - Target methods and GDB server support

src/platforms/native/Makefile.inc
This frees about 13 kB or 30 kB with ENABLE_DEBUG=1
=> Native: Link against nanolib.

src/target/nrf51.c
Otherwise "tar  ext ...; mon s; att 2; quit", start new gdb "tar ext ..."
crashes, at least on pc-hosted platforms.
=> nrf51: Add nop_function as halt_poll.

src/platforms/stlink/stlink_common.c
If PC13/14 float and PB11 is pulled high, recognize as baite.
Handle as rev.1 board. Deciphered from:
http://www.avrki.ru/picture/articles/samodelniy_st_link_v2/shemf_st_link_v2.jpg
=> stlink: Check for baite variant.

src/target/kinetis.c, src/target/nrf51.c, src/target/target.c
=> Target: Default to nop-function() for all exported target functions.

src/target/adiv5.c
This shows up when printing the ROM table to the debug console as garbage characters before indented table entries. The buffer holding the spaces used for the indent is one byte too short.
=> Fix buffer overflow in adiv5_component_probe()

src/target/lpc11xx.c
... and add support for LPC1114/333 (LPC1100XL series), similar to how it was done for the LPC17xx. This series requires making an IAP call to determine the part ID, it seems that there is no other way.
I've tested this PR on an LPC1114/333 and it detects it, ~~and the PR doesn't alter any existing code paths so there should be no regressions~~; I did a test with an LPC1114FN28 and it seems all good. We can now easily add other LPC1100XL devices in the new switch statement. But we need to check that the IAP call can be made safely or it might break other devices (see comments below).
One other question I have with this PR is that I had to save the target registers prior to the IAP call and then restore them afterwards before resuming otherwise the IAP call corrupts the program state. But …
=> Add support for LPC1114/333 (LPC1100XL series)

src/command.c
I had issues with the `mon jtag_scan <ir_list>` feature, and discovered, that the GDB monitor command parsing is buggy.
* The *estimated* argv count was wrong
* The tokenizing loop probably triggered some sort of UB, I do not really understand it. My version does not cause issues with libc stack protectors and -fsanitize=address
**How to reproduce:**
Compile PROBE_HOST=pc-hosted with a recent version of GCC (I used 9.2), and
add `-fsanitize=address` to *C_FLAGS* and *LD_FLAGS*.
=> BUGFIX: tokenization of gdb monitor commands

src/platforms/pc-stlinkv2/stlinkv2.c
V2 devices after power on are in DFU mode. It is needed to leave DFU before
doing anything else.
=> Stlinkv2: Always call stlink_leave_state() first.

src/target/lpc11xx.c
Tested on real hardware, works fine. 
```Debug mode is enabled
Target voltage: unknown
No. Att Driver
1      LPC1343 M3/M4
0x0000029e in read_adc_naiive (channel=0 '\000') at main.c:96
96		while (!adc_eoc(ADC1));
Loading section .text, size 0x3c90 lma 0x0
Loading section .data, size 0x1e0 lma 0x3c90
Start address 0x7dc, load size 15984
Transfer rate: 22 KB/sec, 940 bytes/write.
Kill the program being debugged? (y or n) [answered Y; input not from terminal]
```
=> Support NXP LPC1343

src/platforms/pc-hosted/jtagtap.c
=> pc-hosted/jtagtap.c: Handle DO as bytes (PR #552)

src/Makefile, src/target/cortexm.c, src/target/samd.c, src/target/samx5x.c, src/target/target_internal.h
Adds a target driver for Microchip SAM D51 / E5x family.
Tested on SAMD51G19A and SAMD51J19A. According to the datasheet, the D51 / E5x family share the same core feature set, differing only in the addition of CAN (E51) or ethernet controllers (E53/54). All members of the family should be equivalent from a debug and programming perspective.
In testing, I've observed two things that I don't believe are related to the code in this commit:
1. Unsupported packet errors showing up on the debug console that don't appear to affect any of the functionality: 
```*** Unsupported packet: qC
*** Unsupported packet: Hg0
*** Unsupported packet: qfThreadInfo
*** Unsupported packet: qL1200000000000000000
*** Unsupported packet: qSymbol::
*** Unsupported packet: vKill;1
*** Unsupported packet: qC
*** …
```
=> Microchip SAM D51 / E5x support

src/target/lpc11xx.c
Otherwise for all Cortex-M not yet handled this LPC messages appears.
=> lpc11: Only print Idcode if not zero and not yet handled.

src/command.c, src/platforms/common/traceswo.h, src/platforms/stlink/platform.h, src/platforms/stm32/traceswo.c, src/platforms/stm32/traceswoasync.c, src/platforms/swlink/platform.h
Make baudrate parameter of traceswo command mandatory for stlink/swlink, and superfluous on other platforms; change help message accordingly.
=> Clearer handling of the baudrate parameter of the traceswo command

src/target/lpc11xx.c, src/target/lpc15xx.c, src/target/lpc43xx.c, src/target/lpc_common.c, src/target/lpc_common.h
This pull request adds the "readuid" command, to read out the unique ID from an LPC11xx/LPC8xx target. I've tested it with a couple of LPC824s and verified that the UID printed in GDB matches the UID that I read out in my own code.
The function `lpc_iap_call()` did not support IAP commands with a return value, so I had to alter it slightly. I've attached the relevant page of the user manual for reference. The maximum number of `uint32`s returned by any IAP command is 4.
=> Add LPC11xx command to read out unique ID from target.

src/platforms/stm32/dfu_f1.c, src/platforms/stm32/dfu_f4.c, src/platforms/stm32/dfucore.c, src/platforms/stm32/traceswo.c, src/platforms/stm32/traceswoasync.c
The explicit include cause the wrong rcc.h to be included and this gives incoorect values for RCC register access.
=> Remove MCU specific include path from traceswo and traceswoasync files

src/platforms/pc/cl_utils.c
=> cl_utils: There is no need for a (dummy) target controller.

src/target/efm32.c
=> efm32: Make local functions static.

src/target/adiv5.c
We need to know more about what devices indicate proper PIDR and what
devices fail to do so.
=> adiv5: Print out SYSROM PIDR.

src/platforms/stm32/dfucore.c
Current version of BMP DFU is not working on STM32F103RC chip. The reason is that DFU interface is defined as 8x001Ka + 248x001Kg
In this interface page size is 1K which is correct for medium and low density 103xC devices but high density 103xC devices, such as 103RC have 2K page size. Because of that, dfu-util treats each 2K page as two 1K pages resulting in alternating blank/correct pages
I've replaced interface string with 4x002Ka + 124x002Kg and it works now. Here is small example of possible solution attached - additional define of STM32F1HD is needed in makefile in order to tweak the  interface string
=> STM32F1 High density devices DFU support

src/platforms/stlink/platform.c
pc-hosted will abort, if the reset line is held externally to some value.
As assert is either driven or driven open drain, we can assume assert
immediate. For deassert, logic levels differences between the debugger and
the debuggee may apply and other ways to check the result are needed, like
CORTEXM_DHCSR_S_RESET_ST.
=> stlink: Do not wait for the reaction on the reset line.

src/target/adiv5.c
- MTB-M0+ (Simple Execution  Trace)
- M33: Devices need finer decoding (DEVTYPE at offset 0xfcc)
=> ADIv5: More CoreSight device decoding:

src/platforms/stm32/dfucore.c
An illegal erase request may get emitted as the DFU program may erase
first. Checking range before flashing is too late.
=> dfucore: Reject erase outside the allowed range

scripts/stm32_mem.py
stm32mem is only meant to flash BMP to a STM32F103x(8|B). No need to
decipher the DFU interface string.
=> stm32_mem: Check file size before flashing(#614)

src/include/general.h, src/platforms/pc/cl_utils.c, src/platforms/pc/gdb_if.c, src/target/samx5x.c
__USE_MINGW_ANSI_STDIO 1 must be set befor any windows specific included.
=> BMP/PC: Allow to compile with mingw64.

src/platforms/stlink/README.md, src/platforms/stlink/stlink_common.c
- To reenumerate, rcc_periph_reset_pulse(RST_USB) seems enough.
- Document bootloader entry and exit behaviour of ST-LINK V2
- Document bootloader entry on ST-LINK V2-1
=> stlink/bootloader: Really allow to detach.

src/platforms/pc/serial_unix.c
Since dp->d_name can be up to 255 bytes long and the 'name' buffer variable is is a superset of it, bump the size of the latter to 4096 bytes (correspoding to PATH_MAX on Linux systems).
Without this fix, build fails on Linux system with GCC 9.2.1:
```
CC      platforms/pc/serial_unix.c
platforms/pc/serial_unix.c: In function ‘serial_open’:
platforms/pc/serial_unix.c:94:5: error: ‘strncat’ output may be truncated copying between 0 and 255 bytes from a string of length 255 [-Werror=stringop-truncation]
94 |     strncat(name, dp->d_name, sizeof(name) - strlen(name) - 1);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:88: serial_unix.o] Error 1
make: *** [Makefile:30: all] Error 2
```
=> pc/serial_unix: bump device path buffer size to 4096 bytes

src/target/lpc11xx.c
This adds very basic support for LPC11U68 (and maybe other of that family)
The patch does not check flash/ram size but allows to connect and successfully use the chip
Tested on LPC11U68 eval board from NXP and a custom product using the same chip
=> add basic support for LPC11U68 (and maybe LPC11U67)

src/target/nrf51.c
The problem also happens with NRF52840. Set CORTEXM_TOPT_INHIBIT_SRST
for all NRF5 device.
People should be more persistent!
=> NRF5: Always set CORTEXM_TOPT_INHIBIT_SRST(#230)

src/target/nrf51.c
introduced by the last #637 when no NRF was found.
=> NRF5: Do not reset target options.

scripts/swolisten.c
The swolisten program failed to print the cbw buffer correctly while
in dump mode. As printf() is used to print the dump, it is expected
that the cbw buffer is zero-terminated, which would only be the case,
if the cbw buffer is initialized with zeros, before filling it with
new data. One could set the entire cbw buffer to zero, but it will be
more efficient to only set the size-th byte to zero.
This patch fixes the above problem, by using the size variable to set
the sixe-th byte of the cbw buffer to zero, before passing it to
printf().
=> Fixed overrun, when dumping data in swolisten.

src/platforms/common/cdcacm.c
3e3e450 reduced the buffer size for the UART interface OUT endpoint to
32B, but left wMaxPacketSize at 64B. This effectively configures the
hardware to receive packets up to 32B in size while telling the host it
can send larger packets. On reception of a larger packet, the usb core
treats it as an error, drops the packet and replies with a STALL
handshake.
This commit fixes the issue by updating the descriptor to match the
buffer configuration.
Fixes #538
=> cdcacm: Fix UART interface OUT endpoint MPS in descriptor.

src/command.c, src/include/target.h, src/target/cortexm.c, src/target/target.c, src/target/target_internal.h
Remaining semihosting calls: SYS_CLOCK, SYS_EXIT_EXTENDED, SYS_HEAPINFO, SYS_ISERROR, SYS_TMPNAM and a few bugfixes.
=> semihosting

src/target/cortexm.c
When building pc-hosted on Windows the variable "errno" clashes with the function "errno" and pc-hosted does not compile.
This PR fixes that error by renaming the variable errorNo.
=> Fixed variable/function name clash building on Windows

src/platforms/f4discovery/platform.h, src/platforms/hydrabus/platform.h, src/platforms/native/platform.h, src/platforms/stlink/platform.h, src/platforms/swlink/platform.h
Now it should work fine with any gcc version. Old one produces error
like in #657
Signed-off-by: Alexey 'Alexxy' Shvetsov <alexxyum@gmail.com>
=> Fix redefinition of io function

src/target/efm32.c, src/target/samd.c, src/target/samx5x.c
Files efm32 samd samx5x uses same function name that collides during
linking (checked with gcc10)
Signed-off-by: Alexey 'Alexxy' Shvetsov <alexxyum@gmail.com>
=> Rename variant_string in efm32 samd samx5x

src/target/cortexm.c
The semihosting sys_clock is a 32-bit timer that counts in 1/100 second. This patch sets the time origin of sys_clock to the second of first use. This way the counter wraps around after 16 months of uptime; sufficient.
=> set semihosting sys_clock time origin

README.md, src/command.c, src/platforms/common/traceswo.h, src/platforms/f4discovery/Makefile.inc, src/platforms/hydrabus/Makefile.inc, src/platforms/native/Makefile.inc, src/platforms/stlink/Makefile.inc, src/platforms/stm32/traceswo.c, src/platforms/stm32/traceswoasync.c, src/platforms/stm32/traceswodecode.c, src/platforms/swlink/Makefile.inc
This patch decodes traceswo in the probe itself. The output goes to the usb serial port.
Adds "decode" option to "traceswo" command.
Increases stlink firmware size by 360 bytes, or by 464 bytes if ENABLE_DEBUG=1.
Note: only tested on stm32f103/stlink.
=> traceswo decoding

src/target/cortexm.c
As requested, semihosting for "blackmagic_hosted". 
PC-hosted semihosting does keyboard, file and screen i/o on the system where blackmagic_hosted runs, using linux system calls, while semihosting in the probe does keyboard, file and screen i/o on the system where gdb runs, using gdb file i/o calls.
The pc-hosted semihosting was tested with the sketches from the Arduino STM32duino-semihosting library. Output attached. 
[semihosting_testbench.txt](https://github.com/blacksphere/blackmagic/files/4642399/semihosting_testbench.txt)
=> pc-hosted semihosting

src/platforms/common/timing.c
Commit 8b4342394fa125 changed the behavior of timeout, when timeout is set to 0.  Previous behavior was to return immediately.  Present behavior is to wait at least 1 ms to return.
On the STM32 platform, the timer is only updated every 100 ms.  So a timeout of 0 will take (up to) 100 ms to time out.
In `gdb_main.c`, there is a call `gdb_if_getchar_to(0)` inside a loop. This is meant to be a nonblocking call, but the error in 8b4342394fa125 means each iteration through the loop takes a full 100 ms.
I have an application that runs many small stub programs from RAM, and the extra latency is quite noticeable.
=> When timeout is 0, `timeout_is_expired()` should return immediately.

src/target/lpc11xx.c
Adds support for the LPC8N04 device documented in UM11074 (rev. 1.3, latest needs an NXP login).
SWD information from debug mode:
```
RESET_SEQ succeeded
AP   0: IDR=04770031 CFG=00000000 BASE=e00ff003 CSW=03000040
ROM: Table BASE=0xe00ff000 SYSMEM=0x1, PIDR 0x04000bb4c0
0 0xe000e000: Generic IP component - Cortex-M0 SCS (System Control Space) (PIDR = 0x04000bb008)-> cortexm_probe
1 0xe0001000: Generic IP component - Cortex-M0 DWT (Data Watchpoint and Trace) (PIDR = 0x04000bb00a)
2 0xe0002000: Generic IP component - Cortex-M0 BPU (Breakpoint Unit) (PIDR = 0x04000bb00b)
ROM: Table END
```
With patch:
```
(gdb) mon s
Target voltage: 3.3V
No. Att Driver
1      LPC8N04 M0+
```
=> Support for LPC8N04 (UM11074)

src/platforms/hosted/stlinkv2.c
These definitions cause the hosted build to fail, and the STLink build at least _appears_ to be happy without them.
=> Remove extra definitions of jtag structures in the STLink hosted setup to support "gcc (GCC) 10.1.0" on Archlinux

src/target/adiv5.c
Since dev_type is an 8 bit unsigned integer, use the PRIx8 macro instead of PRIx32.
=> adiv5: fix debug print of dev_type

src/target/lpc11xx.c
LPC84x uses a different address for IAP entry function compared to other LPC microcontrollers. Flash operations will not work unless we use the correct IAP entry address.
=> Use correct IAP entry address for LPC84x

scripts/stm32_mem.py
Fixes this issue:
$ python3 ./stm32_mem.py blackmagic.bin
File "./stm32_mem.py", line 199
if (os.path.getsize(args.progfile) > 0x1f800):
^
TabError: inconsistent use of tabs and spaces in indentation
=> stm32_mem: Fix python3 crash due to mix of tabs and spaces

src/platforms/native/platform.h
I believe it should be PB0 instead of RB0 for TPWR Pin
=> Fix typo on PB0

src/platforms/native/platform.c
Many places are using hardware revision 3 such as https://github.com/blacksphere/blackmagic/blob/46b681e050bbfb27acafab88a3b67bda292825ca/src/platforms/native/platform.c#L201, it will nice to explain that the hardware revision 3 belong to the mini v2.1e and later in the comments.
=> Add comments for hardware revision of v2.1

src/target/adiv5_swdp.c
when writing CSW in cortexm_cache_clean().
=> adiv5_swdp: On ACK_FAULT, error() and try again once #715

src/Makefile, src/target/cortexm.c, src/target/lpc546xx.c, src/target/target_internal.h
Added support for LPC546xx. Code based of off LPC43xx target.
I've tested it on an LPC54628J512ET180 using the hosted platform with a J-link.
=> Add LPC546xx support.

src/platforms/f4discovery/platform.c
At GPIO OSPEED 50 MHz, signals showed excessive ringing. Slowing down GPIO OSPEED  to 2 MHz let me scan a Nucleo-H743 only directly connected by SWCLK and SWDIO and ground connected only by the USB cable and a common hub. On the scope edges have sensible risetime, with shortest low and high time around 50 ns.
=> f4discovery: Slow done JTAG pins so avoid ringing.

src/platforms/hosted/platform.c, src/platforms/pc/cl_utils.c, src/platforms/pc/cl_utils.h
Useful for tracking low level problems on native with hosted.
=> hosted: Allow to disable high level commands for BMP.

src/platforms/common/swdptap.c
Thanks to JojoS.
Probably mostly cosmetic, but is keeps the device from driving SWDIO
until the next commands.
=> swdptap: Turnaround immediate after a reading with parity.

src/target/stm32h7.c
Receving an 'O' packet while flashing confuses GDB and then weird stuff happens.
=> stm32h7: Don't tc_printf from flash functions

src/command.c, src/include/target.h, src/platforms/pc/cl_utils.c, src/target/adiv5.c, src/target/adiv5.h, src/target/cortexm.c, src/target/cortexm.h, src/target/lpc11xx.c, src/target/nrf51.c, src/target/sam3x.c, src/target/sam4l.c, src/target/stm32f1.c, src/target/stm32f4.c, src/target/stm32h7.c, src/target/stm32l0.c, src/target/stm32l4.c, src/target/target.c, src/target/target_internal.h
Rework probing on Cortex M.
Attention to users! Some devices where Romtable PIDR has unexpected values will not get recognized until the right values are put in the code. Please help to fix! Otherwise, only devices with their Romtable PIDR known can be probed selectiv. Please report these values.
- With connect under reset, activate hardware reset
- In DHCSR, enable DEBUG and try hard to halt device, if we are not in hardware reset
- Set DEMCR early to see all ROMTABLE entries and request halt on reset
- With connect under reset, release reset now
- Eventually apply device specific work-arounds, eg. for STM32F7 already set DEBUGMCU_CR
- Scan Romtable
- Many devices are now already known by their Romtable PIDR.
Probing can now be much more selective with less wild memory reads
- In the …
=> Cortexm romtable

src/include/platform_support.h, src/platforms/hosted/bmp_remote.c, src/platforms/hosted/bmp_remote.h, src/platforms/hosted/dap.c, src/platforms/hosted/platform.c, src/platforms/hosted/stlinkv2.c, src/remote.c, src/remote.h, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c, src/target/jtag_devs.h, src/target/jtag_scan.c, src/target/jtag_scan.h
With hosted/firmware, when scanning the jtag chain, transfer the jtag device and chain information to the firmware so that the high level commands later have valid information. W/o this information, the firmware crashes.
=> Hosted/Firmware: Fix Jtag high level #756

src/platforms/hosted/Readme.md
This commit changes the type of a variable from 'unsigned long'
to 'unsigned int', as this is causing a build faulure on msys2 systems.
Also, add some short notes about building on msys2 systems.
=> Add documentation details for building PC-hosted BMP in msys2.

src/target/cortexm.c, src/target/kinetis.c
This PR adds support for Kinetis K12 and some (optional) initial placeholders for other K-series MCUs using combined `SIM_SDID[DIEID]` and `SIM_SDID[FAMID]` as used by OpenOCD. There are only a few K12 devices so they can be uniquely identified using the existing query for `SIM_FCFG1[PFSIZE]`, but might need to look at additional registers for other K-series chips.
This chip at least reports ARM as designer in the ADIv5 PIDR, so I added `PROBE(kinetis_probe)` to the default condition. I could create a separate probe function for the older K-series if you prefer.
Just got this probe yesterday. It's working great!
```
(gdb) monitor swdp_scan
Target voltage: 3.3V
No. Att Driver
1      MK12DX256Vxx5 M4
2      Kinetis Recovery (MDM-AP)
(gdb) attach 1
Attaching to program: …
```
=> Add support for Kinetis K12 and placeholders for other K-series MCUs

src/target/kinetis.c
This adds support for the NXP S32K118. This is an automotive-grade part
that is derived from the Kinetis line, so it has a very similar
interface to other parts in the family.
Tested on an S32K118EVB
=> target: kinetis: add S32K118

src/target/cortexm.c, src/target/lpc546xx.c
Enable the lpc546xx target. Tested on the LPCXpresso54628 dev board,
able to flash and debug.
=> Switch on the lpc546xx target

src/target/adiv5.h, src/target/cortexm.c, src/target/stm32f1.c
This patch adds support for STM32F1 clones that report AP_DESIGNER 0x555 and PartNo 0x29b, reporting STM32F1 (clone) medium density.
=> Add support for STM32F1 clone with new AP_DESIGNER id

src/command.c, src/target/cortexm.h
It makes sense that the timeout value is unsigned, it also
resolves build errors on some platforms.
=> Change the type of 'cortexm_wait_timeout' to unsigned.

src/Makefile
More recent versions of GNU make remove the `-` prefix from
`$(MAKEFLAGS)`, which breaks the build:
```bash
> make -C src --trace all_platforms
set -e ;\
mkdir -p artifacts/v1.7.1-91-g98b4ec5 ;\
echo "<html><body><ul>" > artifacts/index.html ;\
for i in platforms/*/Makefile.inc ; do \
...\
make w --trace --no-print-directory clean ;\
make w --trace --no-print-directory;\
...\
done ;\
echo "</ul></body></html>" >> artifacts/index.html ;\
cp artifacts/*.bin artifacts/v1.7.1-91-g98b4ec5
Building for hardware platform: f4discovery
make[1]: *** No rule to make target 'w'.  Stop.
```
Per the
[documentation](https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html),
there's no need to manually apply insert `$(MAKEFLAGS)`, it should be
automatically included when using …
=> Fix building with newer GNU make

src/target/cortexm.c, src/target/stm32f1.c
Adding support for [GigaDevice GD32E230C8T6](https://www.gigadevice.com/products/microcontrollers/gd32/arm-cortex-m23/value-line/gd32e230-series/), which previously showed up as `Unknown ARM Cortex-M Designer 43b Partno 4cb M23` and flash operations would not work. This part series is essentially just a Cortex-M23 core with STM32F1-style peripherals.
The part I was testing with had an idcode of `0x410`, but I'm not sure whether the other [GD32E23x](https://www.gigadevice.com/products/microcontrollers/gd32/arm-cortex-m23/) parts share the same ID or not.
=> Support GD32E23x

src/target/cortexm.c, src/target/lpc546xx.c, src/target/lpc_common.c
**Summary**
Modifications to fix flash support on the lpc546xx:
- fix IAP entrypoint to be `0x03000204`, not the value at that address
- add a reset and attach sequence before erasing flash sectors. there's
little documentation around this, but experimentally, erasing sector 0
fails when the ROM bootloader is mapped to it (on reset). stepping the
chip once and attaching is enough to snap the chip out of it, permitting
flash erase on sector 0.
- add a few test commands to the lpc546xx table (read_uid, erase/write
sector, etc).
- write the magic CRC value when writing to sector 0
(`lpc_flash_write_magic_vect`).
- move the lpc546xx probe to before the lpc43xx probe, to prevent
getting the lpc546xx into Lockup when reading an illegal memory location
during lpc43xx probing
Fixes #786.
I don't …
=> target/lpc546xx: fix lpc546xx flash support (#801)

.gitignore
This folder is generated when running `make -C src all_platforms`. Add
it to ignored files.
=> add src/artifacts to .gitignore

src/platforms/hosted/ftdi_bmp.h
Hosted mode has the option to build with `HOSTED_BMP_ONLY=1`. This
removes dependencies on libusb, as well as a dependency on libftdi.
This patch removes `#include <ftdi.h>` from the `platform.c` file under
Hosted mode, and removes all references to it when built with
`-DHOSTED_BMP_ONLY=1`.
Signed-off-by: Sean Cross <sean@xobs.io>
=> hosted: remove ftdi when built with BMP_ONLY

src/target/kinetis.c
This adds support for the NXP S32K148. This is an automotive-grade part
that is derived from the Kinetis line, so it has a very similar
interface to other parts in the family.
=> target: kinetis: add S32K148

.gitattributes
On different platforms, line endings can differ. Git tries to
intelligently convert source code to match native line endings when
doing a checkout, unless a particular configuration flag is set.
An alternate approach is to create a `.gitattributes` file and manually
specify various types of files. This ensures files are properly handled.
It also prevents git from creating patches that consist of nothing more
than replacing line endings.
=> gitattributes: add attributes file

src/platforms/hosted/bmp_remote.c, src/platforms/hosted/bmp_remote.h, src/platforms/hosted/platform.c, src/platforms/pc/cl_utils.c
Expect the command to fail, due to old firmware or remote not implementing
the power switch.
=> hosted: Really handle setting tpwr on remote on the command line #817

src/target/stm32h7.c
@UweBonnes helped me debug the BMP with my stm32h750.
while the stm document (RM 0433) claims that the h750 only has 1 bank with 1 sector (128k) of user main memory flash (pages 151-152), we were able to write and successfully verify into other regions in bank 1 and also into bank 2 (0x0810 0000 as indicated for the other chips).
here is a transcript, I removed the warnings about the preamble not matching
```shell
./src/blackmagic -a 0x08000000 ~/local/src/DaisyExamples/field/KeybrdTest/build/ex_field_keyboard_test.bin 
Flash Write succeeded for 61472 bytes,   26.879 kiB/s
./src/blackmagic -a 0x08000000 -V ~/local/src/DaisyExamples/field/KeyboardTest/build/ex_field_keyboard_test.bin 
Read/Verify succeeded for 61472 bytes,   52.947 kiB/s
./src/blackmagic -a 0x08030000 …
```
=> fixing some memory map errors for stm32h7

src/platforms/common/cdcacm.c
This prevents also the intervention of "ModemManager" that can happen on some linux systems.
Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>
=> The USB CDC is no modem and does not use the AT protocol

src/platforms/native/platform.c
Special iRST_SENSE handling does not apply at least for BMP 2.1c.
On V2.1c, iRST_SENSE was set as output high and xRST high shorted
iRST_SENSE to ground via Q2
FIXME: Check for older versions!
=> native: Remove high current draw (#814)

src/target/stm32f1.c
IDCODE is already known from the Romtable
Probably this has the same effect as #836
=> stm32f1: On ST parts there is no need to read IDCODE again.

src/target/adiv5.c, src/target/cortexm.c, src/target/stm32f1.c
Revert last patch mangling up all STM32F0.  Fix #836 by always halting CPU before romtable scan. Release from halt only once after scan
=> Cortexm halt

src/Makefile, src/target/cortexm.c, src/target/stm32g0.c, src/target/stm32h7.c, src/target/stm32l4.c, src/target/target.c, src/target/target_internal.h
Fixes #819.
This PR provides a comprehensive STM32G0 target driver in a separate file. G0 has some divergences from L4/G4.
And may leave cleaner room in stm32l4.c for #707 and #458. Maybe...
Refer to this message for content details:
https://github.com/blacksphere/blackmagic/issues/819#issuecomment-780142079
Waiting for Dual-bank G0B/C release (in the ST's pipe) might be reasonable to fully test it.
=> Comprehensive STM32G0 driver

src/platforms/hosted/bmp_serial.c
=> Put null terminating characters when scanning for BMP probes on linux

src/target/stm32f4.c, src/target/stm32l4.c
Hello,
This little PR for the support of the G4 category 4 devices (up to 512 kiB single bank).
I also bring a little "PRIu32 -> PRIx32" fixup.
Additionally, G43/44 now conform to G49/G4A option bytes. Their option bytes support were probably broken as they previously took L4 values so Securable Memory Area was not tunable.
CAUTION: I have not tested this new G4 chip as I do not have any at hand!
This contribution is based on the documentation only.
=> STM32G49/G4A Category 4 devices support

src/Makefile, src/platforms/stlink/Makefile.inc, src/platforms/swlink/Makefile.inc
SWD/JTAG Bitbang is compiled with -O3 for good bitbang speed.
=> Compile with -Os as default. Change like "make OPT_FLAGS=..."

src/target/efm32.c, src/target/kinetis.c, src/target/nxpke04.c, src/target/samd.c, src/target/samx5x.c, src/target/target_internal.h
Some target probe functions used static RAM variables. This will fail if several of the  same targets are in the JTAG/SWD chain and unnecessary remove RAM form the RAM pool if the target is not used. If the target needs more than one word, it allocated priv_storage is used. For a single needed word, one word has been added to the target structure as a union to allow decent naming.
=> Clean static from probe

src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/dap.c
This reverts commit 61e237ec87c525876817e72fc82ce28b2a4951ae.
This makes a CMSIS-DAP probe with version < 1.2 work again on DP V1 devices.
Status of other combination unknown:
DP  V1 V2 V2/Multidrop
Probe
<  1.2  ok ok --
>= 1.2   ? ?  ?
=> Revert "cmsis_dap: Always write full reportsize + 1 buffers"

src/target/adiv5.c, src/target/cortexm.c, src/target/rp.c
Various fixes for the rp2040 target:
- Firstly fixing some casting errors in debug calls causing build errors for the native probe.
- Added `rp_flash_resume` method for added stability after erase or load commands.
- Added more debug logging for RP2040 target.
- Increased timeout for `flash_range_program` command when XOSC has not been enabled.
- Increased spinner timeout to 500ms (fixes #875)
=> RP2040 fixes

src/platforms/hosted/Makefile.inc
I'm not completely clear on this makefile syntax, but this compiles cleanly on MacOS, with pre-installed hidapi from homebrew.
=> Fix hosted compile on MacOS.  hidapi-libusb has a different name

src/gdb_main.c, src/include/general.h, src/platforms/common/cdcacm.c, src/platforms/stm32/dfucore.c, src/target/adiv5.c, src/target/adiv5_swdp.c, src/target/cortexm.c, src/target/nrf51.c, src/target/sam3x.c, src/target/stm32f1.c, src/target/stm32f4.c, src/target/target.c
Hi!
I'm trying to get another open source project (https://github.com/vedderb/bldc) that integrates black magic probe to more closely follow the latest version. To minimize the changes it would be nice to get a few fixes from there included in upstream. It's mostly compiler warnings due to a different set of compiler flags being used, but there is also one new command for the nRF5x.
Let me know if I should change something!
=> Add nRF51 erase UICR command and fix some warnings

src/platforms/hosted/bmp_libusb.c
Fix bug introduces by recent commit
=> bmp_libusb: Check only for cmsis_dap if no cable has been found yet.

src/platforms/common/cdcacm.c, src/platforms/stm32/serialno.c, src/platforms/stm32/usbuart.c, src/remote.c, src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c
E.g. STM32WLE5 is the same chip as the dual core STM32WL55. The base register
for the AP of the second core is still valid on the WLE, but romtable access
fails. Proper recovery is needed. This should fix #832
=> adiv5: Recover from bad CIDR access (#832)

src/target/lpc11xx.c
Fix for issue #904.
Adds support for NXP LPC11xx XL series by adding the device IDs (reading the DEVICE_ID register from an alternate address -- which is not officially documented).
At the same time, I added the "target command" readuid to the MCUs where it was missing (and the MCU does support the command). And I added comments to the Device IDs, with a brief description.
=> Add support for NXP LPC11xx XL series, plus minor fixes

src/gdb_main.c, src/morse.c
When the BMP looses connection to the target MCU (for example, after accidentally redefining the SWCLK or SWDIO pin to GPIO or another function), the red LED of the BMP starts blinking in a morse code pattern ("TARGET LOST").
This pull request resets the LED after successfully re-attaching to the target (or attaching to some other target).
=> Reset error LED after successful attach to target

src/platforms/f4discovery/Makefile.inc, src/platforms/f4discovery/Readme.md, src/platforms/f4discovery/platform.c, src/platforms/f4discovery/platform.h, src/platforms/stm32/blackpillv2.ld
@UweBonnes 
> I am not to happy to add new platforms that do not show new capabilities. They need to be compiled for every test and if basic changes are needed in all platforms, I do not have a reference part. Furthermore, the F4 lacks USB endpoints. A variant of the F4 disco, e.g. "make PROBE_HOST=f4discovery BLACKPILL=1" leaving the f4discovery intact would however be accaptable.
+
=> stm32f4x1 blackpillv2

src/gdb_packet.c
Escape '*' in responses of the Remote Serial Protocol, to avoid that it is interpreted as the start of an RLE sequence.
Fixes #915.
=> Escape '*' in responses of the Remote Serial Protocol

src/command.c, src/include/platform_support.h, src/platforms/native/platform.c, src/remote.c
Refuse the "monitor tpwr enable" command (with an error message) if a voltage is sensed on VREF. This decreases the chance for a power conflict (when both the BMP and the target power the VREF pin, possibly with a different voltage).
For example, if 2.5V is sensed on the VCC/VREF pins and "monitor tpwr enable" is issued, this patch keeps power disabled and replies "Power conflict, power not enabled."
Caveat #1: I put the threshold for detecting external power on 0.5V. So if VREF is powered with 0.4V, "monintor tpwr enable" will proceed. The value of 0.5V is a bit arbitrary; I want to be sure it is above the noise level.
Caveat #2: This patch does not protect against "monitor tpwr enable" been given first and external power (on VREF) being applied afterwards. This case will (hopefully) be …
=> Avoid power conflict, test VREF before enabling target power

src/platforms/hosted/dap.c
The same buffer is used for both command and response, causing part of the command to be overwritten before it's retried. Solve this by saving and restoring a copy of the command before retrying.
Also included a commit marking some inline functions as static to fix compile errors due to symbol conflicts when the header is included in multiple translation units.
=> hosted/dap: Copy command buffer in wait/retry loop

src/target/cortexm.c
Pull request for https://github.com/blacksphere/blackmagic/issues/943
"Semihosting call SYS_EXIT is implemented incorrectly"
=> semihosting exit code

src/platforms/pc/cl_utils.c, src/target/stm32g0.c
This feature enables programming the 1024 bytes length OTP area on STM32G0 series.
It makes use of the `irreversible` command already existing to prevent setting RDP level 2.
This PR suggests allowing `monitor` commands from hosted as preliminary action (main action preserved). There is null backward incompatibility.
Typical usage, best used from hosted:
```shell
$ ./blackmagic -M "irreversible enable" -a 0x1FFF73E0 otp_8bytes.bin 
Irreversible operations: enabled
Flash Write succeeded for 8 bytes,    1.143 kiB/s
$ ./blackmagic -r -a 0x1FFF7000 -S 0x400 bla.bin && hexdump bla.bin 
Read/Verify succeeded for 1024 bytes,   78.769 kiB/s
0000000 ffff ffff ffff ffff ffff ffff ffff ffff
*
00003e0 aabb aabb ccdd ccdd ffff ffff ffff ffff
00003f0 ffff ffff ffff ffff ffff ffff ffff ffff
0000400
$ …
```
=> STM32G0 OTP area programming and hosted monitor command allowed as preliminary action

src/target/adiv5_swdp.c
GCC did not warn about possibly missing initialization and so for gdb target
was not recognized.
=> adiv5_swdp: Initialize a volatile variable

src/target/adiv5.c
Fix 'start_time' undeclared when compiling with `make PROBE_HOST=stlink ENABLE_DEBUG=1`
target/adiv5.c:410:29: error: 'start_time' undeclared (first use in this function)
=> start_time undeclared if ENABLE_DEBUG=1

src/platforms/hosted/cmsis_dap.h
when running CC=x86_64-w64-mingw32-gcc make PROBE_HOST=hosted
=> type of ‘assert’ defaults to ‘int’

src/crc32.c
The variable `start_time` indicates when a CRC32 operation began. This
variable is used to benchmark the speed of the CRC32 function.
Currently, this is tied to `PC_HOSTED`. However, the actual usage is
tied to `DEBUG_WARN`. This means that the variable is undefined when
`DEBUG_WARN` is defined and we're not configured for `PC_HOSTED` mode.
Add macro guards around this variable so that it is defined when
debugging is enabled, rather than only when building on `PC_HOSTED`.
Signed-off-by: Sean Cross <sean@xobs.io>
=> crc32: define `start_time` when debug is enabled

src/crc32.c, src/target/samd.c
This adds support for the SAMD09, used in the Adafruit SeeSaw board.
=> Add support for Samd09

scripts/stm32_mem.py
Avoid crash at end of programing.
Also add minor fixes.
```
-
USB Device Firmware Upgrade - Host Utility -- version 1.2
Copyright (C) 2011  Black Sphere Technologies
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
-
Device ID:       1d50:6017
Manufacturer:    Black Sphere Technologies
Product:         Black Magic Probe (Upgrade)
Serial:          7BAE5BAD
-rogramming memory at 0x0801B400
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/usb/core.py", line 1021, in ctrl_transfer
buff = util.create_buffer(data_or_wLength)
File "/usr/lib/python3/dist-packages/usb/util.py", line 162, in create_buffer
return array.array('B', _dummy_s * length)
TypeError: can't multiply sequence by non-int of type 'str'
During handling of the above exception, …
```
=> Stm32 mem fixes

src/target/adiv5.c, src/target/cortexm.c
#249 shows that the device was running after probe with attach with connect under reset was requested.
=> Cortexm: With connect under reset, keep the device halted until attach.

src/target/samd.c
Up to now only the whole flash can be locked in one piece. Locking by segments is not supported. 
When locking the bootloader only the largest chunk (32kB) can be locked. 
By specifying an optional numerical parameter (can be given in decimal or 0x prefied hexadecimal) to lock_bootprot (0 is for 32k, 6 is for 512 bytes) and lock_flash monitor commands the extended functionality is obtained. If this parameter is not specified the commands behave as previously.
=> Added support for fine-grained bootloader and flash locking in samd.c

src/target/samd.c
The code from #987 assumed unsigned long was 32-bit, which is not true for x86_64 Linux/Mac and other potential Black Magic App targets. This generally fixes the soundness of the type punting going on.
=> samd: Fixes for the "hosted" build

src/gdb_main.c
Little cleanup of this sscanf attempt previously marked as not working.
Tested with arm-none-eabi-gcc 10.2.1 and z1/2/3/4 breakpoint and watchpoint types.
=> sscanf cleanup in GDB Z packet handler

src/platforms/native/platform.c, src/platforms/native/platform.h, src/platforms/stm32/usbuart.c
This patch set adds detection and support of native Hardware V4, 5 and 6.
This version is different than PCB revisions. This is the hardware version that used to be encoded using GPIO strapping. Now these versions are stored in user option bytes of the STM32. This future proves us and is making more GPIO available to add new features.
For the fun of it, here is a picture showing a selection of the different native Black Magic Probes throughout history.
Before this is merged we need to test this patch on all the past hardware to hopefully avoid regression and issues:
=> Native hw6

src/gdb_main.c, src/gdb_packet.c, src/include/gdb_packet.h, src/platforms/swlink/platform.h, src/target/adiv5_swdp.c
Hi
I tried to incorporate the comments, except one :  i let the qRcmd suffix etc... because they are  the actual name of the command i.e.  "qRcmd" => exec_qRcmd(), "qCRC"' => exec_qCRC etc.... I find that much easier to deal with, just search for the command.
Assuming i didnt break anything (had to backport manually things from my working tree), there are 2 follow ups coming : 
1- Construct the memory map using the heap (+autorealloc) instead of 1k on the heap.  I have to backport it from C++ to C.
2- For arm,  the exception allocation is the default arm one i.e. 23 reg x 4 bytes. But cortex m0(+), m3, m4 etc.. are thumb(2) only, so only 10 registers. 120 bytes => 40 bytes, if/when exceptions stack, that makes a difference.
BTW, Is there a .clang-format available to format things properly …
=> Reduce stack usage, Take 2

src/target/stm32g0.c
=> Temporarily enable DBG clock in stm32g0_detach()

scripts/bootprog.py
As requested in #984, replace int literals with bytes literals.
Still using `bytes(…)` when all I have is a int.
=> scripts: bootprog.py: use bytes literals

src/platforms/hosted/bmp_libusb.c, src/platforms/hosted/platform.c, src/platforms/hosted/stlinkv2.c
This fixes a regression introduced since v1.7.1 that, under certain circumstances causes a segfault in the BlackMagic Probe Debug App, aka "hosted".
This also aims to improve the general quality of the code involved by bringing it inline with the codebase overall style, and fixing the glaring USB spec violations and UB C issues.
This closes #998.
=> Fix a "hosted" regression that causes a segfault

src/platforms/hosted/dap.c
It seems that the addition of the DragonProbe target exposed some per-existing weaknesses in our CMSIS-DAP implementation that results in comms not working with some adaptors - this PR fixes said protocol implementation issues.
=> hosted: with mubes help, fixes some issues with how we talk CMSIS-DAP

driver/blackmagic.inf, driver/blackmagic_upgrade.inf, src/command.c, src/platforms/common/cdcacm.c, src/platforms/f4discovery/Readme.md, src/platforms/hosted/Readme.md, src/platforms/hosted/bmp_serial.c, src/platforms/pc/serial_unix.c, src/platforms/stm32/dfucore.c, upgrade/main.c
As the GitHub organization was renamed to Black Magic Debug. The copyright and USB vendor strings are not correct any more. This PR fixes this.
We are leaving the codebase Copyright header strings in place as they are correct and the code was written and copyrighted by the Black Sphere Technologies company.
The only issue that remains that the new probes might not be detected correctly by Black Magic App (BMA aka. hosted) in "serial" mode. The code for the device detection in there is so convoluted and hard to read that I decided not to touch it until it is completely rewritten in a proper way.
=> Copyright and vendor strings update

src/platforms/96b_carbon/Makefile.inc, src/platforms/96b_carbon/Readme.md, src/platforms/96b_carbon/platform.c, src/platforms/96b_carbon/platform.h, src/platforms/96b_carbon/usbdfu.c, src/platforms/stm32/96b_carbon.ld
The carbon contains two SoCs, an STM32 (host) and an nRF51 (BLE). The
STM32 implements the probe and allows the board to reprogram its own
radio firmware!
=> Add 96Boards Carbon as a probe host

UsingRTT.md, driver/99-blackmagic.rules, src/Makefile, src/command.c, src/gdb_main.c, src/include/rtt.h, src/include/rtt_if.h, src/platforms/hosted/platform.c, src/platforms/hosted/rtt_if.c, src/platforms/stm32/rtt_if.c, src/platforms/stm32/usbuart.c, src/platforms/tm4c/usbuart.c, src/rtt.c
When debugging arm processors, there are three ways for the target to  print debug messages on the host: Semihosting, Single Wire Output SWO, and Real-Time Transfer RTT.
[Black Magic Probe](https://github.com/blacksphere/blackmagic) (BMP) is an open source debugger probe that already implements Semihosting and Single Wire Output. This patch adds Real-Time Transfer RTT output to usb serial port.
- RTT is implemented, not as a user program, but as a serial port device. To read RTT output, use a terminal emulator and connect to the serial port.
- A novel way to detect RTT automatically "fastsrch", fast and convenient.
Readme here: [UsingRTT](https://github.com/blacksphere/blackmagic/blob/af3674a15f2f4a8bed53b36fe236e92e17d5ae9d/UsingRTT.md)
Firmware for STM32F103 and STM32F411: …
=> rtt to usb serial

src/Makefile
this adds on-demand regeneration for `include/version.h`.
without this patch, parts of the code were always recompiled, even though nothing changed at all.
=> update include/version.h only when content changes

src/target/ch32f1.c
As part of the start of code-base cleanup, this fixes some of the formatting in ch32f1.c.
It also fixes the build for BMDA where the assumption that `uint32_t` == `unsigned int` doesn't hold true on x86_64 and, thanks to -Werror, produces a no-build.
=> Formatting and printf format string fixes for the ch32f1 support

src/platforms/hosted/bmp_libusb.c, src/platforms/pc/serial_unix.c
This fixes a clean exit on error bug, and an issue with how BMDA detects some probes ("cables" in the current terminology used)
=> A couple of misc fixes to BMDA ported from Uwe's RISC-V support branch

src/target/cortexa.c
The implementation is incomplete, as `cortexa_halt_poll` will never return `TARGET_HALT_WATCHPOINT` and the watchpoint address.  It is unclear how, if possible, to get the address from the hardware.
=> Implement watchpoints on Cortex-A

src/target/rp.c
This PR changes two values in `rp.c` to better reflect the hardware:
1. SRAM is actually 0x42000 bytes long in total, not 0x40000. It is recommended to put the stack in the part above 0x40000 so blocking access to this severely limits debugging.
2. The MAX_FLASH macro is changed to 16MB rather than 2MB. I am not sure if this is a good change, though, because other parts of the code probe for the size, which seems like maybe would be a better idea? I don't fully understand this code so I'm not sure.
=> Fix RP2040 memory sizes

src/platforms/hosted/bmp_serial.c
Looks like 5e3cade left a few string comparisons un-migrated which caused this specific build to fail. This migrates those couple instances over.
=> Complete the version string migration from 5e3cade, fixing build for HOSTED_BMP_ONLY=1

src/platforms/common/cdcacm.c, src/platforms/swlink/platform.h
The flow control lines are commonly used to bring MCU into different boot modes (e.g. ESP32)
=> added RTS and DTR to UART interface

Makefile, src/Makefile
Now it is possible to run the all_platforms build target from the toplevel directory.
The src level all_platforms target now also checks for locm3 existence
as well as triggers build of the needed locm3 libraries.
This prepares for switching the build tests to using the all_platforms build target instead of just the native one.
=> build: Added all_platforms target to toplevel Makefile

src/Makefile, src/platforms/hosted/Makefile.inc
The target was building but not including the BMDA binary, as the
build system does not expect a binary that does not end with `.bin`.
Additionally this corrects the BMDA Makefile.inc that was missing the
`all` and `host_clean` targets.
=> build: Corrected the all_platform build target.

contrib/zsh/_blackmagic, src/platforms/hosted/bmp_hosted.h, src/platforms/hosted/bmp_libusb.c, src/platforms/hosted/bmp_serial.c, src/platforms/pc/cl_utils.c
In this PR we have: Completely rewritten the help output to make it more useful and readable. In addition, we have generated a better usage output from the help option and fixed 'hosted' appearing in the version output.
As a side benefit, this includes complete ZSH completions under contrib/zsh.
=> Feature: BMDA better usage output and help

src/target/cortexa.c
Patch for `cortexa.c` pulled from #1045 for @dragonmux
=> cortex-a: Fix compiling for native probe

src/platforms/stm32/serialno.c
As a result of #1036 which this closes, we ended up looking over the serial number handling code and cleaning it up, simplifying where possible.
=> STM32 bootloader serial number handling cleanup

.clang-format
Add a format file for `clang-format`. This is based on the `.clang-format` file from Linux, adjusted to work with this project.
Notably, it opts for 120 characters, given that some functions are rather wide.
Care was chosen to adopt settings that resulted in a minimum of disruption when run through the formatter, however since no formatter has been used before this necessarily results in code that does not conform to the formatter.
This PR is made more to spur discusson on this, depending on whether or not this is a desirable thing to have.
=> clang-format: add initial format file

src/platforms/pc/serial_unix.c
When using BMPA on OSX, BMPA will hang on the second invocation if the device is not specified as /dev/cu* rather than /dev/tty*. Change default BMPA behavior to use /dev/cu* on OSX.
=> Change from tty.usb* to cu.usb* for more consistent behavior on OSX

src/target/rp.c
Following on from the discussions in #1045, this PR aims to provide a better way to identify the size of the SPI flash connected to the RP2040. It does this in two steps:
First, look for repeating sectors in the flash region. This was the original approach that was used and should work if a valid program is loaded in memory, but it will fail if the flash memory is blank, or written with other uniform data. The idea is that if you attempt to read an address outside of the valid flash sector, you will get the data from the start of the sector. 
The second attempt is a bit more aggressive: trying to reading the JEDEC ID of the flash chip. This will interrupt the flash XIP and revert back to SPI mode, but we assume that there is no valid program stored in the memory, otherwise we should have …
=> RP2040: Better detection of flash size

src/gdb_main.c
This PR fixes a small regression that made it into v1.8 which breaks the ability to set and hit breakpoints. This fixes #1054.
This should be merged into both master and v1.8
=> Fix a formatting bug that breaks, among other things, breakpoints

src/target/adiv5.c, src/target/adiv5.h, src/target/cortexm.c, src/target/stm32l4.c
STM32WLE still sees AP1 but on first scan aborts gracefully after some errors
and on later runs sees AP1 as unusable. Fixes #832.
=> stm32wlxx: CPU2 needs wake-up call and has unexpected PIDR4 in AP1

src/platforms/hosted/platform.c, src/platforms/hosted/platform.h
This PR enables target power control in BMPA and adds the support functions required.
Note, this has only been tested on Windows, however, given the nature of the changes it should work across all platforms.
=> Enable power control in BMPA and add required functions

src/platforms/stm32/serialno.c
Fixed a small regression that made it in with #1041 resulting in a transposition of alpha characters in serial numbers. This should restore the serial number generation behaviour we had.
Many thanks to @Qyriad for pointing it out to us with a clear before and after example to lead the way
=> Serial number regression fix

src/target/ch32f1.c, src/target/cortexm.c
A user reported that all their STM32 targets were no longer found when doing SWD scan (reported via Discord). This lead us to looking at the CH32F1 code which we spotted was breaking `t->idcode` state and needed some improving.
This PR fixes this regression in v1.8 caused by the CH32F1 probe code.
This should be merged into both master and the v1.8 branch.
=> Feature: CH32F1 cleanup and correctness improvements

src/platforms/hosted/cmsis_dap.c
Fixed the naming of the cmsis_type_e enum as it was inconsistent with the naming scheme we use.
=> CMSIS-DAP support type clairty

src/target/sam3x.c
Exposed while building hosted with -Og option
=> Fix uninitialized variables in target sam3x

src/target/stm32f1.c
Add additional case clause to MCU detection for the GigaDevice GD32F303CG in ```gd32f1_probe```
=> Add idcode for GD32F303CG detection

.clang-format, .clang-tidy, Makefile, scripts/run-clang-tidy.py, src/Makefile
This adds:
* support for clang-tidy, a script for parallel running it on the code base, and a Makefile target to trigger it
* support for clang-format, and a Makefile target to trigger it
For IDEs like VSCode, the clang-tidy extension by notskm should automatically pick the new configuration up and display linting inline. Likewise, the clang-format extension by xaver can be used to automatically enforce the formatting requirements this provides by enabling format-on-save (`"editor.formatOnSave": true` in settings.json).
In a future PR we will introduce a PR-time CI job that will validate code meets the formatting requirements and add a CI job that runs clang-tidy on merge to main to help with tracking progress on linting cleanup
=> Feature: clang-tidy and clang-format support

.vscode/extensions.json
This is a follow-up PR to #1078 which comes about from a suggestion by Esden on Discord that to help with clang-tidy and clang-format use and enforcement, the project should come with extension recommendations as appropriate to reduce the barriers to entry.
This adds recommendations for VSCode extensions to be used with the project
=> VSCode extension recomendations

src/target/sam3x.c
in #1076 we initialized variables to 0, but in the event that a new driver is added and not properly handled, we would try to do GPNVM bit operations on a flash peripheral with address 0x0, I think this is a saner approach, where if a driver is not known the command immediately fails
=> target/sam3x: saner uninitialized variable prevention

src/platforms/stlink/platform.h
This PR is a rehash of #407 which has unfortunately bitrot despite being a valuable contribution.
While the original PR's RX pin addition is no longer needed (it was done in another PR), the LED pinout fix it offers is still valid and useful.
=> ST-Link: Fix the LED pinout on the Nucleo boards

src/platforms/stm32/serialno.c
There was still a small issue with the current 24 digit serial number code, which this fixes.
We also ran clang-format on the file, bringing it fully in line with the required style and formatting.
Before: 0670FF530000000000000000
After: 0670FF535567494867085055
=> Fix 24 digit serial numbers

.github/workflows/build-and-upload.yml, .github/workflows/build-pr.yml
Fixed the push and pull_request branch requirements for our CI to run. The branch rename yesterday silently broke this. This re-enables CI on the project
=> Fix: main branch CI

src/platforms/blackpillv2/Readme.md
According to [1] all PCB revisions have BOOT0 and NRST labels near
buttons. Reference those in README for ease of use.
PB2/BOOT1 has a 10k pull-down on PCB (in all revisions, according to
[1]), so there is no need to do anything on the board (like "jumpering
to GND") unless the board was modified by user. Hence don't reference
PB2/BOOT1 in the README, as it was just confusing to the user.
[1] https://github.com/WeActTC/MiniSTM32F4x1/tree/master/HDK
=> blackpillv2: clarify how to enter to bootloader mode

README.md
This PR addresses a couple of problems with the project README:
* The BMDA section at the bottom being a bit all over the place in naming and inconsitent with the current project naming scheme
* Links being inconsistent (sometimes proper Markdown links, other times just raw URLs)
* The build instructions for full BMDA being wrong
* Headings in the document violating Markdown rules and being inconsistent
This came to our attention because of user alvarop on Discord
=> Fix several errors in the main project README

src/platforms/stlink/Makefile.inc, src/platforms/stlink/README.md, src/platforms/stlink/platform.c, src/platforms/stlink/platform.h
This PR replaces #396 which appears to have become abandoned.
This enables using the stlink platform with ST-Link clones that have no UART interface, only SWIM. By specifying `SWIM_AS_UART=1` when building, it repurposes the SWIM_RST and SWIM pins as UART TX and RX respectively.
=> Feature: ST-Link SWIM-UART switchability

src/target/kinetis.c
This PR fixes a part-killing regression found by xobs. It does this by reworking the Kinetis Flash command generation and issuing routines so more closely match the behaviour of the v1.7 ones while retaining the benefits of the revamped approach.
This closes #1029 and should be merged both to main and to v1.8.
=> Fix: kinetis Flash control correctness

src/platforms/native/platform.c
We are using GD32F103 on the BMP V2.3 hardware. The GD32F103 has an
errata for the ADC where the end of conversion (EOC) bit is not reset
when reading the ADC result. This resulted in us not waiting for the new
value to be acquired and reading an old value instead. The solution for
that is resetting the EOC bit manually after reading the ADC result, so
that on the next acquisision we wait for the conversion to finish.
This patch also increases the sampling time as the GD32 have lower ADC
impedance than the STM32 and this should help us read a more accuarate
target voltage.
=> BMP V2.3: Fix outdated ADC reads.

src/target/target.c
Make the buffers used to program a target's Flash better bounded in lifetime and memory usage.
In the old setup, if the user requested the programming of, say, 3 unique Flash regions, we would allocate 3 buffers, work away programming the regions, and only at the very end run `target_flash_done_buffered` on each region to clean up - making the final writes possibly out of order, and meaning we gradually grow memory usage with quite large buffers till we finally de-allocate them all in one shot. This clearly causes issues on some targets as we're memory constrained, and they can have large buffer requirements and many Flash regions.
In this new regime, as we get to the end of each Flash region when running `target_flash_write`, we run `target_flash_done_buffered` to clean up. This won't …
=> Fix: target Flash buffer lifetime bounding

src/target/efm32.c, src/target/kinetis.c, src/target/lmi.c, src/target/lpc17xx.c, src/target/lpc43xx.c, src/target/lpc546xx.c, src/target/lpc_common.c, src/target/nrf51.c, src/target/nxpke04.c, src/target/rp.c, src/target/samd.c, src/target/samx5x.c, src/target/stm32f1.c, src/target/stm32f4.c, src/target/stm32g0.c, src/target/stm32h7.c, src/target/stm32l0.c, src/target/stm32l4.c, src/target/target.c, src/target/target_internal.h
Targets which support an `erase_mass` monitor command and which take a while to complete the operation cause GDB issues by making it hit internal state timeouts for the GDB server likely having gone away ("Ignoring packet error, continuing...") but it trying to keep going regardless.
This makes for a poor user experience and gives no indication whether BMP has locked up or if the operation is just taking a while. This PR addresses that by refactoring the mass erase command into the target layer, and introducing new timeout-based reporting that lets the user know BMP is still working on it and hasn't crashed.
This has the benefit of letting GDB know we're alive too and resetting the state timeout that causes the error messages otherwise.
In a separate issue, we will bring up the issue of …
=> Feature: mass erase progress indication

src/target/stm32f4.c
The final erase_mass command check is looking for the EOP (End of
OPeration) bit to be set. This bit is only set when the EOP interrupts
(EOPIE = 1) are enabled. We are not enabling those on the target so this
bit will never get set. As we are monitoring the BSY flag to make sure
the erase_mass operation is still ongoing and finished it is enough if
we just check the error flags.
=> stm32f4: Fix erase_mass command return error.

src/target/efm32.c
couple cleanups, and implement missing methods in mass erase, devices with >= 512 KiB flash support read-while-write and have two separate flash regions with independent mass erase commands
addendum, fix bootloader bit handling, current method only allows erasing of the bit
this is untested, both before and after, solely based on documentation, I have access to some efm32 dev boards at work I might be able to borrow, but unsure if any would be affected by these changes
emlib mass erase function:
```
MSC_Status_TypeDef MSC_MassErase(void)
{
bool wasLocked;
wasLocked = MSC_IS_LOCKED();
MSC->LOCK = MSC_LOCK_LOCKKEY_UNLOCK;
/* Enable writing to the MSC module. */
MSC->WRITECTRL |= MSC_WRITECTRL_WREN;
/* Unlock the device mass erase. */
MSC->MASSLOCK = MSC_MASSLOCK_LOCKKEY_UNLOCK;
/* Erase the …
```
=> efm32 cleanup

src/target/cortexm.c, src/target/nrf51.c
Under certain conditions outlined below, mass erase on nRF51/nRF52 targets fails. This PR fixes that issue.
For the bug to be reproduced, one must meet the following conditions:
* Be attached
* Have run the target (using the GDB run command)
* Interrupt the target (Ctrl + C)
If one tries mass erasing the target after meeting these conditions, it will appear to work but do nothing.
Many thanks to Discord user giobauermeister for reporting this
=> Fix: nRF52 mass erase

src/include/target.h, src/target/target.c
As part of ongoing work to clean up the code and improve readability, this addresses some clang-tidy warnings from the target API and layer implementation.
Tested on all our available hardware without regression.
=> target: Fixed several clang-tidy warnings which improve readability of the code

src/platforms/hosted/Makefile.inc
When building BMPA with HOSTED_BMP_ONLY=0 build will fail on the Mac (ARM64, at least) since the compilation does not find the libusb headers. This patch adds appropriate include. Maybe a better place to add this to the file. If there are strong feels let me know and I can move it as directed.
=> Add homebrew include so that libusb headers found.

.github/workflows/build-pr.yml, src/platforms/hosted/Makefile.inc
This patch set fixes some issues with the BMDA makefile.
Outside of targets we should use space indentation as tabs can be problematic. In this case when a library is not found the `$(error ...)` function is called. This fails as it is indented with tabs and make does not like that. So it is better to just generally indent everything outside of the target with spaces.
Older versions of make do not support the ` .SHELLSTATUS` variable. So we need to do some acrobatics to implement that with just the `$(shell ...)` function.
=> Fix: BMDA lib detect

.github/workflows/build-and-upload.yml
During cleanup of the BMDA build system, a proper dependency on libusb was established, but no added to the main branch GHA workflow. This PR rectifies that.
=> misc: Added the libusb-dev BMDA to the GHA main build workflow

src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/dap.c, src/platforms/hosted/dap.h
With the help of @mubes, this addresses a CMSIS-DAP protocol compliance issue which was breaking use of BMDA with some CMSIS-DAP debuggers but was otherwise shielded/hidden by the immediate link reset that occurs following the removed sequence test code.
This improves our compatibility with DragonProbe.
=> Fix: DAP SWDP init

src/platforms/hosted/cli.c
This option is still useful to many users and there isn't a particular reason for it to be marked deprecated.
This fixes #1096
=> Fix: Remove the BMDA `-d`/`--device` deprecation warning

src/include/jtagtap.h, src/platforms/common/jtagtap.c, src/platforms/common/swdptap.c, src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/dap.c, src/platforms/hosted/dap.h, src/platforms/hosted/ftdi_bmp.c, src/platforms/hosted/ftdi_bmp.h, src/platforms/hosted/jlink_jtagtap.c, src/platforms/hosted/libftdi_jtagtap.c, src/platforms/hosted/libftdi_swdptap.c, src/platforms/hosted/remote_jtagtap.c, src/platforms/hosted/remote_swdptap.c, src/remote.c, src/target/adiv5.h
In this PR we address a few aspects of the SWDP and JTAG TAP routines which were less than ideal. This resulted in over 400 bytes of Flash saved and what should be much more understandable routines to maintain moving forward.
The first major thing we addressed was the type confusion (`uint8_t` instead of `bool`) and inappropriate use of `int` for values that must not be negative. The second was refactoring out the delayed and non-delayed paths that can be taken. The third was creating a much higher degree of re-use and re-usability where possible with clarified names for parameters to better indicate what they do.
This also applies clang-format to many of the files involved, bringing the code base closer to formatting unity.
This has been tested on a couple of flavors of STM32 target …
=> Fix: SWDP and JTAG TAP routine types and understandability

.clang-tidy, src/Makefile, src/command.c, src/gdb_main.c, src/include/general.h, src/platforms/common/jtagtap.c, src/platforms/launchpad-icdi/platform.c, src/platforms/native/platform.c, src/platforms/stm32/dfu_f1.c, src/platforms/stm32/dfu_f4.c, src/platforms/stm32/gdb_if.c, src/platforms/stm32/usbuart.c, src/target/flashstub/stub.h, src/target/rp.c
This PR splits PR #1092 to stage and merge the switch to C11 component, which then also fixes #1120.
Fairly straight-forwardly, this fixes up standards violations that prevent the clean compilation of the code in C11 mode without changing what anything is doing. This includes upgrading libopencm3 and bringing consistency to how we write inline assembly statements.
The other major thing that had to be changed was including the proper header for alloca and marking all presently un-fixable uses as a bug due to the dangers of accidentally overflowing or smashing the stack with alloca.
Sorting out a setup to test the code in #1092 is proving time-consuming and difficult, so this gets the biggest pre-requisite part of that PR out the way.
=> Feature: Switch to C11

src/include/general.h
The _DEFAULT_SOURCE and _GNU_SOURCE defines must exist in order to
enable certian glibc features. Therefore, it is common to define these
either in header files or on the command line.
Some platforms define these in their system headers. For example,
ESP-IDF defines this in their `features.h` file. This results in
a clash when blackmagic is compiled.
Check that these defines do not already exist prior to defining them.
=> general: check _DEFAULT_SOURCE and _GNU_SOURCE

src/gdb_hostio.c, src/gdb_main.c, src/gdb_packet.c, src/hex_utils.c, src/include/gdb_packet.h
This PR addresses the issue that the GDB folks have blown us off once again and refuse to fix GDB to support targets (and therefore GDB servers) which simply can't have threads.
In this PR we implement support for the machinery GDB uses for threads support, but only to fake there being a single thread in any given "process" (debug port on the scan chain). This has the side effect of requiring the implementation of such things as vKill otherwise GDB 11 and newer won't actually execute a process kill as they don't use the old method.
This will need merging to both main and v1.8
This fixes #929
=> Feature: fake thread support

src/gdb_main.c
A small amount of fallout from #1125 - we accidentally regressed the ability to debug flash erase and write because of a nano newlibc bug whereby they don't support the size_t size modifier in their implementation of sscanf() or sprintf(). Our change to use size_t more and print with %zX therefore makes for problems.
This PR fixes that regression. This needs merging to both main and v1.8
=> gdb_main: Fixed a small DEBUG_GDB regression for vFlashErase and vFlashWrite debugging

src/Makefile, src/target/adiv5.c, src/target/adiv5.h, src/target/cortexm.c, src/target/cortexm.h, src/target/efm32.c, src/target/kinetis.c, src/target/nrf51.c, src/target/rp.c, src/target/target_internal.h, src/target/target_probe.c, src/target/target_probe.h
Cherry-picked from #1033
This PR doesn't actually allow (easily) the disabling targets, just lays some groundwork for it, and cleans a couple things up
=> target: add weak aliasing to allow disabling targets

src/platforms/common/jtagtap.c
Adding a nop instruction in the no_delay TMS sequence routine fixes timing on the f4discovery platform
=> fix: Add nop instruction for timing purpose

src/include/jtagtap.h, src/platforms/common/jtagtap.c, src/platforms/hosted/remote_jtagtap.c, src/remote.c, src/remote.h, src/target/jtag_scan.c
This PR finishes the cleanup of the JTAG TAP code and adds a couple of new things needed for supporting buggy targets and RISC-V debugging.
The two new items this introduces are:
* Support for running the JTAG clock for a number of cycles with fixed TDI and TMS pin values
* Support for skipping or dwelling in the JTAG Idle state as required
This should mark the last of the RISC-V support setup.
=> Feature: JTAG TAP RISC-V prep

src/target/adiv5.c
the ADIv5 AP scan bails out too early (on the first encountered invalid AP) rather than after 8 invalid APs.
This was a regression introduced by cda83d30 because that commit checks the wrong loop variable, and then checks the variable against the wrong value. We also fixed the nomenclature up as the code was a litte hard to understand.
This PR fixes this behaviour, fixing #1134.
=> Fix: ADIv5 AP scan early bailout

src/command.c, src/target/lpc11xx.c
This PR implements a new command for doing resets while holding pins in the JTAG interface in specific state. The reason this is necessary is given by LPC82x processors where if in a deep low-power mode do not have running clocks but if reset with TDI held low, will wind up in their bootloaders, allowing BMP to scan for them and attach.
This fixes #1126
=> Feature: LPC82x low power reset

src/command.c, src/target/target_internal.h
In this PR we address the state of command.c with its various styles, formatting choices, type badness and general inconsistencies.
This PR cleans up the commands and improves their output to GDB to make for a nicer user experience while doing what it can to streamline the code to claw back a bit of space.
Tested working on both v2.1e and v2.3a hardware, and against TM4C and LPC43xx targets.
=> Feature: monitor command reformatting and cleanup

src/command.c, src/include/target.h, src/platforms/hosted/bmp_remote.c, src/platforms/hosted/bmp_remote.h, src/platforms/hosted/dap.c, src/platforms/hosted/platform.c, src/platforms/hosted/stlinkv2.c, src/remote.c, src/target/adiv5.h, src/target/jtag_devs.h, src/target/jtag_scan.c, src/target/jtag_scan.h
In this PR we address that some processors don't have conforming implementations of IEEE 1149.1 (JTAG) which prevents jtag_scan() from functioning correctly for them.
We relax the conformance checks to warnings, and address the state of the JTAG scan code, performing type fixes and nomenclature cleanup.
This has been tested against STM32F4, LPC3470, and TM4C.
This fixes #1130.
=> Fix: Unable to detect non-conforming JTAG processors

src/target/cortexm.c, src/target/lmi.c
In this PR we seek to address issues probing for TI Tiva-C and Stelaris devices which, because of where the probe routine is in the sequence, get put into a bad state and fail to scan under certain circumstances by the time the routine fires.
In addressing this we have inadvertantly ended up diving into the LM3S datasheets and adding support for a couple of new micros + fixing the Flash and RAM regions for another.
This fixes #958
=> Fix: Tiva-C/Stelaris device probing issues

src/target/ch32f1.c
This PR cleans up some type abuse and missing `static` in the CH32F1 code.
The cleanup was prompted by #1148 which fixes a bug in how CH32F1 parts are probed for vs other clones.
=> Fix: ch32f1 cleanup

src/gdb_main.c
Avoids the IDLE LED to be dimmed after detaching the target. 
Should be #941 friendly as it avoids toggling the LED (human visible).
Additionally, I see no requirement in the GDB protocol to always answer "OK" on a D (detach) command when the target is already detached. I clarified a bit. 
This avoids sending "OK" forever in case of 0x04 command (port closed).
=> Do not turn IDLE LED off when port closed and target already detached

src/platforms/hosted/jlink_adiv5_swdp.c, src/platforms/hosted/stlinkv2.c, src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c, src/target/cortexm.c, src/target/cortexm.h, src/target/efm32.c, src/target/lpc17xx.c, src/target/semihosting.h, src/target/stm32l4.c
a second round of cleanup on adi code, this fixes the misleading idcode naming, we were actually reading the DP DPIDR register, it also fixes the JEP106 code for raspberry, and the handling of designer code in a couple registers (the reason for the wrong jep code)
=> raspberry magic number begone

src/command.c, src/include/target.h, src/platforms/hosted/cli.c, src/platforms/hosted/jlink_adiv5_swdp.c, src/platforms/hosted/stlinkv2.c, src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c, src/target/ch32f1.c, src/target/cortexm.c, src/target/lpc11xx.c, src/target/lpc15xx.c, src/target/stm32f1.c, src/target/stm32f4.c, src/target/stm32g0.c, src/target/stm32h7.c, src/target/stm32l0.c, src/target/stm32l4.c, src/target/target.c, src/target/target_internal.h
built on top of #1143 mind the extra commits
This tries to improve readabilty and correctness in the initialization of the dp and the reading and usage of targetid
This needs some more thorough testing, but so far it looks good, on some embedded jlink targets target id is now being read where it was not before
changed the logic in the target probe "selection" including the change mentioned on discord
~~note: i think we can, and should, safely move the target id reading inside the dp_init method, but I'll leave that for a future cleanup~~
=> Rework/cleanup TARGETID handling

src/target/cortexm.c, src/target/stm32f1.c, src/target/target_probe.c, src/target/target_probe.h
The following PR adds support for ArteryTek ATF32F403A/407/415 family of MCUs based on Cortex M4 and peripherals compatible to STM32F103 family.
Some of the elements of this family does support an _external Flash_ feature, which would require customized flash routines. The current solution will impose flash limit to 256KB, which are accessible using the STM32F103 compatible interface.
The PR was tested with the [WeActStudio Blackpill](https://github.com/WeActStudio/WeActStudio.BlackPill) based on AT32F403ACGU. English datasheet for these parts can be obtained on the [ArteryTek website](https://www.arterytek.com/en/product/AT32F403A.jsp).
A simple Blink Led program was used to test using VisualGDB and Visual Studio 2022. The GDB interaction log is on the attachment: …
=> Added support for AT32F403A/407/415.

src/target/rp.c
In this PR we re-order and clean up the RP2040 support code to make it easier to read and ordered/structured more like other existing targets.
This does include some clang-tidy warnings fixes and reduces code size by a few bytes, but is otherwise purely reorganisation and renaming work.
Tested working against our RP2040.
=> Fix: rp2040 code cleanup

src/platforms/hosted/jlink.c
Adds PID 0x1015 to the list of valid J-Link probes ( Closes #1154 )
Fixes the PID-VID transposition error
Adds Warning when ignoring unknown PIDs sp that the user knows what happened
=> Fix jlink vid-pid

src/target/cortexm.c
this is the id used to probe, which may or may not be the same as the one on the ap
fixup related to #1159
=> target/cortexm: print t->part_id not ap->partno in unknown device warning

src/target/stm32h7.c
this is a naive attempt at fixing #1159, following the assumptions I made there
Other targets that were probably affected by the same problem:
stm32f4
stm32g0
stm32lx
=> target/stm32h7: fix ids

src/command.c, src/gdb_main.c
Windows does not have alloca.h, conditionally use malloc.h on Windows
=> Correct BMDA build error for BMP only

src/target/adiv5.c, src/target/adiv5_jtagdp.c
This fixes a few printf-style warnings that slipped through due to the
fact that they're only enabled on debug builds. This enables building
this file on an Xtensa platform where -Werror and -Wformat is enabled by
default.
=> adiv5: use PRIxNN specifiers for debug printfs

src/platforms/hosted/cli.c
This PR addresses the robustness point bought up in #691 so the BMDA CLI isn't left to the whims of the compiler or some future reorganisation that might change the command line mode enum
Fixes #691
=> hosted/cli: Made sure the command line options structure is initialised with opt_mode = BMP_MODE_DEBUG before args parsing

src/platforms/hosted/Makefile.inc
This PR cleans up the CFLAGS and LDFLAGS building to use pkg-config to find libusb1 and corrects the pkg-config presence check
=> Fix: BMDA uses the wrong libusb

src/platforms/native/platform.c
We were disabling the UART on all Hardware V1 and newer, as V1 and V2
had the SWD pins connected to the UART pins. Since V3 this is not the
case any more so we can keep the UART enabled when an SWD debugger is
connected to the BMP.
Closes #1103
=> native: Enable uart on HW >=V3 when debugging.

.github/PULL_REQUEST_TEMPLATE.md
The description block in the PR template comming after the checklist turns out to be bad for ergonomics, so as requested by Esden, this PR switches the two so the order of blocks is now description, checklist, closing issues.
=> misc: Switched the descripton and checklist blocks around so the template has better flow

src/platforms/hosted/jlink_adiv5_swdp.c
Fixes an error made while cleaning up code in #1169
Extra bits are being set to 1 that were not before, due to an erroneous memset
=> hosted/jlink: fix bad line reset cmd building

src/Makefile, src/target/rp.c, src/target/sfdp.c, src/target/sfdp.h, src/target/sfdp_internal.h, src/target/target_internal.h
This PR is dual-purpose. It adds support for parsing SFDP tables from SPI Flash both for Flashless microcontrollers that use externally connected SPI Flash, and as the first step in providing support in BMP for directly accessing and modifying the contents of SPI Flash chips.
We have partially converted the RP2040 support code to use the new SFDP readout support and showcase the API, however it's recognised we should do more to identify the different erase page sizes and extract their instructions + the chip erase instruction as all this information is available in the SFDP data. These extra pieces of information will be extracted in later PRs and put to use.
Tested on our RP2040.
=> Feature: SFDP support for SPI Flash

src/platforms/hosted/cmsis_dap.c, src/target/adiv5.c
Due to the excellent work by @mubes on ORBTrace and the CMSIS-DAP interface it features that BMDA can use, it was found that BMP was, after doing a Debug Port (DP) write, under certain conditions then immediately following it with an Access Port (AP) access that fires an abort. This flushes the queue on the DP and causes data corruption that's especially noticeable when trying to Flash a part.
To trigger this bug requires crossing a threshold access speed, and should be possible on native hardware, albeit very difficult. ARM's own advice is to perform a read on the DP or a safe register on the AP, triggering a wait state till the write completes. This makes accesses safe by functioning as a barrier.
This PR implements the DP read version of the fix which provides the least slowdown (a …
=> Fix: ADIv5 early AP accesses trigger aborts, corrupting DP writes

HACKING, README.md, UsingRTT.md
The [GitHub wiki](https://github.com/blackmagic-debug/blackmagic/wiki) has been deprecated in favor of the [official website](https://black-magic.org/), yet some links to the wiki remained in the repo. This PR points them to the website instead.
* N/A It builds for hardware native (`make PROBE_HOST=native`)
* N/A It builds as BMDA (`make PROBE_HOST=hosted`)
* N/A I've tested it to the best of my ability
=> misc: change old wiki links to point to website instead

COPYING-MIT, src/command.c, src/gdb_main.c, src/include/platform_support.h, src/platforms/96b_carbon/platform.c, src/platforms/blackpillv2/platform.c, src/platforms/common/jtagtap.c, src/platforms/f072/platform.c, src/platforms/f3/platform.c, src/platforms/f4discovery/platform.c, src/platforms/hosted/bmp_remote.c, src/platforms/hosted/bmp_remote.h, src/platforms/hosted/platform.c, src/platforms/hosted/remote_jtagtap.c, src/platforms/hydrabus/platform.c, src/platforms/launchpad-icdi/platform.c, src/platforms/native/platform.c, src/platforms/native/platform.h, src/platforms/stlink/platform.c, src/platforms/swlink/platform.c, src/remote.c, src/remote.h, src/target/adiv5_swdp.c, src/target/stm32g0.c, src/target/target.c
Certain low pin-count parts very heavily overload the device pins with functionality. This can mean it's inappropriate to drive TCK/SWCLK before initiating a scan, after scan but before attach, and after detach.
This PR introduces tristating support for these devices when running native hardware revision 6 and newer, allowing BMP to work around this problem. This also means BMP will play nicer with other devices on the roadmap.
This has been tested working against both the SWD and JTAG modes of the Tiva-C TM4C123GH6PM.
Fixes #945
=> Feature: high-z TCK/SWCLK when idle

src/platforms/hosted/jlink_adiv5_swdp.c, src/platforms/hosted/stlinkv2.c, src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c
As part of the ongoing work to improve our ADIv5 compliance correctness, Perigoso had to "brick" support for ADIv5 JTAG for version 0 Debug Ports as the standard provides no reasonable way to detect these. As it happens, unfortunately, both the Tiva-C and the LPC43xx devices have version 0 DPs in JTAG mode (but not SWD!).
This PR restores JTAG on these parts to working by looking for a "magic" JTAG ID Code which Perigoso and us have jointly determined a probable safe way to detect at least some of these DPv0 parts.
This is tested on and works to detect both the aforementioned processor series.
=> Fix: JTAG ADIv5 DPv0 detection

src/gdb_main.c
vMustReplyEmpty is a known and correctly handled packet, and thus we should not be printing a warning for it
=> gdb_main: don't print debug for vMustReplyEmpty packets

src/platforms/f072/platform.h, src/platforms/f3/platform.h, src/platforms/native/platform.c, src/platforms/native/platform.h, src/platforms/native/usbdfu.c, src/platforms/stlink/platform.h, src/platforms/stm32/usbuart.c, src/platforms/swlink/platform.h
While trying to figure out how printf() worked for the umpteenth time in the code base, we finally stumbled across the RDI file IO halo code which serves `_write()`, `isatty()` and other parts of newlib's `FILE *` support via the SVC interrupt.
Having stared at the code long and hard, we figured out that we can make use of the weak linkage of the two aforementioned functions to avoid having to do this interrupt vector halo, saving around 200 bytes of Flash space, and then write out the manual assembly to insert the RDI vector routine by careful manipulation of state in a bare function.
We've then added documentation to make this easier to find in future, and removed a private function from the public platform headers. This PR is the result.
=> Fix: newlib file IO hooks

src/target/ch32f1.c
Differentiate CH32F103 from CKS32F103 and APM32F103 based on REV ID (upper 16 bits of DBGMCU_IDCODE)
This patch allows for the differentiation between CH32F103 parts from CKS32F103 and APM32F103 parts since the latter parts will not upload firmware using the CH32F103 'fast' methodology.
(see Issue #1200: Loading firmware onto APM32F103CB fails)
Fixes #1200
=> Differentiate CH32F103 from CKS32F103 and APM32F103 based on REV ID

src/target/ch32f1.c
Fixes debug build.
Sidenote: The debug build currently is too big and will not fit unless some targets are disabled.
=> ch32f1: Correct the debug output format string.

src/platforms/hosted/bmp_hosted.h, src/platforms/hosted/platform.h
These two files were missing license headers. Added headers consistent with other code in the same area.
=> Added two missing license headers in BMDA.

src/Makefile, src/include/general.h, src/target/cortexa.c, src/target/cortexm.c, src/target/gdb_reg.c, src/target/gdb_reg.h, src/target/target_internal.h
This PR size-optimizes the target description XML strings used for Cortex-M and Cortex-A targets, by removing the string literals which contained the verbatim XML and replacing them with functions `create_tdesc_cortex_m()`, `create_tdesc_cortexmf()`, and `create_tdesc_cortex_a()`. These functions generate the target description strings at runtime with sequences of string formatting instead of monolithic string literals.
The size-optimized code is, unfortunately, much less readable than the verbatim string literals, but the XML they generate has been left in as comments for clarity, and the string deduplication has overall saved ~3.2 KiB of flash space.
As you may have noticed, this PR is marked as a draft. We have *not* tested this code on any Cortex-A targets (or non floating point …
=> target/cortex: dynamically generate target description strings to save code size

src/target/sam4l.c
SAM4L added a DEBUG_INFO command that uses insufficiently-specific formatting.
This breaks compiles on ESP32.
Use specific formatters. Additionally, ensure that FLASHCALW_BASE is
defined as a long int, which allows it to be formatted with "%x".
Signed-off-by: Sean Cross <sean@xobs.io>
This fixes the build for ESP32 by adding more formatting information to sam4l
=> sam4l: fix debug formatting

src/Makefile, src/target/adiv5.c, src/target/adiv5.h, src/target/cortexm.c, src/target/renesas.c, src/target/target_internal.h, src/target/target_probe.c, src/target/target_probe.h
This adds support for Renesas RA family of microcontrollers
What is not implemented:
- debug unlock, these devices have a feature very similar to "back access key" on Kinetis parts, this is done on a secondary AP (I think that code needs some work before I try to implement it)
- MF3 flash type, there are multiple types of flash peripheral on this family, only the "RV40" types have been implemented, it's also the only I have the means to test
- IDCODE for most devices is unknown, a method to "brute force" detection is in place
~This is not quite ready, as right now, although completely functional (for RV40), writing to flash is extremely(unusably so) slow, and needs optimization~
debugging looks to work, but testing was superficial
~I'm opening the PR as I've run out of spoons to work on …
=> Feature: renesas ra support

src/platforms/hosted/Makefile.inc, src/target/cortexm.c, src/target/target_probe.c
👋 
This PR fixes the usage of weak aliasing for probe targets under macOS. 
AppleClang has several incompatibilities with `__attribute__((weak,
alias))` that prevent sane GCC-like usage on macOS:
- it does not support `__attribute__((alias))` at all, only the `#pragma
weak symbol1 = symbol2` syntax (1)
- the compiler removes unused static functions prior to aliasing, which renders the above [into an error](https://bugs.llvm.org/show_bug.cgi?id=17775).
To fix this, I implemented weak aliasing using the `#pragma` directive and [the recommended indirection macros from the GCC docs](https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html) and removing the static inline specifiers from the functions if building under macOS.
[1] : See, for instance, https://sourceforge.net/p/openocd/tickets/304/ and …
=> Fix AppleClang compatibility

CONTRIBUTING.md, HACKING, src/target/HACKING.md
Over the last month or so various conventions and rules have been agreed for the project, but had not been documented to date. This PR rectifies this by writing out things like the `typedef` naming convention as entries in HACKING.md.
This solves a documentation problem which has lead to excess review comments and a slightly more difficult contribution process, which this should ease.
=> Feature: improved code guidelines

src/command.c
This PR aims to fix the formatting regression we caused in 65c5899 in the RTT command's code.
The regression was introduced before it was well understood that the newlib from ARM isn't built with support for `%zu` and the refactor looks like it was a little rushed.
=> Fix: RTT formatting regression

src/target/cortexm.c
=> cortexm: fix printf format for cpuid_partno

src/target/rp.c
Target write operations return boolean values: `true` indicates a write
was successful, while `false` indicates there was a failure.
Inside the rpi target, there is a delegate function `rp_rom_call` that
performs the heavy lifting. It also returns `true` on success and
`false` on failure.
The rp_flash_write() function was inverting this logic, which caused it
to return `false` on success and `true` on failure. This behaviour was
exhibited as only the first 0x89c bytes successfully write to the
device.
Invert this logic in order to get rpi working again.
=> rp: invert success logic in rp_flash_write

src/platforms/stm32/rtt_if.c
I ran into an issue with `rtt_write` hanging the BMP in some cases. Upon looking at the code it looks like there is a bug in the STM32 `rtt_write` implementation which causes execution to enter an infinite loop when hit.
The `usbd_ep_write_packet` function is documented to return `len` on success, and `0` on failure. In the offending code, the function is called with a `len` of zero, which means that it will only ever return zero, and as a consequence there is no way to distinguish failure from success (I am not well-versed enough with the USB code to know if a call with `len = 0` for flushing can ever fail).
Either way, since this function is called in a while loop until it returns a nonzero value, this would amount to an infinite loop, hanging the BMP forever. This is what I observe on …
=> rtt: Fix infinite loop in rtt_write

src/target/rp.c
Reading the sfdp parameter table in the flash causes the spi peripheral to be reconfigure, and, while the previous configuration is restored, this causes the running program to be aboarded. Instead read the sfdp table only if there is no valid program in the flash, or we are going to be modifying the flash anyway (e.g. on erase).
This also includes some other enhancements for accelerating the flash loading.
Fixes #1228
=> rp: Don't abort program when attaching

src/gdb_main.c, src/include/platform_support.h, src/platforms/hosted/cli.c, src/platforms/hosted/cli.h, src/platforms/hosted/platform.c
Add reduced poll frequency for hosted use cases, over-ride with `-F` for (hopefully unusual) case that high speed polling is desirable.
=> Addition of selectable fast polling for hosted use cases

src/target/stm32f4.c
STM32F4 has bug in stm32f4_probe() function
When program reach stm32f4_probe() function, target structure had wrongly fulfilled `t->idcode` field (with value `1041`). Which causes wrong chip selection ahead in the program. This issue doesn't present in [BMP ver 1.7.1](https://github.com/blackmagic-debug/blackmagic/tree/v1.7.1).
My fix works for me with the STM32F446 board. But maybe similar bugs are present in other targets as well.
=> stm32f4: fix wrong idcode when probing

src/target/cortexm.c
Hi,
* Is a new feature implemented?  No
* What existing problem(s) does the pull request solve? Compatibility with some LPC11U67/LPC11U68
* How does the pull request solve these problems? MCU not identified without
Trivial patch attached to add support for another LPC11U6x part_id.
Works fine with the patch. 
Thank you
=> support for another lpc11u6x part id

src/platforms/hosted/bmp_libusb.c, src/platforms/hosted/cli.h, src/platforms/hosted/serial_win.c
=> Fix compiler errors in serial_win.c

src/platforms/hosted/bmp_libusb.c, src/platforms/hosted/bmp_serial.c, src/platforms/hosted/cli.h, src/platforms/hosted/serial_win.c
Building hosted for BMP only generated a compiler error.
=> Fix compiler error when building hosted for BMP only

src/platforms/hosted/serial_unix.c
This PR fixes a compiler error introduced with the clang-format work done previously.
=> hosted/serial_unix: Fix error building hosted on Linux

src/platforms/hosted/probe_info.h
This PR simply adds an entry in the probe info structure for the probe product name string. No additional changes are made to the serial code, this PR enables the structure to then be used in the USB probe scanning.
=> hosted/bmp_serial: Added product to probe info structure. Serial NOT updated

src/platforms/stlink/Makefile.inc, src/platforms/stlink/platform.h
Hi,
I checked if `SWIM_AS_UART` mode mentioned [here](https://github.com/blackmagic-debug/blackmagic/blob/main/src/platforms/stlink/README.md) is working as expected, and it turns out there is an issue. The flag was correctly switching USART port to 1 and setting up pin remap, however it left DMA channels and GPIO pins configured for USART2.
SWO output feature was using the same first UART controller, so I had to switch it off for this particular quirk.
Tested on random STLINK dongle from Aliexpress.
I don't like that a lot of those macros are basically duplicated twice (with the port number being the only difference), but I can't figure if there is a nice way to address it.
* [ x ] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md) …
=> Fix USART on SWIM pins for STLINK

src/target/rp.c
As part of reviewing James Turton's RP2040 fixes, we noticed that the ROM call function is still using a progress spinner when run in monitor mode. This PR seeks to address this using the `target_print_progress` call introduced with the mass erase overhaul which also results in a nice drop in Flash usage.
Targeting to v1.9 as this is clean up and doesn't functionally change the routine.
=> Fix: RP ROM call progress reporting

src/target/adiv5.c
In f4345e4 we made adjustments to the ADIv5 component table, which were based on the SCS classes not matching up which seemed like a copy-paste mistake. As it turns out this is actually that the Cortex-M23 and Cortex-M33 SCSs are defined as debug components in the processor TRMs, but this is actually incorrect as they're generic IP. This PR fixes this by detecting those two SCS's and adjusting the class ID going into the sanity check.
It additionally adjusts the sanity check message so it's a bit more clear what's wrong. This should fix the warning seen in #1243 which raised some eyebrows.
=> Fix: adiv5 nuisance CID warnings

src/platforms/hosted/ftdi_bmp.c
With thanks to sys64738 from the 1b² Discord, this PR addresses the current FTDI configuration data for the FT4242H being incorrect and leading to probes built around this device being non-functional with BMDA. This has been tested to work and adds some extra pinout information which is quite handy.
=> fix: BMDA FTDI configuration for FT4232H

src/platforms/hosted/ftdi_bmp.c, src/target/stm32f1.c
stm32f1: small update to identification logic to correctly identify GD32F330 parts as GD32F3 M4. Without the patch they are identified as GD32F1 M4.
None
=> stm32f1: Identify GD32F330 correctly

src/target/rp.c
Use PRIu32 instead of `%u` for printing the timeout.
This fixes a build issue on ESP32.
=> rp: fix format for debug print

src/platforms/hosted/bmp_serial.c, src/platforms/hosted/probe_info.c, src/platforms/hosted/probe_info.h
Moving this function allows it to be re-used in the USB scanning of probes.
=> hosted: Moved function "extract_serial" from bmp_serial to probe_info to allow reuse in bmp_libusb

src/target/nrf51.c
NRF52 read command had a wrong inversion causing `Failed` commands when they where in fact successful, likely a leftover of the command return type change
=> target/nrf52: stop inverting return on nrf51_cmd_read_*

src/include/rtt_if.h
With the inclusion of a89689f3cbd32661375054f2f54669f4fcae1122, `libopencm3/usb/usbd.h` is now unconditionally included on all non-hosted builds. This causes the build to fail if libopencm3 is not present, which occurs on platforms where this library is not used.
As a separate issue, the ESP32 build uses ccache which appears to ignore the CMake `add_definitions()` directive, and thus does not get the `NO_LIBOPENCM3=1` parameter during ccache generation.
This patch makes two minor changes to `rtt_if.h`:
1. It gates the inclusion of `libopencm3/usb/usbd.h` by both `PC_HOSTED=0` and `NO_LIBOPENCM3=1`, meaning both of these must be true in order to include that file
2. `rtt_if.h` now explicitly includes `platform.h`, which fixes the ccache issue as well as ensuring that `RTT_DOWN_BUF_SIZE` …
=> rtt_if: fix build when libopencm3 is not used

src/platforms/hosted/bmp_serial.c, src/platforms/hosted/probe_info.c, src/platforms/hosted/probe_info.h
Add VID/PID to probe_info structure.
Rename probe_info_add function to probe_info_add_by_serial and add a function probe_info_add_by_id.
Call "by_id" function from "by_serial" with default VID/PID.
=> Add VID/PID to probe_info structure

src/target/stm32f1.c
In this PR we address the issues found in the STM32F1 Flash operation wait code which cause early exits and incomplete operations erroneously. This also includes some documentation on the chosen steps for operation and mode of operation to hopefully stave off future breakage by well intentioned hands.
Fixes #1257
=> Fix: stm32f1 Flash routine functionality fixes

src/platforms/common/swdptap.c
This PR seeks to address the SWD reliability issues that have been plaguing BMP for the last couple of releases. It does so by re-timing the SWD routines and attempting to make sure we are as clean about setup-and-hold timings as we reasonably can be. The results speak for themselves we think.
Before:
After:
The provided screenshots represent the same area of BMP's transactions with a STM32F411 for both cases.
=> Fix: SWD timings

src/target/target_flash.c
While reviewing the conversation on #1230 we noticed that the Flash erase and write routines could be improved on with their handling for end-of-Flash block operations and the failure diagnostics for both erase and write improved on, allowing per-target diagnostics to be eliminated in due course for a debug build Flash usage improvement.
This PR is the culmination of that which should not semantically change the routines but which does improve their speed and Flash usage slightly while making it easier to do the right thing going forward.
Opening as draft as this has not yet been tested and we will endeavour to so in the next few days.
=> Fix: Flash operation completions

src/platforms/hosted/probe_info.c
=> probe_info: Transfer VID and PID to bmp_info_s

src/platforms/hosted/probe_info.c
=> probe_info: Fix probe filtering by probe number

src/platforms/stlink/Makefile.inc
When compiling stlink platform, set BLUEPILL compiler option if BLUEPILL environment variable set
=> stlink: set BLUEPILL compiler option if BLUEPILL environment variable set

src/exception.c, src/gdb_packet.c, src/hex_utils.c, src/include/hex_utils.h, src/include/platform_support.h, src/platforms/hosted/cli.h, src/platforms/hosted/serial_unix.c, src/platforms/hosted/serial_win.c, src/rtt.c, src/timing.c
This PR contains a (non-exhaustive) set of `const`-correctness fixes for the code base. These are designed to help improve code quality and correctness by providing more information to the compiler about what we expect to be modifiable (or not). This should also improve the available optimisation opportunities due to allowing additional optimisations that are unsafe when values are modifiable.
This is the second in the stream of cleanup PRs.
=> Fix: `const`-correctness

src/include/jtagtap.h, src/platforms/common/jtagtap.c, src/target/adiv5_jtagdp.c, src/target/jtag_scan.c, src/target/jtag_scan.h, src/target/jtagtap_generic.c
In this PR we address some conformity issues with the firmware-side JTAG-TAP code and remove a point of confusion (the `jtag_proc_t *jp` parameters in the JTAG abstraction layer). This finishes what was started in #1118 and #1131
=> Fix: JTAG-TAP cleanup

src/platforms/hosted/bmp_hosted.h, src/platforms/hosted/bmp_serial.c, src/platforms/hosted/cli.h, src/platforms/hosted/serial_unix.c, src/platforms/hosted/serial_win.c, src/platforms/hosted/utils.c, src/platforms/hosted/utils.h
This PR addresses several shortcomings of the string handling code in BMDA that lead to several possible exploits and general badness. This also fixes the Linux `HOSTED_BMP_ONLY=1` handling of devices as this severely broke in v1.8.
=> Fix: BMDA security fixes

src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c
Currently BMP gets "stuck" if trying to evaluate an ARM micro with a DP that has the sticky error bit set and declares it a lost cause. This PR addresses this by adding sticky bit reset sequences just after the DP is discovered, and just after a failed AP scan, which should allow normal scan to proceed on otherwise scuffed targets.
Fixes: #1288
=> Fix: adiv5 sticky error handling

src/platforms/hosted/platform.c, src/platforms/hosted/serial_unix.c, src/target/adiv5_swdp.c
This PR addresses a regression caused in #1001. While that PR did fix a real bug, use of dp->error(dp) in the SWD DP access function causes BMP to misbehave and behave badly. In reality this is most likely because an exception is getting throw and not getting caught, but we have no real way to find out and be sure. To solve this, we instead use adiv5_dp_write() directly so we don't go through a read cycle on the control/status DP register (and a series of traversals through the DP access routine) to write the abort DP register (which still requires traversals through the DP access routine, but which ADIv5 guarantees won't fail).
This fixes the behaviour where a user would see
```
Calling lmi_probe
Timeout while waiting for BMP response
remote_ap_mem_read error -4 around 0x400fe000 …
```
=> Fix: ADIv5 SWD fault handling

src/target/stm32l4.c
This PR seeks to address the STM32W part ID regression caused by the improved ADIv5 implementation correctness. This also redresses the work-around at the top of the probe routine for the STM32L4/L5/G4/W parts as the reference manuals for this part series indicates it is unnecessary (though reading the special part ID register is still required for L4 and G4 parts).
Unfortunately we don't have any STM32L55 parts (in particular) to test against, so this is untested, however it is based on the prior work by Uwe to address this same problem so should be OK.
=> Fix: STM32W device IDs

src/target/stm32f1.c
In this PR we address the option bytes write regression for STM32F1 as GD32F1 which was privately reported. As it turns out, because 0x5aa5 is the erased state for the first option byte, this fails the erased state check at the top of `stm32f1_option_write_erased()` and results in the code writing this first byte, which is not erased and the write aborts with an error (`FLASH_SR`'s `PGERR` bit being set). Because `stm32f1_flash_busy_wait()` checks for this error on the way out, it returns false, this then causes the write control loop in `stm32f1_option_write()` to abort.
In this regression fix we test if `i != 0` in that control loop as a second condition before aborting the write. In the future a map of the erased option bytes should be written per-part supported, and this used as the …
=> Fix: STM32F1 option bytes regression

src/platforms/hosted/bmp_hosted.h, src/platforms/hosted/bmp_libusb.c, src/platforms/hosted/bmp_serial.c, src/platforms/hosted/cli.c, src/platforms/hosted/cli.h, src/platforms/hosted/ftdi_bmp.c, src/platforms/hosted/ftdi_bmp.h, src/platforms/hosted/platform.c, src/platforms/hosted/serial_unix.c, src/platforms/hosted/serial_win.c
As part of his work rebuilding find_debuggers() for BMDA, @sidprice noticed that we'd been a little inconsistent in the naming conformity branch, resulting in this set of naming fixes. We suggest this is applied using a squash commit.
=> Fix: BMDA CLI options structure naming

src/target/rp.c
In this PR we address the issues around how the RP2040 boot ROMs handle when the attached Flash is blank, as the ROMs leave the controllers involved in a state where we cannot access the Flash. This is characterised by seeing something like this when using BMDA run as `src/blackmagic -tv 1`:
```
8 byte SFDP read at 0x0:
00 00 00 00 00 00 00 00
Flash device ID: 00 00 00
```
After this fix, the result is a reliable working SFDP readout:
```
RP2040 Flash controller in POR state, reconfiguring
8 byte SFDP read at 0x0:
53 46 44 50 05 01 00 ff
8 byte SFDP read at 0x8:
00 05 01 10 80 00 00 ff
Flash size: 2MiB
```
=> Fix: RP2040 blank flash bringup

src/platforms/common/jtagtap.c
In this PR we address the JTAG timing issues that the earlier refactor in #1118 accidentally introduced. These timings issues impact the ability for the JTAG-PDI branch to function, and made the timings for ARM parts marginal. The timings issues occur while doing TMS sequences.
The following captures show the before-and-after of this timing fix:
=> Fix: JTAG timings

src/platforms/hosted/dap.c
This fixes a regression introduced in 52cad38.
52cad38 rewrote the pointer math and forgot brackets, unintentionally changing the sign of the 2-offset, leading to the command requesting to shift 32 bits more than it provided.
=> hosted/dap: Fixed error in link reset pointer math.

src/platforms/common/usb_serial.c
Fixed a regression caused in #1190 that puts the CDC notification replies out over the wrong endpoint.
The effect of this regression is that BMP erroneously replies to state change requests, like asking for DTR to be set, over the wrong endpoint channel - using the serial data IN endpoint rather than the notification endpoint.
Many thanks to @compuphase for the data in their bug report allowing us to so quickly pinpoint this.
Fixes #1310
=> fix: USB serial DTR handling and resulting USB packet sent on the wrong endpoint regression

src/crc32.c
in #1286 a return type change was introduced in the crc32 routines (17c4f1fe19efeb88bbd37ed0b1e054ae59ab22cd) but one return was missed and it borked crc32 calculation results in BMDA and non-stm32 probes.
=> crc32 fixup: missing return type change

src/target/stm32f1.c
In this PR we address a regression in the identification of STM32F0 parts. This was caused in 661d3ccf (#1291) when trying to refactor the part identification code common between GD32 parts and genuine STM32 parts.
=> stm32f1: Fixed a regression in the identification of STM32F0 parts

src/platforms/hosted/serial_win.c
Previously I would get this error while trying to run hosted blackmagic:
```
$ ./src/blackmagic.exe -jtv 31
Black Magic Debug App (for BMP only) v1.9.0-rc0-4-g5e3f0084-dirty
Using:
BMP  98B69BC2
Error retrieving value for key ParentIdPrefix, got error 00000000: The operation completed successfully.
Unexpected problems finding the device!
```
This PR handles the case where `RegGetValue` can return `ERROR_SUCCESS`, fixing this issue
=> Fix: not handling ERROR_SUCCESS return code from RegGetValue

src/target/nrf51.c
Thanks to the Discord user dsmullen (@drspangle), we were informed that nRF52 devices were still triggering memory issues in the firmware. In this case, the device they were trying to Flash was after a 4kiB write buffer and this was running their probe out of memory.
With their kind help for testing, we have capped the maximum write buffer size for nRF targets to 1kiB, and applied some cleanup to the Flash routines as suggested by Perigoso which have also reduced Flash usage a small amount more. This has all been tested working.
=> Fix: nrf52 probe memory exhaustion

src/command.c
if the user types "mon rtt" there is only one argument, argv[1] is undefined, and strlen(argv[1]) can cause a null pointer ref.
=> check argc

src/target/stm32f4.c
t->part_id was being used, but that code is unlikely to match the idcode used internally by ST leading to a bad look up, use device_id which is read from the internal ST register
fixes #1328
=> target/stm32f4: correct code used to look up part name

driver/99-blackmagic-plugdev.rules, driver/99-blackmagic-uucp.rules
Added a second set of symlinks so the friendly names continue to work using the probe serials even when a user plugs multiple BMPs into one host machine.
Before this change, a machine with any number of BMPs plugged in would have a /dev that looks like:
```
❯ ls /dev/ttyBmp*
/dev/ttyBmpGdb  /dev/ttyBmpTarg
```
After, the same /dev now looks like:
```
❯ ls /dev/ttyBmp*
/dev/ttyBmpGdb  /dev/ttyBmpGdb8BB20695  /dev/ttyBmpGdbBFC590F5  /dev/ttyBmpTarg  /dev/ttyBmpTarg8BB20695  /dev/ttyBmpTargBFC590F5
```
=> Fix: udev symlinks when multiple probes are attached to one host

src/Makefile, src/platforms/hosted/serial_unix.c
Fixes BMDA build issues on OSX:
(i) Adds certain compiler flags if not OSX (-Wmaybe-uninitialized -Wstringop-overflow -Wunsafe-loop-optimizations)
(ii) Add 'const' to serial_open declaration on OSX
=> BMDA: Fix build on OSX

src/main.c, src/platforms/hosted/Makefile.inc, src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/dap.c, src/platforms/hosted/dap.h, src/platforms/hosted/dap_command.c, src/platforms/hosted/dap_command.h, src/platforms/hosted/jlink_adiv5_swdp.c, src/platforms/hosted/platform.c, src/platforms/hosted/stlinkv2.c, src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c
This PR addresses the issue reported in https://github.com/blackmagic-debug/blackmagic/issues/1319 and on Discord where a user trying to attach to various Cortex-M cores via SWD would get an attach failure from the firmware, the remote protocol going non-responsive (BMDA connected to BMF), or have the debug server abort (BMDA via ST-Link, JLink, CMSIS-DAP). This would happen only if there was a delay between scan and attach.
The underlying issue causing this (something happening on the bus that causes the target to go into the protocol error state defined by ADIv5.2 §B1.2 subtitle "Protocol errors (SW-DP only)", and §B4.2.5) remains unchanged, however this PR gives BMP proper handling for the no-response answer used to indicate this state and a proper error recovery mechanism which means …
=> Fix: Cortex-M SWD attach regression

src/gdb_main.c, src/include/target.h, src/target/cortexa.c, src/target/cortexm.c, src/target/stm32f1.c, src/target/target.c, src/target/target_internal.h
On some probes with little SRAM or for targets with large Flash buffer allocations, the allocation of a large buffer to hold the target register description induces a heap memory exhaustion, seen as crashes and freeze-ups. This PR seeks to address this by limiting this large SRAM allocation to just the duration of the GDB request during which it is required, sacrificing a little speed for reduced memory pressure.
Many thanks to Aqz2 for providing the traces and information to allow us to isolate this as being the cause of several recent issues. This PR replaces https://github.com/blackmagic-debug/blackmagic/pull/1334
Fixes https://github.com/blackmagic-debug/blackmagic/pull/1327
=> Fix: target register description allocation induced memory exhaustion

src/platforms/hosted/cli.c
Using the hosted CLI on macOS, I found I was not able to flash my target. It would say the flash succeeded having written zero bytes.
I tracked this down to the way the file is loaded in, where the size is captured improperly during the mmap.
I also cleaned up that structure, as the `real_size` variable was not necessary on Windows platforms.
With this change, I'm able to flash successfully.
=> Fix: Flashing from the hosted CLI on macOS/*nix

src/command.c, src/gdb_main.c, src/gdb_packet.c, src/include/command.h, src/main.c, src/platforms/hosted/gdb_if.c
In this PR we implement a feature to allow BMDA to be cleanly shut down rather than having to always signal it.
This has been done for two reasons.
The first more minor one is to help with users scripting GDB/BMDA wishing to shut the server back down after completing a GDB script.
The second reason is to make ASAN, LSAN and friends more useful - leak sanitizer can only act after a clean non-signalled shutdown of the program so this provides a mechanism to allow the program to exit normally and trigger LSAN processing. Likewise this allows testing with other sanitizers with this restriction in the future.
=> Feature: clean BMDA shutdown

src/platforms/hosted/dap.c
In this PR we address a crash in the CMSIS-DAP code triggered when IR post-scan for a device is 0, causing `dap_jtagtap_tdi_tdo_seq` to be called with ticks = 0, final_tms = true. This prevents the crash but is not guaranteed to leave things in a good state (though it should)
=> hosted/dap: Fixed dap_jtagtap_tdi_tdo_seq() crashing when ticks is 0 and final_tms is true

src/target/target.c
This PR addresses the issue reported in https://github.com/blackmagic-debug/blackmagic/issues/1353 which causes a crash due to calling a NULL pointer in `target_regs_description`. This occurs because not all targets set the t->regs_description member. This fix restores the previous behaviour that was changed in 2c52af6 and improves robustness.
Fixes: #1353
=> Fix: Target registers description crash

src/target/target.c, src/target/target_internal.h
In this PR we address the secondary problem encountered by zyp in https://github.com/blackmagic-debug/blackmagic/issues/1353
This issue is caused by the undefined and strictly forbidden casting of incompatible function pointer types to assign to the target structure function pointers as defaults. The net result is that on platforms where this visibly matters, it generates segfaults/crashes. On other platforms it generates unpredictable and unreliable behaviour.
This has been fixed by introducing a couple more no-op functions with the correct return types to use, and assigning suitable ones (without cast, where possible) to the various function pointers.
=> Fix: target default functions undefined behaviour

src/platforms/hosted/remote_swdptap.c, src/remote.c, src/target/adiv5.c, src/target/adiv5_swdp.c
In this PR we address the SWD regression identified in https://github.com/blackmagic-debug/blackmagic/issues/1359 which was caused by the protocol recovery addition in https://github.com/blackmagic-debug/blackmagic/pulls/1331 exposing the DPv2+ protocol recovery being incorrect and scan not setting the DP version field so causing recovery to progress incorrectly (post-recovery the device had DP#0 reselected in the multi-drop chain making things work when they shouldn't).
After this change, discovery and recovery both work correctly and reliably for DPv0, DPv1 and DPv2 SWD devices.
Fixes #1359
=> Fix: DPv2+ SWD regression

.clang-tidy, src/target/lpc17xx.c
In this PR we address the LPC17xx detection reliability and issues cause by the support being very rudimentary and written with some assumption that don't really hold. These assumptions being that nobody uses the MPU, that the IAP ROM disables the MPU if needed while making IAP calls, and that doing UB stack reads as part of varargs couldn't backfire horribly.
Fixes https://github.com/blackmagic-debug/blackmagic/issues/1366
=> Fix: LPC17xx detection reliability/issues

src/platforms/hosted/cmsis_dap.c
When using HID as transport, the responses are always the same length, so we only need to check that the received length is more than or equal that the expected response length.
This fixes debugging with [dap42](https://github.com/devanlai/dap42) adapter, tested with an stm32f103 target.
=> hosted/cmsis_dap: Fixes CMSIS-DAP adapters connected with USB HID.

src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/dap.c, src/platforms/hosted/dap.h
Due to some code duplication in BMDA (which itself needs addressing but will be taken care of in v1.10), a second instance of #1359 was laying in wait in the CMSIS-DAP implementation. This PR addresses this second copy of the buggy protocol recovery code.
Fixes: #1370
=> Fix: BMDA's CMSIS-DAP protocol recovery

src/command.c
This patch brings back the once removed space in the `monitor version` command output.
=> command: Added missing space in front of fw version.

src/target/stm32l4.c
stm32wb10 & stm32wb15, stm32wb family smallest parts are reporting as 0x4940 and were not detected (see #1337)
Add missing id, chip info and handle part specific 2kb page size (bigger chips have 4k pages)
Detection tested on BMDA + stlink against stm32wb15cc and stm32wb10cc chip, debugging and loading code checked against stm32wb15cc on a nucleo board.
fixes #1337
=> stm32l4: add stm32wb1x parts detection.

src/gdb_main.c
After catching a fault, some versions of gdb (haven't mapped out exactly which, but behavior is observed with gdb-multiarch 10.1.90.20210103-git as shipped with Debian stable) sends a continue with signal command (`C`) rather than a regular continue (`c`), and when this goes unhandled, gdb gets confused and thinks the target is running, causing the symptoms seen in #1090.
Since the command arguments are ignored in any case, simply making `C` an alias of `c` solves the problem.
Fixes #1090
=> gdb_main: Handle continue with signal command

src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/dap.c, src/platforms/hosted/dap.h
This fixes #1370:
- Fixes attaching to multi-drop targets by using correct write sequence.
- Fixes memory reading, allowing to correctly decode ROM tables.
fixes #1370
=> Fix CMSIS-DAP access to RP2040

src/gdb_main.c, src/include/gdb_main.h, src/main.c, src/platforms/hosted/platform.h
This is a rewrite of the main loop as suggested in https://github.com/blackmagic-debug/blackmagic/pull/1281. Rather
than constantly sitting inside `gdb_main()`, the program's main loop does its own polling of the target. This enables
a host to do its own waiting without needing to insert hooks in various functions.
This prevents WDT triggers on ESP32 where RTT blocks the IDLE thread from running. The IDLE thread is responsible for resetting the WDT. It can also be used inside the main loop to regulate hosts such as `PC_HOSTED` where constant USB polling is undesirable.
=> gdb_main: move main loop into `main()`

src/target/stm32l4.c
Right now stm32wb55 cannot be flashed, with the "Error erasing flash with vFlashErase packet".
This is because stm32l4_flash_busy_wait checks FLASH_SR_ERROR_MASK before resetting FLASH_SR and FLASH_SR_OPTVERR is already set when stm32wbXX is started, as written in ERRATA ES0394 2.2.9.
That PR fixes that.
=> STM32L4, STM32WB: Clear OPTVERR before checking FLASH_SR_ERROR_MASK

src/include/jtagtap.h, src/include/swd.h, src/platforms/common/jtagtap.c, src/platforms/common/swdptap.c, src/platforms/hosted/bmp_remote.c, src/platforms/hosted/bmp_remote.h, src/platforms/hosted/cmsis_dap.c, src/platforms/hosted/cmsis_dap.h, src/platforms/hosted/ftdi_bmp.h, src/platforms/hosted/jlink_adiv5_swdp.c, src/platforms/hosted/libftdi_swdptap.c, src/platforms/hosted/platform.c, src/platforms/hosted/remote_jtagtap.c, src/platforms/hosted/remote_swdptap.c, src/platforms/hosted/stlinkv2.c, src/platforms/hosted/stlinkv2.h, src/remote.c, src/target/adiv5.c, src/target/adiv5.h, src/target/adiv5_jtagdp.c, src/target/adiv5_swdp.c, src/target/cortexm.c, src/target/jtag_scan.c, src/target/stm32f1.c
This PR does a couple of things:
1. It de-duplicates code in the ADIv5 implementation, fixing UB issues in the target memory write code, and improves our nomenclature
2. It partially reverts a change made in PR #857 which wrongly removed the SWD interface header and structures, which had made the ADIv5 code a bit of an inconsistent soup, and also expanded per-DP memory consumption by 16 bytes (48 bytes extra consumed for a RP2040 for example)
The results are more consistency, leaner firmware, and better compiler optimisation.
The re-introduction of the SWD structure also allowed removal of some of the reaching in that BMDA was doing to the firmware, allowing us to start decoupling BMDA
=> Fix: ADIv5 code duplication

src/platforms/hosted/Makefile.inc, src/platforms/hosted/bmp_hosted.h, src/platforms/hosted/bmp_serial.c, src/platforms/hosted/probe_info.c, src/platforms/hosted/probe_info.h
This PR fixes the way BMDA handles probe enumeration when built `HOSTED_BMP_ONLY=1` and provides a framework for rebuilding the probe enumeration of the full build BMDA. This forms a basis for the work Sid Price has been doing to try and replace the spaghetti mess that is find_debuggers() and the lack of support of OSX.
=> Fix: BMDA probe info

src/target/adiv5.c, src/target/adiv5.h, src/target/cortexm.c, src/target/jep106.h, src/target/lpc11xx.c
While building the RISC-V branch, we discovered that those processors also use the JEP-106 specification for parts identification. This moves the JEP-106 headers out from the ADIv5 header into their own new one, allowing their use the by RISC-V support too.
=> Fix: JEP-106 codes organisation

src/target/cortexa.c, src/target/cortexm.c, src/target/gdb_reg.c, src/target/gdb_reg.h
This PR does two things in preparation for both RISC-V and AVR support - it splits up the XML description preamble into 3 parts, and then adjusts the nomenclature to make the API non-specific to ARM as this improves the degree of reuse we get from Qyriad's excellent work
=> Fix: GDB register API nomenclature and organisation

.clang-format, src/platforms/hosted/ftdi_bmp.c, src/target/stm32f1.c, src/target/target.c
While building the RISC-V support branch, we hit upon a miss-formatting of multi-line ternaries and fixed several clang-tidy lints in the STM32F1 code. This PR promotes those changes into v1.10 ahead of the RISC-V support.
=> Fix: ternary and misc formatting fixes

src/platforms/common/jtagtap.c, src/platforms/hosted/remote_jtagtap.c, src/target/jtag_scan.c, src/target/jtag_scan.h
In this PR we address several JTAG bugs (including a regression from PR #1131) which were impacting the ability for the firmware to correctly talk to RISC-V targets, among others. There are still issues with the timings being very tight on many devices, but this does at least appear to be reliable and gives reasonable clocking waveforms too as shown in the capture below.
This blocks PR #1380 till merged and must be applied on top of that PR if wishing to test RISC-V with BMP or other BMD firmware platforms.
=> Fix: JTAG correctness

src/platforms/hosted/probe_info.c
Use stdlib.h instead of the non-standard malloc.h. Darwin doesn't have it.
This fixes the build for `PROBE_HOST=hosted` on macOS (I have Ventura 13.2), which otherwise breaks due to a missing `malloc.h`. Previous OS versions or macOS SDKs might have had a compatibility `malloc.h` that is now removed; I'm not sure.
N/A
=> hosted/probe_info: don't use malloc.h

src/platforms/hosted/bmp_libusb.c
BMDA fails to build under Windows
This affects v1.9 and main
=> bmp_libusb: Corrected include file path

src/include/exception.h
Add include guards to use the correct header under Windows
Note this also needs back-porting to v1.9.0
=> exception.h: Added include guards for setjmp.h and setjmpex.h

src/gdb_main.c, src/target/nrf51.c
This is a fix for a problem, which occured when trying to connect to the Control Access Port Targets on NRF52 chips: After attaching, it ran into an endless loop, because the CAP is no real CPU core and therefore no CPU Register Read is implemented. The fix adds the case, when 0 registers are available and respons to GDB by sending an dummy register with the value 'XX', which indicates, that the register value hasn't been collected.
This check is implemented when handling the 'g' packet.
fixes [#1353](https://github.com/blackmagic-debug/blackmagic/issues/1353)
=> Fix: Attaching to nRF Control Access Port Targets

src/target/adiv5.c, src/target/cortexm.c, src/target/jep106.h, src/target/stm32f1.c
Adds support for MindMotion MM32F5277, Arm China STAR-MC1 architecture.
Cleanup and document MM32 Cortex-M0 flashing code.
Tested flashing the following:
- MM32SPIN27 M0
- MM32L073 M0
- MM32F3273 M3
- MM32F5277 STAR-MC1
bmda session log attached: [f5277.txt](https://github.com/blackmagic-debug/blackmagic/files/10817039/f5277.txt)
Additional MM32 processors can be added as described in #1362.
=> mm32: support for mm32f5277

src/gdb_main.c
Don't reattach the target when handling `qXfer:features` or `qXfer:memory-map`. GDB uses at least `qXfer:features` when connecting to the debug server, halting the target. Official documentation claims that connecting to the server won't attach the target.
This change removes an unwanted behavior (see #1390) where reconnecting GDB to a BMP after detaching from a target will sometimes reattach the target. This is contrary to the official documentation. There is a workaround: scanning for targets before disconnecting from GDB in the first session, but that is non-intuitive and undocumented.
In case there is a benefit from retrieving the relevant information from `last_target`, it is still consulted, if available, for these `qXfer` requests, without reattaching the target.
fixes #1390
=> gdb_main: don't reattach on connect

src/target/cortexm.c
Added a missing probe call to sam3x_probe, which re-enables support to SAM* devices.
Without this the target MCUs are shown as unknown devices, and flashing routines fail on them.
=> target/cortexm.c: Added missing probe call to sam3x_probe

src/target/ch32f1.c
Fix no. 1
It is not possible to run blackmagic (PROBE_HOST=hosted) without flag -H, --high-level when writing to CH32F103C8T6 MCU’s flash memory.
Fixed by increasing the delay (that does not interrupt the MCU) in function ch32f1_wait_flash_ready().
Note! This problem does not show when using arm-none-eabi-gdb load.
Fix no. 2
Using blackmagic (PROBE_HOST=hosted) for writing to CH32F103C8T6 MCU’s flash memory  prints a lot of DEBUG_WARN messages to the console.
The condition tested for, FLOCK bit set in the FLASH_CTLR register, is never be met. Fixed by setting the FLOCK bit in the FLASH_CTLR register in function ch32f1_flash_lock().
=> Two fixes related to CH32F103C8T6 MCU found on some Blue Pill boards

src/platforms/hosted/bmp_remote.c, src/platforms/hosted/bmp_remote.h, src/platforms/hosted/platform.c
BMDA was not controlling the target power when the "--power" option was used.
=> Fix lack of target power control in BMDA

src/platforms/hosted/cli.c
The function cl_execute is not called in BMDA when a BMP is attached. The code removed was an attempt to control the target power and was never called.
=> Remove dead code from cl_execute

src/Makefile, src/target/adiv5.c, src/target/cortexm.c, src/target/jep106.h, src/target/lpc55xx.c, src/target/target_probe.c, src/target/target_probe.h
This PR is a revamp of #861 to meet the current code base standards and contribution guidelines, and replaces that PR. This provides initial basic support for LPC55 targets which will then be supplemented by #1189 which expands this considerably to provide full target support.
This basic support provides detection, "debug mailbox" recovery support, and recovery-mode mass erase.
Fixes #736
=> Feature: Initial LPC55 support

src/platforms/common/usb_serial.c, src/target/nxpke04.c
This PR addresses the spew of nasty linker warnings that occur when building the BMD firmware with GCC 12, and a cast alignment issue that crops up under 12 in some situations.
This fixes our source compatability with the newer GCC and allows trouble-free use of the current ARM toolchain.
Fixes #1324 and #1363
=> Fix: GCC 12 compatability

src/target/stm32f1.c
This PR is a follow-up to https://github.com/blackmagic-debug/blackmagic/pull/1306 which sought to address an issue with how we handle STM32F{0,1,3} option bytes that turned up when `stm32f1_flash_busy_wait` was made to properly check the Flash controller status and report it, and we made the Flash and options bytes handling code use and act on that status return.
The gist of what was wrong is that on the GD32F103, the options byte erase never actually erases option byte slot 0 (read protect), a request to write the option bytes then tries to program that slot back to its original value and fails by triggering the controller to report a programming error due to the the slot not being erased (0xffff) in hardware. This translated into it failing the write and reporting an error.
The old PR …
=> Fix: STM32F1 option bytes handling correctness
