blackmagic-debug/blackmagic

- src/sam3x.c
This pull request adds Atmel SAM4S support to the sam3x.c driver. I have tested it with a SAM4S4BA.
> SAM4S support

- src/samd20.c
This appears to be related to Atmel Errata Reference 12015 (see § 35.4.1 DSU in the datasheet) but only applies to revision B silicon - not revision C. While this is an old silicion revision (latest is revision E as of 17 Jan 2015) I found one on a development board.
> Fixed run command on SAM D20 old revision B silicon.

- src/sam3x.c
This patch adds support for the U subfamily of the SAM3 controllers.
> sam3x: add SAM3U support

- src/efm32.c
Instead of the Device ID register which isn't constant for EFM32G parts.
Fixes issue with #106 found by @lbonn
> [efm32] Use SW-DP IDCODE register for identification

- src/kinetis.c
Kinetis for KL25 is extended with KL02 support. The family members are rather similar in terms of flash API and device ID location, so I generalized the KL25 device support APIs. I have tested the change on a MKL02Z32VFG4 device. Works from command line and from the Kinetis Design Studio as well. Please kindly review the changes.
> added support for KL02 family

- scripts/dfu-convert.py
- src/platforms/hydrabus/Makefile.inc
- src/platforms/hydrabus/Readme.md
- src/platforms/hydrabus/platform.c
- src/platforms/hydrabus/platform.h
- src/platforms/hydrabus/usbdfu.c
Supersedes #67.
- Squashed commits so we don't have ST binary stuff in the history.
- Updated to match the platform refactoring.
- Removed Windows .bat file and updated platform readme with the command.
> Add HydraBus support

- src/platforms/native/platform.c
- src/platforms/native/platform.h
This pull requests contains two small patches, that are needed for the upcoming Black Magic Probe V2 hardware. :)
> Bmpm2 support

- src/Makefile
- src/adiv5.c
- src/adiv5_jtagdp.c
- src/adiv5_swdp.c
- src/cortexa.c
- src/cortexm.c
- src/efm32.c
- src/gdb_main.c
- src/include/adiv5.h
- src/include/cortexm.h
- src/include/target.h
- src/jtag_scan.c
Working on Xilinx Zynq 7000 (Cortex-A9 dual core)
> Cortex-A support

- src/kinetis.c
This pull request adds Kinetis KL27 support and incorporates the fixes from https://github.com/blacksphere/blackmagic/issues/122
I have tested flash programming on KL25 and KL27 microcontrollers on a custom board. Both work reliably.
Because of https://github.com/blacksphere/blackmagic/issues/131, this pull request is based on an older commit, but there are not any merge conflicts.
> Add Kinetis KL27 support

- src/lpc11xx.c
> Add NXP LPC82x support

- src/exception.c
- src/platforms/native/Makefile.inc
- src/platforms/native/platform.c
- src/platforms/native/platform.h
- src/platforms/stm32/usbuart.c
- src/target/adiv5.c
- src/target/cortexa.c
- src/target/cortexm.c
- src/target/sam3x.c
If no debugger is attached write to USB UART as before if option is set.
> Use semihosting for debug output if available.

- src/platforms/libftdi/jtagtap.c
- src/platforms/stm32/jtagtap.c
- src/platforms/tm4c/jtagtap.c
The parameter is TDI (as in input) not TDO. The header signature and
comment are correct.
> Corrected jtagtap_next signature.

- src/target/cortexa.c
...and timeout if no response.
> cortexa: Wait for instruction complete on resume.

- src/target/efm32.c
For #169 
@linuxchris12 please confirm this is correct.
> EFM32HP (happy gecko) support

- README.md
Add a badge with a link to the Kickstarter
> Update README with Kickstarter

- src/target/stm32l0.c
- src/target/stm32l4.c
Patches submitted by @UweBonnes by email.
> More STM32L0 and STM32L4 devices

- src/target/stm32f4.c
> stm32f4: Translate ITCM addresses to AXIM on flash write.

- src/gdb_main.c
> Add range checking on mem access packets.

- src/platforms/stm32/dfu_f1.c
As the first 4 pages of the bootloader will always keep write protection
once read protection is applied, with the second update of the bootloader
only the higher pages where updated effectivly.
In most cases this resulted in an inaccessible device!
> dfu_f1/dfu_upgrade: Do not set read protection.

- src/platforms/f4discovery/platform.h
- src/platforms/hydrabus/platform.h
- src/platforms/native/platform.h
- src/platforms/stlink/platform.h
- src/platforms/stm32/dfucore.c
- src/platforms/swlink/platform.h
STLinkV2-1 has F103CB on board! F103C8 can use upper flash with hopefully
acceptable error rate.
> stlink: Announce 124 kiB flash size in DFU to commplement #204.

- src/Makefile
Add explicit dependency of command.c on version.h
Remove version.h on make clean.
> Fix parallel build.

- src/platforms/stlink/platform.h
- src/platforms/swlink/platform.h
> stlink/swlink: Remove missleading comments.

- src/target/stm32f4.c
- src/target/stm32l0.c
Add new F4 and F7 devices and reqork option handling.
> Stm32f2_4_7

- scripts/gdb.py
Small fix for a off by one error.
> Fix gdb.py to program last chunk of a memory range

- src/target/lpc11xx.c
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Identify and support LPC1112/102 MCU as well

- src/target/target.c
> target: Fix wrong size calculation for write.

- src/target/stm32f1.c
This allows download to CCM Ram.
> stm32f1.c: Export CCM RAM of F303.

- src/target/kinetis.c
> added MKL27<128kB support

- src/platforms/stlink/platform.c
The reset function works, but it is very unreadable and uses the wrong PORT when you change the definitions in the header.
I suppose using the libopencm3 headers is a bit more intuitive here.
> Change the ST-Link SRST reset function

- driver/99-blackmagic.rules
Add udev rules for tty from wiki and usb permission rules.
> No sudo for dfu-util udev rules

- src/target/samd.c
Just added commands to lock and unlock the boot rom for SAMD microcontrollers. This is useful for working with the Feather M0 since the bootloader section in flash is locked.
> Added ability to lock and unlock boot rom for samd controllers

- src/target/stm32l4.c
This commit should solve issue #455, introduced by PR #445.
Main changes, all in stm32l4.c:
- Both RAM and Flash are added only in the attach function, not in the probe one.
- The memory map is freed with `target_mem_map_free()` before adding the new map.
- To avoid proliferation of `switch{}` statements and slightly reduce `if` complexity, a new info data structure has been introduced. This is also propaedeutic to adding new similar targets without large changes in the code.
- Minor editing
Tested with STM32L476 Nucleo, Windows 10, gdb 8.0.1, stlink platform.
Especially the third point, will allow me to finally add the WB series without the need of a separate probe function (and additional source files, let's rework it once again).
BTW, the RM has now been published: [STM32WB55xx …
> Correction of #445 attach-detach problem

- src/target/stm32l4.c
Not yet tested on a real part.
> Add Stm32G03 from reference manual Rev.2

- src/target/stm32l4.c
Based on #488 Stephen Roe.
Fixes ID of STM32G03.
> Add STM32G4

- Makefile
- src/Makefile
- src/gdb_packet.c
- src/include/gdb_if.h
- src/platforms/libftdi/Makefile.inc
- src/platforms/pc-stlinkv2/Makefile.inc
- src/target/efm32.c
- src/target/samd.c
Various minor enhancements, mostly to prepare a new host that's not ARM or PC based.
> Minor enhancements

- src/platforms/common/cdcacm.c
- src/platforms/f4discovery/platform.c
- src/platforms/hydrabus/platform.c
- src/platforms/launchpad-icdi/platform.h
- src/platforms/stm32/blackmagic.ld
- src/platforms/stm32/dfucore.c
- src/platforms/stm32/f4discovery.ld
- src/platforms/stm32/stlink.ld
- src/platforms/stm32/stm32_can.ld
- src/platforms/stm32/traceswo.c
- src/platforms/stm32/usbuart.c
- src/platforms/tm4c/tm4c.ld
Required fixes:
* use usbd_request_return_codes -- commit 54b117c5a5767df8dc114612dfd8e8cb88b72c6b
* drop deprecated timer_reset() -- commit 034dbf20ff8c54dcbee5238390b37a0d35180f44
* drop 48 & 120 MHz configs -- commit a9dde2832eb8039b9e0d21a50b9b991ddbfc4e2d
* ld scripts: drop duplication of standard sections -- commit 9a05dcb6c0aef712052d337457838f6041ffd57a
> Target latest libopencm3 version

- src/command.c
- src/platforms/libftdi/platform.h
- src/platforms/pc-stlinkv2/platform.h
- src/platforms/pc-stlinkv2/stlinkv2.c
- src/platforms/pc-stlinkv2/stlinkv2.h
- src/platforms/stlink/README.md
- src/target/cortexm.c
Fixes for the PC-STLINKV2 platform
> Pc stlinkv2

- src/target/cortexm.h
> cortexm.c: Fix DWT Mask

- src/platforms/f4discovery/Makefile.inc
- src/platforms/hydrabus/Makefile.inc
- src/platforms/native/Makefile.inc
- src/platforms/stlink/Makefile.inc
- src/platforms/swlink/Makefile.inc
Thanks to Sid Price for noticing #520.
> Linker: Recent libopencm3 linker already sets the stack.

- src/platforms/pc/gdb_if.c
This is necessary on OSX (and probably BSDs) where they default to non blocking which causes recv() to return -1 with errno set to EAGAIN.
> Set the accepted to socket to be blocking as that is what the code expects

- src/target/adiv5.c
While not working on most STM32, it succeeds on STM32G474.
Thanks to Dave Marples <dave@marples.net>
> adiv5: Activate DP reset sequence, guarded with timeouts.

- src/target/kinetis.c
Tested on KL16Z128VFM4, using custom hardware
> Add support for the kinetis KL16Zxx devices.

- src/platforms/stlink/README.md
Instruction on how to reflash STLink from BMP with ST bootloader back to STLink firmware.
> stlink: update docs on how ti reflash BMP back to STLink original firmware

- src/platforms/stm32/dfucore.c
This fixes incorrect flash size in dfu iface string
> fixup F103x8 flash size before build dfu iface string

- src/platforms/pc-stlinkv2/stlinkv2.c
- src/platforms/pc/cl_utils.c
- src/target/adiv5.c
+ other small changes in DEBUG output.
> cl-utils: Display targets found.

- src/target/cortexm.c
- Issue only one reset. Start with SRST and only if not seen, use SYSRESETREQ
- Wait for DHCSR_S_RESET_ST before issuing more commands
- Add timeout to catch reset line stuck low
- Remove AP errors
> Harden cortexm_reset() and remove double reset(#601)

- src/target/adiv5.c
- src/target/adiv5.h
- src/target/cortexm.c
- src/target/cortexm.h
- src/target/lmi.c
- src/target/samd.c
- src/target/stm32f4.c
No functional change intendend.
> Make more things static.

- src/platforms/pc/cl_utils.c
- src/platforms/stlink/platform.c
> stlink: Print Target voltage

- src/gdb_main.c
- src/include/target.h
- src/target/cortexm.c
- src/target/target.c
- src/target/target_internal.h
Implement additional semihosting calls.
> Semihosting

- src/target/stm32f4.c
Option bytes are not accessible with level 1 protection, so
Use FLASH_OPTCR(x)
Fix crash with "mon opt write xxxx"
Handle option manipulation better when HW Watchdog fuse is set
Allow abbreviated "mon option x<yyy>" commands
> stm32f4: Fix option byte handling (#654)

- src/target/stm32l4.c
Corrects STM32G431 flash map logic, as per RM0440.
> fix flash map for STM32G431, as it is a special case

- src/target/adiv5.c
CMSIS-DAP without connected target looped infinite in that situation.
> Adiv5: Protect DBG/SYSTEM Power-Up request with timeout too.

- src/platforms/pc/serial_win.c
- src/target/adiv5.c
> Fixes to serial on windows

- src/platforms/common/swdptap.c
On F103 no high time < 80 ns and no low time < 100 ns was seen with a scope
> SWD Timing: Enhance SWD high time with low speed loss.

- src/gdb_main.c
Thanks to Dave Marples <dave@marples.net>, extracted from  #607
> gdb: Reset flash_mode with when erase or flash fails.

- src/target/sam3x.c
Add chip id for SAM4SD32C and SAM4SD32B.
> Add SAM4SD32C/B support.

- src/platforms/hosted/Makefile.inc
Use ASAN=1 on the make command line to activate,
> hosted: Make ASAN build optional.

- src/command.c
- src/include/serialno.h
- src/platforms/common/cdcacm.c
- src/platforms/launchpad-icdi/Makefile.inc
- src/platforms/launchpad-icdi/platform.c
- src/platforms/stm32/serialno.c
launchpad-icdi: Allow to set a serial number with make
> serial_no: Fix error with "mon trace" #732

- src/Makefile
It seems, some git behaviour change got by unnoticed.
> src/Makefile: Fix version.h generation.

- src/target/adiv5.c
Reduces printout when scanning the romtable
> adiv5: Check Debug Base Address early

- src/platforms/common/cdcacm.c
(https://github.com/blacksphere/blackmagic/issues/740)
> Fix icdi usb error

- src/target/stm32h7.c
Add support for:
* STM32H7B3/B0/A3 (RM0455)
* STM32H723/33/25/35/30 (RM0468)
Successfully tested with:
* STM32H7A3ZIT (RM0455)
* STM32H747XIH (check for regressions)
> stm32h7: Add support for new product lines

- src/platforms/stlink/README.md
- Document flashing BMP Firmware and reverting to ST firmware
- Consistant nameing
> stlink: Rework README.md

- src/target/adiv5.h
- src/target/cortexm.c
- src/target/stm32f1.c
- src/target/target_internal.h
Hopefully this one is correct
it contains a small cosmetic fix : reorder the designer id so they are in increasing order (2 lines swapped)
> gd32f1/f3 detection and ram/flash autoset

- src/command.c
- src/include/target.h
- src/platforms/hosted/Readme.md
- src/platforms/hosted/bmp_libusb.c
- src/platforms/hosted/platform.c
- src/platforms/pc/cl_utils.c
- src/platforms/pc/cl_utils.h
- src/target/adiv5_swdp.c
- src/target/target.c
Dropout from working with the RPI Pico not onle related to Multi-drop and RP.
> assorted fixes, 3 * for hosted command line, 1 for cmsis dap debugger detection

- src/target/cortexm.c
- src/target/lpc11xx.c
This pull request adds support for the NXP LPC802, LPC804, LPC832 and LPC834 MCU series.
> Add support for NXP LPC802, LPC804, LPC832 and LPC834

- src/platforms/f4discovery/platform.h
- src/platforms/hydrabus/platform.h
- src/platforms/native/platform.h
- src/platforms/stlink/platform.h
- src/platforms/stm32/usbuart.c
- src/platforms/swlink/platform.h
Allows to use gdb while sending data through UART. Seems to work on Maple mini.
> Make USBUART TX/RX async

- src/target/adiv5.c
This adds a TRY_CATCH around the adiv5_ap_read_id() in
adiv5_component_probe() and resets the DP when that happens.
It seems like the STM32WLE5 comes with the AP of the inactive core
enabled in a way that does not make it detectable, and the current code
times out and leaves the whole device hanging.
Catching the timeout and calling adiv5_dp_abort() seems to restore the
device to a useable state.
Tested on Seed LoRa-E5 (STM32E5JC).
> adiv5: catch timeout on adiv5_ap_read_id and abort

- src/target/stm32l4.c
This adds support for the STM32WL series in stm32l4.c. These parts have the same flash registers layout as the L4 series, but a different base. Since there are already two sets of registers in this target file, this adds support for register maps that can be customized for each device ID.
Tested it on a Seed LoRa-E5, that's based on the STM32WLE5, the single core version of the WL55. Unfortunately it looks like ST left the second core AP configured on the single core part, and the probe hangs when probing it. I currently hacked my way around it by making it only probe the first AP and the flash and debugging capabilities seems to work fine, I'll have to figure how work around that cleanly, but this should work fine on the WL55.
> Add support for STM32WLxx

- src/platforms/pc/gdb_if.c
Thanks to "pshri" for dissecting and adding messages, as  problems with
Hpyer-V and port permissions happened on Win10
> pc/gdb_if.c: More verbosity for Error messages #873

- src/platforms/hosted/Makefile.inc
-Wno-format-truncation may not be understood by all systems
> hosted: Fix last commit

- src/platforms/pc/cl_utils.c
Duplicate BMP_MODE_FLASH_VERIFY -> BMP_MODE_FLASH_WRITE_VERIFY
> Fix de83dbb

- src/target/lpc_common.c
> Bug fix in Flash erase function for LPC MCUs.

- src/target/kinetis.c
- src/target/lpc_common.c
a side change for a warning that still looks like it's there on HEAD.
> more nxp k14x support

- src/platforms/hosted/bmp_hosted.h
- src/target/kinetis.c
- src/target/nxpke04.c
Target code changes to are pure for formal correctness and not tested!
> Fixes to compile with gcc11 #925

- src/target/stm32l4.c
Version of #458 synchronized with the current state of the project. I did not extend the erase_pages command to other targets, as it takes a very long time to verify. Work with options is also not implemented. Flashing, erasing, debugging work as expected.
> Support for STM32WB55

- src/target/stm32l4.c
Support for read/write/erase option bits.
> Add option bit support for STM32WLxx

- scripts/bootprog.py
- scripts/dfu-convert.py
- scripts/dfu.py
- scripts/gdb.py
- scripts/get_openocd_nrf51_ids.py
- scripts/hexprog.py
- scripts/stm32_mem.py
- src/platforms/hydrabus/Makefile.inc
Make sure all scripts are using python version 3, fix some issues on the way.
> Python3 fixes and shebang line update

- src/target/cortexm.c
- src/target/sam3x.c
- src/target/target.c
- src/target/target_internal.h
adds support for SAME70, SAMS70, SAMV71 and SAMV70
closes #963 
> target: add samx7x probe method

- src/platforms/96b_carbon/Makefile.inc
- src/platforms/96b_carbon/platform.c
- src/platforms/96b_carbon/platform.h
- src/platforms/stm32/96b_carbon.ld
The pull request we merged to add 96b carbon target was a tiny bit stale. It needed some TLC :D
> 96b_carbon: Updated so that it compiles in the current codebase.

- src/target/rp.c
Fixes #1013. I have done some testing and the suggestion @UweBonnes made to reset using `SYSRESETREQ` seems to be the correct fix here.
I have also fixed up some other oddities with the rp2040's flash handling and added the `erase_sector` command to help when debugging the rp2040.
> RP2040 updates

- src/platforms/hosted/cmsis_dap.c
Kindly sent in with a request for anonymity, this delivers a slightly more correct and more robust CMSIS-DAP implementation for BMDA
> hosted/cmsis-dap: Various CMSIS-DAP implementation correctness improvements

- src/target/sam3x.c
> target/sam: slight gpnvm command usage correctness

- README.md
> readme: sample usage update

- src/platforms/hosted/stlinkv2.c
cortexm_initial_halt() repeats the DHCSR write with high values for TRNCNT in
CSW. This is needed to catch a STM32F7 mostly in WFI. While the repeated write
is running, STLINKV3 on a Nucleo-WL55 (V3J7M2B0S0) answers first with
STLINK_SWD_AP_WAIT and on more read if write command is still running with
STLINK_SWD_AP_FAULT. At some point when the last command is finished, normal
STLINK_ERROR_OK indicates finally successful read. Treat STLINK_SWD_AP_FAULT
after STLINK_ERROR_WAIT as STLINK_ERROR_WAIT in that case. STLINK_SWD_AP_FAULT
may still be issued on other invalid accesses and should still be treated as
error in the other possible cases. Fixes #1071.
> stlinkv2: Treat a fault after wait as an error

- src/target/cortexm.c
I fixed some terrible bugs. You're welcome.
> Fix a couple of bugs in Cortex-M watchpoint and register handling

- CODE_OF_CONDUCT.md
As discussed on Discord, this adds a CoC based on the Contributors Covenant, widely regarded as a good CoC to enforce. Fairly short but to the point
> Added a code of conduct based on the Contributors Covenant

- src/target/stm32f1.c
trying to do something about #921 
I am not able to physically test this as I don't have any GD32E230 devices
@walmis do you think you could do some testing for me?
fixes #921
> STM32F1 general cleanup and GD32E230 option write special case

- src/target/rp.c
Fix build error and logic in rp.c
> Fix build error and logic in rp.c

- .clang-tidy
- src/target/kinetis.c
In preparation for fixing the Kinetis part-killer bug we did some cleanup, reformatting and rationalising of the Kinetis code so it should be easier to add new supported parts and work on in the future.
In light that Perigoso is working on #228 and depends on these changes, we have elected to bring this PR forward before the part-killer bugfix. As the bugfix is based on this we recommend merging to both main and v1.8
> Kinetis handling implementation cleanup

- src/target/target.c
This PR is based on a branch that does a similar thing on Uwe's repo (thank you for the idea Uwe!)
This implements a command - `monitor erase_range <address> <count>` - for erasing selected ranges of Flash memory on a target (eg, to erase a wrongly Flashed firmware image, or a bad bootloader).
This will be the first in a series of PRs which pull useful fixes and improvements in off forks to enhance the code base and close outstanding issues. We will in all likelihood follow this PR up with another that guts per-target equivalents of this command.
> target: Implemented a command to allow erasing Flash ranges on any target

- src/target/cortexm.c
I have no means to test this, but looking at the symptoms, and the git history, I believe this should fix it
fix #912
> target: fix probing for lpc1343

- src/target/ch32f1.c
I receive a new Bluepill+ board from WeAct Studios which has a APM32F103CBT6 µC part number (APEX/Geehy). But had an issue with BMP V1.8.0. Writing flash simply froze (GDB load command).
My board was identified as `CH32F1 medium density (stm32f1 clone) M3` which caused the issue, since this clone does not support the Fast Flash feature. Reading documentation, I saw that the Fast Flash Flag has a default value of **0** in a regular STM32 and also on the APM32Fxx.
Reading the source code, I noticed that this condition is not tested during the `probe` function.
The PR that I am posting solves the issue for me, but I have no CH32F part to test if the patch breaks something for this family.
Now my board is identified as `STM32F1 (clone) medium density M3` and works as expected.
> Fixed compatibility issues with CH32F1 driver and other STM32F103 clones

- src/platforms/stm32/gdb_if.c
Ported out from Uwe's RISC-V branch, this makes use of the WFI instruction in STM32 based probes when they're idle. To be seen if this causes problems or not - this one will need some further testing before merge.
> stm32/gdb_if: Use _WFI when nothing to do.

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- COPYING-BSD
In this PR we introduce pull request templates and contribution guidelines for the repository. This formalises the contribution process and provides steps for first-time contributors to follow.
> Feature: repo templates

- src/target/samd.c
This PR fixes the SAMD series mask and does some rudimentary reformatting of the constants defined top of file.
This fixes #571.
> Fix: SAMD series mask

- src/target/samd.c
This PR provides a workaround fix for SAMD11 errata which can be triggered by the normal cortexm_attach routine.
If the DFLL48M is left unrequested and then a configuration attempt is made, it locks up the chip till reset. This stops attach working in GDB when trying to work with bugged firmware that triggers this errata.
We work around this by releasing the target from reset before attach, which corrects this problem state.
Tested working against the ATSAMD11 on LUNA.
Fixes #578
> Fix: ATSAMD attach errata

- src/gdb_hostio.c
- src/platforms/hosted/dap.c
- src/platforms/hosted/jlink.c
> misc: superfluous semicolon cleanup

- UsingRTT.md
- driver/README.md
A little bit cleanup and clarification about the RTT feature.
The documentation was not clear for those that are looking for TLDR; :D
> rtt: Cleaned up updated and improved the RTT usage documentation.

- .github/workflows/build-pr.yml
- scripts/diff_size.py
ADHD kicked in and I got distracted for a bit, this is the result
This PR adds a job to the build PR workflow that builds the PR base ref, aka main, and the pr head, and diffs the size output from the build logs
It's a bit of a hack, don't look too closely at the python script, not something I'm that proud of
here's a PR I used to test:
https://github.com/perigoso/blackmagic/pull/2
> add size diff to PR workflow

- src/include/timing.h
- src/platforms/hosted/bmp_remote.h
- src/target/gdb_reg.h
> misc: fix malformed include guards

- src/target/renesas.c
add a known id for RA4M2 (we fixed the dev board at work that was debug locked)
while testing this board I found out on both RA4M2 and RA4M3 flashing is not working properly, something must have happened along the way in my original patch and I failed to notice while testing
> target/renesas: add known id for RA4M2

- src/target/renesas.c
Adds id for RA2A1, from #1243 
closes #1243
> target/renesas: add known id for RA2A1

- src/target/stm32f1.c
When trying to load the flash content via gdb the flash erase fails for a stm32f1xx target:
(gdb) load
Error erasing flash with vFlashErase packet
This fixes the wrong EOP evaluation logic, and also due to errata "2.12 Flash memory BSY bit delay versus STRT bit setting", it makes sense to evaluate both status bits, EOP and BSY.
* [ x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [ x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ x] It builds for hardware native (`make PROBE_HOST=native`)
* [ x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [ x] I've tested it to the best of my ability
* [ x] My commit messages provide a useful …
> stm32f1xx: Fix broken vFlashErase

- src/target/sam3x.c
PR to the fix/clang-format-cleanup branch
> target/sam3x: remove duplicate flash size calls

- UsingRTT.md
- src/command.c
- src/include/rtt.h
- src/include/target.h
- src/rtt.c
- src/target/target.c
Tentative fix, issue "RTT for F072 (STM32F072) platform not working #1248."
The problem seems to be two errors:
- the nrf52 target announces more ram to gdb than physically present,
and bmp hangs when rtt reads ram that is not physically present.
target announcing the exact amount of ram is not practical.
solution: add an option to restrict the address range rtt searches.
``mon rtt ram startaddress stopaddress``
- current rtt fetches address and size of circular buffer once, at initialisation, and head and tail pointers afterwards.
if target software modifies buffer address or buffer size after rtt initialisation, bmp has out-of-date pointers to rtt circular buffers.
solution: before accessing rtt circular buffers on target, each time fetch full control block from target. check rtt …
> rtt: fix #1248, RTT for F072 (STM32F072) platform not working

- src/command.c
- src/rtt.c
- fixes typo in command.c
- cleans up code in rtt.c, see closing comment in #1276 
- also attached test programs for rtt, perhaps useful for other developers [rtt_bluepill.zip](https://github.com/blackmagic-debug/blackmagic/files/9945616/rtt_bluepill.zip)
> rtt: cleanup

- .pre-commit-config.yaml
- src/gdb_main.c
- src/gdb_packet.c
- src/platforms/hosted/bmp_libusb.c
- src/platforms/hosted/cli.c
- src/platforms/hosted/utils.c
- src/rtt.c
- src/target/cortexm.c
This PR adds a hook to the pre-commit file, said hooks checks for assignments inside parentheses
depends on #1286
> Feature: pre-commit accidental assignment

- src/rtt.c
> #1302 followup

- src/target/target_flash.c
self explanatory, see  #1336
fixes  #1336
> target_flash: fix missing null check on target_flash_erase

- src/rtt.c
just a slight convention deviation / mistake I found by accident
> rtt: correct enum type naming

- src/rtt.c
This PR cleans up and address some stylistic issues with the RTT code (C89 style declaration-then-use which is bugprone to the UB read-before-initialisation pattern, rather than declaration-with-initialisation)
> Fix: RTT code cleanup

- src/target/ch32f1.c
Gdb load to a Blue Pill board with a CH32F103C8T6 MCU will cause gdb to hang and use a lot of CPU.
Text on MCU:
CH32F103
C8T6
401525A20
WCH
Fix 1. Have the ch32f1_probe() function set flashsize to 64 even if the MCU register that is supposed to hold that value is zero (0).
Fix 2. In function ch32f1_wait_flash_ready() a delay that do not disturb the MCU have been added, giving the MCU extra uninterrupted time to complete whatever it internally needs to complete. 
fixes #1406
> ch32f1: Fixed hanging gdb load command for certain CH32F103C8T6 MCU's

- src/target/stm32g0.c
Add identification for new STM32C011 and STM32C031 parts. These appear to be simplified version of STM32G03x parts. As such they share their part_id with STM32G03x parts but their DBG_IDCODE differs.
The patch is implemented by adding an additional switch() statement to the STM32G03x identification path. If there is another preferred way of doing this, please let me know and I will adjust.
References: STM reference manuals: RM0444 & RM0490.
> stm32g0: Add identification for STM32C011 and STM32C031

- src/target/stm32g0.c
Issuing a `monitor option erase` command to revert option bytes to factory defaults applies STM32G0x1 values so far.
This contribution applies a slightly different configuration (specifically the BOREN bit) on STM32C0x1 targets.
> STM32C0 option bytes factory reset correctness

- CONTRIBUTING.md
This looks to section out the contributing guidelines a little more by moving the commit message guidlines under a new heading this helps to seperate it out from the "If you are working from an existing clone of the repository" hopefully preventing any misreads or missing the section when skimming over the text
> Misc: Add heading to section out the commit message format

- .github/workflows/build-and-upload.yml
- .github/workflows/build-pr.yml
- src/Makefile
- src/include/exception.h
- src/platforms/96b_carbon/platform.c
- src/platforms/96b_carbon/platform.h
- src/platforms/blackpillv2/platform.c
- src/platforms/blackpillv2/platform.h
- src/platforms/f072/platform.h
- src/platforms/f3/platform.h
- src/platforms/f4discovery/platform.c
- src/platforms/f4discovery/platform.h
- src/platforms/hosted/Makefile.inc
- src/platforms/hosted/gdb_if.c
- src/platforms/hydrabus/platform.c
- src/platforms/hydrabus/platform.h
After the incidence of several recent Windows build issues and our continually accidentally breaking the build there in subtle ways, we have finally built CI for Windows, added artefact handling for it, and expanded out CI for Linux to test multiple compilers.
This PR also upgrades the CI setup to use the current generation actions, fixing the complaints about outdated Node.js, and upgrades the ARM GCC used.
PRs use a subset of the overall suite of possible options to give us a flavour of whether things are OK, while the main branch build goes all-out and builds 5 different versions for Linux, 6 for Windows, and makes the results for all available.
> Feature: Windows CI

- src/target/renesas.c
A couple generic cleanups, initially motivated by going through Renesas documentation.
> Renesas: general renesas cleanups

- .github/workflows/build-and-upload.yml
- .github/workflows/build-pr.yml
No functional change, just fixed some comment typos in `build-and-upload.yml` and `build-pr.yml` while reviewing them.
> github: Fixed some comment typos in CI .ymls

- src/target/imxrt.c
This fixes the build on ESP32.
> imxrt: use PRIu32 for debug print

- .github/workflows/lint.yml
Update GitHub lint workflow action, fixing deprecation warnings
- before-commit/run-action@v2.0.3->pre-commit/action@v3.0.0
- actions/checkout@v3.0.2->actions/checkout@v3
This PR supersedes #1473 
closes #1473
> github: update action/checkout tag used in lint

- src/platforms/hosted/jlink.c
- src/platforms/hosted/stlinkv2.c
This is the followup to #1478, bringing the same simplification to ST-Link and JLink USB interface drivers.
Not yet tested on hardware.
> Simplify ST-Link and JLink USB code

- src/target/stm32f1.c
Add basic support for GigaDevices GD32E50x Cortex-M33 chips.
GigaDevice GD32E50x are Cortex-M33 cores with STM32F1-style peripherals. 
Per the "User Manual", flash is in 8KiB pages; 
and `DBGMCU_BASE=0xE0044000`, unlike on other chips.
This chip is not detected by BMP yet. 
Upon testing locally both with `blackpill-f411ce` platform and BMDA working via WeAct CMSIS-DAP / the blackpill BMP, the chip is detected via SWD, is flashable and debuggable (gdb hbreak, load, cont/Ctrl+C etc.)
See #1426 for more information.
PC 1: Linux Mint 21 (Ubuntu focal) with `gcc-arm-none-eabi` 10.3, newlib-3.3.0 and gdb-multiarch. Flash & debug tested.
PC 2: Gentoo 2.13 stable amd64/17.1 with `cross-arm-none-eabi/gcc:12.2.1` and newlib-4.3.0. Build tested.
fixes #1426
> target: GigaDevice GD32E50x

- src/platforms/common/usb_types.h
Fix (some) warnings for `-Wpedantic`
> Fix: enum fwd ref pedantic warning

- src/platforms/common/aux_serial.c
Fix warnings for `-Wbad-function-cast`
> Fix: bad-function-cast warnings

- src/target/samx5x.c
This fixes flashing on samx5x chips with larger amounts of flash (e.g. 512KiB).
Currently, we lock and unlock each flash region multiple times when the flash block size differs from the size of a protected flash region — i.e. the size of flash encoded by a single bit in the RUNLOCK register.
However, the RUNLOCK register also reads as "locked" while a write is still in progress, and we check that before each subsequent write. When we also manually lock after each block, and the block is smaller than a protected region, we misinterpret our own lock as an indication that the write is still in progress, and error out.
> samx5x: don't assume that flash block size == flash region lock size

- src/target/riscv_debug.h
> Fix: riscv typo

- .pre-commit-config.yaml
I forgot to remove a line in #1743. Moreover, @dragonmux has been telling me she's had trouble running `clang-format`, so this PR fixes it by using the correct, version-controlled hook.
> pre-commit hooks fixups

- src/target/renesas_rz.c
Change to the naming for RZ/A1LU to RZ/A1 as it was discovered the identification algorithm in use applies to both the A1LU and the A1H, and likely others in the RZ/A1 family.
This is substantiated (though not proven) by other projects making use of a singular rza1.svd file when referencing the entire family (see [rust](https://github.com/rz-rs/rza1) for one example).
> target: Adjusted RZ/A1LU to RZ/A1 target name

- meson.build
Fixed typo in file ./meson.build for gcc warning option
Fixed typo in file ./meson.build for gcc warning option
Changed line/statement from
-Wunsuffixed-float-constant
to
-Wunsuffixed-float-constants
> fix: Fixed typo in meson.build for gcc warning option

- README.md
On power shell some options like lists can cause issues and need to be wrapped in double quotes
Adds a note to adress #1769
fixes #1769
> readme: add note about PowerShell command line options

- src/gdb_main.c
- src/include/target.h
- src/target/cortexar.c
- src/target/cortexm.c
- src/target/riscv32.c
- src/target/target.c
- src/target/target_internal.h
When testing the BMDA gpiod support with JTAG I came across a segfault when running `info registers` on a riscv32 target (GD32VF103).  Investigating this led to discovering a series of issues around single register reads. This was during dumping of the `tscratch` register.
To improve matters here a few things are done.  Firstly the target_reg_read and target_reg_write functions are altered to return `size_t` instead of `ssize_t` and to return 0 to indicate failure rather than -1.  The use in `gdb_main_loop` was incorrectly storing the result in a `size_t` variable which resulted in failure attempting to hexify an unreasonably large number of bytes because the failure return of -1 was not caught by the < 0 check as `size_t` is unsigned.
After this the reading of `tscratch` would still …
> Some fixes to single register read/write

- src/target/cortexm.h
> Fix: 1 typo

- src/target/stm32l4.c
The flash size register for the STM32U5xx was in a different place, but all the other registers were compatible with the L5. So I modified the way the flash size was loaded (moving the register definition to its own location in the device structure), and then revised the code that calls it (turns out that the only read16 call was for flash size, so I changed the name).
That was enough to get it working for U5xx, but it turns out that the block size was also wrong. I've corrected the block size for U5xx, but I have not changed anything else. However, I made a comment for where I would suggest we start tackling that problem.
Much thanks to @ALTracer and @dragonmux for helping me get this far so quickly.
> stm32l4: Fix flash for STM32U5xx

- .github/workflows/build-pr.yml
- .pre-commit-config.yaml
@dragonmux let me know today morning that CI builds here [started failing for `macos-latest`](https://github.com/blackmagic-debug/blackmagic/actions/runs/8850206496/job/24304134265), and that they'd traced the issue to [this GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114007).
As it turns out, current GCC cannot parse the Clang/C++-ism that Xcode started using, taking advantage of C23's features. I tried working around this by switching to another SDK in CI, but instead I discovered that GCC hotpatches system includes based on the sysroot defined at configure time: https://gcc.gnu.org/onlinedocs/gcc/Fixed-Headers.html
This PR works around the issue by removing `macos-latest` from the matrix and replacing it with `macos-13` (the last known good version). This can be reenabled (or …
> ci: Disable macos-latest with GCC

- src/platforms/hosted/bmp_remote.c
> hosted/remote: Fix platform_nrst_get_val spell error

- src/target/semihosting.c
* This is a small new feature.
* The existing problem is BMD not supporting semihosting calls 0x30 SYS_ELAPSED, 0x31 SYS_TICKFREQ.
* This PR solves it by providing small implementations giving out platform time in milliseconds, conforming to ARM ABI. https://github.com/ARM-software/abi-aa/blob/main/semihosting/semihosting.rst
Tested on `blackpill-f411ce` platform with extra diagnostic logging against gd32f303cc-bluepillplus running a modified instance of `blackmagic-test-fw-archive` semihosting project (to avoid exiting early on errors). Stop-the-world delay observed by target is around 19ms in JTAG mode at max frequency for each syscall handled in-probe, no USB or GDB communication. SWD might be faster. Also tested on BMDA+BMP for a delay of 133ms (I am subtracting the in-sketch …
> Feature: Add support for SYS_ELAPSED/SYS_TICKFREQ as milliseconds

- src/platforms/common/stm32/traceswoasync.c
* This is a new feature.
* The existing problem is traceswoasync.c driver existing and working for F103 but incompatible with F4.
* This PR solves it by porting some of the macros from aux_serial.c driver.
Required for enabling/switching to Async capture on F4 platforms. Split from #1529.
Can only test the combination with platform-specific enablement PRs (pending). Previously tested builds from non-PR branches. The macros expected/required from platforms will be provided in a separate follow-up PR.
> Feature: Adapt traceswoasync (F103) to F4 API

- src/target/cortexar.c
Prerequisite to further work on resuming from a load to RAM.
* Solves issue where CPSR couldn't be written at the end of a load or with a manual "set $cpsr="
* Macro defines 25U as the remapped position in GDB and accounts for the remapping in `cortexar_reg_ptr` and `cortexar_reg_width`
> cortexar: fixed CPSR mapping for GDB

- src/target/cortexar.c
- Issue (GDB/BMP hang on 'run') was caused by `cortexar_halt_resume` being called after reset when the system was not actually in a halted state. This appeared to happen at two points in the 'run' execution: 
1. when gdb called vKill (calls `cortexar_detach` after reset which calls `cortexar_halt_resume`)
2. when gdb called vCont (calls `cortexar_halt_resume`)
- This fix drops out of `cortexar_halt_resume` if the target is not already halted (no reason to resume in that case)
- gdb_main assumes memory is accessible for read at any time; this fix adds a check for halted status in `cortexar_mem_read` and if not halted, temporarily halts the target (resumes at end of function).
- gdb_main allows setting of breakpoints at any time; this fix adjusts the `cortexar_virt_to_phys` function to …
> Fix: cortexar: BMP/gdb connection hang on run

- src/target/at32f43x.c
* This is a new feature.
* The existing problem is AT32F437 target watchdogs, WDT & WWDT, potentially resetting the chip during halting debug with BMD; and WFI sleep states interfering with halt-polling (and possibly RTT).
* This PR solves that by writing bits in DEBUG peripheral (analogous to ST DBGMCU) which control Sleep Emulation and Watchdog timer auto-freeze, with no save-restore but via read-modify-write.
WDT/WFI handling is required for feature parity with stm32f1.c and other target drivers.
> Feature: watchdog & sleep management on ArteryTek AT32F43x

- src/platforms/hosted/serial_win.c
Print the auxiliary serial COM port when starting BMDA. This port is not necessary for BMDA to function but may provide useful information to the user.
> hosted/serial_win: Print auxiliary serial COM port

- src/platforms/stlink/Makefile.inc
- src/target/meson.build
During the process of sorting out the SWO implementations, we noticed that a couple of the target family friendly texts had mistakes or were incomplete. This PR corrects this, making the listing more accurate and easier to understand.
> Fix: Build system cleanup

- scripts/meson-build-all.sh
This script takes all the different configurations found in the cross-file directory and builds them.
Each build is contained in it's own build-NAME directory to prevent collisions and allows easy and quick incremental rebuilds if needed.
> meson: Added a script to build all the existing cross targets.

- src/target/stm32f1.c
* This is a new feature.
* Currently there's no easy way to extend SRAM of AT32F403A via `monitor option` commands because EOPB0 is out of reach for the normal 16-byte driver.
* The PR solves it by conditionally bumping the option byte ranges.
Past first commit see my work of adding yet more part ID lists for other families in AT32F4 lineup. This is probably getting unmanageable, so I started incorporating F_SIZE and "Product ID" readouts from UID (in their DESig analog). If this is fine, e.g. does not result in problems for RDP1-enabled targets, then all such lists can be dropped or gated under ENABLE_DEBUG to not hog precious BMF flash -- it only needs to know flash parameters (banks, sector size, total size), not exact package & pinout. I may move this to a separate PR (and a split …
> Feature: Arterytek option bytes and more part IDs

- src/include/stdio_newlib.h
- src/platforms/common/stm32/serialno.c
- src/target/stm32_common.c
- src/target/stm32mp15.c
* Update own copyright entries to point to GitHub-provided noreply address.
I did update one of them in PR1949, this PR replaces the rest of entries.
* Bump stdio_newlib.h from 2023 to 2023-2024 although it haven't been functionally touched since 2023.
> misc: Update own email address

- src/gdb_packet.c
Allow supplying a packet buffer from an external source. This allows the GDB packet functions to be thread-safe, assuming the packet buffer comes from some form of thread-local storage.
Guard this function with a macro to allow keeping the previous behavior.
This allows platforms such as Farpatch to support multiple clients. A simple lock around accessing gdb provides some measure of concurrency management. When built without the macro, the function is marked as "static", in an effort to induce the compiler to inline the function to get the benefits of the new approach.
> gdb_packet: allow for external packet buffer

- CONTRIBUTING.md
In this PR we have updated the contribution guidelines to set forth the project policy on LLM/"AI" generated contributions.
There are 3 reasons for doing this:
* We have determined that there is an unacceptable risk from the training data used for these models that copyrighted work may end up in a contribution without proper attribution or licensing, and that the license of the source work may not even be compatible with the project's
* It places an undue burden on the maintainers to have to work through and spot subtle mistakes that even the contributor doesn't understand as a result, to work out what the correct behaviour should be
* There is a growing body of research showing these tools hurt productivity instead of help, while increasing negative outcomes such as poor code quality and …
> Fix: Contribution guidelines

- Makefile
> build: correct spelling in Makefile

- src/platforms/hosted/remote/protocol_v4.c
- src/platforms/hosted/remote/protocol_v4.h
- src/platforms/hosted/remote/protocol_v4_defs.h
- src/platforms/hosted/serial_win.c
- src/remote.c
- src/remote.h
- src/target/meson.build
In this PR we introduce a couple of new remote protocol commands to allow the probe to report what target architectures and target families have been compiled in and are supported by the firmware. This is designed to allow utilities like `bmputil` to discover target support from the probe to determine the firmware variant running (for automatic upgrades and `bmputil-cli probe info --list-targets`).
A follow-up PR is intended to introduce support for asking the probe for a complete targets support string - this string will be contained in the OTG Flash on BMP v2.3+ units and is purely for display purposes on the host. To this end we reserve the packets `HT` for a bitmask of supported targets in the future, and `Ht` for this string version. Such as string will list specific supported …
> Feature: Supported targets remote reporting

- .gitignore
- shell.nix
The shell.nix has to be updated to pull in newer versions of the GCC toolchain. The newer toolchain is better at optimising and keeps the binaries within the ROM bounds which the older toolchains fail at.
> misc: Update `shell.nix` and add clangd's .cache to gitignore

- src/target/stm32g0.c
Add support for the STM32U0 targets (STM32U031, STM32U073, STM32U083).
The following commands have been tested with a STM32U083 target: `flash-erase`, `mon erase_mass`, `load`, `mon uid` and debugging (`run`, `break`, `backtrace`, etc.).
This is a follow-up of [this previous PR](https://github.com/blackmagic-debug/blackmagic/pull/2091).
The old PR aims at supporting the STM32U0 target too but it consumes more flash space and it does not expose the `mon uid` command.
I only exposed the `mon uid` target-specific command for now. Other existing g0 options fail on the u0 target, the adaptation code may fit in another PR.
> stm32u0: add this target in the stm32g0 driver
